### PR TITLE
Move Enzyme extension tests to dedicated test group

### PR DESCRIPTION
**Pull request by glwagner**
Continues from #3327

### CODE REVIEW

**Comment by glwagner** [comment]
cc @wsmoses

**Comment by wsmoses** [comment]
FYI, the GPU Enzyme tests probably fail, because GPU reverse-mode rules are not added to KA (forward mode, however exists).

**Comment by glwagner** [comment]
> FYI, the GPU Enzyme tests probably fail, because GPU reverse-mode rules are not added to KA (forward mode, however exists).

They did pass previously though! (GPU tests ran on #3327.) We'll see what happens here.

**Comment by wsmoses** [comment]
Oh, actually that makes sense since the unit test here just does the field allocation, and doesn't hit a KA call that would result in an issue.

**Review by navidcy — APPROVED** [review]

**Pull request merged**
