### PR TITLE
An attempt to bump KernelAbstractions 0.8 + CUDAKernels 0.4

### PR DESCRIPTION
**Pull request by navidcy**
supersedes #2781

### CODE REVIEW

**Comment by navidcy** [comment]
So a lot of things break when I bump KernelAbstractions 0.8.4 + CUDAKernels 0.4.3....

cc @glwagner, @simone-silvestri

**Comment by simone-silvestri** [comment]
Some `@inline` are missing in `conditional_derivatives.jl`

**Comment by simone-silvestri** [comment]
Other `@inline`s missing in `Advection/topologically_conditional_interpolation.jl`

**Comment by navidcy** [comment]
I found a few more -- let's see.

**Comment by simone-silvestri** [comment]
Nice, maybe this will also increase the performance!

**Comment by navidcy** [comment]
There are several issues with `fill_halos`, e.g.
https://buildkite.com/clima/oceananigans/builds/8920#0183f07f-61ab-4914-baf5-c227ebe4c3ef/16-332

Are these missing `@inline`s?

**Comment by simone-silvestri** [comment]
Yep (in `fill_halo_regions_value_gradient.jl`)

**Comment by vchuravy** [comment]
Yeah KA got rid of the force-inlining on the GPU. @lcw started the work of adding it back in a better way than before. The benefit is that we are no longer using Cassette so errors should be vastly improved.

**Comment by navidcy** [comment]
OK, there are still:

- something with `regrid!` and `length`?
  https://buildkite.com/clima/oceananigans/builds/8922#0183f16b-a7d8-4da0-a8b8-25afbb402f81/16-433
- https://buildkite.com/clima/oceananigans/builds/8922#0183f16b-a7f9-49df-ad9b-62f98a92be8a/24-595
- something with `convert`?
  https://buildkite.com/clima/oceananigans/builds/8922#0183f16b-a81c-4a0a-a552-0edffc90518f/24-459

**Comment by navidcy** [comment]
@simone-silvestri can you have a look here? Some help with this would be great... Just have a look at the error of the tests that fail and let me know if you can understand where the root of the manner is?

**Comment by simone-silvestri** [comment]
Weird errors, it looks like the GPU calculations are inaccurate

**Comment by navidcy** [comment]
@vchuravy feel free to merge if you feel it's for the best... tests won't pass :)

**Comment by navidcy** [comment]
(I even cancelled the ci job to save resources)

**Comment by tomchor** [comment]
@navidcy should we close this pr now that KA was updated?

**Comment by navidcy** [comment]
definitely

**Pull request closed without merging**
