### PR TITLE
Make broadcasting depend on CUDA default stream

### PR DESCRIPTION
**Pull request by glwagner**
This may have been the cause of #1767.

### CODE REVIEW

**Comment by glwagner** [comment]
Note to self: if we want to do asynchronous broadcast-like operations, we have to write the kernels.

**Comment by glwagner** [comment]
I think our race condition test is passing after this without the need for a custom `mean!`, so I think this is good to go. It's probably important because there could be other bugs associated with bad interactions between operations on the CUDA default stream and broadcasting...

**Review by ali-ramadhan — APPROVED** [review]
Ah nice find!

**Comment by francispoulin** [comment]
A while ago we discussed having a `norm!` that worked on both CPUs and GPUs but I don't remember whether this was actually implimented.  Does someone else know the current state of `norm!`?

**Pull request merged**
