### PR TITLE
Implement `Scan`, generalizing `Reduction` to accumulating scans like `cumsum!`

### PR DESCRIPTION
**Pull request by glwagner**
This PR generalizes `Reduction` to also support accumulating "scanning" operations like `cumsum!`.

This should not change the existing user interface but instead add the new feature, something like

```julia
cumulative_u = Accumulation(cumsum!, u, dims=3)
```

and

```julia
cumint_u = CumulativeIntegral(u, dims=3)
```

~~Previously I don't think this was possible on GPU because `cumsum!` was not supported for `CuArray` (?) But it is now it seems.~~ To support this feature, we've implemented kernels for forward and reverse accumulation.

I also have used the generalization of `Scan` to clean up the internals / user interface for `Average` and `Integral` (now they are proper type aliases).

cc @hdrake @iuryt

### CODE REVIEW

**Comment by glwagner** [comment]
Here we go:

```julia
julia> using Oceananigans

julia> grid = RectilinearGrid(size=(1, 1, 3), extent=(1, 1, 1))
1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── Periodic x ∈ [0.0, 1.0)  regularly spaced with Δx=1.0
├── Periodic y ∈ [0.0, 1.0)  regularly spaced with Δy=1.0
└── Bounded  z ∈ [-1.0, 0.0] regularly spaced with Δz=0.333333

julia> c = CenterField(grid)
1×1×3 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: ZeroFlux, top: ZeroFlux, immersed: ZeroFlux
└── data: 3×3×9 OffsetArray(::Array{Float64, 3}, 0:2, 0:2, -2:6) with eltype Float64 with indices 0:2×0:2×-2:6
    └── max=0.0, min=0.0, mean=0.0

julia> set!(c, (x, y, z) -> rand())
1×1×3 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: ZeroFlux, top: ZeroFlux, immersed: ZeroFlux
└── data: 3×3×9 OffsetArray(::Array{Float64, 3}, 0:2, 0:2, -2:6) with eltype Float64 with indices 0:2×0:2×-2:6
    └── max=0.925176, min=0.853073, mean=0.877648

julia> cumsum_op = Accumulation(cumsum!, c, dims=3)
Accumulating cumsum! over dims 3 of 1×1×3 Field{Center, Center, Center} on RectilinearGrid on CPU
└── operand: 1×1×3 Field{Center, Center, Center} on RectilinearGrid on CPU
    └── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo

julia> cumsum_c = Field(cumsum_op)
1×1×3 Field{Center, Center, Center} on RectilinearGrid on CPU
├── data: OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, size: (1, 1, 3)
├── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── operand: Accumulating cumsum! over dims 3 of 1×1×3 Field{Center, Center, Center} on RectilinearGrid on CPU
├── status: time=0.0
└── data: 3×3×9 OffsetArray(::Array{Float64, 3}, 0:2, 0:2, -2:6) with eltype Float64 with indices 0:2×0:2×-2:6
    └── max=0.0, min=0.0, mean=0.0

julia> compute!(cumsum_c)
1×1×3 Field{Center, Center, Center} on RectilinearGrid on CPU
├── data: OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, size: (1, 1, 3)
├── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── operand: Accumulating cumsum! over dims 3 of 1×1×3 Field{Center, Center, Center} on RectilinearGrid on CPU
├── status: time=0.0
└── data: 3×3×9 OffsetArray(::Array{Float64, 3}, 0:2, 0:2, -2:6) with eltype Float64 with indices 0:2×0:2×-2:6
    └── max=2.63294, min=0.925176, mean=1.77933
```

**Comment by glwagner** [comment]
Cool. Getting to the finish line will be a bit of work I guess. I think we usually want to integrate downwards so that's annoying. Not sure if that exists exactly, or we have to implement some lazy version of `reverse` to achieve it

**Comment by iuryt** [comment]
Isn't that a way to obtain the reverse cumulative integration by simply multiplying by something?
Something like `cumint[end] - cumint + cumint[1]` 
I don't remember exactly, but I think that there is a way to do it.

**Comment by glwagner** [comment]
Ah that is a nice trick. It's something like the reversed `cumsum` of `y` is `sum(y) + cumsum(-y)` I think.

**Comment by glwagner** [comment]
Ah that is a nice trick! I Think its something like

```julia
cumsum!(b, a, dims=3)
A = view(b, :, :, Nz) # total sum of a over 3rd dimension
b .= A .- b .+ a # compute the reversed cumsum
```

**Comment by glwagner** [comment]
Dang, pretty cool:

```julia
julia> grid = RectilinearGrid(size=(1, 1, 3), extent=(1, 1, 1))
1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── Periodic x ∈ [0.0, 1.0)  regularly spaced with Δx=1.0
├── Periodic y ∈ [0.0, 1.0)  regularly spaced with Δy=1.0
└── Bounded  z ∈ [-1.0, 0.0] regularly spaced with Δz=0.333333

julia> c = CenterField(grid); set!(c, (x, y, z) -> rand())
1×1×3 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── boundary conditions: FieldBoundaryConditions
│   └── west: Periodic, east: Periodic, south: Periodic, north: Periodic, bottom: ZeroFlux, top: ZeroFlux, immersed: ZeroFlux
└── data: 3×3×9 OffsetArray(::Array{Float64, 3}, 0:2, 0:2, -2:6) with eltype Float64 with indices 0:2×0:2×-2:6
    └── max=0.53406, min=0.317935, mean=0.436216

julia> ci_op = CumulativeIntegral(c, dims=3)
CumulativeIntegral of BinaryOperation at (Center, Center, Center) over dims 3
└── operand: BinaryOperation at (Center, Center, Center)
    └── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo

julia> ci = compute!(Field(ci_op))
1×1×3 Field{Center, Center, Center} on RectilinearGrid on CPU
├── data: OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, size: (1, 1, 3)
├── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── operand: CumulativeIntegral of BinaryOperation at (Center, Center, Center) over dims 3
├── status: time=0.0
└── data: 3×3×9 OffsetArray(::Array{Float64, 3}, 0:2, 0:2, -2:6) with eltype Float64 with indices 0:2×0:2×-2:6
    └── max=0.436216, min=0.105978, mean=0.275398

julia> rci_op = CumulativeIntegral(c, dims=3, reverse=true)
CumulativeIntegral of BinaryOperation at (Center, Center, Center) over dims 3
└── operand: BinaryOperation at (Center, Center, Center)
    └── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo

julia> rci = compute!(Field(rci_op))
1×1×3 Field{Center, Center, Center} on RectilinearGrid on CPU
├── data: OffsetArrays.OffsetArray{Float64, 3, Array{Float64, 3}}, size: (1, 1, 3)
├── grid: 1×1×3 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×3 halo
├── operand: CumulativeIntegral of BinaryOperation at (Center, Center, Center) over dims 3
├── status: time=0.0
└── data: 3×3×9 OffsetArray(::Array{Float64, 3}, 0:2, 0:2, -2:6) with eltype Float64 with indices 0:2×0:2×-2:6
    └── max=0.436216, min=0.152218, mean=0.306224
```

**Comment by glwagner** [comment]
@jagoosw thoughts?

**Comment by jagoosw** [comment]
This looks great! I think we can re-state light integration as a field reduction with this.

**Comment by tomchor** [comment]
> I think we can use this to compute a cumulative integral as well, adding the feature to metric field reductions.

That's a great feature to add! I can remember it being request more than a few times over the years.

**Review by tomchor — APPROVED** [review]
This looks great! My only question is: is "scan" a default / frequently-used name for what we're doing here? I ask because I had never heard of it and when I think of a "scan" of a `Field`, I don't picture what is implemented here. That said I do agree the name makes sense after seeing what it does.

**Comment by tomchor** [comment]
> That said I do think we can come up with a better name, maybe we can continue to discuss here even after this is merged.

Would `CumulativeScan` work?

**Comment by glwagner** [comment]
Ok here's an idea: replace `Scan` with `Accumulation`. I think a sum can be thought of as "accumulating" without any leaps. We then would have _reducing_ accumulations (intermediate accumulations are not stored), and _cumulative_ accumulations (where the result is not reduced).

We then have the mapping:

* `Scan` to `Accumulation`
* `Accumulation` to `Cumulation` (but we only really need the cumulative sum / integral anyways probably...)
* `Accumulating` to `Cumulating`

Honestly discussing this, the phrase "cumulative sum" is not the most clear, either.

**Comment by glwagner** [comment]
> > That said I do think we can come up with a better name, maybe we can continue to discuss here even after this is merged.
> 
> Would `CumulativeScan` work?

Couldn't this be confusing though, if the "cumulative scan of a sum" is in fact just a sum (and not a cumulative sum)?

**Comment by tomchor** [comment]
> Ok here's an idea: replace `Scan` with `Accumulation`. I think a sum can be thought of as "accumulating" without any leaps. We then would have _reducing_ accumulations (intermediate accumulations are not stored), and _cumulative_ accumulations (where the result is not reduced).

Pardon my being pedantic, but "cumulative accumulations" sounds pretty redundant. We might not have enough words in the English language to describe this functionality precisely :laughing:

**Comment by glwagner** [comment]
> Pardon my being pedantic, but "cumulative accumulations" sounds pretty redundant.

I think "cumulative sum" is redundant too. If I say I have an "accumulation of beans", I'm talking about the whole pile of beans.

It doesn't seem to me that terminology exists, to answer your first question about whether "scan" is commonly used. There isn't any term that is commonly used.

**Comment by iuryt** [comment]
I am not very familiar with this use of scan, and despite "cumulative sum" sounding redundant, it express to me better the idea that I am not simply summing all values of a series. I agree that we might not find a perfect word for that... haha

**Comment by iuryt** [comment]
Could `SerialAccumulation` or `ProgressiveTotaling` also work? Or something with `Aggregation`?
Not sure those are good though, just brainstorming.

**Comment by glwagner** [comment]
Well to be clear, the name we are searching for is something that can describe _both_ reductions like sum, maximum, minimum (and average and integral, which are similar to sum but involve grid metrics) --- _and_ operations like cumsum.

The things these have in common (in contrast to local operations like derivative, plus, minus, etc) is that they involve a loop over one or more dimensions (which is why they have a `dims` property) and therefore cannot be evaluated locally, they have to be precomputed.

For example, we could envision also supporting `sort!` through the `Scan` abstraction...

**Pull request merged**
