### PR TITLE
Creates long_name and units attributes for the time dimension in netcdf outputs

### LINKED ISSUE #1208: Include units and longname for time in netcdf output
This is a very minor thing, but I have been using netCDF files almost exclusively and I've noticed that, while all the length dimensions have their names and units very well defined in the attributes, the `time` dimension does not. 

It's clear what `time` is so this isn't a big issue, but it would be nice somewhere along the line to also include that.

Thanks!

### PR DESCRIPTION
**Pull request by tomchor**
Closes #1208 

This is my first PR to this repository, so let me know if I did anything that wasn't considered best practices!

### CODE REVIEW

**Review by ali-ramadhan — APPROVED** [review]
Looks great! Thanks for adding this!

**Comment by ali-ramadhan** [comment]
Just realized we don't have any tests checking that output attributes were correctly set, but this can addressed in a future PR I think.

**Comment by tomchor** [comment]
> Just realized we don't have any tests checking that output attributes were correctly set, but this can addressed in a future PR I think.

If it helps, at least with this one I tested on my laptop and it worked okay.

**Comment by ali-ramadhan** [comment]
That's definitely good! It's not an issue that would crash a simulation but next time I'm editing `test_output_writers.jl` I'll remember to add some simple tests for this.

**Pull request merged**
