### PR TITLE
Bump to 0.75.3

### PR DESCRIPTION
**Pull request by glwagner**
Captures immersed boundary condition API #2437 docs update #2474

### CODE REVIEW

**Comment by tomchor** [comment]
@glwagner I think the bump here isn't necessary. You bumped the version with the IBM Boundary condition PR, now we just have to tag that version, no?

**Comment by glwagner** [comment]
oh sorry you mean we just didn't register it?

**Comment by glwagner** [comment]
Also theres a warning so I'm bumping again with #2482

**Comment by tomchor** [comment]
> oh sorry you mean we just didn't register it?

Yes, sorry if that wasn't clear!

I thought registering and tagging could be used interchangeably since the registrator automatically registers _and_ tags a new version, no? I'll try to be more precise with the language in the future

**Pull request closed without merging**
