### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Review by francispoulin — APPROVED** [review]

**Comment by francispoulin** [comment]
I looked at the error and see this but don't pretend to know why this has happened.

``` 
Checkpointer [GPU]: Test Failed at /net/ocean/home/data44/data5/glwagner/.buildkite-agent/builds/sverdrup-4/clima/oceananigans/test/test_checkpointer.jl:19
  | Expression: all(test_model.timestepper.G⁻.w.data .≈ true_model.timestepper.G⁻.w.data)
 ```

**Comment by tomchor** [comment]
> I looked at the error and see this but don't pretend to know why this has happened.
> 
> ```
> Checkpointer [GPU]: Test Failed at /net/ocean/home/data44/data5/glwagner/.buildkite-agent/builds/sverdrup-4/clima/oceananigans/test/test_checkpointer.jl:19
>   | Expression: all(test_model.timestepper.G⁻.w.data .≈ true_model.timestepper.G⁻.w.data)
>  ```
> ```

Hmm yeah, the model output changed. Not sure what's causing this since I've never investigated the checkpointer. But the fact that the regression tests work points towards it being the checkpointer itself that changed, and not simulation results, no?

**Comment by navidcy** [comment]
@glwagner any idea why `gpu-simulations-tests` fail?

**Comment by glwagner** [comment]
> @glwagner any idea why `gpu-simulations-tests` fail?

Which grid points are specifically failing in the test?

**Comment by navidcy** [comment]
> > @glwagner any idea why `gpu-simulations-tests` fail?
> 
> Which grid points are specifically failing in the test?

How does one go about and answers this question? The log is not informative... Shall I run the tests myself online and then printout the two arrays?

**Comment by glwagner** [comment]
> > > @glwagner any idea why `gpu-simulations-tests` fail?
> > 
> > 
> > Which grid points are specifically failing in the test?
> 
> How does one go about and answers this question? The log is not informative... Shall I run the tests myself online and then printout the two arrays?

Yeah, that's what you have to do to determine it... not urgent though...

**Comment by glwagner** [comment]
Sorry didn't mean to close!

**Comment by navidcy** [comment]
> > > > @glwagner any idea why `gpu-simulations-tests` fail?
> > > 
> > > 
> > > Which grid points are specifically failing in the test?
> > 
> > 
> > How does one go about and answers this question? The log is not informative... Shall I run the tests myself online and then printout the two arrays?
> 
> Yeah, that's what you have to do to determine it... not urgent though...

I tried to do that but the HPC at ANU when I use a queue with GPU access it does not have internet access. So it stops at `include("data_dependencies.jl")` line...

**Comment by glwagner** [comment]
If you download data on the login node it should work, because DataDeps doesn't need to download if the file is present

**Comment by glwagner** [comment]
@ali-ramadhan says don't merge because there is a latent bug in CUDA 3.4.2!

**Comment by ali-ramadhan** [comment]
@navidcy Due to #1995 is it worth pinning CUDA.jl to the current version? Might also _magically_ fix some GPU issues although I see that `cpu-time-stepping-tests-2` is also failing.

**Comment by navidcy** [comment]
> @navidcy Due to #1995 is it worth pinning CUDA.jl to the current version? Might also _magically_ fix some GPU issues although I see that `cpu-time-stepping-tests-2` is also failing.

I'll try this. However, these GPU-related error started appearing in #1994 as well...

**Comment by navidcy** [comment]
I removed the "Do not merge" since it's now pinned to CUDA @ v3.3.4. :)

**Comment by navidcy** [comment]
omg, @ali-ramadhan! gpu-simulation tests passed!

**Review by glwagner — APPROVED** [review]

**Review by ali-ramadhan — COMMENTED** [review]
🎉

**Pull request merged**
