### PR TITLE
Attempt to unclog documentation builds on Buildkite

### PR DESCRIPTION
**Pull request by ali-ramadhan**

### CODE REVIEW

**Review by glwagner — APPROVED** [review]

**Comment by ali-ramadhan** [comment]
@mukund-gupta Maybe try this branch to see if it fixes the issue you encountered with this error: https://buildkite.com/clima/oceananigans/builds/1947#b5157111-6448-4db8-bc8b-8a777f85001a/19-300

**Comment by ali-ramadhan** [comment]
Seems that many builds are not getting stuck on both CPU and GPU. I wonder if it's a new package version causing problems since this started happening after I updates the Manifest.toml.

And the docs update `docs/Manifest.toml` before building so it could explain why the docs build was getting stuck while the others seemed fine: https://github.com/CliMA/Oceananigans.jl/blob/e02790202614916bd918a039216a73c61ff7048a/.buildkite/pipeline.yml#L326

**Comment by ali-ramadhan** [comment]
Can confirm that tests get stuck when I manually run `] test` on Tartarus. It first gets stuck at

```
[2021/04/09 09:02:15.825] INFO    Testing budgets with Flux boundary conditions [GPU]...
[2021/04/09 09:02:15.825] INFO      Testing budgets with Flux boundary conditions [GPU, (Periodic, Bounded, Bounded), u, north]...
```

so presumably whatever is causing it to hang is a commonly used function/bit of code...

**Comment by ali-ramadhan** [comment]
When I killed it I got

```
fatal: error thrown and no exception handler available.                                                                                                                                                                                                                                
InterruptException()                                                                                                                                     
jl_mutex_unlock at /buildworker/worker/package_linux64/build/src/locks.h:143 [inlined]                                                                             
jl_task_get_next at /buildworker/worker/package_linux64/build/src/partr.c:476                                                                                                                                                                                                                  
^Cpoptask at ./task.jl:704                                                                                                                                                                                                                                                                     
wait at ./task.jl:712 [inlined]                                                                                                                                                                             
task_done_hook at ./task.jl:442                                                                                                                                                                                                                                                                
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]                                                                                                                                                                                                                
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398                                                                                                                  
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]                                                                                                                                                                                                              
jl_finish_task at /buildworker/worker/package_linux64/build/src/task.c:198                                                                               
start_task at /buildworker/worker/package_linux64/build/src/task.c:717                                                                                   
unknown function (ip: (nil))                                                                                                                                     
WARNING: Force throwing a SIGINT
```

so maybe we have a bad KernelAbstractions.jl `wait`?

**Comment by glwagner** [comment]
Ah, interesting. I think you're right that it seems probable to be a KernelAbstractions thingy (but want to point out that `wait` can be called in other contexts / packages and has usage outside `KernelAbstactions`).

Also explains why it mysteriously started happening due to auto update of `docs/Manifest.toml`. Should we stop updating `docs/Manifest.toml`? Is that possible?

**Comment by ali-ramadhan** [comment]
I was able to reproduce the hanging by running the test manually in the REPL. It gets stuck somewhere in `run!(simulation)` but couldn't get a useful stacktrace out.

It does not hang in v0.54.0.

I tried downgrading and pinning KernelAbstractions.jl and CUDA.jl back down to the version used in the v0.54.0 Manifest.toml but it still got stuck... Could be some other package.

> Should we stop updating docs/Manifest.toml? Is that possible?

Couldn't find anything in the Pkg.jl docs that would help but maybe we should switch the order of the `instantiate` and `develop` calls here? https://github.com/CliMA/Oceananigans.jl/blob/e02790202614916bd918a039216a73c61ff7048a/.buildkite/pipeline.yml#L326

**Comment by navidcy** [comment]
I notice that in the [Documenter.jl Docs](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/) it's suggested:

```julia
julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
```

**Comment by glwagner** [comment]
Here's the differences in how `docs/Manifest.toml` is updated for a successful and the current build:

| [build 1872](https://buildkite.com/clima/oceananigans/builds/1872#a5258c04-eef6-400d-88ab-7523a0ed366c) |  [build 1983](https://buildkite.com/clima/oceananigans/builds/1983#8cacbe56-6c7e-403b-8ef2-18cdd7f6ef68) from this PR |
:-------------------------:|:-------------------------:
| Docs build successfully! | Build is hanging? |
| image | image

The differences are:

* ArrayInterface (3.1.6 -> 3.1.7)
* CUDA (2.4.1 -> 2.4.3)
* ChainRulesCore (0.9.36 -> 0.9.37)
* GPUArrays (6.2.1 -> 6.2.2)
* NNlib (0.7.17 -> 0.7.18)
* StructTypes (1.5.0 -> 1.5.2)
* TaylorSeries (0.10.11 -> 0.10.12)

**Comment by glwagner** [comment]
@navidcy I think its a red herring. The issue is that the update of some package is causing `run!(simulation)` to hang. For prior builds this problem only affects the documentation build (because only `docs/Manifest.toml` was updated, not `Oceananigans.jl/Manifest.toml`). Here, we have updated _all_ packages and now the issue has infected the entire build.

**Comment by glwagner** [comment]
Actually, I believe that @ali-ramadhan found that the issue is _compilation_ of `run!(simulation)`. For some reason the compiler chokes on it. The weird thing is that `time_step!(model, dt)` works (which is what I'd naively expect was the issue).

**Comment by navidcy** [comment]
omg... I'm thoroughly confused.

what's a red herring?

also, what is puzzling even more, is that on the list on the left (that you mention all is "ok") I see
CUDA v2.4.1 + FFTW v1.3.2
But FFTW v1.3.2 requires AbstractFFTs v1 while CUDA v2.4.1 compats only allow AbstractFFTs 0.4, 0.5. How could that be?

**Comment by glwagner** [comment]
https://github.com/JuliaGPU/CUDA.jl/blob/5767efb7fa65c3811b187ab310f0bb5e484bc2e4/Project.toml#L31

**Comment by navidcy** [comment]
> https://github.com/JuliaGPU/CUDA.jl/blob/5767efb7fa65c3811b187ab310f0bb5e484bc2e4/Project.toml#L31

That's not v2.4.1...
This is that:

https://github.com/JuliaGPU/CUDA.jl/blob/v2.4.1/Project.toml

**Comment by glwagner** [comment]
Touche.

**Comment by glwagner** [comment]
PencilFFTs 0.12.2 also requires AbstractFFTs v1:

https://github.com/jipolanco/PencilFFTs.jl/blob/master/Project.toml

**Comment by navidcy** [comment]
> PencilFFTs 0.12.2 also requires AbstractFFTs v1:
> 
> https://github.com/jipolanco/PencilFFTs.jl/blob/master/Project.toml

Indeed....! But again the url you provided is from PencilFFTs#master and not [v0.12.2](https://github.com/jipolanco/PencilFFTs.jl/blob/v0.12.2/Project.toml)... :)

**Comment by navidcy** [comment]
I'm simply confused with the whole shenanigans of this issue. I need a fresh start perhaps :)

**Comment by glwagner** [comment]
> > PencilFFTs 0.12.2 also requires AbstractFFTs v1:
> > https://github.com/jipolanco/PencilFFTs.jl/blob/master/Project.toml
> 
> Indeed....! But again the url you provided is from PencilFFTs#master and not [v0.12.2](https://github.com/jipolanco/PencilFFTs.jl/blob/v0.12.2/Project.toml)... :)

True, its still tagged as 0.12.2 but I guess the compat could have been updated without bumping the version.

**Comment by glwagner** [comment]
The first build to exhibit the issue (all tests pass except docs) appears to be [1881](https://buildkite.com/clima/oceananigans/builds/1881#481a169e-486f-478f-973e-41c3b9bbc1da).

**Comment by navidcy** [comment]
Nice. This might help our investigations. Will get to it tomorrow.

**Comment by ali-ramadhan** [comment]
Still also confused here... Just merged `master` into this branch. Maybe things magically got fixed over the weekend 😄

**Comment by navidcy** [comment]
> Still also confused here... Just merged `master` into this branch. Maybe things magically got fixed over the weekend 😄

Wishful thinking..

**Comment by glwagner** [comment]
Can close this now since #1573 ...

**Pull request closed without merging**
