### PR TITLE
Bring back support for closure tuples with CATKE

### LINKED ISSUE #3804: Error using closure tuples with CATKEVerticalDiffusivity
```julia
using Oceananigans
using Oceananigans.Units
using Oceananigans.TurbulenceClosures: CATKEVerticalDiffusivity

grid = RectilinearGrid(size=128, z=(-128, 0), topology=(Flat, Flat, Bounded))

closure = (VerticalScalarDiffusivity(VerticallyImplicitTimeDiscretization(), κ=1e-4),
           CATKEVerticalDiffusivity())

model = HydrostaticFreeSurfaceModel(; grid, closure,
                                    tracers = (:b, :e),
                                    buoyancy = BuoyancyTracer())

bᵢ(z) = 1e-5 * z
set!(model, b = bᵢ)
simulation = Simulation(model, Δt=1minute, stop_iteration=10)

run!(simulation)
```

generates the error

```julia
julia> include("tupled_vertical_diffusion.jl")
[ Info: Initializing simulation...
[ Info:     ... simulation initialization complete (2.367 seconds)
[ Info: Executing initial time step...
ERROR: LoadError: type Tuple has no field κe
Stacktrace:
  [1] getproperty
    @ ./Base.jl:37 [inlined]
  [2] time_step_catke_equation!(model::HydrostaticFreeSurfaceModel{…})
    @ Oceananigans.TurbulenceClosures.TKEBasedVerticalDiffusivities ~/Projects/Oceananigans.jl/src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/time_step_catke_equation.jl:25
  [3] compute_diffusivities!(diffusivities::@NamedTuple{…}, closure::CATKEVerticalDiffusivity{…}, model::HydrostaticFreeSurfaceModel{…}; parameters::Symbol)
    @ Oceananigans.TurbulenceClosures.TKEBasedVerticalDiffusivities ~/Projects/Oceananigans.jl/src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_vertical_diffusivity.jl:197
  [4] compute_diffusivities!
    @ ~/Projects/Oceananigans.jl/src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_vertical_diffusivity.jl:181 [inlined]
  [5] #compute_diffusivities!#24
    @ ~/Projects/Oceananigans.jl/src/TurbulenceClosures/closure_tuples.jl:79 [inlined]
  [6] compute_diffusivities!
    @ ~/Projects/Oceananigans.jl/src/TurbulenceClosures/closure_tuples.jl:76 [inlined]
  [7] update_state!(model::HydrostaticFreeSurfaceModel{…}, grid::RectilinearGrid{…}, callbacks::Tuple{}; compute_tendencies::Bool)
    @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/Projects/Oceananigans.jl/src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl:72
  [8] update_state!
    @ ~/Projects/Oceananigans.jl/src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl:64 [inlined]
  [9] update_state!
    @ ~/Projects/Oceananigans.jl/src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl:29 [inlined]
 [10] time_step!(model::HydrostaticFreeSurfaceModel{…}, Δt::Float64; callbacks::Tuple{}, euler::Bool)
    @ Oceananigans.TimeSteppers ~/Projects/Oceananigans.jl/src/TimeSteppers/quasi_adams_bashforth_2.jl:123
 [11] time_step!(sim::Simulation{HydrostaticFreeSurfaceModel{…}, Float64, Float64, OrderedCollections.OrderedDict{…}, OrderedCollections.OrderedDict{…}, OrderedCollections.OrderedDict{…}})
    @ Oceananigans.Simulations ~/Projects/Oceananigans.jl/src/Simulations/run.jl:122
 [12] run!(sim::Simulation{HydrostaticFreeSurfaceModel{…}, Float64, Float64, OrderedCollections.OrderedDict{…}, OrderedCollections.OrderedDict{…}, OrderedCollections.OrderedDict{…}}; pickup::Bool)
    @ Oceananigans.Simulations ~/Projects/Oceananigans.jl/src/Simulations/run.jl:97
 [13] run!(sim::Simulation{HydrostaticFreeSurfaceModel{…}, Float64, Float64, OrderedCollections.OrderedDict{…}, OrderedCollections.OrderedDict{…}, OrderedCollections.OrderedDict{…}})
    @ Oceananigans.Simulations ~/Projects/Oceananigans.jl/src/Simulations/run.jl:85
 [14] top-level scope
    @ ~/Projects/Oceananigans.jl/validation/vertical_mixing_closures/tupled_vertical_diffusion.jl:20
 [15] include(fname::String)
    @ Base.MainInclude ./client.jl:489
 [16] top-level scope
    @ REPL[1]:1
in expression starting at /Users/gregorywagner/Projects/Oceananigans.jl/validation/vertical_mixing_closures/tupled_vertical_diffusion.jl:20
Some type information was truncated. Use `show(err)` to see complete types.
```

### PR DESCRIPTION
**Pull request by glwagner**
Resolves #3804

@hengdiliang let me know if this solves your issue

### CODE REVIEW

**Review by hengdiliang — APPROVED** [review]
Thanks!

**Comment by glwagner** [comment]
@hengdiliang does this solve your issue?

Turbulence closure tests pass in a reasonable amount of time (4 min on CPU, 26 min on GPU) so it would seem previous compilation issues with closure tuples are mitigated now.

**Comment by glwagner** [comment]
Can I get a review? @navidcy ?

**Comment by glwagner** [comment]
@hengdiliang could be nice if you post results from a little validation test just to document that this not only runs, but runs correctly

**Comment by hengdiliang** [comment]
I tried to update Ocenanigans version in ClimaOceanBiogeochemistry as:
```
Oceananigans v0.92.0 `https://github.com/CliMA/Oceananigans.jl#glw/tuples-with-catke`
```
Then I ran CATKE together with horizontal closures:
```
catke = CATKEVerticalDiffusivity()
horizontal_closure = HorizontalScalarDiffusivity(ν=1e3)
```
It still returns an error message:
`ERROR: type Tuple has no field κe`

Is it indicating the problem is still unresolved, or am I testing in an incorrect way?

**Comment by glwagner** [comment]
Hmm, check your environment again, or try restarting julia, because I don't think you should get that error (the tests pass for example)

**Comment by hengdiliang** [comment]
@glwagner  Yes you are right. I tried restarting Julia, and it worked without the error message. Sorry!

**Comment by glwagner** [comment]
> @glwagner Yes you are right. I tried restarting Julia, and it worked without the error message. Sorry!

no worries!

**Pull request merged**
