### PR TITLE
Fixes checkpointer GPU to CPU loading and writing fields with function boundary conditions

### PR DESCRIPTION
**Pull request by sandreza**
Fixes GPU to CPU loading and writing fields with function boundary conditions

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Awesome, thanks!

Just a quick explanation so we can also add a comment to the line this PR modifies: Previously if a required property such as the velocity fields contained references to functions (usually through boundary conditions) then they weren't saved to disk. However, checkpoint restoration is impossible without the velocity fields. So if a required property contains function references it should still be serialized to disk. Through dispatch, fields are serialized such that function boundary conditions are replaced with `missing` so everything works out and restoration is possible, although boundary conditions need to be restored manually.

So I actually think we're missing the code that allows for CPU -> GPU checkpoint restoration and I can't find it, but we should add it back in. It changes this line

https://github.com/sandreza/Oceananigans.jl/blob/625db8d8eadeeed7e9e5591e2b01c0ee8dd3623c/src/OutputWriters/checkpointer.jl#L126

to something like

```julia
arch = haskey(kwargs, :architecture) ? kwargs[:architecture] : file["architecture"]
```
so that architectures passed via `kwargs` aren't overwritten by the architecture stored in the checkpoint file.

We should also add two tests to make sure these issues don't occur in the future:
1. Checkpoint a model with at least one field containing a function boundary condition. Make sure you can restore from checkpoint, and ensure that the boundary condition shows up as `missing` when doing so (without manual restoration). Restoration should print a warning about the `missing` boundary condition. Time stepping a model with a `missing` boundary condition should produce an understandable error.
2. If a GPU is available, we should checkpoint a CPU model and restore it using `kwargs = Dict(:architecture => GPU())` and make sure the restored model is a GPU model with CuArrays and that we can time step it.

**Comment by glwagner** [comment]
Right --- this is something that slipped between the cracks when boundary conditions were added as `Field` properties, right?

**Comment by ali-ramadhan** [comment]
Yeah checkpointing is fine if you have no functions in your boundary conditions but I don't think we have a test where a model with function boundary conditions is checkpointed, so we should add one as part of this PR.

**Comment by ali-ramadhan** [comment]
Test currently fails because when restoring a function boundary condition from checkpoint it should come back as `missing` (functions cannot be serialized). However, it seems that the default boundary conditions actually show up so this bug needs to be investigated. I believe the bug lies in the `TracerFields` function but will look into it a bit more.

**Pull request merged**
