### PR TITLE
File splitting in `NetCDFOutputWriter` when `max_filesize` is exceeded

### PR DESCRIPTION
**Pull request by josuemtzmo**
This PR aims to allow the user to split netCDF files into smaller files when the filesize exceeds the max_filesize. This addresses https://github.com/CliMA/Oceananigans.jl/issues/2967, and follows the PR https://github.com/CliMA/Oceananigans.jl/pull/3506

### CODE REVIEW

**Review by navidcy — APPROVED** [review]
lgtm!

**Comment by glwagner** [comment]
we could merge without the test, and then open another PR immediately if tests don't pass. If someone wants to take responsibility for putting in a quick fix for a distributed test (which seems unlikely)

**Comment by glwagner** [comment]
good solution to the buildkite problem :-D

**Comment by navidcy** [comment]
@josuemtzmo welcome to Oceananigans

**Comment by navidcy** [comment]
(Merge at your convenience.)

**Comment by navidcy** [comment]
Yo @josuemtzmo, I'll merge. Congrats still hold!

**Comment by josuemtzmo** [comment]
Sorry, I was going to merge it today.

**Comment by navidcy** [comment]
Don't apologize! I just wanted to merge it to #3503 in the hope I can merge that as soon as test pass (if they pass)...

**Pull request merged**
