### PR TITLE
Extend operations for two `ZeroField`s

### PR DESCRIPTION
**Pull request by zhihua-zheng**
Code suggested by @glwagner.

### CODE REVIEW

**Review by tomchor — COMMENTED** [review]
Can you add tests?

**Comment by zhihua-zheng** [comment]
> Can you add tests?

New tests passed.

**Comment by tomchor** [comment]
> > Can you add tests?
> 
> New tests passed.

Thanks! Some of the tests segfaulted so I restarted them. I'll approve it once tests pass and then we should be ready to go! Feel free to ping me if I'm taking too long ;)

**Review by glwagner — APPROVED** [review]

**Review by tomchor — APPROVED** [review]
Tests passed!

**Comment by tomchor** [comment]
@glwagner are you okay if we register a new patch release version so that we can move forward with https://github.com/tomchor/Oceanostics.jl/pull/169 in Oceanostics?

**Comment by glwagner** [comment]
Go for it

**Comment by tomchor** [comment]
> Go for it

Thanks! `Project.toml` is already at 0.90.14, while the last registered version is still at 0.90.13, so I'll just register a new version without bumping the patch number.

**Pull request merged**
