### PR TITLE
New Threaded Benchmark Scripts

### PR DESCRIPTION
**Pull request by hennyg888**
Co-authored-by: Francis J. Poulin <fpoulin@uwaterloo.ca>

I've added back the threaded benchmark written by @francispoulin in an older branch. I also added plots to it.
There is actually already a threaded benchmark script:
https://github.com/CliMA/Oceananigans.jl/blob/master/benchmark/benchmark_multithreading.jl
https://github.com/CliMA/Oceananigans.jl/blob/master/benchmark/benchmark_multithreading_single.jl
They differ in that the one I'm adding is essentially weak scaling shallow water model, while the one that's already there is strong scaling nonhydrostatic model.
If everyone thinks that it's appropriate, then I'll likely change the name of the extant benchmarking scripts to more accurately reflect their content. 
I would likely also do some more minor changes such as changing the default grid size down from 512^3, adding in plots, and configuring the output tables a bit more.

### CODE REVIEW

**Comment by hennyg888** [comment]
The results from running the new multithreading benchmark scripts are posted in #1861.

**Review by francispoulin — APPROVED** [review]
Looks good to me.  This will be a good starting point for when we want to test the threading efficiency of the code.

Strange that docs don't build but can't believe it's because of these files.

**Comment by glwagner** [comment]
> Looks good to me. This will be a good starting point for when we want to test the threading efficiency of the code.
> 
> Strange that docs don't build but can't believe it's because of these files.

CI was offline yesterday and is just back this morning! Let's restart and see what happens.

**Comment by glwagner** [comment]
What are the current results of the benchmark?

**Comment by francispoulin** [comment]
> What are the current results of the benchmark?

I think Henry has the results at the top of #1861.  They can be copied here if you prefer.

**Comment by francispoulin** [comment]
Hmm, docs still seem to fail.

**Comment by glwagner** [comment]
> Hmm, docs still seem to fail.

What's the error?

**Comment by francispoulin** [comment]
Copied below.

```
ERROR: LoadError: `makedocs` encountered an error. Terminating build
--
  | Stacktrace:
  | [1] error(s::String)
  | @ Base ./error.jl:33
  | [2] runner(#unused#::Type{Documenter.Builder.RenderDocument}, doc::Documenter.Documents.Document)
  | @ Documenter.Builder /storage7/buildkite-agent/.julia-3423/packages/Documenter/4JDQo/src/Builder.jl:255
  | [3] dispatch(#unused#::Type{Documenter.Builder.DocumentPipeline}, x::Documenter.Documents.Document)
  | @ Documenter.Utilities.Selectors /storage7/buildkite-agent/.julia-3423/packages/Documenter/4JDQo/src/Utilities/Selectors.jl:170
  | [4] #2
  | @ /storage7/buildkite-agent/.julia-3423/packages/Documenter/4JDQo/src/Documenter.jl:257 [inlined]
  | [5] cd(f::Documenter.var"#2#3"{Documenter.Documents.Document}, dir::String)
  | @ Base.Filesystem ./file.jl:106
  | [6] #makedocs#1
  | @ /storage7/buildkite-agent/.julia-3423/packages/Documenter/4JDQo/src/Documenter.jl:256 [inlined]
  | [7] top-level scope
  | @ ~/builds/tartarus-9/clima/oceananigans/docs/make.jl:155
  | in expression starting at /var/lib/buildkite-agent/builds/tartarus-9/clima/oceananigans/docs/make.jl:155
  | 🚨 Error: The command exited with status 1
  | user command error: exit status 1
```

**Comment by hennyg888** [comment]
After going down the rabbit hole of `Documenter.jl` all I can say is that the error message we're seeing means nothing.
All it means that in the makedocs process, there was an error. It is not the makedocs that's throwing the error, but actually something much earlier that pushed an error into the docs.internal.errors field of the document object. Here's where it happens as according to the error log we can see:
https://github.com/JuliaDocs/Documenter.jl/blob/master/src/Builder.jl#L255
As seen in https://github.com/CliMA/Oceananigans.jl/blob/master/docs/make.jl#L162, the makedocs strict option is set to true which follows that:
**`strict`** -- [`makedocs`](@ref) fails the build right before rendering if it encountered
any errors with the document in the previous build phases.
Interesting enough, the error we see can be summarized as "error: there's an error", but does not give any more info on what exactly the error was.

**Comment by francispoulin** [comment]
Thank you @hennyg888 for looking this up.  It is very strange that the docs still seem to keep on failing, even though we didn't change any of the docs in this PR.

Anyone have any ideas why this might be failing?

**Comment by francispoulin** [comment]
This error is also happening in #1892 so presumably not because of the changes made to the code.

**Comment by glwagner** [comment]
> Copied below.
> 
> ```
> ERROR: LoadError: `makedocs` encountered an error. Terminating build
> --
>   | Stacktrace:
>   | [1] error(s::String)
>   | @ Base ./error.jl:33
>   | [2] runner(#unused#::Type{Documenter.Builder.RenderDocument}, doc::Documenter.Documents.Document)
>   | @ Documenter.Builder /storage7/buildkite-agent/.julia-3423/packages/Documenter/4JDQo/src/Builder.jl:255
>   | [3] dispatch(#unused#::Type{Documenter.Builder.DocumentPipeline}, x::Documenter.Documents.Document)
>   | @ Documenter.Utilities.Selectors /storage7/buildkite-agent/.julia-3423/packages/Documenter/4JDQo/src/Utilities/Selectors.jl:170
>   | [4] #2
>   | @ /storage7/buildkite-agent/.julia-3423/packages/Documenter/4JDQo/src/Documenter.jl:257 [inlined]
>   | [5] cd(f::Documenter.var"#2#3"{Documenter.Documents.Document}, dir::String)
>   | @ Base.Filesystem ./file.jl:106
>   | [6] #makedocs#1
>   | @ /storage7/buildkite-agent/.julia-3423/packages/Documenter/4JDQo/src/Documenter.jl:256 [inlined]
>   | [7] top-level scope
>   | @ ~/builds/tartarus-9/clima/oceananigans/docs/make.jl:155
>   | in expression starting at /var/lib/buildkite-agent/builds/tartarus-9/clima/oceananigans/docs/make.jl:155
>   | 🚨 Error: The command exited with status 1
>   | user command error: exit status 1
> ```

This is only the top of the error. Farther down, we see

```
┌ Warning: failed to run `@example` block in src/generated/shallow_water_Bickley_jet.md:70-77
--
  | │ ```@example shallow_water_Bickley_jet
  | │ model = ShallowWaterModel(architecture = GPU(),
  | │                           timestepper = :RungeKutta3,
  | │                           advection = WENO5(),
  | │                           grid = grid,
  | │                           gravitational_acceleration = g,
  | │                           coriolis = FPlane(f=f))
  | │ ```
  | │   c.value = CUDA error (code 100, CUDA_ERROR_NO_DEVICE)
  | └ @ Documenter.Expanders /storage7/buildkite-agent/.julia-3423/packages/Documenter/4JDQo/src/Expanders.jl:563
```

**Comment by francispoulin** [comment]
Ah, so it's solving the `ShallowWaterModel` example on a `GPU` instead of a `CPU`.  I thought someone changed that already but we can certainly try that and see if that improves things.

**Comment by glwagner** [comment]
> Ah, so it's solving the `ShallowWaterModel` example on a `GPU` instead of a `CPU`. I thought someone changed that already but we can certainly try that and see if that improves things.

What happened was that this PR was merged into master with the failing docs. Then, this branch was opened from master at that time. Soon after that the change was fixed, but master has not been merged into this branch. To fix this problem, merge master into this branch.

**Comment by hennyg888** [comment]
@francispoulin @glwagner @ali-ramadhan @christophernhill 
I took a look at all the benchmarking scripts in our benchmarks folder and realized that many of them are very similar and can be unified. For example, the single script for shallow water model's strong and weak scaling differ only by one substring. 
The latest commit I pushed to this branch unifies all of the launcher and single scripts for shallow water model into three scripts. Now, at the top of the launcher script `distributed_shallow_water_model.jl`, there are two boolean variables that the user can toggle for strong vs weak scaling and mpi vs threaded parallel execution. Everything including output graphs, HTML tables, and info messages also change accordingly based on the two booleans.

There are some other features that Francis and I have discussed but would like your approval first before adding them in.
Other possible additions to the script can include a for loop which wraps around the whole launcher script which loops through the strong/weak scaling and mpi/threaded parallelism options to allow for running 4 benchmarks at once. Another possible addition is to have what model is benchmarked also be an option. Granted, I could just copy and paste the shallow water model scripts and replace all instances of `shallow water` with `nonhydrostatic` or `hydrostatic` and tune some options a little bit, but then this would again cause avoidable clutter. Having what model is benchmarked as an easily changeable option can be achieved through a model setup function that dispatches what model is initialized based on a custom model type object that's passed to it. Everything else would be cosmetic formatting of outputs and info messages.

**Pull request merged**
