### PR TITLE
Use grids' native coordinates in continuous BCs 

### LINKED ISSUE #3073: Continuous boundary functions don't use grids' native coordinates
After #2979 the following is wrong since it refers to `x, y` coords and not the grid's native ones which they can be `λ, φ` for curvilinear grids.

https://github.com/CliMA/Oceananigans.jl/blob/c765c98c5880eb8a4a570a39b89824af01d75203/src/BoundaryConditions/continuous_boundary_function.jl#L105-L133

I think we should replace, e.g.,

```julia
y = ynode(i′, j, k, grid, Face(), LY(), LZ())
z = znode(i′, j, k, grid, Face(), LY(), LZ())
```

with

```julia
_, y, z = node(i′, j, k, grid, Face(), LY(), LZ())
```

### PR DESCRIPTION
**Pull request by navidcy**
Resolves #3073

### CODE REVIEW

**Review by glwagner — APPROVED** [review]

**Comment by navidcy** [comment]
Gotcha. Might try to remedy this.

**Comment by glwagner** [comment]
It might work to write

```julia
y = node(i′, j, k, grid, Face(), LY(), LZ())[2]
```

**Comment by navidcy** [comment]
But `node` will compute all 3 components anyway. Isn't this the issue @simone-silvestri was referring to?

**Comment by glwagner** [comment]
Since `[2]` is resolved at compile time and `2` is known I believe this can get compiled away, ie the result will simply be evaluating the second component of tuple

**Comment by glwagner** [comment]
This illustrates it:

```julia
julia> f(x) = x + 1
f (generic function with 1 method)

julia> g(x) = 2x
g (generic function with 1 method)

julia> h(x) = (f(x), g(x))
h (generic function with 1 method)

julia> m(x) = h(x)[1]
m (generic function with 1 method)
```

So `m(x)` only needs to evaluate `f` and doesn't need to compute "2x". This gets compiled away at the LLVM level:

```julia
julia> @code_llvm m(1)
;  @ REPL[21]:1 within `m`
define i64 @julia_m_402(i64 signext %0) #0 {
top:
; ┌ @ REPL[20]:1 within `h`
; │┌ @ REPL[18]:1 within `f`
; ││┌ @ int.jl:87 within `+`
     %1 = add i64 %0, 1
; └└└
  ret i64 %1
}

julia> @code_llvm f(1)
;  @ REPL[18]:1 within `f`
define i64 @julia_f_406(i64 signext %0) #0 {
top:
; ┌ @ int.jl:87 within `+`
   %1 = add i64 %0, 1
; └
  ret i64 %1
}
```

In constrast if we call `h` we get

```julia
julia> @code_llvm h(1)
;  @ REPL[20]:1 within `h`
define void @julia_h_408([2 x i64]* noalias nocapture sret([2 x i64]) %0, i64 signext %1) #0 {
top:
; ┌ @ REPL[18]:1 within `f`
; │┌ @ int.jl:87 within `+`
    %2 = add i64 %1, 1
; └└
; ┌ @ REPL[19]:1 within `g`
; │┌ @ int.jl:88 within `*`
    %3 = shl i64 %1, 1
; └└
  %.sroa.0.0..sroa_idx = getelementptr inbounds [2 x i64], [2 x i64]* %0, i64 0, i64 0
  store i64 %2, i64* %.sroa.0.0..sroa_idx, align 8
  %.sroa.2.0..sroa_idx1 = getelementptr inbounds [2 x i64], [2 x i64]* %0, i64 0, i64 1
  store i64 %3, i64* %.sroa.2.0..sroa_idx1, align 8
  ret void
}
```

We can also getindex 2:

```julia
julia> n(x) = h(x)[2]
n (generic function with 1 method)

julia> @code_llvm n(1)
;  @ REPL[29]:1 within `n`
define i64 @julia_n_414(i64 signext %0) #0 {
top:
; ┌ @ REPL[20]:1 within `h`
; │┌ @ REPL[19]:1 within `g`
; ││┌ @ int.jl:88 within `*`
     %1 = shl i64 %0, 1
; └└└
  ret i64 %1
}
```

**Pull request merged**
