### PR TITLE
(0.91.4) Fix interpolations in off-diagonal components of strain-rate tensor

### PR DESCRIPTION
**Pull request by tomchor**
I think the interpolation here for the w-terms of the strain-rate tensor hasn't being correctly done. In particular it was assuming  that `w` was a `CenterField`.

Can someone please double-check?

### CODE REVIEW

**Review by glwagner — APPROVED** [review]
I think this is right

**Comment by tomchor** [comment]
If people are okay with it, I'll merge as soon as tests pass and register a new patch version, since this is a bugfix.

**Comment by tomchor** [comment]
These tests aren't passing, and I have no clue why. The error is:

```
ERROR: `Enzyme=7da242da-08ed-463a-9acd-ee780be4f1d9` depends on `ChainRulesCore=d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4`, but no such entry exists in the manifest.
```

But I never changed anything related to that. Does anyone know what's going on?

**Comment by navidcy** [comment]
Stochastic CI variability? I restarted them...

**Comment by tomchor** [comment]
Okay finally tests passed!

@navidcy I tried restarting the tests over and over (honestly more than 10 times over the past few days) and they always failed. I could only make them pass this morning when I restarted them one at a time. That is, starting one, and only restarting the next failed test when the previous one had fully run.

So maybe the variability we see in tests has to do with different processes trying to access the same resources... ?

**Comment by navidcy** [comment]
What you observe about one at a time etc I have observed it other times but I can’t say for sure…

**Comment by glwagner** [comment]
> Okay finally tests passed!
> 
> @navidcy I tried restarting the tests over and over (honestly more than 10 times over the past few days) and they always failed. I could only make them pass this morning when I restarted them one at a time. That is, starting one, and only restarting the next failed test when the previous one had fully run.
> 
> So maybe the variability we see in tests has to do with different processes trying to access the same resources... ?

Yes it is a race condition

**Pull request merged**
