### PR TITLE
Fixing grid and calling NormalFlow

### PR DESCRIPTION
**Pull request by francispoulin**

### CODE REVIEW

**Comment by glwagner** [comment]
Do `NormalFlow` boundary conditions really work here?

**Comment by glwagner** [comment]
If we are going to update this example, it's probably better to use `ImmersedBoundaryGrid` like in the other immersed boundary validation experiments...

**Comment by francispoulin** [comment]
> Do `NormalFlow` boundary conditions really work here?

I don't know but it complained that it could find them so I thought we should specify where they are.  Maybe this needs to be changed?

**Comment by francispoulin** [comment]
> If we are going to update this example, it's probably better to use `ImmersedBoundaryGrid` like in the other immersed boundary validation experiments...

Good point and I can look into that before this is reviewed.

**Comment by glwagner** [comment]
> > Do `NormalFlow` boundary conditions really work here?
> 
> I don't know but it complained that it could find them so I thought we should specify where they are. Maybe this needs to be changed?

The problem is that the velocity field is far from uniform at the outlet where a constant outflow of 1.0 is being prescribed. I wonder if this would cause numerical issues. To use `NormalFlow` we either need a sponge layer, or to implement a more sophisticated outlet condition like an Orlanski condition.

**Comment by whitleyv** [comment]
@francispoulin @glwagner 
> problem is that the velocity field is far from uniform at the outlet where a constant outflow of 1.0 is being prescribed. I wonder if this would cause numerical issues. To use `NormalFlow` we may either need a sponge layer, or to implement a more sophisticated outlet condition like an Orlanski condition.

I have a version with a sponge layer I used for my own testing I could add.

I updated the arbitrary grid branch to have the validation correct with normal flow's location specified, but the master version never got changed.

> > If we are going to update this example, it's probably better to use `ImmersedBoundaryGrid` like in the other immersed boundary validation experiments...
> 
> Good point and I can look into that before this is reviewed.

I was waiting for no-slip condition on the `ImmersedBoundaryGrid` before this validation is useful again, because otherwise you just get fun videos, but no actual validation. I have a work in progress script with a bunch of analysis I can add when we're ready to do so. Until then it might be best just to remove this file completely because it's so out of date.

**Comment by francispoulin** [comment]
I don't mind this example being removed since it's pretty old. It would be nice to bring it back with the newer methods, and if that means until after no-slip is polished off, I don't see a problem with that.

**Comment by glwagner** [comment]
Removing it is fine with me.

**Comment by glwagner** [comment]
I think this is superceded by #1824

**Comment by glwagner** [comment]
@francispoulin we might not need this anymore.

**Comment by francispoulin** [comment]
> @francispoulin we might not need this anymore.

Agreed

**Pull request closed without merging**
