### PR TITLE
Fix inconsistent variable definition in `ScalarDiffusivity` constructor

### PR DESCRIPTION
**Pull request by navidcy**
The main contribution of this PR is that it corrects the `time_discretization` positional argument in the `ScalarDiffusivity` constructor. It was sometimes referred to as `time_discretization` and other times as `time_disc`.

### CODE REVIEW

**Review by simone-silvestri — APPROVED** [review]

**Review by glwagner — APPROVED** [review]
Hard work by unsung heros

**Comment by navidcy** [comment]
`test_dynamics.jl` fail.

Is this correct here?
https://github.com/CliMA/Oceananigans.jl/blob/ad110ecdc635192c110e229df4fbfa04fc7a2266/src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl#L39

**Comment by glwagner** [comment]
> `test_dynamics.jl` fail.
> 
> Is this correct here?
> 
> https://github.com/CliMA/Oceananigans.jl/blob/ad110ecdc635192c110e229df4fbfa04fc7a2266/src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl#L39-L41
> 
> I guess it should be `if formulation == VerticallFormulation() and ...`?

No that's correct --- we can't use vertically implicit time-stepping with `HorizontalFormulation`.

The reason is that `HorizontalFormulation` has no vertical terms.

**Comment by glwagner** [comment]
This should probably wait until #2284

**Comment by navidcy** [comment]
> > `test_dynamics.jl` fail.
> > Is this correct here?
> > https://github.com/CliMA/Oceananigans.jl/blob/ad110ecdc635192c110e229df4fbfa04fc7a2266/src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl#L39-L41
> > 
> > I guess it should be `if formulation == VerticallFormulation() and ...`?
> 
> No that's correct --- we can't use vertically implicit time-stepping with `HorizontalFormulation`.
> 
> The reason is that `HorizontalFormulation` has no vertical terms.

Then the error message should be `only supported for `VerticalFormulation or ThreeDimensionalFormulation"`, right?

**Comment by navidcy** [comment]
OK fixed it. Apparently tests were passing before because the `time_discretization` argument was not working properly.

**Pull request merged**
