### PR TITLE
Updates building docs instructions

### LINKED ISSUE #1542: Can't build docs locally based on instructions in "Contributor's guide"
I'm trying to build the docs locally because I want to resolve https://github.com/CliMA/Oceananigans.jl/issues/1478. I followed the instructions in [the docs](https://clima.github.io/OceananigansDocumentation/stable/contributing/#Documentation) but I'm not able to generate `index.html`. Here's a pastebin with the first few errors that appear: https://pastebin.com/25A8SqeX

It looks like the doc generator is comparing the actual output with some expected output? Is that something the docs should do?

Anyway, I've never built julia docs before so I'm kinda unfamiliar with this. Help is appreciated!

### PR DESCRIPTION
**Pull request by navidcy**
This PR updates the instructions for building the docs locally.

@tomchor, @francispoulin: could you let me know if these new instructions do the job for you? Please try on a fresh clone of the repo.

Closes #1542. (Or at least that's the hope....)

### CODE REVIEW

**Comment by francispoulin** [comment]
I did a fresh clone and checked out your branch.  I instantiated the library and then did `dev ..` and the library seemeed to be in good shape.  Actually, it complained about my MPI so I had to rebuild that but then things seemed to be in good shape.

I thought I would try `make_example.jl` first, as that should be faster than making everything.   Success!  there were some warnings but no errors and I could view the example no problem.

I'll now try the full make and check on it tomorrow, since I know it's going to be slow. 

Thanks @navidcy for putting this together!

**Comment by navidcy** [comment]
Wait, why did you do `dev`? The instructions didn't mention `dev`... :)

**Comment by navidcy** [comment]
I'm claiming that these is enough to build the docs:
```
julia --project -e 'using Pkg; Pkg.instantiate()'
julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
julia --project=docs/ docs/make.jl
```

But please correct me if I'm wrong... :)

**Review by tomchor — APPROVED** [review]

**Comment by tomchor** [comment]
Worked like a charm for me. (Although it took a loong time.)

Thanks @navidcy

**Comment by francispoulin** [comment]
Sorry for my mistake @navidcy .  I probably shouldn't try these things late in the evening.  When I did a new clone and followed the instructions I did get errors.  Below I copied the first two.

I will wipe this clean and try it again and let you know if it works.

```
 Error: doctest failure in src/model_setup/turbulent_diffusivity_closures_and_les_models.md:36-41
│ 
│ ```jldoctest
│ julia> using Oceananigans.TurbulenceClosures
│ 
│ julia> closure = SmagorinskyLilly()
│ SmagorinskyLilly: C=0.23, Cb=1.0, Pr=1.0, ν=0.0, κ=0.0
│ ```
│ 
│ Subexpression:
│ 
│ closure = SmagorinskyLilly()
│ 
│ Evaluated output:
│ 
│ SmagorinskyLilly: C=0.23, Cb=1.0, Pr=1.0, ν=1.05e-6, κ=1.46e-7
│ 
│ Expected output:
│ 
│ SmagorinskyLilly: C=0.23, Cb=1.0, Pr=1.0, ν=0.0, κ=0.0
│ 
│   diff = SmagorinskyLilly: C=0.23, Cb=1.0, Pr=1.0, ν=0.0, κ=0.0ν=1.05e-6, κ=1.46e-7
└ @ Documenter.DocTests ~/.julia/packages/Documenter/f5jts/src/DocTests.jl:385
┌ Error: doctest failure in src/model_setup/turbulent_diffusivity_closures_and_les_models.md:50-60
```

**Comment by francispoulin** [comment]
I tried it again with a fresh clone and still received an error.  The details are copied below.  However, `make_example.jl` does seem to be working so it's not all bad.  Unfortunately, I'm not sure why this occurs.

```
ERROR: LoadError: `makedocs` encountered a doctest error. Terminating build
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] runner(#unused#::Type{Documenter.Builder.Doctest}, doc::Documenter.Documents.Document)
   @ Documenter.Builder ~/.julia/packages/Documenter/f5jts/src/Builder.jl:217
 [3] dispatch(#unused#::Type{Documenter.Builder.DocumentPipeline}, x::Documenter.Documents.Document)
   @ Documenter.Utilities.Selectors ~/.julia/packages/Documenter/f5jts/src/Utilities/Selectors.jl:170
 [4] #2
   @ ~/.julia/packages/Documenter/f5jts/src/Documenter.jl:249 [inlined]
 [5] cd(f::Documenter.var"#2#3"{Documenter.Documents.Document}, dir::String)
   @ Base.Filesystem ./file.jl:106
 [6] #makedocs#1
   @ ~/.julia/packages/Documenter/f5jts/src/Documenter.jl:248 [inlined]
 [7] top-level scope
   @ ~/software/Second_Oceananigans/Oceananigans.jl/docs/make.jl:160
in expression starting at /home/fpoulin/software/Second_Oceananigans/Oceananigans.jl/docs/make.jl:160
```

**Comment by navidcy** [comment]
This was the error after a try on a clean copy of the repo?

**Comment by navidcy** [comment]
It says that is a doctest error. I think if you wanna run again you first need to delete the jld2 and nc files the doctests create. 

@ali-ramadhan should we add a command in the docs/make.jl to cleanup those files after docs are built?

**Comment by francispoulin** [comment]
Thanks @navidcy for the advice.  Sadly, even after I delete all the nc and jld2 files in docs, I still get the same problem.  there is an error in each example ti seems, `doctest failure` and then there is the error copied above.

It seems that you, @tomchor and the server all get this to work so please feel free to go ahead and merge.  At least I can get the one example working.  That's progress.

**Comment by tomchor** [comment]
@francispoulin have you tried making sure that your global Julia environment is clean?
What's the output of `julia -e "using Pkg; Pkg.status()"`?

**Comment by navidcy** [comment]
But why does
```Julia
closure = SmagorinskyLilly()
```
gives out
```Julia
SmagorinskyLilly: C=0.23, Cb=1.0, Pr=1.0, ν=1.05e-6, κ=1.46e-7
```
for you when the default values are https://github.com/CliMA/Oceananigans.jl/blob/b22057a49dfe25b1b091d4d4c9cdb0e126bc0c62/src/TurbulenceClosures/turbulence_closure_implementations/smagorinsky_lilly.jl#L63

?

**Comment by navidcy** [comment]
> @francispoulin have you tried making sure that your global Julia environment is clean?
> What's the output of `julia -e "using Pkg; Pkg.status()"`?

That's also a good point... Perhaps it goes and finds an outdated Oceananigans version from your global Julia environment.

**Comment by francispoulin** [comment]
Everything looks fine to me.  See below.

```
Oceananigans.jl/docs$ julia -e "using Pkg; Pkg.status()"
      Status `~/.julia/environments/v1.6/Project.toml`
  [13f3f980] CairoMakie v0.6.1
  [35d6a980] ColorSchemes v3.12.0
  [864edb3b] DataStructures v0.18.9
  [5789e2e9] FileIO v1.7.0
  [e9467ef8] GLMakie v0.4.1
  [f67ccb44] HDF5 v0.15.4
  [033835bb] JLD2 v0.4.3
  [682c06a0] JSON v0.21.1
  [0f8b85d8] JSON3 v1.8.1
  [b964fa9f] LaTeXStrings v1.2.1
  [da04e1cc] MPI v0.17.2
  [85f8d34a] NCDatasets v0.11.3
  [9e8cae18] Oceananigans v0.54.2 `https://github.com/CliMA/Oceananigans.jl.git#ali/julia-1.6`
  [d96e819e] Parameters v0.12.2
  [91a5bcdd] Plots v1.12.0
  [f27b6e38] Polynomials v2.0.12
  [d330b81b] PyPlot v2.9.0
  [295af30f] Revise v3.1.15
  [c4c386cf] Rsvg v1.0.0
  [de0858da] Printf
```

However my docs project, which I believe we are using here, is a lot smaller and maybe part of the problem?

```
(docs) pkg> status
      Status `~/software/Second_Oceananigans/Oceananigans.jl/docs/Project.toml`
  [e30172f5] Documenter v0.27.2
  [daee34ce] DocumenterCitations v0.2.5
  [033835bb] JLD2 v0.4.10
  [98b081ad] Literate v2.8.1
  [442fdcdd] Measures v0.3.1
  [85f8d34a] NCDatasets v0.11.6
  [91a5bcdd] Plots v1.16.5
  [f27b6e38] Polynomials v2.0.12
  [bdfc003b] TimesDates v0.2.6
  [37e2e46d] LinearAlgebra
  [d6f4376e] Markdown
```

I am trying it again with specifying the path to julia and that did not help.

I am puzzled but won't be able to look at this any more today I don't think.  Sorry.

**Comment by tomchor** [comment]
It looks like you have an old version of Oceananigans in your global Julia environment. That's probably what's making the tests fail. I think ideally the global environment should be empty. Here's mine:


```bash
(base) tomas@np900:~/repos/Oceananigans.jl$ julia -e "using Pkg; Pkg.status()"
      Status `~/.julia/environments/v1.6/Project.toml` (empty project)
```

**Comment by navidcy** [comment]
> It looks like you have an old version of Oceananigans in your global Julia environment. That's probably what's making the tests fail. I think ideally the global environment should be empty. Here's mine:
> 
> ```shell
> (base) tomas@np900:~/repos/Oceananigans.jl$ julia -e "using Pkg; Pkg.status()"
>       Status `~/.julia/environments/v1.6/Project.toml` (empty project)
> ```

Yeap! Everything **is not** fine. :)

**Comment by navidcy** [comment]
I will merge this PR @francispoulin. I'm very confident we can make this work for you. Let's just zoom and we'll figure it out. I find it much easier this way...

If problem persist open an issue.

**Comment by navidcy** [comment]
Hm... on second thought I'll wait...

I'll try to read the [Pkg documentation](https://docs.julialang.org/en/v1/stdlib/Pkg/) to try to figure out a way to make this bullet proof.

**Comment by navidcy** [comment]
Does anyone know if there is a way when we activate a project in Julia to preclude access to all packages in the general Julia `(v1.6)` environment? That would make this procedure smoother...

**Comment by navidcy** [comment]
@ali-ramadhan, should this line
https://github.com/CliMA/Oceananigans.jl/blob/b22057a49dfe25b1b091d4d4c9cdb0e126bc0c62/docs/make.jl#L1
be
`push!(LOAD_PATH, joinpath(@__DIR__, "."))`?

Supposedly people call `docs/make.jl` from the repo's home directory, right? Thus going a level up is not appropriate? Am I confused?

**Comment by navidcy** [comment]
See https://github.com/JuliaGPU/CUDA.jl/blob/96d6e11259053573ad8164f462d9f9eb8e204893/.buildkite/pipeline.yml#L338-L342

**Comment by francispoulin** [comment]
I am happy to say that I successflly built the docs on my local machine for the first, but not last time.

@navidcy : Your instructions are very clear.  The problem was with my `.julia` file, I think, but you should not have to account for this peculiar experience.  Thanks to you and @tomchor for helping me along with this.  I am happy to have learned more about this.

Please merge away!

**Comment by navidcy** [comment]
OK, I'm merging and deferring the `push!(LOAD_PATH, joinpath(@__DIR__, "."))` discussion for elsewhere.

**Pull request merged**
