### PR TITLE
Redefines equality (==) for VerticallyStretchedRectilinearGrids

### PR DESCRIPTION
**Pull request by tomchor**
Closes https://github.com/CliMA/Oceananigans.jl/issues/2018

### CODE REVIEW

**Comment by navidcy** [comment]
@tomchor did you try the MWE in #2018 with this fix and it's all good?

**Comment by tomchor** [comment]
> @tomchor did you try the MWE in #2018 with this fix and it's all good?

It fixes it for CPUs, but I get an error for GPU architecture. It's likely that we need to allow scalar operations due to `==`. I'm planning on trying that tomorrow and I won't merge before it also works for GPUs. (I was wondering if we should add this as a test...)

**Comment by navidcy** [comment]
> It fixes it for CPUs, but I get an error for GPU architecture. It's likely that we need to allow scalar operations due to `==`. I'm planning on trying that tomorrow and I won't merge before it also works for GPUs. (I was wondering if we should add this as a test...)

Hm... Whatever we do should work for both. I think @glwagner and I were thinking about equality between grids at some point. Probably (I'm not sure -- you can double check that), the fix fails for GPUs because when it tries to compare the two grids, the one saved on disk has `Arrays` while the other one haw `CuArrays`. If that's the case, we need a solution that remedy this and call two grids "equal" despite the device they live on. Some of these issue are related or discussed within #1825 and #1998.

**Comment by navidcy** [comment]
> > A test would be nice to come along with this PR. I can help out with that if you want.
> 
> Thanks! I'll take you up on that if you don't mind. Given that you said that other grids also have arrays, it might be best to expand checkpoint testing for all grids?

Yeap. But first we need to sort the GPU/CPU issue. For example, two grids that are identical but the arrays of one live on CPU but the other on GPU should they be considered equal? I believe in that case we should add methods so that:
```julia
julia> grid1 == grid2
true

julia> grid1 == grid2
false
```

**Comment by navidcy** [comment]
But I would suggest we postpone this until after #1998 so that we don't do double work. Also, by putting `architecture` in grids will (potentially) make it easier to compare grids across devices.

**Comment by navidcy** [comment]
@tomchor, you can always do
```julia
pkg> add Oceananigans#tc/pickup
```
and continue research if that does the job.

I'm just a bit reluctant to apply a quick fix that works only for one case only to have to do the same work again for the lat/lon grid for example, etc. I'm very keen to solve this bug before #1998 -- postponing after #1998 was just a suggestion. But the solution should be one that covers all grids and all architectures. Not something that works only for one grid and leaves the bug for some others.

Perhaps let's see what others have to chip in on this?

**Comment by tomchor** [comment]
> @tomchor, you can always do
> 
> ```julia
> pkg> add Oceananigans#tc/pickup
> ```
> 
> and continue research if that does the job.
> 
> I'm just a bit reluctant to apply a quick fix that works only for one case only to have to do the same work again for the lat/lon grid for example, etc. I'm very keen to solve this bug before #1998 -- postponing after #1998 was just a suggestion. But the solution should be one that covers all grids and all architectures. Not something that works only for one grid and leaves the bug for some others.
> 
> Perhaps let's see what others have to chip in on this?

Oh yeah, I didn't mean to half-fix it. I do believe it should be a "proper" fix. I just think that adding architecture to grids (#1998) isn't gonna change what the fix is. I'll have more info tomorrow after I actually try to do this for GPUs.

**Comment by tomchor** [comment]
So, everything that I've tested so far leads me to believe this is working with vertically stretched grids for now. I've tested a few examples with both CPU and GPU architecture and they've picked up successfully. However, since @navidcy and @glwagner have reservations about this fix (regarding #1998) I won't expand it to all abstract grids for now.

I'll leave this PR open though since I need this fix to complete my research, if that's okay.

**Pull request merged**
