### PR TITLE
Welcome Julia v1.7

### PR DESCRIPTION
**Pull request by navidcy**
This PR makes tests and validations pipelines to run using Julia v1.7.
Furthermore, it updates `Manifest.toml` files from v1.0 to v2.0.

### CODE REVIEW

**Comment by navidcy** [comment]
@simone-silvestri, most `test_something.jl` files were re-including `include("utils_for_runtests.jl")`. Did you made this? Is there a reason for this?

The problem is that `utils_for_runtests.jl` defines some constants and Julia v1.7 does not allow re-definition of constants. So the tests were failing...

**Comment by simone-silvestri** [comment]
Ah wow, nice catch! I think `utils_for_runtests.jl` was already there. In any case we could merge it with the `dependencies_for_runtests.jl` file, so that it s all in one file and just include it once in `runtests.jl`.

**Comment by navidcy** [comment]
I'm not sure this will run smoothly on Julia v1.6. E.g., on v1.6:

```Julia
(Oceananigans) pkg> instantiate
ERROR: AssertionError: sourcepath !== nothing
Stacktrace:
  [1] is_package_downloaded(ctx::Pkg.Types.Context, pkg::Pkg.Types.PackageSpec)
    @ Pkg.Operations ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1789
  [2] #13
    @ ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:131 [inlined]
  [3] _all
    @ ./reduce.jl:923 [inlined]
  [4] #all#698
    @ ./reducedim.jl:886 [inlined]
  [5] all
    @ ./reducedim.jl:886 [inlined]
  [6] is_instantiated(ctx::Pkg.Types.Context)
    @ Pkg.Operations ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:131
  [7] instantiate(ctx::Pkg.Types.Context; manifest::Nothing, update_registry::Bool, verbose::Bool, platform::Base.BinaryPlatforms.Platform, allow_build::Bool, allow_autoprecomp::Bool, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1358
  [8] instantiate
    @ ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1325 [inlined]
  [9] #instantiate#252
    @ ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1321 [inlined]
 [10] instantiate()
    @ Pkg.API ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:1321
 [11] do_cmd!(command::Pkg.REPLMode.Command, repl::REPL.LineEditREPL)
    @ Pkg.REPLMode ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:405
 [12] do_cmd(repl::REPL.LineEditREPL, input::String; do_rethrow::Bool)
    @ Pkg.REPLMode ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:386
 [13] do_cmd
    @ ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:377 [inlined]
 [14] (::Pkg.REPLMode.var"#24#27"{REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::IOBuffer, ok::Bool)
    @ Pkg.REPLMode ~/julia/usr/share/julia/stdlib/v1.6/Pkg/src/REPLMode/REPLMode.jl:550
 [15] #invokelatest#2
    @ ./essentials.jl:708 [inlined]
 [16] invokelatest
    @ ./essentials.jl:706 [inlined]
 [17] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit ~/julia/usr/share/julia/stdlib/v1.6/REPL/src/LineEdit.jl:2441
 [18] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL ~/julia/usr/share/julia/stdlib/v1.6/REPL/src/REPL.jl:1126
 [19] (::REPL.var"#44#49"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ./task.jl:411
```

Should we wait a bit before merging? Maybe we make sure all developers are on 1.7?

**Comment by navidcy** [comment]
I guess with this PR must also come a compat entry
```Julia
julia = "^1.7"
```

**Comment by glwagner** [comment]
Do we want to require users to have julia 1.7?

**Comment by navidcy** [comment]
> Do we want to require users (or just developers?) to have julia 1.7?

Not for now I think. 
Especially since 1.6.4 is the LTS.

**Comment by tomchor** [comment]
> > Do we want to require users (or just developers?) to have julia 1.7?
> 
> Not for now I think. Especially since 1.6.4 is the LTS.


I agree with this. But we might wanna keep this open (maybe as a draft?) so that we can migrate little by little, keeping track of the issues, as other developers also migrate to 1.7. Just a thought.

**Pull request closed without merging**
