### PR TITLE
`try` to `fill_halo_regions!` when calling `set!(u::Field, v)`

### LINKED ISSUE #1961: At least *try* to `fill_halo_regions!` within `set!(::Field, ...)`?
Sometimes this is not possible, but oftentimes (especially when called by a user), it is.

### PR DESCRIPTION
**Pull request by glwagner**
Giving it a go.

Resolves #1961

### CODE REVIEW

**Comment by simone-silvestri** [comment]
This has implications in terms of code performance, if we have `set!(field)` somewhere in the code it will trigger automatically a `fill_halo_regions!` which we might not want as we are very careful to where we call `fill_halo_regions!`

There are two options then:
(1) remove all instances of `set!` in the internals and make sure to never use it
(2) implement a different interface that can be user-facing which triggers set! and fill_halo_regions! together.

I would vote for (2)

**Comment by glwagner** [comment]
This PR sort of does (2)... it's just that the user API is `set!`, and the internal function is `_set!`.... what do you think?

**Comment by glwagner** [comment]
```
(base) gregorywagner:src/ (glw/set-fill-halos) $ grep -r set! ./*                                                                                                                                          [16:33:51]
./AbstractOperations/conditional_operations.jl:import Oceananigans.Fields: condition_operand, conditional_length, set!, compute_at!, indices
./AbstractOperations/conditional_operations.jl:@inline concretize_condition!(c::ConditionalOperation) = set!(c.operand, c)
./AbstractOperations/conditional_operations.jl:    set!(f, c)
./CubedSpheres/cubed_sphere_faces.jl:import Oceananigans.Fields: AbstractField, FunctionField, Field, FieldBoundaryBuffers, minimum, maximum, mean, location, set!
./CubedSpheres/cubed_sphere_faces.jl:##### set!
./CubedSpheres/cubed_sphere_faces.jl:function cubed_sphere_set!(u, v)
./CubedSpheres/cubed_sphere_faces.jl:        set!(get_face(u, face), get_face(v, face))
./CubedSpheres/cubed_sphere_faces.jl:set!(u::CubedSphereField, v) = cubed_sphere_set!(u, v)
./CubedSpheres/cubed_sphere_faces.jl:set!(u::CubedSphereField, v::Function) = cubed_sphere_set!(u, v)
./CubedSpheres/cubed_sphere_faces.jl:set!(u::CubedSphereField, v::Union{Array, CuArray, OffsetArray}) = cubed_sphere_set!(u, v)
./CubedSpheres/cubed_sphere_faces.jl:set!(u::CubedSphereField, v::CubedSphereField) = cubed_sphere_set!(u, v)
./Distributed/distributed_grids.jl:        set!(bottom_field, cpu_bottom)
./Fields/set!.jl:function set!(Φ::NamedTuple; kwargs...)
./Fields/set!.jl:        set!(ϕ, value)
./Fields/set!.jl:    set!(u::Field, v)
./Fields/set!.jl:function set!(u::Field, v)
./Fields/set!.jl:    _set!(u::Field, v)
./Fields/set!.jl:function _set!(u::Field, v)
./Fields/set!.jl:function _set!(u::Field, f::Function)
./Fields/set!.jl:        set!(u_cpu, f_field)
./Fields/set!.jl:        set!(u, u_cpu)
./Fields/set!.jl:        set!(u, f_field)
./Fields/set!.jl:function _set!(u::Field, f::Union{Array, CuArray, OffsetArray})
./Fields/set!.jl:function _set!(u::Field, v::Field)
./Fields/field_reductions.jl:set!(c, (x, y, z) -> x + y + z)
./Fields/Fields.jl:export set!, compute!, @compute, regrid!
./Fields/Fields.jl:include("set!.jl")
./ImmersedBoundaries/grid_fitted_immersed_boundaries.jl:    set!(bottom_field, ib.bottom_height)
./ImmersedBoundaries/grid_fitted_immersed_boundaries.jl:    set!(mask_field, ib.mask)
./ImmersedBoundaries/active_cells_map.jl:    set!(active_cells_field, is_immersed_operation)
./Models/NonhydrostaticModels/set_nonhydrostatic_model.jl:import Oceananigans.Fields: set!
./Models/NonhydrostaticModels/set_nonhydrostatic_model.jl:using Oceananigans.Fields: _set!
./Models/NonhydrostaticModels/set_nonhydrostatic_model.jl:    set!(model; kwargs...)
./Models/NonhydrostaticModels/set_nonhydrostatic_model.jl:`set!(ϕ::AbstractField, data)` function exists.
./Models/NonhydrostaticModels/set_nonhydrostatic_model.jl:set!(model, u=u₀, v=v₀, T=T₀)
./Models/NonhydrostaticModels/set_nonhydrostatic_model.jl:function set!(model::NonhydrostaticModel; enforce_incompressibility=true, kwargs...)
./Models/NonhydrostaticModels/set_nonhydrostatic_model.jl:        _set!(ϕ, value)
./Models/ShallowWaterModels/set_shallow_water_model.jl:using Oceananigans.Fields: _set!
./Models/ShallowWaterModels/set_shallow_water_model.jl:import Oceananigans.Fields: set!
./Models/ShallowWaterModels/set_shallow_water_model.jl:function set!(model::ShallowWaterModel; kwargs...)
./Models/ShallowWaterModels/set_shallow_water_model.jl:        _set!(ϕ, value)
./Models/ShallowWaterModels/shallow_water_model.jl:    set!(bathymetry_field, bathymetry)
./Models/HydrostaticFreeSurfaceModels/matrix_implicit_free_surface_solver.jl:    set!(η, reshape(storage, solver.problem_size...))
./Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl:import Oceananigans.TimeSteppers: reset!
./Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl:function reset!(sefs::SplitExplicitFreeSurface)
./Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl:    @apply_regionally set!(free_surface.η, free_surface.state.η̅)
./Models/HydrostaticFreeSurfaceModels/distributed_split_explicit_free_surface.jl:"""Integrate z at locations `location` and set! `height`` with the result"""
./Models/HydrostaticFreeSurfaceModels/set_hydrostatic_free_surface_model.jl:using Oceananigans.Fields: _set!
./Models/HydrostaticFreeSurfaceModels/set_hydrostatic_free_surface_model.jl:import Oceananigans.Fields: set!
./Models/HydrostaticFreeSurfaceModels/set_hydrostatic_free_surface_model.jl:    set!(model; kwargs...)
./Models/HydrostaticFreeSurfaceModels/set_hydrostatic_free_surface_model.jl:`set!(ϕ::AbstractField, data)` function exists.
./Models/HydrostaticFreeSurfaceModels/set_hydrostatic_free_surface_model.jl:set!(model, u=u₀, v=v₀, T=T₀)
./Models/HydrostaticFreeSurfaceModels/set_hydrostatic_free_surface_model.jl:function set!(model::HydrostaticFreeSurfaceModel; kwargs...)
./Models/HydrostaticFreeSurfaceModels/set_hydrostatic_free_surface_model.jl:        @apply_regionally _set!(ϕ, value)
./Models/Models.jl:import Oceananigans.TimeSteppers: reset!
./Models/Models.jl:function reset!(model::AbstractModel)
./MultiRegion/multi_region_field.jl:import Oceananigans.Fields: set!, compute!, compute_at!, validate_field_data, validate_boundary_conditions
./MultiRegion/multi_region_field.jl:set!(mrf::MultiRegionField, v)  = apply_regionally!(set!,  mrf, v)
./MultiRegion/multi_region_field.jl:set!(mrf::MultiRegionField, f::Function)  = apply_regionally!(set!, mrf, f)
./Oceananigans.jl:    interior, set!, compute!, regrid!, location,
./OutputReaders/field_time_series.jl:import Oceananigans.Fields: Field, set!, interior, indices
./OutputReaders/field_time_series.jl:    set!(time_series, path, name)
./OutputReaders/field_time_series.jl:##### set!
./OutputReaders/field_time_series.jl:function set!(time_series::InMemoryFieldTimeSeries, path::String, name::String)
./OutputReaders/field_time_series.jl:        set!(time_series[n], field_n)
./OutputReaders/field_time_series.jl:function set!(fts::FieldTimeSeries, fields_vector::AbstractVector{<:AbstractField})
./OutputWriters/windowed_time_average.jl:import Oceananigans.Fields: location, indices, set!
./OutputWriters/windowed_time_average.jl:set!(u::Field, wta::WindowedTimeAverage) = set!(u, wta.result)
./OutputWriters/checkpointer.jl:import Oceananigans.Fields: set!
./OutputWriters/checkpointer.jl:##### set! for checkpointer filepaths
./OutputWriters/checkpointer.jl:set!(model, ::Nothing) = nothing
./OutputWriters/checkpointer.jl:    set!(model, filepath::AbstractString)
./OutputWriters/checkpointer.jl:function set!(model, filepath::AbstractString)
./Simulations/run.jl:using Oceananigans.Fields: set!
./Simulations/run.jl:import Oceananigans.OutputWriters: checkpoint_path, set!
./Simulations/run.jl:        set!(sim.model, checkpoint_file_path)
./Simulations/run.jl:    # Reset! the model time-stepper, evaluate all diagnostics, and write all output at first iteration
./Simulations/run.jl:        reset!(sim.model.timestepper)
./Simulations/simulation.jl:import Oceananigans.TimeSteppers: reset!
./Simulations/simulation.jl:    reset!(sim)
./Simulations/simulation.jl:function reset!(sim::Simulation)
./Simulations/simulation.jl:    reset!(sim.model.timestepper)
./TimeSteppers/quasi_adams_bashforth_2.jl:function reset!(timestepper::QuasiAdamsBashforth2TimeStepper)
./TimeSteppers/TimeSteppers.jl:reset!(timestepper) = nothing
(base) gregorywagner:src/ (glw/set-fill-halos) $ grep -r ' set!' ./*                                                                                                                                       [16:33:55]
./AbstractOperations/conditional_operations.jl:import Oceananigans.Fields: condition_operand, conditional_length, set!, compute_at!, indices
./AbstractOperations/conditional_operations.jl:@inline concretize_condition!(c::ConditionalOperation) = set!(c.operand, c)
./AbstractOperations/conditional_operations.jl:    set!(f, c)
./CubedSpheres/cubed_sphere_faces.jl:import Oceananigans.Fields: AbstractField, FunctionField, Field, FieldBoundaryBuffers, minimum, maximum, mean, location, set!
./CubedSpheres/cubed_sphere_faces.jl:##### set!
./CubedSpheres/cubed_sphere_faces.jl:        set!(get_face(u, face), get_face(v, face))
./Distributed/distributed_grids.jl:        set!(bottom_field, cpu_bottom)
./Fields/set!.jl:function set!(Φ::NamedTuple; kwargs...)
./Fields/set!.jl:        set!(ϕ, value)
./Fields/set!.jl:    set!(u::Field, v)
./Fields/set!.jl:function set!(u::Field, v)
./Fields/set!.jl:        set!(u_cpu, f_field)
./Fields/set!.jl:        set!(u, u_cpu)
./Fields/set!.jl:        set!(u, f_field)
./Fields/Fields.jl:export set!, compute!, @compute, regrid!
./ImmersedBoundaries/grid_fitted_immersed_boundaries.jl:    set!(bottom_field, ib.bottom_height)
./ImmersedBoundaries/grid_fitted_immersed_boundaries.jl:    set!(mask_field, ib.mask)
./ImmersedBoundaries/active_cells_map.jl:    set!(active_cells_field, is_immersed_operation)
./Models/NonhydrostaticModels/set_nonhydrostatic_model.jl:import Oceananigans.Fields: set!
./Models/NonhydrostaticModels/set_nonhydrostatic_model.jl:    set!(model; kwargs...)
./Models/NonhydrostaticModels/set_nonhydrostatic_model.jl:function set!(model::NonhydrostaticModel; enforce_incompressibility=true, kwargs...)
./Models/ShallowWaterModels/set_shallow_water_model.jl:import Oceananigans.Fields: set!
./Models/ShallowWaterModels/set_shallow_water_model.jl:function set!(model::ShallowWaterModel; kwargs...)
./Models/ShallowWaterModels/shallow_water_model.jl:    set!(bathymetry_field, bathymetry)
./Models/HydrostaticFreeSurfaceModels/matrix_implicit_free_surface_solver.jl:    set!(η, reshape(storage, solver.problem_size...))
./Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl:    @apply_regionally set!(free_surface.η, free_surface.state.η̅)
./Models/HydrostaticFreeSurfaceModels/distributed_split_explicit_free_surface.jl:"""Integrate z at locations `location` and set! `height`` with the result"""
./Models/HydrostaticFreeSurfaceModels/set_hydrostatic_free_surface_model.jl:import Oceananigans.Fields: set!
./Models/HydrostaticFreeSurfaceModels/set_hydrostatic_free_surface_model.jl:    set!(model; kwargs...)
./Models/HydrostaticFreeSurfaceModels/set_hydrostatic_free_surface_model.jl:function set!(model::HydrostaticFreeSurfaceModel; kwargs...)
./MultiRegion/multi_region_field.jl:import Oceananigans.Fields: set!, compute!, compute_at!, validate_field_data, validate_boundary_conditions
./Oceananigans.jl:    interior, set!, compute!, regrid!, location,
./OutputReaders/field_time_series.jl:import Oceananigans.Fields: Field, set!, interior, indices
./OutputReaders/field_time_series.jl:    set!(time_series, path, name)
./OutputReaders/field_time_series.jl:##### set!
./OutputReaders/field_time_series.jl:function set!(time_series::InMemoryFieldTimeSeries, path::String, name::String)
./OutputReaders/field_time_series.jl:        set!(time_series[n], field_n)
./OutputReaders/field_time_series.jl:function set!(fts::FieldTimeSeries, fields_vector::AbstractVector{<:AbstractField})
./OutputWriters/windowed_time_average.jl:import Oceananigans.Fields: location, indices, set!
./OutputWriters/windowed_time_average.jl:set!(u::Field, wta::WindowedTimeAverage) = set!(u, wta.result)
./OutputWriters/checkpointer.jl:import Oceananigans.Fields: set!
./OutputWriters/checkpointer.jl:##### set! for checkpointer filepaths
./OutputWriters/checkpointer.jl:    set!(model, filepath::AbstractString)
./OutputWriters/checkpointer.jl:function set!(model, filepath::AbstractString)
./Simulations/run.jl:using Oceananigans.Fields: set!
./Simulations/run.jl:import Oceananigans.OutputWriters: checkpoint_path, set!
./Simulations/run.jl:        set!(sim.model, checkpoint_file_path)
````

**Comment by glwagner** [comment]
How about `set_interior!` for the internal function?

**Comment by simone-silvestri** [comment]
Ok, set_interior! is good

**Comment by glwagner** [comment]
Ok check it out @simone-silvestri . I also cleaned up some split explicit stuff.

**Comment by glwagner** [comment]
Too bad this PR went by the wayside. I think I'll close it now. We can revisit in the future if we want.

**Comment by glwagner** [comment]
@simone-silvestri I think we should revive this at some point. Are you still ok with the general design involving `set_interior!`?

**Comment by glwagner** [comment]
@simone-silvestri still interested in reviving this PR. Please comment.

**Pull request closed without merging**
