### PR TITLE
Cnh/full cube implicit solver test

### PR DESCRIPTION
**Pull request by christophernhill**
me tinkering with dot() and norm() and Cube. 

DON'T MERGE! 

next step is to add a set!(u,0), which seems to be missing? 

I think dot() and norm() in here may work for regular fields and "faceiefied" fields?

### CODE REVIEW

**Comment by glwagner** [comment]
Ah, the only issue is there will be huge conflicts with #1575. It shouldn't be hard to refactor these changes to work with the code on that PR though I don't think.

**Comment by christophernhill** [comment]
> Ah, the only issue is there will be conflicts with #1575. It shouldn't be hard to refactor these changes to work with the code on that PR though I don't think.

@glwagner we can merge this in at some point. I didn't want to lose it meantime. Looks like #1575 needs other bits doing too, since #1522 did its stuff!!

**Comment by glwagner** [comment]
@christophernhill this is probably stale --- should we close?

**Comment by christophernhill** [comment]
Time to move on.....

**Comment by glwagner** [comment]
Such is life

**Pull request closed without merging**
