### PR TITLE
Reorganized docs structure

### PR DESCRIPTION
**Pull request by tomchor**
This is an attempt to make the left menu of the docs feel a bit more intuitive and organized. What I did:

- Moved benchmarks, function index and library to appendix. I think not many people need that information, so it makes sense put it there I think)
- Moved appendix to be the last item on the menu (as is customary for most documents)
- Moved gallery to after the contributor's guide (since I think contributor's guide is more important so it can come first)

I know this is unprompted (nobody complained about the docs) but I think it's a positive change. Eager to hear opinions.

### CODE REVIEW

**Comment by glwagner** [comment]
Those changes seem positive to me! I can't find the preview though, any idea where that might be?

**Comment by tomchor** [comment]
No idea! According to @navidcy it should be at https://clima.github.io/OceananigansDocumentation/previews/PR1838, but it says page not found.

**Comment by tomchor** [comment]
Also here's a more proper source for that: https://github.com/JuliaDocs/Documenter.jl/issues/1131#issuecomment-554940993

So idk what's wrong here. @navidcy any idea?

**Comment by navidcy** [comment]
> Also here's a more proper source for that: [JuliaDocs/Documenter.jl#1131 (comment)](https://github.com/JuliaDocs/Documenter.jl/issues/1131#issuecomment-554940993)
> 
> So idk what's wrong here. @navidcy any idea?

Strange...
From looking at the log, it seems it didn't push the preview...
https://buildkite.com/clima/oceananigans/builds/3216#7afaa702-7973-4f52-8d71-73e07874666d

Let me look into it bit more :)

**Review by navidcy — APPROVED** [review]
Approve 👍🏼; just good to see the preview that all renders OK before merging.

**Comment by navidcy** [comment]
Now we have a preview: https://clima.github.io/OceananigansDocumentation/previews/PR1838/

(I don't know why... I didn't really do anything...)

**Comment by navidcy** [comment]
Looks good to me

**Comment by francispoulin** [comment]
I'm happy with these changes too.

Francis


________________________________

**Comment by tomchor** [comment]
> Now we have a preview: https://clima.github.io/OceananigansDocumentation/previews/PR1838/
> 
> (I don't know why... I didn't really do anything...)

Weird... Documenter.jl works in mysterious ways

**Pull request merged**
