### PR TITLE
Change default halo size to 3 in non-`Flat` directions

### PR DESCRIPTION
**Pull request by glwagner**
Opening to see what happens.

### CODE REVIEW

**Comment by francispoulin** [comment]
Only good things, I'm sure

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
I approve the idea. But only merge when tests are sorted out. ;)

**Comment by glwagner** [comment]
@navidcy you did it!!

**Comment by glwagner** [comment]
The sun is rising

**Comment by navidcy** [comment]
Merge merge merge!

**Pull request merged**
