### PR TITLE
Fixes interpolation error in centered fourth order tracer advection

### PR DESCRIPTION
**Pull request by glwagner**

### CODE REVIEW

**Comment by glwagner** [comment]
@navidcy

**Review by ali-ramadhan — APPROVED** [review]
Haha copy paste strikes again

**Comment by navidcy** [comment]
This may explain why 2D turbulence script worked while the baroclinic double gyre was blowing up...

**Comment by glwagner** [comment]
> This may explain why 2D turbulence script worked while the baroclinic double gyre was blowing up...

I think it very much does.

**Pull request merged**
