### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Review by simone-silvestri — APPROVED** [review]

**Review by francispoulin — APPROVED** [review]
I glanced over the changes and nothing seems to be out or order.  If tests pass then we should be good to go.

**Comment by glwagner** [comment]
Valiant effort. Looks like some matrix solver tests don't pass --- @simone-silvestri perhaps you can take a look when you have time.

**Comment by simone-silvestri** [comment]
I ll take a look

**Comment by navidcy** [comment]
Seems that it passed when I rerun.

**Pull request merged**
