### PR TITLE
(0.84.1) Fixes string generator for `summary(::SpecifiedTimes)`

### LINKED ISSUE #3163: `specified_times_str(::SpecifiedTimes)`
Why here we drop the last two elements?

https://github.com/CliMA/Oceananigans.jl/blob/d7d146bc59f966d65eb66a875c16679bef365130/src/Utils/schedules.jl#L177

### PR DESCRIPTION
**Pull request by glwagner**
Closes #3163

### CODE REVIEW

**Comment by navidcy** [comment]
Demo that it works?

**Comment by glwagner** [comment]
# Before

```julia
julia> s = SpecifiedTimes(0, 1, 2)
SpecifiedTimes([0.0, 1.0, 2.0], 0)

julia> specified_times_str(s)
"[0 seconds, ]"
```

# After

```julia
julia> using Oceananigans

julia> using Oceananigans.Utils: specified_times_str

julia> s = SpecifiedTimes(0, 1, 2)
SpecifiedTimes([0.0, 1.0, 2.0], 0)

julia> specified_times_str(s)
"[0 seconds, 1 second, 2 seconds]"
```

**Review by navidcy — APPROVED** [review]

**Comment by glwagner** [comment]
I updated the patch

**Comment by navidcy** [comment]
Oh are we doing the `(0.84.1) PR Name` also for patch releases? Nice!

**Comment by glwagner** [comment]
I don't know. Should we?

**Comment by navidcy** [comment]
it's not a bad idea, but it's one more thing to the list...

I'm happy either way...

For breaking changes is crucial! I even tried to do it for the past view minor releases the other day. It help when you wanna figure out what changed when.

**Comment by glwagner** [comment]
I think it's easier to remember if we always do it when we change `Project.toml`

**Comment by navidcy** [comment]
Merge?

**Pull request merged**
