### PR TITLE
Bugfix in heuristic workgroup

### PR DESCRIPTION
**Pull request by glwagner**
Could be (left, right) or (right, left)... hm!

### CODE REVIEW

**Comment by simone-silvestri** [comment]
does it change the performance?

**Comment by glwagner** [comment]
I think it will for slices (I'd have to go digging but I recall mysterious benchmarks showing 10x slowdown for yz models). Probably worth doing the benchmarks before merging.

**Review by simone-silvestri — APPROVED** [review]

**Comment by navidcy** [comment]
Merge this? Bench it?

**Comment by glwagner** [comment]
I'll merge this now since benchmarking / major changes are planned anyways...

**Pull request merged**
