### PR TITLE
Add shortcuts for zeroing out advection of/by `ZeroField`s

### LINKED ISSUE #1780: `calculate_Gw` for `IncompressibleModel` with `WENO5` and `Float32` cannot compile on GPU
Inspired by the recent activity in #1770, @hennyg888 and I both tried running `benchmark_incompressible_model.jl` with advection set to `WENO5` to learn what the speed up is for this advection scheme from CPUS to GPUS.

In the first resolution, `N=32`, it runs on a `CPU` without any problem.  However, when it starts to run on a `GPU` there is an error, which is copied below.  

When I copy the lines directly into `REPL` to define the grid, model and do one time step, I don't get an error.  Any ideas what might be going wrong in this benchmarking example?

```
[2021/06/28 09:40:32.366] INFO  Benchmarking 1/16: (CPU, Float32, 32)...
[2021/06/28 09:40:38.930] WARN  Inflating model grid halo size to (3, 3, 3) and recreating grid. The model grid will be different from the input grid. To avoid this warning, pass halo=(3, 3, 3) when constructing the grid. -@-> /home/fpoulin/software/New_Oceananigans/Oceananigans.jl/src/Grids/automatic_halo_sizing.jl:41
[2021/06/28 09:42:28.384] INFO  Benchmarking 2/16: (GPU, Float32, 32)...
[2021/06/28 09:42:32.299] WARN  Inflating model grid halo size to (3, 3, 3) and recreating grid. The model grid will be different from the input grid. To avoid this warning, pass halo=(3, 3, 3) when constructing the grid. -@-> /home/fpoulin/software/New_Oceananigans/Oceananigans.jl/src/Grids/automatic_halo_sizing.jl:41
ERROR: LoadError: InvalidIRError: compiling kernel gpu_calculate_Gw!(Cassette.Context{nametype(CUDACtx), KernelAbstractions.CompilerMetadata{KernelAbstractions.NDIteration.StaticSize{(32, 32, 32)}, KernelAbstractions.NDIteration.DynamicCheck, Nothing, Nothing, KernelAbstractions.NDIteration.NDRange{3, KernelAbstractions.NDIteration.StaticSize{(2, 2, 32)}, KernelAbstractions.NDIteration.StaticSize{(16, 16, 1)}, Nothing, Nothing}}, Nothing, KernelAbstractions.var"##PassType#257", Nothing, Cassette.DisableHooks}, typeof(Oceananigans.Models.IncompressibleModels.gpu_calculate_Gw!), OffsetArrays.OffsetArray{Float32, 3, CuDeviceArray{Float32, 3, 1}}, RegularRectilinearGrid{Float32, Periodic, Periodic, Bounded, OffsetArrays.OffsetVector{Float32, StepRangeLen{Float32, Float64, Float64}}}, WENO5, Nothing, Nothing, Nothing, Buoyancy{SeawaterBuoyancy{Float32, LinearEquationOfState{Float32}, Nothing, Nothing}, Oceananigans.BuoyancyModels.ZDirection}, NamedTuple{(:velocities, :tracers), Tuple{NamedTuple{(:u, :v, :w), Tuple{Oceananigans.Fields.ZeroField, Oceananigans.Fields.ZeroField, Oceananigans.Fields.ZeroField}}, NamedTuple{(:T, :S), Tuple{Oceananigans.Fields.ZeroField, Oceananigans.Fields.ZeroField}}}}, NamedTuple{(:u, :v, :w), Tuple{OffsetArrays.OffsetArray{Float32, 3, CuDeviceArray{Float32, 3, 1}}, OffsetArrays.OffsetArray{Float32, 3, CuDeviceArray{Float32, 3, 1}}, OffsetArrays.OffsetArray{Float32, 3, CuDeviceArray{Float32, 3, 1}}}}, NamedTuple{(:T, :S), Tuple{OffsetArrays.OffsetArray{Float32, 3, CuDeviceArray{Float32, 3, 1}}, OffsetArrays.OffsetArray{Float32, 3, CuDeviceArray{Float32, 3, 1}}}}, Nothing, NamedTuple{(:u, :v, :w, :T, :S), NTuple{5, typeof(Oceananigans.Forcings.zeroforcing)}}, NamedTuple{(:time, :iteration, :stage), Tuple{Float32, Int64, Int64}}) resulted in invalid LLVM IR
Reason: unsupported dynamic function invocation (call to overdub)
Stacktrace:
  [1] overdub
    @ ~/software/New_Oceananigans/Oceananigans.jl/src/Advection/upwind_biased_advective_fluxes.jl:98
  [2] _advective_momentum_flux_Ww(::Int64, ::Int64, ::Int64, ::RegularRectilinearGrid{Float32, Periodic, Periodic, Bounded, OffsetArrays.OffsetVector{Float32, StepRangeLen{Float32, Float64, Float64}}}, ::WENO5, ::Oceananigans.Fields.ZeroField, ::OffsetArrays.OffsetArray{Float32, 3, CuDeviceArray{Float32, 3, 1}})
    @ ~/software/New_Oceananigans/Oceananigans.jl/src/Advection/momentum_advection_operators.jl:16
  [3] overdub
    @ ~/software/New_Oceananigans/Oceananigans.jl/src/Advection/momentum_advection_operators.jl:16
  [4] δzᵃᵃᶠ(::Int64, ::Int64, ::Int64, ::RegularRectilinearGrid{Float32, Periodic, Periodic, Bounded, OffsetArrays.OffsetVector{Float32, StepRangeLen{Float32, Float64, Float64}}}, ::typeof(Oceananigans.Advection._advective_momentum_flux_Ww), ::WENO5, ::Oceananigans.Fields.ZeroField, ::OffsetArrays.OffsetArray{Float32, 3, CuDeviceArray{Float32, 3, 1}})
    @ ~/software/New_Oceananigans/Oceananigans.jl/src/Operators/difference_operators.jl:27
  [5] overdub
    @ ~/software/New_Oceananigans/Oceananigans.jl/src/Operators/difference_operators.jl:27
  [6] div_Uw(::Int64, ::Int64, ::Int64, ::RegularRectilinearGrid{Float32, Periodic, Periodic, Bounded, OffsetArrays.OffsetVector{Float32, StepRangeLen{Float32, Float64, Float64}}}, ::WENO5, ::NamedTuple{(:u, :v, :w), Tuple{Oceananigans.Fields.ZeroField, Oceananigans.Fields.ZeroField, Oceananigans.Fields.ZeroField}}, ::OffsetArrays.OffsetArray{Float32, 3, CuDeviceArray{Float32, 3, 1}})
    @ ~/software/New_Oceananigans/Oceananigans.jl/src/Advection/momentum_advection_operators.jl:62
  [7] overdub
    @ ~/software/New_Oceananigans/Oceananigans.jl/src/Advection/momentum_advection_operators.jl:62
  [8] w_velocity_tendency(::Int64, ::Int64, ::Int64, ::RegularRectilinearGrid{Float32, Periodic, Periodic, Bounded, OffsetArrays.OffsetVector{Float32, StepRangeLen{Float32, Float64, Float64}}}, ::WENO5, ::Nothing, ::Nothing, ::Nothing, ::Buoyancy{SeawaterBuoyancy{Float32, LinearEquationOfState{Float32}, Nothing, Nothing}, Oceananigans.BuoyancyModels.ZDirection}, ::NamedTuple{(:velocities, :tracers), Tuple{NamedTuple{(:u, :v, :w), Tuple{Oceananigans.Fields.ZeroField, Oceananigans.Fields.ZeroField, Oceananigans.Fields.ZeroField}}, NamedTuple{(:T, :S), Tuple{Oceananigans.Fields.ZeroField, Oceananigans.Fields.ZeroField}}}}, ::NamedTuple{(:u, :v, :w), Tuple{OffsetArrays.OffsetArray{Float32, 3, CuDeviceArray{Float32, 3, 1}}, OffsetArrays.OffsetArray{Float32, 3, CuDeviceArray{Float32, 3, 1}}, OffsetArrays.OffsetArray{Float32, 3, CuDeviceArray{Float32, 3, 1}}}}, ::NamedTuple{(:T, :S), Tuple{OffsetArrays.OffsetArray{Float32, 3, CuDeviceArray{Float32, 3, 1}}, OffsetArrays.OffsetArray{Float32, 3, CuDeviceArray{Float32, 3, 1}}}}, ::Nothing, ::NamedTuple{(:u, :v, :w, :T, :S), NTuple{5, typeof(Oceananigans.Forcings.zeroforcing)}}, ::NamedTuple{(:time, :iteration, :stage), Tuple{Float32, Int64, Int64}})
    @ ~/software/New_Oceananigans/Oceananigans.jl/src/Models/IncompressibleModels/velocity_and_tracer_tendencies.jl:139
  [9] overdub
    @ ~/software/New_Oceananigans/Oceananigans.jl/src/Models/IncompressibleModels/velocity_and_tracer_tendencies.jl:139
 [10] macro expansion
    @ ~/software/New_Oceananigans/Oceananigans.jl/src/Models/IncompressibleModels/calculate_tendencies.jl:127
 [11] overdub
    @ ~/.julia/packages/KernelAbstractions/Yy47c/src/macros.jl:80
 [12] overdub
    @ ~/.julia/packages/Cassette/N5kbV/src/overdub.jl:0
```

### PR DESCRIPTION
**Pull request by glwagner**
@francispoulin @navidcy let's manually test whether this resolves #1780. (It'd be better to have a test that fails, but the tests #1782 stubbornly refuse to fail.)

### CODE REVIEW

**Comment by glwagner** [comment]
This works on sverdrup:

```julia
(base) glwagner@sverdrup:Oceananigans.jl$ julia --project
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.1 (2021-04-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Oceananigans
[ Info: Precompiling Oceananigans [9e8cae18-63c1-5223-a75c-80ca9d6e9a09]

julia> N = 32
32

julia> grid = RegularRectilinearGrid(Float32, size=(N, N, N), extent=(1, 1, 1))
RegularRectilinearGrid{Float32, Periodic, Periodic, Bounded}
                   domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [-1.0, 0.0]
                 topology: (Periodic, Periodic, Bounded)
  resolution (Nx, Ny, Nz): (32, 32, 32)
   halo size (Hx, Hy, Hz): (1, 1, 1)
grid spacing (Δx, Δy, Δz): (0.03125f0, 0.03125f0, 0.03125f0)

julia> model = IncompressibleModel(architecture=GPU(), advection=WENO5(), clock=Clock{Float64}(0, 0, 1), buoyancy=Buoyancy(model=SeawaterBuoyancy(Float64)), grid=grid)
┌ Warning: Inflating model grid halo size to (3, 3, 3) and recreating grid. The model grid will be different from the input grid. To avoid this warning, pass halo=(3, 3, 3) when constructing the grid.
└ @ Oceananigans.Grids /archive1/glwagner/Projects/Oceananigans.jl/src/Grids/automatic_halo_sizing.jl:41
IncompressibleModel{GPU, Float32}(time = 0 seconds, iteration = 0) 
├── grid: RegularRectilinearGrid{Float32, Periodic, Periodic, Bounded}(Nx=32, Ny=32, Nz=32)
├── tracers: (:T, :S)
├── closure: Nothing
├── buoyancy: SeawaterBuoyancy{Float64, LinearEquationOfState{Float64}, Nothing, Nothing}
└── coriolis: Nothing

julia> time_step!(model, 1)

julia> 
```

@francispoulin can you confirm this solves #1780 ?

**Comment by francispoulin** [comment]
I am happy to say that when I tried our MWE on this branch I also had no errors. 

Even better, I tried it on the benchmark example and found that it did the `Float32` case with `GPU` on a grid of `32` cubed did work.   

However, I see that some tests fail?

Also, @glwagner , care to share what you did here as it seems to work but I am very much puzzled as to why it works.

**Comment by glwagner** [comment]
The error message on #1780 is

```
Stacktrace:
  [1] overdub
    @ ~/software/New_Oceananigans/Oceananigans.jl/src/Advection/upwind_biased_advective_fluxes.jl:98
  [2] _advective_momentum_flux_Ww(::Int64, ::Int64, ::Int64, ::RegularRectilinearGrid{Float32, Periodic, Periodic, Bounded, OffsetArrays.OffsetVector{Float32, StepRangeLen{Float32, Float64, Float64}}}, ::WENO5, ::Oceananigans.Fields.ZeroField, ::OffsetArrays.OffsetArray{Float32, 3, CuDeviceArray{Float32, 3, 1}})
    @ ~/software/New_Oceananigans/Oceananigans.jl/src/Advection/momentum_advection_operators.jl:16
```

The function `_advective_momentum_flux_Ww(i, j, k, grid, scheme, W, w)` is called in `div_Uw`. The type of the argument `W` is `ZeroField` when `div_Uw` is called with `background_fields.velocities` is the advecting velocity field:

https://github.com/CliMA/Oceananigans.jl/blob/78f63ff9329b15ce20c33faed11e96ebf0dbc67d/src/Models/IncompressibleModels/velocity_and_tracer_tendencies.jl#L140

This PR helps the compiler realize that `div_Uw` called when `U` is a tuple of `ZeroField` should return zero.

**Comment by francispoulin** [comment]
Thanks for the explaination.  

It seems the two errors are for the CPU and GPU case that involve testing the advection scheme, but only one time stepping scheme test fails.

```
Advection schemes: Error During Test at /net/ocean/home/data44/data5/glwagner/.buildkite-agent/builds/sverdrup-9/clima/oceananigans/test/test_time_stepping.jl:261
--
  | Test threw exception
  | Expression: time_stepping_works_with_advection_scheme(arch, advection_scheme)
  | TaskFailedException
  |  
  | nested task error: MethodError: div_Uu(::Int64, ::Int64, ::Int64, ::RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded, OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}}, ::Nothing, ::NamedTuple{(:u, :v, :w), Tuple{Oceananigans.Fields.ZeroField, Oceananigans.Fields.ZeroField, Oceananigans.Fields.ZeroField}}, ::Field{Face, Center, Center, CPU, O
```

**Comment by glwagner** [comment]
That's not the whole error, right?

I'll look into it.

**Comment by francispoulin** [comment]
No, that's just the beginning part

**Review by francispoulin — APPROVED** [review]
Looks good to me and glad all tests now pass!

**Pull request merged**
