### PR TITLE
Create copies of AveragedTimeInterval for each output

### LINKED ISSUE #1517: Very different results for the dissipation with NetCDFOutputWriter using snapshots and time-averaged fields
I've been experiencing a odd behavior when outputting dissipation where the results outputting a snapshot and a time-averaged field are different. This doesn't seem to happen for other outputs for some reason and I'm having a hard time understanding what's going on. 

Maybe the best way to illustrate this is with a simplified version of the Eady turbulence example in the docs. The first part of the simulation is basically the same as the example, except with a simple constant isotropic diffusivity for closure (and a different progress messenger). I'm listing it below for completeness, but if you're familiar with the example in the docs you can skip this:

```julia
using Oceananigans
using Oceananigans.Utils
using Oceananigans.Units
using Printf

grid = RegularRectilinearGrid(size=(24, 24, 16), x=(0, 1e6), y=(0, 1e6), z=(-4e3, 0))
coriolis = FPlane(f=1e-4) # [s⁻¹]

const basic_state_parameters = ( α = 10 * coriolis.f, # s⁻¹, geostrophic shear
                           f = coriolis.f,      # s⁻¹, Coriolis parameter
                           N = 1e-3,            # s⁻¹, buoyancy frequency
                          Lz = grid.Lz)         # m, ocean depth

using Oceananigans.Fields: BackgroundField

# Background fields are defined via functions of x, y, z, t, and optional parameters
U(x, y, z, t, p) = + p.α * (z + p.Lz)
B(x, y, z, t, p) = - p.α * p.f * y + p.N^2 * z

U_field = BackgroundField(U, parameters=basic_state_parameters)
B_field = BackgroundField(B, parameters=basic_state_parameters)


#++++ Drag
const cᴰ = 1e-4 # quadratic drag coefficient

@inline drag_u(x, y, t, u, v, cᴰ) = - cᴰ * u * sqrt(u^2 + v^2)
@inline drag_v(x, y, t, u, v, cᴰ) = - cᴰ * v * sqrt(u^2 + v^2)

drag_bc_u = BoundaryCondition(Flux, drag_u, field_dependencies=(:u, :v), parameters=cᴰ)
drag_bc_v = BoundaryCondition(Flux, drag_v, field_dependencies=(:u, :v), parameters=cᴰ)

u_bcs = UVelocityBoundaryConditions(grid, bottom = drag_bc_u)
v_bcs = VVelocityBoundaryConditions(grid, bottom = drag_bc_v)
#-----

#++++ Turbulence closures
const κ = 1e-2 # [m² s⁻¹] Laplacian vertical viscosity and diffusivity
closure = IsotropicDiffusivity(ν=κ, κ=κ,)
#----

#++++ Model instantiation
using Oceananigans.Advection: WENO5
model = IncompressibleModel(
           architecture = CPU(),
                   grid = grid,
              advection = WENO5(),
            timestepper = :RungeKutta3,
               coriolis = coriolis,
                tracers = :b,
               buoyancy = BuoyancyTracer(),
      background_fields = (b=B_field, u=U_field),
                closure = closure,
    boundary_conditions = (u=u_bcs, v=v_bcs)
)
#----


#+++++ Background and ICs
# A noise function, damped at the top and bottom
Ξ(z) = randn() * z/grid.Lz * (z/grid.Lz + 1)

# Scales for the initial velocity and buoyancy
Ũ = 1e-1 * basic_state_parameters.α * grid.Lz
B̃ = 1e-2 * basic_state_parameters.α * coriolis.f

uᵢ(x, y, z) = Ũ * Ξ(z)
vᵢ(x, y, z) = Ũ * Ξ(z)
bᵢ(x, y, z) = B̃ * Ξ(z)

set!(model, u=uᵢ, v=vᵢ, b=bᵢ)

ū = sum(model.velocities.u.data.parent) / (grid.Nx * grid.Ny * grid.Nz)
v̄ = sum(model.velocities.v.data.parent) / (grid.Nx * grid.Ny * grid.Nz)

model.velocities.u.data.parent .-= ū
model.velocities.v.data.parent .-= v̄
#-----

#++++ Progress messenger
using Oceanostics: SingleLineProgressMessenger
start_time = 1e-9*time_ns()
#-----

#++++ Simulation
simulation = Simulation(model, Δt = 20minutes, iteration_interval = 20,
                                                     stop_time = 8days,
                                                     progress = SingleLineProgressMessenger(initial_wall_time_seconds=start_time))
#----



#++++ Outputs
using Oceananigans.AbstractOperations
using Oceananigans.Fields: ComputedField
using Oceanostics.TurbulentKineticEnergyTerms: KineticEnergy, AnisotropicViscousDissipation, IsotropicViscousDissipation

u, v, w = model.velocities # unpack velocity `Field`s
```

Now comes the important part. I'm defining two kernels: one for the dissipation and another for the TKE and then I'm outputting both as a snapshot field and as a time-averaged field:

```julia
using KernelAbstractions: @index, @kernel
using Oceananigans.Grids: Center, Face
using Oceananigans.Fields: KernelComputedField
using Oceananigans.Operators
@kernel function isotropic_viscous_dissipation_ccc!(ϵ, grid, ν, u, v, w)
    i, j, k = @index(Global, NTuple)

    Σˣˣ = ∂xᶜᵃᵃ(i, j, k, grid, u)
    Σʸʸ = ∂yᵃᶜᵃ(i, j, k, grid, v)
    Σᶻᶻ = ∂zᵃᵃᶜ(i, j, k, grid, w)

    Σˣʸ = (ℑxyᶜᶜᵃ(i, j, k, grid, ∂yᵃᶠᵃ, u) + ℑxyᶜᶜᵃ(i, j, k, grid, ∂xᶠᵃᵃ, v)) / 2
    Σˣᶻ = (ℑxzᶜᵃᶜ(i, j, k, grid, ∂zᵃᵃᶠ, u) + ℑxzᶜᵃᶜ(i, j, k, grid, ∂xᶠᵃᵃ, w)) / 2
    Σʸᶻ = (ℑyzᵃᶜᶜ(i, j, k, grid, ∂zᵃᵃᶠ, v) + ℑyzᵃᶜᶜ(i, j, k, grid, ∂yᵃᶠᵃ, w)) / 2

    @inbounds ϵ[i, j, k] = 2 * (Σˣˣ^2 + Σʸʸ^2 + Σᶻᶻ^2 + 2 * (Σˣʸ^2 + Σˣᶻ^2 + Σʸᶻ^2))
end
ε_i = KernelComputedField(Center, Center, Center, isotropic_viscous_dissipation_ccc!, model;
                          computed_dependencies=(κ, u, v, w))


# Vertical vorticity [s⁻¹]
tke = KineticEnergy(model, u, v, w)

outputs = (tke=tke, ε_i=ε_i)

using Oceananigans.OutputWriters: NetCDFOutputWriter, TimeInterval, AveragedTimeInterval
simulation.output_writers[:snap] = NetCDFOutputWriter(model, outputs,
                                                        schedule = TimeInterval(100minutes),
                                                        filepath = "snap.eady.nc",
                                                        mode = "c")
simulation.output_writers[:avg2] = NetCDFOutputWriter(model, outputs,
                                                        schedule = AveragedTimeInterval(100minutes; window=99.99minutes, stride=1),
                                                        filepath = "avg2.eady.nc",
                                                        mode = "c")
#----


#++++ Run simulation
println("Running!")
run!(simulation)
#-----
```

This runs without any problem or warning. When I plot the TKE the results are as expected. The plots below are averaged in space.

TKE is pretty much what I expected, meaning both outputs differ very little:

Screenshot from 2021-03-29 07-43-44

Dissipation is not what I expected since the difference between snapshot and time-averages is way too large:

Screenshot from 2021-03-29 07-44-20

Am I missing something obvious here?  Does anyone have an idea of what's happening?

Thanks!

PS: Here are the packages being used:

```
  [c7e460c6] ArgParse v1.1.2
  [63c18a36] KernelAbstractions v0.5.4
  [9e8cae18] Oceananigans v0.53.2
  [d0ccf422] Oceanostics v0.2.1
  [5fb14364] OhMyREPL v0.5.10
  [d96e819e] Parameters v0.12.2
  [91a5bcdd] Plots v1.11.0
  [276daf66] SpecialFunctions v1.3.0
  [de0858da] Printf
  [10745b16] Statistics
```

CC: @wenegrat

### PR DESCRIPTION
**Pull request by glwagner**
This PR copies `schedule::AveragedTimeInterval` for each time-averaged output object when wrapping objects in `WindowedTimeInterval`. Independent copies of the schedule are needed when multiple outputs are time-averaged and then added to `simulation.diagnostics`, because each schedule has a mutable state that's specific to each output. When a single schedule is used for multiple outputs, the schedule's state is mangled for one or more of the outputs.

This PR also extends the NetCDF time-averaging tests to test the case of multiple outputs in addition to the case of a single output.

Resolves #1517 

cc @tomchor, @navidcy

### CODE REVIEW

**Comment by glwagner** [comment]
A single output passes, but multiple outputs fail:

```
[2021/07/02 15:41:47.527] INFO      Testing time-averaging of a single NetCDF output [CPU]...
[2021/07/02 15:41:47.722] INFO      Testing time-averaging of multiple NetCDF outputs [CPU]...
  | NetCDF output writer [CPU]: Test Failed at /storage7/buildkite-agent/builds/tartarus-mit-edu-8/clima/oceananigans/test/test_netcdf_output_writer.jl:600
  | Expression: (ds["c1"])[:, n + 1] ≈ c̄1(averaging_times)
  | Evaluated: [0.9898351329432816, 0.9873526755690587, 0.9852760567272434, 0.9836993068328084] ≈ [0.9852523062199882, 0.9816589807887, 0.9786560482076754, 0.9763777557588359]
```

The incorrect output is `c1`. Apparently the second output is correct.

**Review by tomchor — APPROVED** [review]
Looks good, thanks for looking into this.

So what fixes the bug is the copying? Could you please explain why this fixes things?

**Comment by glwagner** [comment]
> Looks good, thanks for looking into this.
> 
> So what fixes the bug is the copying? Could you please explain why this fixes things?

Independent copies of the schedule are needed when multiple outputs are time-averaged and then added to `simulation.diagnostics` because each schedule has a mutable state that's specific to each output. When a single schedule is used for multiple outputs, the schedule's state is mangled for one or more of the outputs.

**Comment by navidcy** [comment]
@glwagner, bump a patch release. :)

**Review by navidcy — APPROVED** [review]

**Pull request merged**
