### PR TITLE
PrimitiveSolution / ConservativeSolution dichotomy for ShallowWaterModel

### PR DESCRIPTION
**Pull request by glwagner**
This PR implements dichotomous forms for `ShallowWaterModel.solution`: if `solution = ConservativeSolution()`, then the solution fields are `uh, vh, h` and the PDE is written in "conservative" form. If `solution = PrimitiveSolution()`, then the `solution` fields are `u, v, η` and the solution is written in the "primitive" form. 

We will also linearize the solution around `h = H + η`; however @francispoulin and I deemed that `LinearizedPrimitiveSolution` might be misleading since the momentum equation is still nonlinear (only the height equation is linearized). Alternative names to `PrimitiveSolution` are welcome... 

To do:

- [ ] implement tendency equations for `solution::PrimitiveSolutionFields`
- [ ] basic tests

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
> Alternative names to `PrimitiveSolution` are welcome...

`PrimitiveSolutionLinearFreeSurface`?

**Comment by francispoulin** [comment]
I like @ali-ramadhan 's suggestion of `PrimitiveSolutionLinearFreeSurface`.  It's not short but it is descriptive, and it's nice that `PrimitiveSolution` comes first, in terms of how things will be ordered.

**Comment by glwagner** [comment]
How about `PrimitiveSolutionLinearizedHeight`? It might be redundant to refer to the surface as "free" in the context of the shallow water equations.

**Comment by francispoulin** [comment]
Better!  How about `PrimitiveSolutionLinearizedHeight`?  The height of course does not need to be linear but it is linearized.  A small point but thought I would suggest it

**Comment by navidcy** [comment]
`PrimitiveSolution` and `ConservativeSolution` kind of confuses me. I know what you mean now that you explain...
Perhaps, `PrimitiveVariables` and `ConservativeVariables`? I don't really like that either....

**Comment by glwagner** [comment]
We might abandon this PR...

**Comment by navidcy** [comment]
> We might abandon this PR...

hopefully not because naming convention does not converge... otherwise forget my post above :)

**Comment by glwagner** [comment]
Closing this because its gone stale and we are moving forward with `HydrostaticFreeSurfaceModel` instead.

**Pull request closed without merging**
