### PR TITLE
Changes vertical stretching function back in Ocean wind + convection example

### PR DESCRIPTION
**Pull request by tomchor**
Closes https://github.com/CliMA/Oceananigans.jl/issues/2043

### CODE REVIEW

**Review by francispoulin — APPROVED** [review]

**Review by glwagner — APPROVED** [review]
Let's take a look at the preview before merging. I agree this stretching function is preferred.

**Comment by glwagner** [comment]
The preview isn't showing for me. But we can fix any issues later, so I say merge away.

**Comment by tomchor** [comment]
> The preview isn't showing for me. But we can fix any issues later, so I say merge away.

Yeah, It's also not loading for me. It feels like whenever I try to check PR previews it's kinda hit or miss. I wonder if this is an issue with Documenter.

But if you're okay with it, I'll merge it and we can fix any problems later.

**Comment by glwagner** [comment]
> > The preview isn't showing for me. But we can fix any issues later, so I say merge away.
> 
> Yeah, It's also not loading for me. It feels like whenever I try to check PR previews it's kinda hit or miss. I wonder if this is an issue with Documenter.
> 
> But if you're okay with it, I'll merge it and we can fix any problems later.

It looks like it works for PRs that I submit, but not others. It may have to do with repo privileges.

**Comment by navidcy** [comment]
So why this figure has this king at the end?

Screen Shot 2021-11-09 at 10 04 54 am

**Comment by navidcy** [comment]
> > > The preview isn't showing for me. But we can fix any issues later, so I say merge away.
> > 
> > 
> > Yeah, It's also not loading for me. It feels like whenever I try to check PR previews it's kinda hit or miss. I wonder if this is an issue with Documenter.
> > But if you're okay with it, I'll merge it and we can fix any problems later.
> 
> It looks like it works for PRs that I submit, but not others. It may have to do with repo privileges.

I think, for some reason whatsoever, the preview is not pushed just from the first commit. I think it's because there is a test whether that was a commit on a PR. And unless you first open the PR and then made the first commit that test returns false...

**Comment by tomchor** [comment]
> So why this figure has this kink at the end?
> 
> Screen Shot 2021-11-09 at 10 04 54 am

That's because the function we're using doesn't always produce `Δz`s that are monotonically increasing. We can probably get rid of that by slightly changing the parameters, but I don't think that's a big deal so I never bothered to do it. I'm open to new functions though if you can think of other functions that produce relatively-constant `Δz`s in the same regions where `Δz`s are small.

**Comment by navidcy** [comment]
OK. I see... Gotchat. It's because the function doesn't take into account that the total depth is `Lz`, right? It doesn't make sure that `Nz` spacings should add up to `Lz`. Right?

**Comment by tomchor** [comment]
> OK. I see... Gotcha. It's because the function doesn't take into account that the total depth is `Lz`, right? It doesn't make sure that `Nz` spacings should add up to `Lz`. Right?

I think it does. That's only done on the last equation (which has `Lz`). I think if it didn't make sure that `z_faces(Nz+1)==Lz` we wouldn't be able to use it here.

**Pull request merged**
