### PR TITLE
Dispatch volume operator on flat dimensions

### LINKED ISSUE #1023: Models with `Flat` dimensions still return NaN
I think the definition of "cell volumes" needs to be dispatched on for models of dimension < 3:

https://github.com/CliMA/Oceananigans.jl/blob/6b2cea36d5782f5a73402b97f4d7476de9237c93/src/Operators/areas_and_volumes.jl#L49-L50

Since `Flat` dimensions have zero grid spacing, cell volumes in models with `Flat` dimensions are spuriously calculated to be `0`, which leads to dividing by `0` in advection operators, eg

https://github.com/CliMA/Oceananigans.jl/blob/6b2cea36d5782f5a73402b97f4d7476de9237c93/src/Advection/tracer_advection_operators.jl#L15-L19

I found this while testing the `internal_wave.jl` example for #1014 . We should have a test that models with `Flat` dimensions don't NaN. In fact, I think most or all of the dynamics tests could be converted to use `Flat`.

### LINKED ISSUE #1026: Bug when trying to show velocities from a model with Flat dimensions
```Julia

julia> using Oceananigans
[ Info: Oceananigans will use 12 threads

julia> model = IncompressibleModel(grid = RegularCartesianGrid(topology=(Periodic, Periodic, Flat), size=(16, 16), extent=(2π, 2π)))
IncompressibleModel{CPU, Float64}(time = 0.000 s, iteration = 0)
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Flat}(Nx=16, Ny=16, Nz=1)
├── tracers: (:T, :S)
├── closure: IsotropicDiffusivity{Float64,NamedTuple{(:T, :S),Tuple{Float64,Float64}}}
├── buoyancy: SeawaterBuoyancy{Float64,LinearEquationOfState{Float64},Nothing,Nothing}
└── coriolis: Nothing

julia> model.velocities.u
Error showing value of type Field{Oceananigans.Grids.Face,Oceananigans.Grids.Cell,Oceananigans.Grids.Cell,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularCartesianGrid{Float64,Periodic,Periodic,Flat,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}},NamedTuple{(:x, :y, :z),Tuple{CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing}},CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing}},CoordinateBoundaryConditions{Nothing,Nothing}}}}:
ERROR: MethodError: no method matching bctype_str(::Nothing)
Closest candidates are:
  bctype_str(::BoundaryCondition{Flux,Nothing}) at /Users/navid/Research/Oceananigans.jl/src/BoundaryConditions/show_boundary_conditions.jl:29
  bctype_str(::BoundaryCondition{var"#s63",T} where T where var"#s63"<:Flux) at /Users/navid/Research/Oceananigans.jl/src/BoundaryConditions/show_boundary_conditions.jl:24
  bctype_str(::BoundaryCondition{var"#s63",T} where T where var"#s63"<:Oceananigans.BoundaryConditions.Periodic) at /Users/navid/Research/Oceananigans.jl/src/BoundaryConditions/show_boundary_conditions.jl:25
  ...
Stacktrace:
 [1] short_show(::NamedTuple{(:x, :y, :z),Tuple{CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing}},CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing}},CoordinateBoundaryConditions{Nothing,Nothing}}}) at /Users/navid/Research/Oceananigans.jl/src/BoundaryConditions/show_boundary_conditions.jl:31
 [2] show(::IOContext{REPL.Terminals.TTYTerminal}, ::Field{Oceananigans.Grids.Face,Oceananigans.Grids.Cell,Oceananigans.Grids.Cell,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularCartesianGrid{Float64,Periodic,Periodic,Flat,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}},NamedTuple{(:x, :y, :z),Tuple{CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing}},CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing}},CoordinateBoundaryConditions{Nothing,Nothing}}}}) at /Users/navid/Research/Oceananigans.jl/src/Fields/show_fields.jl:12
 [3] show(::IOContext{REPL.Terminals.TTYTerminal}, ::MIME{Symbol("text/plain")}, ::Field{Oceananigans.Grids.Face,Oceananigans.Grids.Cell,Oceananigans.Grids.Cell,OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},RegularCartesianGrid{Float64,Periodic,Periodic,Flat,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}},NamedTuple{(:x, :y, :z),Tuple{CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing}},CoordinateBoundaryConditions{BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing},BoundaryCondition{Oceananigans.BoundaryConditions.Periodic,Nothing}},CoordinateBoundaryConditions{Nothing,Nothing}}}}) at ./multimedia.jl:47
 [4] display(::REPL.REPLDisplay, ::MIME{Symbol("text/plain")}, ::Any) at /Users/navid/julia/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:214
 [5] display(::REPL.REPLDisplay, ::Any) at /Users/navid/julia/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:218
 [6] display(::Any) at ./multimedia.jl:328
 [7] #invokelatest#1 at ./essentials.jl:710 [inlined]
 [8] invokelatest at ./essentials.jl:709 [inlined]
 [9] print_response(::IO, ::Any, ::Bool, ::Bool, ::Any) at /Users/navid/julia/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:238
 [10] print_response(::REPL.AbstractREPL, ::Any, ::Bool, ::Bool) at /Users/navid/julia/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:223
 [11] (::REPL.var"#do_respond#54"{Bool,Bool,REPL.var"#64#73"{REPL.LineEditREPL,REPL.REPLHistoryProvider},REPL.LineEditREPL,REPL.LineEdit.Prompt})(::Any, ::Any, ::Any) at /Users/navid/julia/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:822
 [12] #invokelatest#1 at ./essentials.jl:710 [inlined]
 [13] invokelatest at ./essentials.jl:709 [inlined]
 [14] run_interface(::REPL.Terminals.TextTerminal, ::REPL.LineEdit.ModalInterface, ::REPL.LineEdit.MIState) at /Users/navid/julia/usr/share/julia/stdlib/v1.5/REPL/src/LineEdit.jl:2355
 [15] run_frontend(::REPL.LineEditREPL, ::REPL.REPLBackendRef) at /Users/navid/julia/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:1144
 [16] (::REPL.var"#38#42"{REPL.LineEditREPL,REPL.REPLBackendRef})() at ./task.jl:356

(Oceananigans) pkg> st
Project Oceananigans v0.40.0
Status `~/Research/Oceananigans.jl/Project.toml`
  [79e6a3ab] Adapt v2.0.2
  [052768ef] CUDA v1.3.3
  [a8cc5b0e] Crayons v4.0.4
  [7a1cc6ca] FFTW v1.2.4
  [033835bb] JLD2 v0.1.14
  [63c18a36] KernelAbstractions v0.4.0
  [85f8d34a] NCDatasets v0.10.4
  [6fe1bfb0] OffsetArrays v1.1.3
  [bac558e1] OrderedCollections v1.3.0
  [1bc83da4] SafeTestsets v0.0.1
  [d496a93d] SeawaterPolynomials v0.2.0
  [90137ffa] StaticArrays v0.12.4
  [ade2ca70] Dates
  [b77e0a4c] InteractiveUtils
  [37e2e46d] LinearAlgebra
  [56ddb016] Logging
  [44cfe95a] Pkg
  [de0858da] Printf
  [9a3f8284] Random
  [10745b16] Statistics
```

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Could also change some of the examples and some tests to use flat dimensions now.

Resolves #1023 
Resolves #1026

### CODE REVIEW

**Comment by navidcy** [comment]
@ali-ramadhan I started converting `two_dimensional_turbulence.jl` to use `Flat` topology and that's how I found #1026. I had some other issues which, hopefully, will be resolved after this is merged.

**Comment by glwagner** [comment]
> @ali-ramadhan I started converting `two_dimensional_turbulence.jl` to use `Flat` topology and that's how I found #1026. I had some other issues which, hopefully, will be resolved after this is merged (?).

Oh my, thanks for catching that!

There are some mysterious bugs in this PR right now. Column models work but doubly periodic ones seem to NaN, as evidenced by the passive tracer advection test in `test_dynamics.jl`.

**Comment by glwagner** [comment]
The issue with this PR is probably some stray manual call to `grid.Δx` (for example), rather than using `Δx(i, j, k, grid)`. Probably fixing this PR is one step toward getting the stretched grid to work...

**Comment by navidcy** [comment]
@glwagner, @ali-ramadhan let's finish this?

**Comment by glwagner** [comment]
I was stumped. Do you see how to make progress?

**Comment by navidcy** [comment]
I actually don't understand the problem at its heart. But I just pinged you two in case this was just forgotten and got lost deep down in the "sea" of issues...

**Comment by ali-ramadhan** [comment]
Closing as this PR has become stale and has been superseded by PR #1513.

**Pull request closed without merging**
