### PR TITLE
Handle edge case of Δt = 0 for `IncompressibleModel`

### LINKED ISSUE #1247: Examples are NaNing out 😱
Seems that examples are NaNing out while building documentation since PR #1198 was merged even though everything was fine for the latest Buildkite build on that PR: https://buildkite.com/clima/oceananigans/builds/649

Two failures on the same commit so it's a consistent issue:
https://buildkite.com/clima/oceananigans/builds/824
https://buildkite.com/clima/oceananigans/builds/830

I was able to reproduce locally as well.

Thankfully this is just master as PR #1198 was not part of v0.45.0.

Not sure how that happened but if this issue can't be fixed soon we should revert #1198.

### LINKED ISSUE #1254: Taking a time step of 0 causes the model to NaN out
This is because the right-hand-side of the pressure Poisson equation depends on 1/Δt so Δt=0 leads to an `Inf` source term:

https://github.com/CliMA/Oceananigans.jl/blob/c3b688f9ef125faeac3aa9d7fd57f0dd2d392380/src/Solvers/solve_for_pressure.jl#L41

This wasn't an issue before since we never `time_step!(model, 0)` but now that the time step is aligned with output writing and simulation stop times, it's possible to end up calling `time_step!(model, 0)`:

https://github.com/CliMA/Oceananigans.jl/blob/c3b688f9ef125faeac3aa9d7fd57f0dd2d392380/src/Simulations/run.jl#L159-L161

Not sure of the best solution to this but one possible solution is if calling `time_step!(model, 0)` causes it to return early without doing anything.

I added the "high priority" label to this issue since it can cause the output to contain `NaN` at the last time step, very undesirable for users.

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Resolves #1254
Resolves #1247 (hopefully)

### CODE REVIEW

**Review by glwagner — APPROVED** [review]
We can't have dt=0 because

https://github.com/CliMA/Oceananigans.jl/blob/c3b688f9ef125faeac3aa9d7fd57f0dd2d392380/src/Solvers/solve_for_pressure.jl#L41

**Comment by ali-ramadhan** [comment]
Yes I pointed that out in #1254.

Question is do we error, warn, or return early if `time_step!(model::IncompressibleModel, 0)` is called?

**Comment by ali-ramadhan** [comment]
Examples build again and don't NaN out so this was indeed the issue. I'll merge.

Shallow water tests are failing because NaN checker, by default, checks for NaNs in `model.velocities.u` which `ShallowWaterModel` doesn't have. Default should probably be `fields(model)[1]`.

**Comment by glwagner** [comment]
I think `time_step!` is not user-facing so we should just make sure to never call `time_step(model, 0)`.

**Pull request merged**
