### PR TITLE
Removes redundant definition for `halo_size`

### PR DESCRIPTION
**Pull request by aramirezreyes**
The definition on line 69 was identical to that of line 86. Fixes https://github.com/CliMA/Oceananigans.jl/issues/2129

### CODE REVIEW

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
Same issue with test not passing. Not sure what happened. Unable to look into it before Jan 3rd.

**Comment by navidcy** [comment]
@aramirezreyes, could you bring this up to date with `main` branch? Perhaps all tests pass then and we can merge.

**Comment by navidcy** [comment]
> @aramirezreyes, could you bring this up to date with `main` branch? Perhaps all tests pass then and we can merge.

turns out I could do that :)

**Comment by aramirezreyes** [comment]
I don't understand what is going on with my two PRs that are not passing the tests. Should I close and create them again from the latest master?

**Comment by navidcy** [comment]
> I don't understand what is going on with my two PRs that are not passing the tests. Should I close and create them again from the latest master?

Nope. It's not your fault. We are having issues with the CI.

**Comment by aramirezreyes** [comment]
Ah! Good to know! Thanks.
Argel Ramírez Reyes

**Comment by glwagner** [comment]
@aramirezreyes this PR may end up being superceded by #2121 unfortunately... I really apologize about the CI issues preventing us from merging this sooner!

**Comment by navidcy** [comment]
@glwagner I suggest we merge this. No?

**Comment by glwagner** [comment]
The tests are failing :-(

**Comment by glwagner** [comment]
This will also mean that we can't merge #2121 cause we'll have to resolve the merge conflict there. We could wait until tomorrow to merge #2121 instead...

**Comment by glwagner** [comment]
I restarted it here: https://buildkite.com/clima/oceananigans/builds/5094 in case #2121 doens't go in. Don't know why github isn't updating the present status. Another commit here might be better.

**Comment by navidcy** [comment]
Closing since it was superseded by #2121. :(

**Pull request closed without merging**
