### PR TITLE
Test N-tuple `MultipleForcings` and make them work on the GPU

### LINKED ISSUE #3736: Error when trying to use `MultipleForcings`
I know `MultipleForcings` is not exported and not tested so it's experimental. It seems like a useful feature so I tried using it but I ran into an error. Seems to be related to forcing function call arguments (or maybe incorrect regularization?) but I haven't been able to figure out the exact cause.

Minimal working example:

```julia
using Oceananigans

using Oceananigans.Forcings: MultipleForcings

grid = LatitudeLongitudeGrid(size=(10, 10, 10), longitude=(0, 1), latitude=(0, 1), z=(-1, 0))

weird_forcing(λ, φ, z, t) = λ * φ + z
wonky_forcing(λ, φ, z, t) = z / (λ - φ)

forcing1 = Forcing(weird_forcing)
forcing2 = Forcing(wonky_forcing)

forcing = (; u=MultipleForcings((forcing1, forcing2)))

model = HydrostaticFreeSurfaceModel(; grid, forcing)
```

produces this error:

```
ERROR: MethodError: no method matching field_arguments(::Int64, ::Int64, ::Int64, ::LatitudeLongitudeGrid{…}, ::@NamedTuple{…}, ::Nothing, ::Nothing)

Closest candidates are:
  field_arguments(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Tuple{T, T, T} where T)
   @ Oceananigans ~/.julia/packages/Oceananigans/Hkk5J/src/Utils/user_function_arguments.jl:8
  field_arguments(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Tuple{T, T} where T)
   @ Oceananigans ~/.julia/packages/Oceananigans/Hkk5J/src/Utils/user_function_arguments.jl:4
  field_arguments(::Any, ::Any, ::Any, ::Any, ::Any, ::Any, ::Tuple{Any})
   @ Oceananigans ~/.julia/packages/Oceananigans/Hkk5J/src/Utils/user_function_arguments.jl:1
  ...

Stacktrace:
  [1] user_function_arguments
    @ ~/.julia/packages/Oceananigans/Hkk5J/src/Utils/user_function_arguments.jl:21 [inlined]
  [2] ContinuousForcing
    @ ~/.julia/packages/Oceananigans/Hkk5J/src/Forcings/continuous_forcing.jl:137 [inlined]
  [3] MultipleForcings
    @ ~/.julia/packages/Oceananigans/Hkk5J/src/Forcings/multiple_forcings.jl:32 [inlined]
  [4] hydrostatic_free_surface_u_velocity_tendency
    @ ~/.julia/packages/Oceananigans/Hkk5J/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl:46 [inlined]
  [5] cpu_compute_hydrostatic_free_surface_Gu!
    @ ~/.julia/packages/KernelAbstractions/3B1v2/src/macros.jl:291 [inlined]
  [6] cpu_compute_hydrostatic_free_surface_Gu!(__ctx__::KernelAbstractions.CompilerMetadata{…}, Gu::Field{…}, grid::LatitudeLongitudeGrid{…}, map::Nothing, args::Tuple{…})
    @ Oceananigans.Models.HydrostaticFreeSurfaceModels ./none:0
  [7] __thread_run(tid::Int64, len::Int64, rem::Int64, obj::KernelAbstractions.Kernel{…}, ndrange::Nothing, iterspace::KernelAbstractions.NDIteration.NDRange{…}, args::Tuple{…}, dynamic::KernelAbstractions.NDIteration.DynamicCheck)
    @ KernelAbstractions ~/.julia/packages/KernelAbstractions/3B1v2/src/cpu.jl:140
  [8] __run(obj::KernelAbstractions.Kernel{…}, ndrange::Nothing, iterspace::KernelAbstractions.NDIteration.NDRange{…}, args::Tuple{…}, dynamic::KernelAbstractions.NDIteration.DynamicCheck, static_threads::Bool)
    @ KernelAbstractions ~/.julia/packages/KernelAbstractions/3B1v2/src/cpu.jl:107
  [9] (::KernelAbstractions.Kernel{…})(::Field{…}, ::Vararg{…}; ndrange::Nothing, workgroupsize::Nothing)
    @ KernelAbstractions ~/.julia/packages/KernelAbstractions/3B1v2/src/cpu.jl:46
 [10] (::KernelAbstractions.Kernel{…})(::Field{…}, ::Vararg{…})
    @ KernelAbstractions ~/.julia/packages/KernelAbstractions/3B1v2/src/cpu.jl:39
 [11] launch!(::CPU, ::LatitudeLongitudeGrid{…}, ::Symbol, ::typeof(Oceananigans.Models.HydrostaticFreeSurfaceModels.compute_hydrostatic_free_surface_Gu!), ::Field{…}, ::Vararg{…}; include_right_boundaries::Bool, reduced_dimensions::Tuple{}, location::Nothing, active_cells_map::Nothing, kwargs::@Kwargs{})
    @ Oceananigans.Utils ~/.julia/packages/Oceananigans/Hkk5J/src/Utils/kernel_launching.jl:168
 [12] launch!
    @ ~/.julia/packages/Oceananigans/Hkk5J/src/Utils/kernel_launching.jl:154 [inlined]
 [13] #compute_hydrostatic_momentum_tendencies!#45
    @ ~/.julia/packages/Oceananigans/Hkk5J/src/Models/HydrostaticFreeSurfaceModels/compute_hydrostatic_free_surface_tendencies.jl:162 [inlined]
 [14] compute_hydrostatic_momentum_tendencies!
    @ ~/.julia/packages/Oceananigans/Hkk5J/src/Models/HydrostaticFreeSurfaceModels/compute_hydrostatic_free_surface_tendencies.jl:136 [inlined]
 [15] #compute_hydrostatic_free_surface_tendency_contributions!#44
    @ ~/.julia/packages/Oceananigans/Hkk5J/src/Models/HydrostaticFreeSurfaceModels/compute_hydrostatic_free_surface_tendencies.jl:68 [inlined]
 [16] compute_hydrostatic_free_surface_tendency_contributions!
    @ ~/.julia/packages/Oceananigans/Hkk5J/src/Models/HydrostaticFreeSurfaceModels/compute_hydrostatic_free_surface_tendencies.jl:63 [inlined]
 [17] compute_tendencies!(model::HydrostaticFreeSurfaceModel{…}, callbacks::Vector{…})
    @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/.julia/packages/Oceananigans/Hkk5J/src/Models/HydrostaticFreeSurfaceModels/compute_hydrostatic_free_surface_tendencies.jl:28
 [18] #apply_regionally!#56
    @ ~/.julia/packages/Oceananigans/Hkk5J/src/Utils/multi_region_transformation.jl:121 [inlined]
 [19] apply_regionally!
    @ ~/.julia/packages/Oceananigans/Hkk5J/src/Utils/multi_region_transformation.jl:118 [inlined]
 [20] macro expansion
    @ ~/.julia/packages/Oceananigans/Hkk5J/src/Utils/multi_region_transformation.jl:206 [inlined]
 [21] update_state!(model::HydrostaticFreeSurfaceModel{…}, grid::LatitudeLongitudeGrid{…}, callbacks::Vector{…}; compute_tendencies::Bool)
    @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/.julia/packages/Oceananigans/Hkk5J/src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl:50
 [22] update_state!
    @ ~/.julia/packages/Oceananigans/Hkk5J/src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl:31 [inlined]
 [23] update_state!
    @ ~/.julia/packages/Oceananigans/Hkk5J/src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl:28 [inlined]
 [24] update_state!(model::HydrostaticFreeSurfaceModel{…})
    @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/.julia/packages/Oceananigans/Hkk5J/src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl:28
 [25] HydrostaticFreeSurfaceModel(; grid::LatitudeLongitudeGrid{…}, clock::Clock{…}, momentum_advection::Centered{…}, tracer_advection::Centered{…}, buoyancy::Nothing, coriolis::Nothing, free_surface::SplitExplicitFreeSurface{…}, tracers::Nothing, forcing::@NamedTuple{…}, closure::Nothing, boundary_conditions::@NamedTuple{}, particles::Nothing, biogeochemistry::Nothing, velocities::Nothing, pressure::Nothing, diffusivity_fields::Nothing, auxiliary_fields::@NamedTuple{})
    @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/.julia/packages/Oceananigans/Hkk5J/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:204
 [26] top-level scope
    @ REPL[30]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

---

Environment: Oceananigans.jl v0.91.11 and

```
julia> versioninfo()
Julia Version 1.10.4
Commit 48d4fd48430 (2024-06-04 10:41 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 48 × AMD Ryzen Threadripper 7960X 24-Cores
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 48 virtual cores)
```

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Resolves #3736

### CODE REVIEW

**Comment by glwagner** [comment]
Should also add something like

```julia
regularize_forcing(mf::MultipleForcings, args...) = regularize_forcing(mf.forcings, args...)
```

so that users can write `u = MultipleForcings(f1, f2)`?

**Review by glwagner — APPROVED** [review]

**Comment by ali-ramadhan** [comment]
Added with tests! Should we export `MultipleForcings`?

**Comment by glwagner** [comment]
> Added with tests! Should we export `MultipleForcings`?

Maybe we don't need to since tupling is the "official" API?

**Comment by glwagner** [comment]
thanks @ali-ramadhan !

**Pull request merged**
