### PR TITLE
Fixes small typo in docs

### PR DESCRIPTION
**Pull request by tomchor**

### CODE REVIEW

**Comment by tomchor** [comment]
Also I just realized that versiondocs for version 0.91.1 aren't online:

image

Is this issue known?

**Review by glwagner — APPROVED** [review]

**Comment by glwagner** [comment]
> Also I just realized that versiondocs for version 0.91.1 aren't online:
> 
> image
> 
> Is this issue known?

@navidcy might know about this...

**Comment by tomchor** [comment]
I've retried the tests a couple of times but I keep getting errors like this:

```
Failed to precompile Oceananigans [9e8cae18-63c1-5223-a75c-80ca9d6e9a09] to "/data5/glwagner/.julia-16001/compiled/v1.10/Oceananigans/jl_Bzx0zi".
ERROR: LoadError: SystemError: opening file "/data5/glwagner/.julia-16001/packages/CUDA_Runtime_jll/dOYZJ/.pkg/platform_augmentation.jl": No such file or directory
```

Is something wrong with the servers at the moment?

**Comment by glwagner** [comment]
Not as far as I know, at least not more than is usually wrong with this very annoying and fragile system we have...

**Pull request merged**
