### PR TITLE
Fix warning on IB boundary condition docs

### PR DESCRIPTION
**Pull request by tomchor**

### CODE REVIEW

**Review by glwagner — APPROVED** [review]
Thanks!

**Comment by glwagner** [comment]
Can I commit a few more tweaks to the docs here?

**Comment by tomchor** [comment]
> Can I commit a few more tweaks to the docs here?

Sure!

**Comment by glwagner** [comment]
Ok, I sent an update that I hope improves the language a bit.

**Review by navidcy — APPROVED** [review]

**Pull request merged**
