### PR TITLE
VerticallyImplicitTimeDiscretization for symmetric isoneutral diffusion

### PR DESCRIPTION
**Pull request by glwagner**
This PR adds the capability for treating the "33" component of the symmetric isoneutral diffusive flux implicitly.

cc @sandreza would be great if you test this.

This depends on #2481

### CODE REVIEW

**Comment by glwagner** [comment]
Not working yet --- we have to be able to calculate the isopycnal slope inside the vertically-implicit diffusion solver, so need some refactoring.

**Comment by glwagner** [comment]
Ok, I think this is basically working now.

https://user-images.githubusercontent.com/15271942/165753191-b9ef8480-72a8-49ef-809e-56fa13d853a3.mp4

For GM, the remaining issue is what happens at horizontal boundaries.

@sandreza let me know if you get satisfactory results from this PR and we will merge.

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
`VerticallyImplicitTimeDiscretization` will be the default, right?

**Comment by glwagner** [comment]
I made it default!

**Pull request merged**
