### PR TITLE
Cleanup unused type variables

### PR DESCRIPTION
**Pull request by simone-silvestri**
Following the warnings issued by julia `v1.8.2`
```

WARNING: method definition for _multiary_operation at /home/ssilvest/Oceananigans.jl/src/AbstractOperations/multiary_operations.jl:23 declares type variable LZ but does not use it.
WARNING: method definition for _multiary_operation at /home/ssilvest/Oceananigans.jl/src/AbstractOperations/multiary_operations.jl:23 declares type variable LY but does not use it.
WARNING: method definition for _multiary_operation at /home/ssilvest/Oceananigans.jl/src/AbstractOperations/multiary_operations.jl:23 declares type variable LX but does not use it.
WARNING: method definition for _derivative at /home/ssilvest/Oceananigans.jl/src/AbstractOperations/derivatives.jl:31 declares type variable LZ but does not use it.
WARNING: method definition for _derivative at /home/ssilvest/Oceananigans.jl/src/AbstractOperations/derivatives.jl:31 declares type variable LY but does not use it.
WARNING: method definition for _derivative at /home/ssilvest/Oceananigans.jl/src/AbstractOperations/derivatives.jl:31 declares type variable LX but does not use it.
WARNING: method definition for show at /home/ssilvest/Oceananigans.jl/src/OutputReaders/field_dataset.jl:52 declares type variable A but does not use it.
WARNING: method definition for show at /home/ssilvest/Oceananigans.jl/src/OutputReaders/field_dataset.jl:52 declares type variable K but does not use it.
WARNING: method definition for show at /home/ssilvest/Oceananigans.jl/src/OutputReaders/field_dataset.jl:52 declares type variable Z but does not use it.
WARNING: method definition for show at /home/ssilvest/Oceananigans.jl/src/OutputReaders/field_dataset.jl:52 declares type variable Y but does not use it.
WARNING: method definition for show at /home/ssilvest/Oceananigans.jl/src/OutputReaders/field_dataset.jl:52 declares type variable X but does not use it.
```

### CODE REVIEW

**Review by navidcy — APPROVED** [review]
Great! Fix merge conflicts and merge away!

**Comment by navidcy** [comment]
Do we need this:
https://github.com/CliMA/Oceananigans.jl/blob/85bf08db49d754ce38814a736d49232f33eee8a7/src/AbstractOperations/at.jl#L61
?

Isn't this the same?
https://github.com/CliMA/Oceananigans.jl/blob/85bf08db49d754ce38814a736d49232f33eee8a7/src/Fields/field.jl#L302

**Comment by simone-silvestri** [comment]
Oh yeah, I didn't notice a fallback was already defined

**Comment by navidcy** [comment]
merge?

**Pull request merged**
