### PR TITLE
Allow non-zero diffusive and viscous fluxes with ImmersedBoundaryGrid

### PR DESCRIPTION
**Pull request by glwagner**
Previously the functions viscous_flux_u* and diffusive_flux_* dispatched on AbstractPrimaryGrid. AbstractPrimaryGrid (now called AbstractUnderlyingGrid is an abstract type for distinguishing between ImmersedBoundaryGrid and the "primitive" / "primary" / "underlying" counterparts (I guess I'm still not sure what the best name is).

As a result, flux calculations with ImmersedBoundaryGrid were hitting fallback flux functions that returned 0.

This PR removes most instances dispatching on grid (except where necessary, where the dispatched type was changed from AbstractPrimaryGrid to AbstractGrid). It also nukes the fallbacks (which were the reason this issue escaped detection originally).

This PR also adds a minimal test that _vertical_ diffusive and viscous fluxes work. It does not test the horizontal fluxes, but the test will catch egregious bugs like the one this PR fixes.

The original motivation for dispatching on AbstractPrimaryGrid is not only wrong but also appears to be unnecessary, since the tests on this PR pass.

For some reason TwoDimensionalLeith was also having trouble compiling on the GPU, so we're skipping those tests for now.

### CODE REVIEW

**Comment by navidcy** [comment]
question: will this be relevant to the #1744?

**Comment by glwagner** [comment]
Yes definitely.

**Comment by navidcy** [comment]
@glwagner I can try to review. Could you write a small description of what was done here?

**Comment by glwagner** [comment]
Previously the functions `viscous_flux_u*` and `diffusive_flux_*` dispatched on `AbstractPrimaryGrid`. `AbstractPrimaryGrid` (now called `AbstractUnderlyingGrid` is an abstract type for distinguishing between `ImmersedBoundaryGrid` and the "primitive" / "primary" / "underlying" counterparts (I guess I'm still not sure what the best name is).

As a result, flux calculations with `ImmersedBoundaryGrid` were hitting fallback flux functions that returned 0.

The original motivation for dispatching on `AbstractPrimaryGrid` is not only wrong but also appears to be unnecessary, since the tests on this PR pass.

For some reason `TwoDimensionalLeith` was also having trouble compiling on the GPU, so we're skipping those tests for now.

**Comment by glwagner** [comment]
@whitleyv do you think you can review this PR?

**Review by whitleyv — APPROVED** [review]

**Pull request merged**
