### PR TITLE
AbstractRectilinearGrid and curvilinear horizontal grid spacing and gradient operators

### PR DESCRIPTION
**Pull request by glwagner**
This PR adds horizontal grid spacing and gradient operators valid on curvilinear grids.

This means that a class of gradient operators will persist which are only valid on Rectilinear grids. To help prevent bugs associated with incorrectly applying these restricted operators to general grids, this PR also adds a new type `AbstractRectilinearGrid`.

Note: apparently we have been using the term "Cartesian" incorrectly, since ["Cartesian" only applies to coordinate systems with _unit_ areas and volumes](https://en.wikipedia.org/wiki/Regular_grid). So really we have a `RegularRectilinearGrid` and `VerticallyStretchedRectilinearGrid` (in the later case, horizontal regularity is implicit).

### CODE REVIEW

**Review by francispoulin — APPROVED** [review]
I see that these changes do two things.  First, add arguments into the difference operators.  Second, remove the difference operators on functions.  I gather the first will be important when dealing with a curvlinear coordinates.  Is there no loner a need for operators on functions?  

I admit I was always a bit uncertain as to why there were two different sets of operators and having one seems reasonable to me.

**Comment by glwagner** [comment]
> Is there no loner a need for operators on functions?

As far as I can tell there was never a need. I think we were being defensive because sometimes julia has trouble inferring the types of _functions_. So those extra definitions may have been intended to help with that. But I don't think we ever proved they are necessary.

**Comment by glwagner** [comment]
> I admit I was always a bit uncertain as to why there were two different sets of operators and having one seems reasonable to me.

Right --- the point is that `args...` generalizes to "no argument".

**Comment by francispoulin** [comment]
Thanks @glwagner , the changes look good and I'm glad there will only be one function now instead of two.

**Comment by glwagner** [comment]
Err... looks like we do actually have to force specialization of some of the operators.

**Pull request merged**
