### PR TITLE
Update packages

### LINKED ISSUE #1220: Upgrade to CUDA v2.3.0?
Manifest.toml restricts CUDA to v.1.3.3

https://github.com/CliMA/Oceananigans.jl/blob/4011a3431144c3a58671e5d827ab39da8fe6e948/Manifest.toml#L51

### PR DESCRIPTION
**Pull request by navidcy**
Closes #1220.

### CODE REVIEW

**Review by ali-ramadhan — APPROVED** [review]
Thanks @navidcy!

Looks like GPU tests on Buildkite are failing due to lack of disk space but hopefully we can fix that soon so we can see whether this PR is safe to merge.

**Comment by ali-ramadhan** [comment]
To avoid `Manifest.toml` merge conflicts should we update NCDatasets.jl (#1217) and StaticArrays.jl (#1222) in this PR as well?

I actually don't think we use StaticArrays.jl...? I used it for the `WENO{N}` implementation but it's currently commented out until it can be made efficient (also users did not like the sympy dependency).

**Comment by navidcy** [comment]
`src/Advection/weno_reconstruction.jl` is the only place StaticArrays is called but seems that everything is commented out?
@ali-ramadhan, I think this calls for a WENO cleanup PR?

**Comment by ali-ramadhan** [comment]
Looks like KernelAbstractions.jl depends on StaticArrays.jl so it was a free dependency I suppose but good to clean up the Project.toml a bit.

@navidcy Ah yeah maybe I'm a little too attached to that `weno_nth_order.jl` implementation haha. Been hoping to make it efficient so we can get fast and automatically generated WENO(n) schemes for n = 3, 5, 7, 9, ... (but it can always be fished out of git history of course).

**Comment by navidcy** [comment]
@ali-ramadhan I didn't mean to imply you delete the `weno_nth_order.jl` implementation. But if we don't have StaticArrays.jl as a direct dependency we can't have `using StaticArrays` inside `src/Advection/weno_reconstruction.jl`.

I vote we put it back as a direct dependency and merge this PR now. What do you reckon @ali-ramadhan?
I'll put it back but stay at `v0.12.5`/ I'm not sure why I can't get the `v1.0` installed. I never managed to install `StaticArrays v1.0` for GeophysicalFlows.jl either btw...

**Comment by navidcy** [comment]
Could I restart the buildkite builds? (I think I can't...)

**Comment by glwagner** [comment]
@ali-ramadhan it might make sense to move the WENO nth order into a draft PR where we can work on making it fast, with a simple benchmark to work from.

**Comment by navidcy** [comment]
@glwagner I agree --- but no need to do it for this PR.

However, I won't merge if I don't see all tests pass and somehow I can't restart the buildkite builds. (Either I don't have rights to do so or I don't know how.) Can you help me out here?

**Comment by ali-ramadhan** [comment]
Sorry @navidcy I think unit tests were failing due to me removing StaticArrays but `weno_reconstruction.jl` and (`test_weno_reconstruction.jl`) still needed it. Tests should pass now 🤞 

Moving nth order WENO into a draft PR makes sense to me so I've nuked it in this PR so we can get rid of the explicit dependency on StaticArrays.

@navidcy Don't think you can restart Buildkite builds right now since @glwagner and I had to be added as Buildkite users (and it's all under some CliMA account).

@jakebolewski might know whether it's possible for GitHub collaborators to have some access to Buildkite?

**Comment by jakebolewski** [comment]
Unfortunately that is not possible, but we could add outside collaborators to a team with the correct permissions

**Pull request merged**
