### PR TITLE
More tests for boundary conditions

### LINKED ISSUE #2091: Do we want to go triply-Bounded for `test_boundary_conditions_integration.jl`?
I noticed this deprecated warning...

https://github.com/CliMA/Oceananigans.jl/blob/d9e2c31e20e78f1b1dcb4d9bd01a959c51bcb60e/test/test_boundary_conditions_integration.jl#L139-L140

### PR DESCRIPTION
**Pull request by navidcy**
Closes #2091.

### CODE REVIEW

**Comment by navidcy** [comment]
@glwagner, what about
https://github.com/CliMA/Oceananigans.jl/blob/3c86d8f37a3bf5ff050e233f7b946685f9057c26/test/test_boundary_conditions_integration.jl#L200

Should we simplify to `topo = (Bounded, Bounded, Bounded)`?

**Comment by glwagner** [comment]
Yes and if statements here:

https://github.com/CliMA/Oceananigans.jl/blob/3c86d8f37a3bf5ff050e233f7b946685f9057c26/test/test_boundary_conditions_integration.jl#L203

and here

https://github.com/CliMA/Oceananigans.jl/blob/3c86d8f37a3bf5ff050e233f7b946685f9057c26/test/test_boundary_conditions_integration.jl#L210

should be removed.

**Comment by navidcy** [comment]
@glwagner, done! :)

**Review by simone-silvestri — APPROVED** [review]

**Comment by navidcy** [comment]
@glwagner, after 9c10cb5 tests break. See https://buildkite.com/clima/oceananigans/builds/4750#6ef5a18e-4db4-4881-aabe-e39eafaf2196/40-312

I thought that the mistake was because I had prescribed `Value` bc's for u at East/West. But the errors persists after I [changed](https://github.com/CliMA/Oceananigans.jl/pull/2103/commits/842861f152fa4193a8fb75d58324e209d5f124e5) that to Open

Could you have a look at:
https://github.com/CliMA/Oceananigans.jl/blob/d6deb950cdcd489ceb872568663ecf5b2c8ccb2a/test/test_boundary_conditions_integration.jl#L213

**Comment by glwagner** [comment]
The error is

```


MethodError: no method matching XFaceField(::Type{Float64}, ::RectilinearGrid{Float64, Bounded, Bounded, Bounded, Float64, Float64, Float64, OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, DataType}, ::FieldBoundaryConditions{BoundaryCondition{Open, ContinuousBoundaryFunction{Nothing, Center, Center, 1, var"#7#8", Nothing, Tuple{}, Tuple{}, Tuple{}}}, BoundaryCondition{Open, ContinuousBoundaryFunction{Nothing, Center, Center, 1, var"#7#8", Nothing, Tuple{}, Tuple{}, Tuple{}}}, BoundaryCondition{Value, ContinuousBoundaryFunction{Face, Nothing, Center, 1, var"#7#8", Nothing, Tuple{}, Tuple{}, Tuple{}}}, BoundaryCondition{Value, ContinuousBoundaryFunction{Face, Nothing, Center, 1, var"#7#8", Nothing, Tuple{}, Tuple{}, Tuple{}}}, BoundaryCondition{Value, ContinuousBoundaryFunction{Face, Center, Nothing, 1, var"#7#8", Nothing, Tuple{}, Tuple{}, Tuple{}}}, BoundaryCondition{Value, ContinuousBoundaryFunction{Face, Center, Nothing, 1, var"#7#8", Nothing, Tuple{}, Tuple{}, Tuple{}}}, BoundaryCondition{Flux, Nothing}})
--
  | Closest candidates are:
  | XFaceField(::AbstractArchitecture, ::Any...) at /var/lib/buildkite-agent/builds/tartarus-8/clima/oceananigans/src/Fields/field.jl:89
  | XFaceField(::AbstractGrid, ::Any...) at /var/lib/buildkite-agent/builds/tartarus-8/clima/oceananigans/src/Fields/field.jl:109
  | Stacktrace:
  | [1] VelocityFields(arch::Type, grid::RectilinearGrid{Float64, Bounded, Bounded, Bounded, Float64, Float64, Float64, OffsetVector{Float64,
<snip>
```

**Comment by navidcy** [comment]
So, perhaps `grid = RectilinearGrid(arch, FT, size=(1, 1, 1), extent=(1, π, 42), topology=(Bounded, Bounded, Bounded))`?

**Pull request merged**
