### PR TITLE
Implements compute_at! pattern for conditional computation

### PR DESCRIPTION
**Pull request by glwagner**
This PR extends the capability of our "conditional computation" framework wherein the "re-calculation" of expensive diagnostics and computations may be avoided if possible.

Previously, expensive field recalculations were avoided *only* at the outermost level (if the field were used directly in output), which in hindsight doesn't seem very useful since we often average or otherwise reduce expensive calculations for output (if we were not reducing an expensive calculation, we could simply calculate it offline).

Avoiding recalculation for field "dependencies" requires adding a third function for field computation: we now have `compute_at!(field, time)`, `conditional_compute!(field, time)`, and `compute!(field, time)`.

`compute_at!(field, time)` is the outermost function called by `fetch_output`. It falls back to `compute!(field)`. Fields opt-in to conditional computation by overloading `compute_at!`; for example, `ComputeField` implements

```julia
compute_at!(field::ComputedField{X, Y, Z, <:FieldStatus}, time) where {X, Y, Z} = conditional_compute!(field, time)
```

Thus `ComputedField`s that have a `field.status` which is not `Nothing` are _conditionally_ computed. But if `field.status === nothing`, the computed field is always recomputed.

The function `conditional_compute!(field, time)` examines `field.status` to determine whether a field has already been computed at `time` or not. If the field has been computed, it does nothing. If the field has not been computed, then `compute!(field, time)` is called, and `field.status.time` is updated.

Conditionally computed fields must define a function `compute!(field, time=nothing)` that takes an optional positional argument `time`. This ensures that both `compute!(field)` and `compute!(field, time)` are available.

Finally, fields that depend on other fields should call `compute_at!(dependency, time)` on all field dependencies.

I hope that makes sense. It sounds a bit convoluted so I'm not sure this is the simplest solution. Criticism welcome.

### CODE REVIEW

**Review by ali-ramadhan — APPROVED** [review]
Looks good to me!

I think we discussed this in the past but I'm guessing that you're using `compute_at!(field, time)` instead of `compute_at!(field, iteration)` because you might need to recompute in between RK stages which would require an extra argument `stage`?

**Comment by glwagner** [comment]
> I think we discussed this in the past but I'm guessing that you're using compute_at!(field, time) instead of compute_at!(field, iteration) because you might need to recompute in between RK stages which would require an extra argument stage?

Right --- the `time` is a unique key (for the time-steppers we currently use).

We could potentially future proof the design a bit more. Rather than explicitly using `model.clock.time`, we could pass `FieldStatus` to `compute_at!(field, status)`. Then if we would rather use a different "key" (such as `iteration` + time stepper `stage`) we only need to change `FieldStatus` and `conditional_compute!(field, status)`.

**Comment by glwagner** [comment]
@ali-ramadhan here's an idea: rather than `FieldStatus`, we can simply re-use `Clock`. Then we can be paranoid and check the `time`, `iteration`, and `stage` for the purposes of recomputation. There's a bit less code which is nice too.

**Comment by glwagner** [comment]
Let's punt on using `Clock` as a key for a future time when it might matter.

**Pull request merged**
