### PR TITLE
[WIP] Adds Rossby Haurwitz and Spherical Bickley jet examples

### PR DESCRIPTION
**Pull request by sandreza**
Currently a work in progress, but it has one validation experiment (Rossby-Haurwitz) and one "for fun" dynamics test (Bickley Jet)

### CODE REVIEW

**Comment by francispoulin** [comment]
This looks very interesting!  Can you post some animations that you generated?

**Comment by sandreza** [comment]
The RH test: 

https://user-images.githubusercontent.com/22668662/114433316-ab35f200-9b8f-11eb-877d-f4be82e1a559.mp4

**Comment by francispoulin** [comment]
Thanks @sandreza , that looks very interesting!

The Rossby Haurwitz is an exact solution in the context of the shallow water model.  I presume it should also be an exact solution (or very close to exact solution) in the hydrostatic model?  

From looking at the `\eta` field near the equator, there seems to be an unbalanced motion going on.  Any idea whether this is numerical error or something physical?

**Comment by sandreza** [comment]
I think it's a mix. The RH solution is not a solution to the equation set that I am using (except in the limit of strong gravity). Secondly (although not visible on the plot) the domain is truncated at 80 degrees, as opposed to being the full sphere

**Comment by glwagner** [comment]
It looks like we don't have clarity on whether the Rossby-Haurwitz case solves the barotropic vorticity equation on the sphere, or the shallow water equations on the sphere. What is a good reference for this case?

**Comment by sandreza** [comment]
> It looks like we don't have clarity on whether the Rossby-Haurwitz case solves the barotropic vorticity equation on the sphere, or the shallow water equations on the sphere. What is a good reference for this case?

The reference is "A Standard Test Set for Numerical Approximations to the
Shallow Water Equations in Spherical Geometry" https://www.sciencedirect.com/science/article/pii/S0021999105800166

**Comment by francispoulin** [comment]
Thanks for clarifying, and the reference. I take that to mean that it is an exact solution to the shallow water equations with a rigid lid.  That's why as gravity gets stronger, it becomes a better solution.  

The  examples that I've seen, like this [one](https://www.tandfonline.com/doi/pdf/10.3402/tellusa.v52i2.12258), usually focus on a band around the equator.  I wonder if starting with a smaller domain might be easier to make sure everything works fine?

**Comment by navidcy** [comment]
This is great @sandreza.

How come tests don't fail on this PR?!!
They've been failing on every other one... Is this far behind master?

**Comment by navidcy** [comment]
Also, did you really wanted to include `RafsPlots.jl` in the PR? :)

@sandreza, I'm adding [WIP] in the PR's title to denote "Work in Progress". Please remove it and ping us when you feel this PR is ready to be reviewed.

**Comment by sandreza** [comment]
> Also, did you really wanted to include `RafsPlots.jl` in the PR? :)
> 
> @sandreza, I'm adding [WIP] in the PR's title to denote "Work in Progress". Please remove it and ping us when you feel this PR is ready to be reviewed.

Thanks Navid! I think @ali-ramadhan is planning on making this branch legit and up-to-date with the latest changes

**Comment by ali-ramadhan** [comment]
Thanks @sandreza! 

This is the Rossby-Haurwitz test case with ω = 0 and g = 100 m/s². This is without momentum advection (`advection = nothing`). It's running for long enough to do a 45 degree rotation. Time step is 20 seconds which corresponds to a "gravity wave CFL" of <0.223. Solution seems to bounce around a bit but otherwise just rotates.

https://user-images.githubusercontent.com/20099589/114553938-2cdf5b80-9c34-11eb-82d0-8d1c2874b84c.mp4

Keeping everything else the same but switching on momentum advection (`advection = VectorInvariant()`) the solution stays still as it rotates (as it should I think), but a corner seems to blows up at t ≈ 1.639 days no matter how small I make the time step.

I'm running inviscid so maybe we need some diffusion? Might also help if we go to higher resolution as well?

https://user-images.githubusercontent.com/20099589/114556283-8cd70180-9c36-11eb-98d6-1aa82c09721e.mp4

**Comment by francispoulin** [comment]
I see that you have very strong gravity, `g = 100 m/s^2`,  to make things as barotropic as possible I presume.

Without advection there seems to be a lot of giggling around.  With advection there still seems to be something odd happening at the equator.  

If you were to take `IncompressibleModel` and run it with one vertical grid point, that is essentially a barotropic model.  If you initialize it with a planar Rossby Haurwitz wave, then it simply propagates westward.  This might be worth setting up just to see what happens in the planar case.  Just a thought.

**Comment by ali-ramadhan** [comment]
Yeah not sure what's happening at the equator. Maybe we need even more gravity?

The corner blow up is probably due to #1584 though, so we should be able to fix it soon and re-run with momentum advection.

@sandreza Is it okay if we turn the Rossby-Haurwitz and spherical Bickley jet into validation experiments or would you rather keep them as examples?

I think in the end, validation experiments will serve as "advanced examples" once we have some time to clean them up and put them in the docs.

**Comment by glwagner** [comment]
I believe this smells like validation rather than an example. Examples are nice if they are simple yet interesting. This is complicated, but kind of boring physically (but super useful for validation, obviously!)

**Pull request merged**
