### PR TITLE
Overhauls `show` and `summary`

### LINKED ISSUE #1612: More concise `show(field::Field)` that prints data (like `show(a::Array)`?)
Wondering if it makes sense to change how we `show` `Field`, or more generally `AbstractDataField`.

It's nice to see some values, especially for working and debugging at the REPL, without having to type `interior(field)` or `field.data`.

### LINKED ISSUE #2064: Using `Base.summary` instead of `short_show` and better show for grids and fields
Right now at the REPL we get

```julia
julia> using Oceananigans

julia> grid = RectilinearGrid(size=3, z=(0, 1), topology=(Flat, Flat, Bounded))
RectilinearGrid{Float64, Flat, Flat, Bounded} on the CPU()
                   domain: x ∈ [1.0, 1.0], y ∈ [1.0, 1.0], z ∈ [0.0, 1.0]
                 topology: (Flat, Flat, Bounded)
        size (Nx, Ny, Nz): (1, 1, 3)
        halo (Hx, Hy, Hz): (0, 0, 1)
grid in x: Flattened
grid in y: Flattened
grid in z: Regular, with spacing 0.3333333333333333
```

so `grid in x:` isn't aligned with the rest of the "data table".

Here's what we get when `z` is stretched:

```julia
julia> grid = RectilinearGrid(size=3, z=[0.0, 0.2, 0.5, 1.0], topology=(Flat, Flat, Bounded))
RectilinearGrid{Float64, Flat, Flat, Bounded} on the CPU()
                   domain: x ∈ [1.0, 1.0], y ∈ [1.0, 1.0], z ∈ [0.0, 1.0]
                 topology: (Flat, Flat, Bounded)
        size (Nx, Ny, Nz): (1, 1, 3)
        halo (Hx, Hy, Hz): (0, 0, 1)
grid in x: Flattened
grid in y: Flattened
grid in z: Stretched, with spacing min=0.2, max=0.5
```

So here's a few ideas:

#### Include "spacing" information under the `domain` row?

One idea would be to show something like

```julia
x: Flat
y: Flat
z: [0.0, 1.0], Δz: 0.33
```

instead of `domain:` (for the regularly-spaced case), and

```julia
x: Flat
y: Flat
z: [0.0, 1.0], extrema(Δz): (0.2, 0.5)
```

for the stretched case. We could also increase the length of the table and put the spacings on their own lines, eg

```julia
x: Flat
y: Flat
z: [0.0, 1.0]
extrema(Δz): (0.2, 0.5)
```

We might also just hide flattened directions (we already express that the directions are `Flat` so why print this again?)

#### Compactify how we show the size + halo. I've always found the way we write `(Nx, Ny, Nz)` to negatively impact readability. 

I think it's ok to just write `size`, because we want to move towards providing a function-based API rather than expecting users to access struct properties directly. Eg we could have just

```julia
size: (1, 1, 1)
halo: (0, 0, 1)
```

What do others think?

### PR DESCRIPTION
**Pull request by glwagner**
This PR translates `short_show` to `Base.summary`, overhauls `show` and `summary` for grids and fields, and implements `prettysummary` for functions that returns a string that's similar to what we get at the REPL:

```julia
julia> hello_world(x) = x
hello_world (generic function with 1 method)

julia> hello_world
hello_world (generic function with 1 method)
```

Closes #2064 
Closes #1612

### CODE REVIEW

**Comment by glwagner** [comment]
For regular spacing:

```julia
julia> grid = RectilinearGrid(size=(1, 1, 1), extent=(2, 2, 2))
1×1×1 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×1 halo
    x: [0.0, 2.0] regularly spaced with Δxᶜᵃᵃ = 2.0
    y: [0.0, 2.0] regularly spaced with Δyᵃᶜᵃ = 2.0
    z: [-2.0, 0.0] regularly spaced with Δzᵃᵃᶜ = 2.0
```

for variable spacing:

```julia
julia> σ = 1.1; # stretching factor

julia> Nz = 24; # vertical resolution

julia> Lz = 32; # depth (m)

julia> hyperbolically_spaced_faces(k) = - Lz * (1 - tanh(σ * (k - 1) / Nz) / tanh(σ));

julia> grid = RectilinearGrid(size = (32, 32, Nz), x = (0, 64),
                              y = (0, 64), z = hyperbolically_spaced_faces)
32×32×24 RectilinearGrid{Float64, Periodic, Periodic, Bounded} on CPU with 1×1×1 halo
    x: [0.0, 64.0] regularly spaced with Δxᶜᵃᵃ = 2.0
    y: [0.0, 64.0] regularly spaced with Δyᵃᶜᵃ = 2.0
    z: [-32.0, -0.0] variably spaced with min(Δzᵃᵃᶜ) = 0.682695, max(Δzᵃᵃᶜ) = 1.830909
```

**Comment by glwagner** [comment]
ok, so now we have

```julia

julia> grid
32×32×24 RectilinearGrid{Float64} on CPU with 1×1×1 halo
├── Periodic x ∈ [0.0, 64.0) regularly spaced with Δx = 2.0
├── Periodic y ∈ [0.0, 64.0) regularly spaced with Δy = 2.0
└── Bounded  z ∈ [-32.0, -0.0] variably spaced with min(Δz) = 0.682695, max(Δz) = 1.830909
```

and

```julia
julia> c
32×32×24 Field{Center, Center, Center} on RectilinearGrid on CPU
├── data: 34×34×26 OffsetArray(::Array{Float64, 3}, 0:33, 0:33, 0:25) with eltype Float64 with indices 0:33×0:33×0:25
│   └── max=0.999994, min=0.000024, mean=0.497759
├── grid: 32×32×24 RectilinearGrid{Float64} on CPU with 1×1×1 halo
└── boundary conditions: west=Periodic, east=Periodic, south=Periodic, north=Periodic, bottom=ZeroFlux, top=ZeroFlux, immersed=ZeroFlux
```

what do we think so far?

**Comment by francispoulin** [comment]
Looks great!  I like how you include the topology on each line, instead of on the first line. Makes it more readable. 

I think the `grid` looks great!

For the `Field`, could we have the `data` on the last line?  It might be cleaner but not sure.

**Comment by glwagner** [comment]
> For the `Field`, could we have the `data` on the last line? It might be cleaner but not sure.

I like that idea.

**Comment by glwagner** [comment]
Now its

```julia
julia> c
4×1×1 Field{Center, Center, Center} on RectilinearGrid on CPU
├── grid: 4×1×1 RectilinearGrid{Float64} on CPU with 1×0×0 halo
├── boundary conditions: west=Periodic, east=Periodic, south=Nothing, north=Nothing, bottom=Nothing, top=Nothing, immersed=ZeroFlux
└── data: 6×1×1 OffsetArray(::Array{Float64, 3}, 0:5, 1:1, 1:1) with eltype Float64 with indices 0:5×1:1×1:1
    └── max=0.971321, min=0.0683512, mean=0.53887
```

**Comment by glwagner** [comment]
@simone-silvestri asked for a little more alignment, so we have

```julia
julia> grid = RectilinearGrid(size = (32, 32, Nz), x = (0, 64),
                              y = (0, 64), z = hyperbolically_spaced_faces)
32×32×24 RectilinearGrid{Float64} on CPU with 1×1×1 halo
├── Periodic x ∈ [0.0, 64.0)   regularly spaced with Δx = 2.0
├── Periodic y ∈ [0.0, 64.0)   regularly spaced with Δy = 2.0
└── Bounded  z ∈ [-32.0, -0.0] variably spaced with min(Δz) = 0.682695, max(Δz) = 1.83091
```

**Comment by francispoulin** [comment]
Looks great!

**Review by simone-silvestri — APPROVED** [review]

**Pull request merged**
