### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by navidcy**
This is an attempt to resolves test failing after 39ee546.

### CODE REVIEW

**Comment by glwagner** [comment]
I don't think we can update packages right now, see #1561 .

Which test is failing? Do we need to revert the PR? I thought only the documentation was failing but maybe I screwed up.

**Comment by navidcy** [comment]
Many are failing...
https://buildkite.com/clima/oceananigans/builds/1965

**Comment by glwagner** [comment]
That shows canceled builds but I don't see the ones that are failing?

**Comment by glwagner** [comment]
Oh ok, this error on CPU initialization?

```
ERROR: LoadError: Failed to precompile GPUArrays [0c68f7d7-f131-5f86-a1c3-88cf8149b2d7] to /storage7/buildkite-agent/.julia-1965/compiled/v1.5/GPUArrays/v5u0T_Ru6eV.ji.
--
  | Stacktrace:
  | [1] top-level scope at none:2
  | [2] eval at ./boot.jl:347 [inlined]
  | in expression starting at /storage7/buildkite-agent/.julia-1965/packages/CUDA/wTQsK/src/CUDA.jl:5
  | WARNING: Error during initialization of module LinearAlgebra:
  | ErrorException("could not load library "libopenblas64_"
  | libopenblas64_.so: ELF load command past end of file")
  | ┌ Error: Error during initialization of module CHOLMOD
  | │   exception =
  | │    could not load library "libcholmod"
  | │    libopenblas64_.so.0: ELF load command past end of file
  | │    Stacktrace:
  | │     [1] dlopen(::String, ::UInt32; throw_error::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109
  | │     [2] dlopen at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Libdl/src/Libdl.jl:109 [inlined] (repeats 2 times)
  | │     [3] __init__() at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:90
  | └ @ SuiteSparse.CHOLMOD /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/SuiteSparse/src/cholmod.jl:187
  | /storage7/buildkite-agent/julia-1.5.4/bin/julia: error while loading shared libraries: libLLVM-9jl.so: ELF load command past end of file
```

I believe these happen occasionally when using `instantiate` and the solution is typically to restart the build?

**Comment by glwagner** [comment]
I am a little perplexed, because it seemed that tests on the PR passed (except for documentation, which is mysteriously broken right now due to a dependency that's getting updated during `dev ..` in the docs build)

image

image

**Comment by navidcy** [comment]
hm... it is weird. Perhaps restarting the build will do the job. I can't restart it though :)

**Comment by glwagner** [comment]
Hmm ok the one you've linked to is a later build than the one displayed on the PR (the PR displayed 1923, but you linked to 1965). I'm not 100% sure what's up.

Unfortunately we cannot restart it now because the documentation build will _never_ finish. We need to solve this docs issue in order to get our CI pipeline functioning correctly again.

**Pull request closed without merging**
