### PR TITLE
Stop 'recomputing w' at the end of each time step

### LINKED ISSUE #338: Explicitly time-step w instead of recomputing it from continuity?
Found out int PR #336 that we can explicitly time-step w which will be nice as it'll work for simulations without a rigid lid.

All tests passed when I made the change so should be a quick change.

### PR DESCRIPTION
**Pull request by glwagner**
This PR removes part of the time-stepping algorithm that uses the continuity equation to 'recompute' the vertical velocity at the end of a time-step, after using a fractional step to project the predictor velocity field onto an incompressible field.
This recomputation of vertical velocity relies on a discrete vertical integral of the continuity equation starting at the bottom of the domain and proceeding upwards.

The reason for omitting "w recomputation" is primarily because vertically integrating the continuity equation _accumulates_ pressure projection round-off error into the vertical velocity field, biased towards the top of the domain. Most models are probably unaffected by this error accumulation and upward bias. However, accumulation of round-off error in a particular part of the domain may become a problem for models with high vertical resolution. The recomputation step also has a computational cost, and the top of the domain is crucial in many oceanographic contexts.

The incompressibility of the flow field is still assured without this recomputation step, and it is probable that the velocity field errors are more isotropic and therefore probably more benign. We should note that the error in the _divergence_ is larger without recomputation. However, it probably still falls below acceptable limits, and it does not accumulate in time.

With this change the regression tests fail. Also, an "incompressibility test" that relies on a measurement of the absolute magnitude of the divergence error fails. We probably simply need to relax the error requirement for the incompressibility test. The regression tests, on the other hand, will have to be regenerated.

cc @sandreza @kburns

Resolves #338

### CODE REVIEW

**Comment by sandreza** [comment]
I agree that this step is not necessary for a non-hydrostatic code with a rigid lid. Since the projected velocity field is already numerically incompressible, there is no need to modify it further. The operator splitting in the pressure projection step will eventually need to be modified with a higher-order correction to the pressure boundary conditions to ensure that the velocity boundary conditions at the walls are better, but this is a separate issue.

**Comment by glwagner** [comment]
> I agree that this step is not necessary for a non-hydrostatic code with a rigid lid. Since the projected velocity field is already numerically incompressible, there is no need to modify it further. The operator splitting in the pressure projection step will eventually need to be modified with a higher-order correction to the pressure boundary conditions to ensure that the velocity boundary conditions at the walls are better, but this is a separate issue.

I'd like to emphasize that the primary motivation for making this change is not that it is "not necessary", but is that it accumulates error in a particular part of the domain, which could lead to a loss of accuracy. @sandreza please let me know if you agree or disagree.

As for correcting the pressure step, this work is planned as we have discussed extensively. Note that the algorithm is correct for free-slip conditions, under which the pressure field normal to the boundaries is zero.

**Comment by glwagner** [comment]
> Although I'm somewhat worried whether the errors in this PR are acceptable.

A test that should be implemented is that mass does not accumulate in time. In other words, the round-off error incurred by the pressure projection is constant, as expected.

> Do we still expect the velocity field to be divergence-free up to machine precision?

In some ways, the calculated divergence is an empirical measurement of the round-off error that accumulates during the discrete pressure solve. I am not 100% sure how to theoretically determine the expected round off error associated with the pressure solve. I suppose that we expect that eigenfunction pressure solution to be accurate to within machine precision. However, we subsequently perform a 3D inverse FFT, followed next by a subtraction to calculate the velocity update, and then a second subtraction to calculate the divergence.

> The sum still accumulates in time but went from e-22 -> e-20 to e-18 -> e-12

Any significant change in accuracy may be an indication that this PR is important. If the divergence changes significantly after recomputing w, this indicates that a substantial amount of round off error is being accumulated in the velocity field. 

We may be able to calculate the expected round off error per grid point.

**Comment by glwagner** [comment]
> Maybe makes sense to merge other PRs and tagging a release then merging this PR? We could also just not release for a little while.

I'm fine with that plan, all the PRs seem to need a bit of work.

**Comment by glwagner** [comment]
I think we are finally ready to move forward with this PR. The "incompressible in time" test will have to be updated, and the regression tests will break. @ali-ramadhan what is the best strategy? Should we merge along with a fix for the "incompressible in time" test, but leave the regression test update for a subsequent PR?

**Comment by ali-ramadhan** [comment]
Is it just me or did we forget to actually time step w in this PR?

If we `git rebase master` and add
```julia
@inbounds U.w[i, j, k] -= ∂zᵃᵃᶠ(i, j, k, grid, pNHS) * Δt
```
in `_fractional_step_velocities!` then maybe the velocity divergence won't be so huge anymore?

**Comment by glwagner** [comment]
Hmm... yes that's quite an omission.

**Comment by ali-ramadhan** [comment]
Not sure if we should be scared that 1705/1731 tests passed without even time stepping w lol.

But the right tests failed I guess.

**Comment by ali-ramadhan** [comment]
Looks like explicitly time-stepping w incurs a much larger velocity divergence but the absolute mean divergence is constant in time which is great. We would just need to increase the test tolerance to pass.

---

Recomputing w from continuity (from above comment):
```
Velocity divergence after 1 time steps [CPU, Float64]: min=-5.921641215572704e-19, max=5.569139984243355e-19, sum=-1.4028983188648256e-22, abs_sum=1.2702557704405045e-16
Velocity divergence after 10 time steps [CPU, Float64]: min=-6.210310043996969e-19, max=6.366977257921125e-19, sum=6.216798316373769e-21, abs_sum=1.5993935090379334e-16
Velocity divergence after 100 time steps [CPU, Float64]: min=-6.505213034913027e-19, max=6.279698983036041e-19, sum=-4.305637877483207e-20, abs_sum=2.6314325338953166e-16
```

This PR from https://travis-ci.com/github/CliMA/Oceananigans.jl/jobs/380971555#L503
```
Velocity divergence after 1 time steps [CPU, Float64]: min=-3.9807493470274435e-8, max=3.843304892886209e-8, sum=-4.317326932155169e-18, abs_sum=3.595941351071455e-5
Velocity divergence after 10 time steps [CPU, Float64]: min=-3.9807473454679864e-8, max=3.843306820505406e-8, sum=-1.57595300437948e-11, abs_sum=3.595941708679444e-5
Velocity divergence after 100 time steps [CPU, Float64]: min=-3.9805324116426805e-8, max=3.843513817734616e-8, sum=-1.7140522321234778e-9, abs_sum=3.5959801582907905e-5
```

**Comment by ali-ramadhan** [comment]
Thermal bubble and Rayleigh-Benard regression tests fully pass which is also great and in agreement with https://github.com/CliMA/Oceananigans.jl/pull/336#issuecomment-518876660

Looks like only the LES regression tests need to be updated or we can increase the test tolerance (currently we are using the default `rtol=√eps`. Most of the grid point values do match so maybe LES regression fails because it uses more time steps or maybe LES causes the velocities to change more?

---

```
  Testing thermal bubble regression [CPU]
Simulation is stopping. Model iteration 10 has hit or exceeded simulation stop iteration 10.
Δu: min=-3.681815e-16, max=+3.647121e-16, mean=+7.837536e-22, absmean=+2.158336e-18, std=+1.273009e-17 (4096/4096 matching grid points)
Δv: min=-3.670973e-16, max=+3.657658e-16, mean=-5.173756e-23, absmean=+2.067713e-18, std=+1.271035e-17 (4096/4096 matching grid points)
Δw: min=-1.281527e-16, max=+1.871333e-15, mean=-1.965276e-20, absmean=+5.739621e-18, std=+3.103542e-17 (4352/4352 matching grid points)
ΔT: min=-1.776357e-15, max=+1.776357e-15, mean=+6.071532e-18, absmean=+2.775558e-17, std=+2.219887e-16 (4096/4096 matching grid points)
ΔS: min=+0.000000e+00, max=+0.000000e+00, mean=+0.000000e+00, absmean=+0.000000e+00, std=+0.000000e+00 (4096/4096 matching grid points)

  Testing Rayleigh–Bénard tracer regression [CPU]
Δu: min=-1.930400e-14, max=+1.984524e-14, mean=+3.909719e-18, absmean=+1.930621e-15, std=+2.841226e-15 (4096/4096 matching grid points)
Δv: min=-2.386980e-14, max=+2.642331e-14, mean=-6.492243e-19, absmean=+1.871573e-15, std=+2.799057e-15 (4096/4096 matching grid points)
Δw: min=-2.242651e-14, max=+2.160425e-14, mean=+3.640442e-18, absmean=+1.618786e-15, std=+2.583244e-15 (4096/4096 matching grid points)
Δb: min=-1.665335e-14, max=+2.053913e-14, mean=+9.239435e-18, absmean=+1.249038e-15, std=+1.938872e-15 (4096/4096 matching grid points)
Δc: min=-6.022960e-15, max=+7.648396e-15, mean=-4.893137e-19, absmean=+5.861175e-16, std=+9.281398e-16 (4096/4096 matching grid points)

  Testing oceanic large eddy simulation regression [VerstappenAnisotropicMinimumDissipation, CPU]
Δu: min=-2.772501e-07, max=+1.865995e-07, mean=-1.633351e-20, absmean=+6.868489e-10, std=+6.155992e-09 (2959/4096 matching grid points)
Δv: min=-1.600098e-07, max=+1.647848e-07, mean=+1.619951e-20, absmean=+6.257578e-10, std=+5.220796e-09 (3396/4096 matching grid points)
Δw: min=-9.857415e-08, max=+1.515074e-07, mean=+7.983410e-20, absmean=+4.958399e-10, std=+3.887294e-09 (2458/4096 matching grid points)
ΔT: min=-3.295630e-07, max=+5.110846e-07, mean=-2.005688e-10, absmean=+2.047434e-09, std=+1.735861e-08 (4092/4096 matching grid points)
ΔS: min=-3.296776e-10, max=+5.103402e-10, mean=-8.673617e-17, absmean=+2.002898e-12, std=+1.753659e-11 (4096/4096 matching grid points)

  Testing oceanic large eddy simulation regression [SmagorinskyLilly, CPU]
Δu: min=-2.139048e-08, max=+1.303954e-08, mean=-1.313232e-20, absmean=+5.768485e-11, std=+5.320877e-10 (3793/4096 matching grid points)
Δv: min=-2.835820e-08, max=+2.339656e-08, mean=+1.094790e-19, absmean=+7.089837e-11, std=+7.190216e-10 (3927/4096 matching grid points)
Δw: min=-1.251260e-08, max=+2.051015e-08, mean=-5.553442e-20, absmean=+5.353006e-11, std=+5.098444e-10 (3508/4096 matching grid points)
ΔT: min=-8.801552e-08, max=+1.836259e-08, mean=-3.245009e-11, absmean=+6.785232e-11, std=+1.609149e-09 (4096/4096 matching grid points)
ΔS: min=-1.598721e-11, max=+1.057288e-11, mean=-3.816392e-17, absmean=+3.764697e-14, std=+4.486543e-13 (4096/4096 matching grid points)
```

**Comment by ali-ramadhan** [comment]
Also, this PR should nuke the `compute_w_from_continuity!` function + kernel, and nuke the associated `compute_w_from_continuity` test.

**Comment by glwagner** [comment]
I can't think of a reason why the LES tests would be more affected. Is the resolution higher?

It makes sense that some tests pass, because `compute_w_from_continuity!` is just rearranging round off errors, in principle.

So is the checklist:

- [ ] increase tolerance on LES regression tests
- [ ] nuke `compute_w_from_continuity!` function and test

?

**Comment by glwagner** [comment]
Actually, I think that we should remake the LES regression test data rather than increase the tolerance.

**Comment by ali-ramadhan** [comment]
I think we're good to merge now. Some of the LES regression tests will fail but we should re-create the regression files in a subsequent PR.

I think we should tag a new release once regression tests are updated since this PR changes changes the numerical methods used. @glwagner Do you think you could do the release notes since most of the recent PRs have been yours?

**Comment by glwagner** [comment]
I can do that! I will also regenerate regression test data.

**Review by ali-ramadhan — APPROVED** [review]

**Comment by glwagner** [comment]
@ali-ramadhan I think this is ready to merge --- but might be best if a second set of eyes evaluates the tests. Looks like only the ocean LES regression tests fail now.

**Pull request merged**
