### PR TITLE
Avoid type instability in HydrostaticSphericalCoriolis

### LINKED ISSUE #2925: Type instability in `hydrostatic_spherical_coriolis.jl`?
Should this

https://github.com/CliMA/Oceananigans.jl/blob/e2841ca6dda4414fcd9177512faec557d6f12adc/src/Coriolis/hydrostatic_spherical_coriolis.jl#L60

be 

```Julia
1 - f(i, j, k, grid, args...)
```
to avoid type instability?

cc @glwagner, @simone-silvestri

### PR DESCRIPTION
**Pull request by navidcy**
Closes #2925

### CODE REVIEW

**Review by glwagner — APPROVED** [review]
What does this function do?

**Comment by simone-silvestri** [comment]
yeah you can change it to `1.0 -  f(i, j, k, grid, args...)` to `FT(!f(i, j, k, grid, args...))` I guess. 
I am not sure using `!peripheral_node` will work because it is a statement, not a function, and we need a function to compose in 
```
ℑxyᶠᶜᵃ(i, j, k, grid, revert_peripheral_node, peripheral_node, Center(), Face(), Center())
```

**Comment by glwagner** [comment]
> yeah you can change it to `1.0 - f(i, j, k, grid, args...)` to `FT(!f(i, j, k, grid, args...))` I guess. I am not sure using `!peripheral_node` will work because it is a statement, not a function, and we need a function to compose in
> 
> https://github.com/CliMA/Oceananigans.jl/blob/e2841ca6dda4414fcd9177512faec557d6f12adc/src/Coriolis/hydrostatic_spherical_coriolis.jl#L69

I think @navidcy is suggesting to define a function

```julia
not_peripheral_node(args...) = !peripheral_node(args...)
```

which could then be used and doesn't need a docstring.

**Comment by navidcy** [comment]
Yeah. Wouldn't that work?

**Comment by simone-silvestri** [comment]
ok sure that would work!

**Comment by navidcy** [comment]
You mean in the regression test or in general?

**Pull request merged**
