### PR TITLE
Teach wizard about minimum time step

### LINKED ISSUE #1197: Minimum time step for `TimeStepWizard`
Would be nice to be able to specify a minimum time step for the `TimeStepWizard`. For me the main use is to avoid "slow motion blowup" where a numerical instability causes the model to blow up but the time step wizard keeps decreasing the time step so it just blows up in slow motion when you want it to NaN and stop executing.

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Resolves #1197

### CODE REVIEW

**Comment by navidcy** [comment]
How about a test?

**Review by navidcy — CHANGES_REQUESTED** [review]
a test perhaps?

**Comment by ali-ramadhan** [comment]
Ah true, we didn't really have unit tests for the `TimeStepWizard` so just added some.

**Review by glwagner — APPROVED** [review]

**Review by navidcy — APPROVED** [review]
🚀

**Pull request merged**
