### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Review by tomchor — APPROVED** [review]

**Review by francispoulin — APPROVED** [review]

**Comment by navidcy** [comment]
Any idea why docs fails? https://buildkite.com/clima/oceananigans/builds/8381#0182beb4-dc53-4ca9-9d6c-76d43f05f6b6

```
/bin/bash: line 2: 815367 Segmentation fault      (core dumped) /storage5/buildkite-agent/julia-1.6.7/bin/julia --color=yes --project=docs/ docs/make.jl
--
  | 🚨 Error: The command exited with status 139
  | user command error: exit status 139
```

**Comment by tomchor** [comment]
> Any idea why docs fails? https://buildkite.com/clima/oceananigans/builds/8381#0182beb4-dc53-4ca9-9d6c-76d43f05f6b6
> 
> ```
> /bin/bash: line 2: 815367 Segmentation fault      (core dumped) /storage5/buildkite-agent/julia-1.6.7/bin/julia --color=yes --project=docs/ docs/make.jl
> --
>   | 🚨 Error: The command exited with status 139
>   | user command error: exit status 139
> ```

No idea. Can you reproduce the error locally?

**Comment by navidcy** [comment]
Locally seems ok.

**Comment by tomchor** [comment]
Nice! Tests are passing :)

**Pull request merged**
