### PR TITLE
Clearer error in operation average constructor

### LINKED ISSUE #857: Error when trying to diagnose `Average` of an abstract operation
```julia
using Oceananigans, Oceananigans.Diagnostics, Oceananigans.AbstractOperations
grid = RegularCartesianGrid(size=(16, 16, 16), extent=(1, 1, 1))
model = IncompressibleModel(architecture=CPU(), grid=grid)  # Same with GPU()
u, v, w = model.velocities
∫uv = Average(u*v, dims=(1, 2), return_type=Array)
```

```
ERROR: MethodError: no method matching architecture(::Oceananigans.AbstractOperations.MultiaryOperation{Oceananigans.Grids.Face,Oceananigans.Grids.Cell,Oceananigans.Grids.Cell,2,typeof(*),Tuple{OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}},Tuple{typeof(identity),typeof(Oceananigans.Operators.ℑxyᶠᶜᵃ)},RegularCartesianGrid{Float64,Periodic,Periodic,Bounded,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}})
Closest candidates are:
  architecture(::Array) at /home/alir/Oceananigans.jl/src/Architectures.jl:46
  architecture(::CUDA.CuArray) at /home/alir/Oceananigans.jl/src/Architectures.jl:47
  architecture(::Field) at /home/alir/Oceananigans.jl/src/Fields/field.jl:167
  ...
Stacktrace:
 [1] Average(::Oceananigans.AbstractOperations.MultiaryOperation{Oceananigans.Grids.Face,Oceananigans.Grids.Cell,Oceananigans.Grids.Cell,2,typeof(*),Tuple{OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}},Tuple{typeof(identity),typeof(Oceananigans.Operators.ℑxyᶠᶜᵃ)},RegularCartesianGrid{Float64,Periodic,Periodic,Bounded,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}}; dims::Tuple{Int64,Int64}, iteration_interval::Nothing, time_interval::Nothing, return_type::Type{T} where T) at /home/alir/Oceananigans.jl/src/Diagnostics/average.jl:52
 [2] top-level scope at REPL[17]:1

```

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Resolves #857 

Minimal working example:
```julia
using Oceananigans, Oceananigans.Diagnostics, Oceananigans.AbstractOperations
grid = RegularCartesianGrid(size=(16, 16, 16), extent=(1, 1, 1))
model = IncompressibleModel(architecture=CPU(), grid=grid)  # Same with GPU()
u, v, w = model.velocities
∫uv = Average(u*v, dims=(1, 2), return_type=Array)
```

Old error (obscure and not useful to users):
```
ERROR: MethodError: no method matching architecture(::Oceananigans.AbstractOperations.MultiaryOperation{Oceananigans.Grids.Face,Oceananigans.Grids.Cell,Oceananigans.Grids.Cell,2,typeof(*),Tuple{OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}},Tuple{typeof(identity),typeof(Oceananigans.Operators.ℑxyᶠᶜᵃ)},RegularCartesianGrid{Float64,Periodic,Periodic,Bounded,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}})
Closest candidates are:
  architecture(::Array) at /home/alir/Oceananigans.jl/src/Architectures.jl:46
  architecture(::CUDA.CuArray) at /home/alir/Oceananigans.jl/src/Architectures.jl:47
  architecture(::Field) at /home/alir/Oceananigans.jl/src/Fields/field.jl:167
  ...
Stacktrace:
 [1] Average(::Oceananigans.AbstractOperations.MultiaryOperation{Oceananigans.Grids.Face,Oceananigans.Grids.Cell,Oceananigans.Grids.Cell,2,typeof(*),Tuple{OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}},Tuple{typeof(identity),typeof(Oceananigans.Operators.ℑxyᶠᶜᵃ)},RegularCartesianGrid{Float64,Periodic,Periodic,Bounded,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}}; dims::Tuple{Int64,Int64}, iteration_interval::Nothing, time_interval::Nothing, return_type::Type{T} where T) at /home/alir/Oceananigans.jl/src/Diagnostics/average.jl:52
 [2] top-level scope at REPL[17]:1
```

New error (more useful):
```
ERROR: MethodError: no method matching Average(::Oceananigans.AbstractOperations.MultiaryOperation{Oceananigans.Grids.Face,Oceananigans.Grids.Cell,Oceananigans.Grids.Cell,2,typeof(*),Tuple{OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}},OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}},Tuple{typeof(identity),typeof(Oceananigans.Operators.ℑxyᶠᶜᵃ)},RegularCartesianGrid{Float64,Periodic,Periodic,Bounded,OffsetArrays.OffsetArray{Float64,1,StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}}}}; dims=(1, 2), return_type=Array)
Closest candidates are:
  Average(::Oceananigans.AbstractOperations.AbstractOperation, ::Oceananigans.Models.AbstractModel; dims, kwargs...) at /home/alir/Oceananigans.jl/src/AbstractOperations/computations.jl:98
  Average(::Oceananigans.AbstractOperations.AbstractOperation, ::Any; dims, kwargs...) at /home/alir/Oceananigans.jl/src/AbstractOperations/computations.jl:86
  Average(::F, ::D, ::P, ::I, ::T, ::Float64, ::R) where {F, R, D, P, I, T} at /home/alir/Oceananigans.jl/src/Diagnostics/average.jl:13 got unsupported keyword arguments "dims", "return_type"
  ...
Stacktrace:
 [1] top-level scope at REPL[10]:1
```

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Ah no this won't work (tests are failing) because `AbstractOperations.Average` needs to call `Diagnostics.Average`...

**Comment by glwagner** [comment]
There should not be any `AbstractOperations.Average`. If there is, there is a bug. The constructors in the `AbstractOperations` module should simply provide new methods for `Diagnostics.Average`.

The problem can be fixed by dispatching the main constructor for `Average` on `Union{Field, Computation}`.

I am ok with this restriction of `Average`. However, it's worth noting that it's changes its capability. Previously, `Average` would work with anything that defines `parent` and `architecture`, including arbitrary user-defined types (this is why it works with `Computation`s, for example). With this change, it will only work with types that are specifically allowed by the constructor.

Partly I think the underlying motivation for this PR could suggest we need to put a bit more effort into streamlining the user interface to `AbstractOperations` and `Computation`s. For example, it could make sense to define a constructor for `Average` that works with `AbstractOperation` without specifying the `result` (where new memory is allocated for `result`, for example). The purpose of requiring `result` is to require users to explicitly allocate the memory they need --- but the interface may not be intuitive.

We may also need to spend some more time refining the `Field` abstraction, and formalizing the connection between `Field`s and other similar objects like `Computation`s and `Average`s.

**Comment by glwagner** [comment]
Here's a couple more thoughts:

* `Average` requires some kind of view or pointer to the data that needs to be average. Currently this object is called `Average.field`. The basic idea behind `Average` is that a reduction is triggered on `Average.field` every so often (currently specified though `time_interval` and `iteration_interval` and stored in `result`.

* A very important usage of `Average`, however is defining it on "lazily evaluated data". This is the case of taking an average of a "`Computation`". To take the average of a `Computation`, we have to trigger the evaluation of the data first. Then we can take its `Average`.

* One way to normalize these user-interfaces is to generalize the concept of an `AbstractField` to be "lazy" in general. There is one special case that does *not* require computation --- the ordinary case of a `Field`. But we can create an infrastructure where all `AbstractField`s are expected to have a function like `compute!` (or perhaps `evaluate!`).

* Note that currently `Computation` data is stored in bare `Array`s. However, it should probably be stored as `Field`, and interacting with a `Computation` should feel the same as interacting with a field (with functions like `data`, `interior`, `getindex`, etc). We may also want to change the name of `Computation` to something that reflects its behavior a little more clearly. Perhaps `ComputedField`, or something.

* `Average` itself should *also* subtype `AbstractField` within this framework. An `Average` is just a special type of computation that requires evaluation, and also reduces a field along a certain dimension. For this to work well, we need a `ReducedField` type (eg #525)

**Comment by ali-ramadhan** [comment]
I'd be on board with assuming `AbstractField` elements must be lazily evaluated with `::Field` being a special no-op case. And with renaming `Computation` to `ComputedField`.

> There should not be any `AbstractOperations.Average`. If there is, there is a bug. The constructors in the `AbstractOperations` module should simply provide new methods for `Diagnostics.Average`.

Right I was referring to the `Average` methods defined in `AbstractOperations`.

> For example, it could make sense to define a constructor for `Average` that works with `AbstractOperation` without specifying the `result` (where new memory is allocated for `result`, for example). The purpose of requiring `result` is to require users to explicitly allocate the memory they need --- but the interface may not be intuitive.

Yeah I considered this as it seems like the most sensible solution but then instead of a useful error, users could end up allocating huge 3D arrays and run out of GPU memory (at which point it might be hard for them to figure out what they did wrong).

> `Average` requires some kind of view or pointer to the data that needs to be average. Currently this object is called `Average.field`. The basic idea behind `Average` is that a reduction is triggered on `Average.field` every so often (currently specified though `time_interval` and `iteration_interval`) and stored in `result`.

Hmmm, does it make sense to rename the `Average.field` property to `Average.kernel` in line with `WindowedTimeAverage` in PR #856?

**Comment by ali-ramadhan** [comment]
For the purposes of resolving #857 what do you think of just throwing a kind of `NotImplementedError`?

```julia
Average(::AbstractOperation; dims, kwargs...) =
    error("Creation of a result array is not implemented yet. You must pass a result array or a model.")
```

This would be a temporary fix that should be revisited when we have a more robust fields and `ComputedField` abstraction.

**Comment by glwagner** [comment]
I think the best quick hack fix would be to just copy-paste the constructor for `Average(::Field, ...)` into `computation.jl`, defined for `Average(::Computation, ...)`. Then our bases are covered and the cost is boiler-plate, which we'll resolve eventually by making `Computation` subtype `AbstractField`... ?

**Comment by ali-ramadhan** [comment]
@glwagner Couldn't find another way so I implemented your suggestion of just copy pasting `Average(::Field, ...)` for `Average(::Computation, ...)`. Not pretty but hopefully we'll come back to fix it soon.

**Pull request merged**
