### PR TITLE
Homogenizes T, S notation in Docs/Buoyancy Models

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Review by francispoulin — APPROVED** [review]
All good stuff

**Comment by glwagner** [comment]
The \theta rebellion has been crushed.

**Comment by navidcy** [comment]
I like θ, but everyone keeps using T and S...
(Sometimes even the rebellions.)

**Comment by glwagner** [comment]
I think the hope is that we would change the code to use \theta... but never got around to it. I feel more ambivalent about the difference now though.

**Review by glwagner — APPROVED** [review]

**Pull request merged**
