### PR TITLE
Validation tests of numerical convergence

### PR DESCRIPTION
**Pull request by glwagner**
This PR adds verification tests for numerical convergence of time-stepping and spatial discretization.

One test does not pass (the most complicated one): forced, fixed slip simulation. More detailed analysis of this test is needed.

Below is a summary of the results.

# Time stepping convergence tests

image

# Advection and diffusion of a one-dimensional cosine

cosine_advection_diffusion_solutions

cosine_advection_diffusion_error_convergence

# Advection and diffusion of a one-dimensional Gaussian

image

image

# Two-dimensional diffusion

image

# Two-dimensional Taylor-Green vortex

taylor_green_convergence

# Two-dimensional forced flow with free-slip boundary conditions

forced_free_slip_convergence

# Two-dimensional forced flow with fixed-slip boundary conditions

_This test does not pass_

We don't know if there is a bug in the test or a problem in Oceananigans.

forced_fixed_slip_convergence

### CODE REVIEW

**Comment by glwagner** [comment]
I have run the forced fixed slip test with multiple time-steps. The error does not decrease as the time-step decreases:

image

**Comment by glwagner** [comment]
At last, I found an algebra mistake in my definition of the problem. The forced fixed slip now passes!

image

@ali-ramadhan I think we should run these in CI eventually. Should we do that in this PR or save for a future PR?

**Comment by christophernhill** [comment]
Greg - thats great news. grad(p).n triumphs (again!).

**Comment by ali-ramadhan** [comment]
That's awesome! No one can make fun of us for not having convergence tests anymore!

@glwagner I might save it for a future PR just to get these scripts merged ASAP but we should do include them as tests before any numerical changes happen.

Would also be good to document all these tests in the "Verification experiments" section of the docs.

**Comment by sandreza** [comment]
@glwagner That's really awesome Greg!

**Comment by glwagner** [comment]
Ok, I will merge this PR and open an issue to write up these tests in the docs, and also to execute the run scripts in tests to ensure they remain runnable as the code is changed.

We could also add one or more of the tests as a regression test. We can discuss in the issue.

**Pull request merged**
