### PR TITLE
AllSchedule for combining scheduling criteria and avoiding checkpointing with NaNs

### PR DESCRIPTION
**Pull request by glwagner**
This PR adds a new schedule called `AllSchedule` that allows scheduling based on multiple criterion.

It also adds a `hasnan(model::AbstractModel)` that checks for a NaN in a model's first field.

Together this allows schedules that avoid actuating if NaNs are detected via

```julia
schedule = AllSchedule(TimeInterval(100), !hasnan)
```

for example. Note that `all` is short-circuiting, so order matters. Putting `!hasnan` second means that `hasnan` will not be called unless `TimeInterval(100)(model)` returns `true` first (this matters for avoiding `hasnan` calls on every time-step).

TODO:

- [x] better name than `MultiSchedule` perhaps `AllSchedules`?
- [x] Also have `AnySchedule` that actuates if _any_ schedules actuate?
- [x] Tests

This feature was discussed on #2086 .

### CODE REVIEW

**Comment by navidcy** [comment]
`AnySchedule` -> `SensitiveSchedule`?

**Comment by navidcy** [comment]
Could you resolve the conflicts @glwagner?

**Comment by glwagner** [comment]
> `AnySchedule` -> `SensitiveSchedule`?

`EitherSchedule`? (but "either" implies there are just two whereas here there can be many).

**Comment by navidcy** [comment]
> > `AnySchedule` -> `SensitiveSchedule`?
> 
> `EitherSchedule`? (but "either" implies there are just two whereas here there can be many).

`AnySchedule` is good! It just took me a while to get used to :)

**Comment by navidcy** [comment]
> > > `AnySchedule` -> `SensitiveSchedule`?
> > 
> > 
> > `EitherSchedule`? (but "either" implies there are just two whereas here there can be many).
> 
> `AnySchedule` is good! It just took me a while to get used to :)

Also I just noticed that these are documented and that's great!

**Comment by glwagner** [comment]
We could also use `AndSchedule` (rather than `AllSchedule`) and `OrSchedule` (rather than `AnySchedule`). "and" / "or" refer to the underlying conditionals that are used in the reductions `all` / `any`. Is this easier to understand (I think it might be).

**Review by tomchor — APPROVED** [review]
Great addition

**Comment by tomchor** [comment]
> We could also use `AndSchedule` (rather than `AllSchedule`) and `OrSchedule` (rather than `AnySchedule`). "and" / "or" refer to the underlying conditionals that are used in the reductions `all` / `any`. Is this easier to understand (I'm not sure)?

I think the `AndSchedule` and `OrSchedule` notation is clearer (or at least more explicit), so I'm leaning toward that one. But I don't feel strongly anyway so feel free to merge this whenever you're happy!

**Comment by glwagner** [comment]
I like "and" / "or" better as well, after having slept on it.

**Pull request merged**
