### PR TITLE
Quarter degree near global simulation

### PR DESCRIPTION
**Pull request by simone-silvestri**
Simulation that produces the video below
https://user-images.githubusercontent.com/33547697/156404654-e5b37a58-d6d8-4ecb-b1df-a69eef4589ee.mp4

(actually this simulation uses monthly average climatology from 1993-2003 while this PR uses only the year 1992 to reduce the memory footprint on OceananigansArtifacts.jl)

Future improvements:
- second order equation of state
- improve vertical mixing (CATKE)
- switch to hybrid fluxes and relaxation for scalars
- possibly quadratic bottom drag?

### CODE REVIEW

**Comment by francispoulin** [comment]
That looks amazing! 

Out of curiosity, how long did it take to run this? (I presume a GPU)?

**Comment by simone-silvestri** [comment]
It takes about 6.8 hours per 1 year of simulation on a Titan V

**Comment by glwagner** [comment]
heck to the yea

**Review by glwagner — APPROVED** [review]
Did we mean to use hyphens (not underscores) in the filename? Looks like it works so it's fine with me! Might be good to adopt a convention generally though.

**Comment by navidcy** [comment]
@simone-silvestri, merge?

**Comment by simone-silvestri** [comment]
I actually haven't run this code yet (there are small changes like data taken from OceananigansArtifacts.jl)
I m going to run it this evening just a little bit (like for 1/2 year) to make sure I haven't made any gross mistake and then I'll merge!

**Comment by simone-silvestri** [comment]
Ok it runs correctly! I'll merge!

**Pull request merged**
