### PR TITLE
Go back to old averaging ways

### LINKED ISSUE #1767: Output of `AveragedField` is sometimes wrong on the GPU
It seems that with Julia 1.6 and recent versions of CUDA.jl, the output of averaged fields is wrong. By inspection it seems that the output is being written to disk prematurely somehow as some grid points contain the sum instead of the mean.

@xkykai and I have tried to reproduce in CUDA.jl but with no luck so far.

I've tried adding a `CUDA.@sync blocking=true` to https://github.com/CliMA/Oceananigans.jl/blob/383173d11a0c96182a4349fc1e33755207bf0886/src/Fields/averaged_field.jl#L62 but that didn't help.

Adding a `sleep(0.01)` afterwards helped a bit (reduced the number of occurences of this issue). It's not a useful hack but it may suggest that a race condition is involved?

X-Ref: This is a minimal reproduction of https://github.com/CliMA/LESbrary.jl/issues/118
X-Ref: https://github.com/JuliaGPU/CUDA.jl/issues/929 (Attempt at reproducing but turned out to be a REPL issue)

# Minimal working example

```julia
using Oceananigans

grid = RegularRectilinearGrid(size=(256, 256, 128), extent=(1, 1, 1))
model = IncompressibleModel(architecture=GPU(), grid=grid)
simulation = Simulation(model, Δt=1, stop_time=100)

set!(model, u=1, v=1, T=1)

U = AveragedField(model.velocities.u, dims=(1, 2))
V = AveragedField(model.velocities.v, dims=(1, 2))
T = AveragedField(model.tracers.T, dims=(1, 2))

simulation.output_writers[:jld2] =
    JLD2OutputWriter(model, (; U, V, T),
          prefix = "stats",
        schedule = TimeInterval(10),
           force = true)

simulation.output_writers[:nc] =
    NetCDFOutputWriter(model, (; U, V, T),
        filepath = "stats.nc",
        schedule = TimeInterval(10),
            mode = "c")

run!(simulation)
```

## Looking at the NetCDF output

```julia
using NCDatasets
ds = NCDataset("stats.nc")
ds["T"][:]
```

```
128×11 Matrix{Float32}:                                                                                                                                                                                                                                                                 
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      0.0      0.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 ⋮                                ⋮                                            ⋮
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
```

## Looking at the JLD2 output

```julia
using JLD2
ds = jldopen("stats.jld2")
T_jld2 = cat([ds["timeseries/T/$iter"][:] for iter in keys(ds["timeseries/t"])]..., dims=2)
```

```
128×11 Matrix{Float32}:                                                                                                                                                                                                                                                                 
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      0.0      0.0      1.0      1.0      1.0                                                                                                                                                                                                      
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 1.0  1.0  1.0      1.0      1.0  1.0      1.0      1.0      1.0      1.0      1.0
 ⋮                                ⋮                                            ⋮
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
 1.0  1.0  1.0  65536.0  65536.0  1.0  65536.0  65536.0  65536.0  65536.0  65536.0
```

### PR DESCRIPTION
**Pull request by ali-ramadhan**
This PR is a hotfix for https://github.com/CliMA/LESbrary.jl/issues/118 and https://github.com/CliMA/Oceananigans.jl/issues/1767.

Seems to fix #1767 for me so we could use this branch temporarily if needed until we can actually fix #1767.

### CODE REVIEW

**Comment by tomchor** [comment]
#1767 seems pretty serious. So is "going back to old ways" not using `mapreduce`? (Sorry, I couldn't really understand the changes)

**Comment by glwagner** [comment]
Why does it fix #1767 ? Doesn't this change only affect averages of abstract operations (not averages of fields)?

**Comment by glwagner** [comment]
> #1767 seems pretty serious. So is "going back to old ways" not using `mapreduce`? (Sorry, I couldn't really understand the changes)

Rather than using

```julia
mean!(avg, avg.operand)
```

to compute the mean, this PR uses

```julia
    # Omit halo regions from operand on averaged dimension
    operand_parent = parent(avg.operand)

    Xa, Ya, Za = location(avg)
    Xo, Yo, Zo = location(avg.operand)

    i = operand_averaging_indices(Xa, Xo, topology(avg.grid, 1), avg.grid.Nx, avg.grid.Hx)
    j = operand_averaging_indices(Ya, Yo, topology(avg.grid, 2), avg.grid.Ny, avg.grid.Hy)
    k = operand_averaging_indices(Za, Zo, topology(avg.grid, 3), avg.grid.Nz, avg.grid.Hz)

    operand_sans_halos = view(operand_parent, i, j, k)

    mean!(avg.data.parent, operand_sans_halos)
```

**Comment by glwagner** [comment]
I guess the crux of the difference is that the "current" (broken) code computes a reduction into `SubArray` (a view over interior indices of `parent(avg)`), whereas the code in this PR computes a reduction into a `CuArray` (into `parent(avg)`).

**Comment by glwagner** [comment]
Can probably close this since #1769 .

**Pull request closed without merging**
