### PR TITLE
More doc built optimizations -- run computationally expensive examples first

### PR DESCRIPTION
**Pull request by navidcy**
with @glwagner

### CODE REVIEW

**Comment by navidcy** [comment]
OK, ready for review!

**Review by glwagner — APPROVED** [review]
did it help?

**Comment by glwagner** [comment]
The docs build in 52 minutes, which is the longest individual job but not much longer than some others. And better than before?

**Comment by navidcy** [comment]
before it was 52 or 56min... so perhaps it helped slightly but also sometimes depending on how many thing tartarus is doing at the moment you can have some variability in times.

**Comment by navidcy** [comment]
(when I say "before" I mean: before this PR but after #3135.)

**Comment by glwagner** [comment]
Ok so no help basically. But maybe this is still a better way to do things.

**Comment by navidcy** [comment]
But it's helpful for future. We now have a way to see how much time each example needs to run so we can order them accordingly!

**Comment by glwagner** [comment]
beautiful

**Comment by navidcy** [comment]
I just noticed:

https://buildkite.com/clima/oceananigans/builds/11955#018909c3-4c60-4b9c-b4e2-c6260d8b2189/40-2662

```
[ Info: shallow_water_Bickley_jet.jl example took 28.452 minutes to build.
```

We should optimize that or make it run first!

**Pull request merged**
