### PR TITLE
Test advection schemes with Float32 and Float64

### PR DESCRIPTION
**Pull request by glwagner**
@francispoulin this will hopefully test the question you've raised on #1780 .

### CODE REVIEW

**Comment by francispoulin** [comment]
Thanks for setting this up @glwagner .  

From looking at the code it seems that like 42 sets the float type to 64.  Is that correct?  The problem that I had was with `Float32`.  Sorry if I missed something here.

**Comment by navidcy** [comment]
That's the default value of the kwarg if nothing else is provided.

**Review by navidcy — APPROVED** [review]

**Comment by francispoulin** [comment]
Thanks @navidcy for pointing this out.  

I can see that now we loop over `float_types`, but I don't see where this is set to `[Float32, Float64]`, as it is in other tests.  Maybe I'm missing something?

**Comment by navidcy** [comment]
> Thanks @navidcy for pointing this out.
> 
> I can see that now we loop over `float_types`, but I don't see where this is set to `[Float32, Float64]`, as it is in other tests. Maybe I'm missing something?

https://github.com/CliMA/Oceananigans.jl/blob/0ddffe59457ece2b07452a421a8125abf4f4820f/test/runtests.jl#L54

**Comment by francispoulin** [comment]
> > Thanks @navidcy for pointing this out.
> > I can see that now we loop over `float_types`, but I don't see where this is set to `[Float32, Float64]`, as it is in other tests. Maybe I'm missing something?
> 
> https://github.com/CliMA/Oceananigans.jl/blob/0ddffe59457ece2b07452a421a8125abf4f4820f/test/runtests.jl#L54

Ah, thanks, I was looking in the script that was modified.  It makes sense that it's specified in `'runtests.jl`.  Thanks @navidcy for the clarification.

I am  happy to see this change and that the tests all pass.  I'm confused about the error that we're getting in #1780 .

**Review by francispoulin — APPROVED** [review]

**Comment by glwagner** [comment]
The difference appears to be that the code on #1780 uses the argument `float_type`, whereas this test only changes `eltype(grid)`.

`float_type` only determines the floating point type of the `Clock` and `buoyancy`. So I'm not sure why or how this causes the test in #1780 to fail.

Either way I think the `float_type` argument has caused enough trouble so I'm trying to banish it in #1786 . Once it's gone let's try to resolve this.

**Comment by francispoulin** [comment]
That makes sense.  I wonder if in #1780, the grid is `Float64` and when I specified the model to be `Float32`, it rightfully complained.

**Comment by glwagner** [comment]
I don't think we should merge this, because it seems to dramatically increase the time it takes to run tests without catching the bug in #1780.

**Comment by glwagner** [comment]
Meh, I guess we don't need this since #1780 is resolved.

**Comment by francispoulin** [comment]
Actually, I don't think #1780 is resolved but will confirm on Monday.

**Pull request closed without merging**
