### PR TITLE
Updates output writers interface to append extension automatically

### PR DESCRIPTION
**Pull request by glwagner**
cc @tomchor

### CODE REVIEW

**Comment by tomchor** [comment]
I think I still prefer to not append the extension and leave things the way they are mainly for three reasons:

- If you don't include the extension, then (using [usual jargon](https://www.computerhope.com/jargon/f/filename.htm)) it's not a complete file name anymore since it doesn't uniquely identify the file. To be correct I think we'd need to go back to `prefix` which isn't super clear imo
- It leads to less clear code if you're postprocessing the output in the name script. Like this pseudo code:

```julia
simulation.output_writers[:writer] = JLD2OutputWriter(model, outputs, filename=filename)

run!(simulation)
real_filename = filename * ".jld2"
jldopen(real_filename)
```

**Comment by tomchor** [comment]
Also what we'd call `filename` would be different than what is called file name in the docs for [`JLD2`](https://docs.juliahub.com/JLD2/O1EyT/0.4.22/internals/#JLD2.jldopen) and [`NCDatasets`](https://alexander-barth.github.io/NCDatasets.jl/stable/variables/#NCDatasets.NCDataset-Tuple{NCDatasets.CFVariable}), which might be a source of confusion in new users.

**Comment by glwagner** [comment]
> * If you don't include the extension, then (using [usual jargon](https://www.computerhope.com/jargon/f/filename.htm)) it's not a complete file name anymore since it doesn't uniquely identify the file.

That link you provided says

> A file name may also describe only the first portion of the file.

**Comment by glwagner** [comment]
> * Like this pseudo code:
> 
> ```julia
> simulation.output_writers[:writer] = JLD2OutputWriter(model, outputs, filename=filename)
> 
> run!(simulation)
> real_filename = filename * ".jld2"
> jldopen(real_filename)
> ```

I appreciate this feedback but need to understand --- how is this code "unclear"?

I think there _is_ a detriment to convenience --- which we have been accepting (without any loss of productivity, if we can be real...) since time eternal with the `prefix` kwarg, before #2416). I do think it'd be nice to solve this with `FieldTimeSeries` so we can write

```julia
simulation.output_writers[:writer] = JLD2OutputWriter(model, outputs, filename=filename)
run!(simulation)
u = FieldTimeSeries(filename, "u")
```

This is easy...

Balanced against the convenience detriment, I think the _cost_ of allowing arbitrary extensions is relatively higher (sharing data, figuring out the format of other people's data...). We also may have many more output writers in the future (Zarr, BSON, whatever), and I think it's friendly to relieve users from the burden of changing the filename.

**Comment by glwagner** [comment]
The other possibility which achieves the same goal (and which I'm fine with) is to enforce `.nc` in `filename` for `NetCDFOutputWriter`. We'd have to change a lot fewer tests for that too...

**Comment by glwagner** [comment]
Also to elaborate a bit: file extensions are _always_ arbitrary. The extension is just for people reading the contents of a directory, so they know what kind of data is contained in a file. For example this is fine:

```bash
$ echo 'println("Hello world!")' >> test.txt                                                                                                                                        
$ julia --project test.txt                                                                                                                                                          [11:28:26]
Hello world!
```

It's just poor communication to put your julia code in files appended with `.txt`. And your text editor won't highlight it correctly 😱 

So I think we really should somehow enforce extensions.

**Comment by tomchor** [comment]
> > * Like this pseudo code:
> > 
> > ```julia
> > simulation.output_writers[:writer] = JLD2OutputWriter(model, outputs, filename=filename)
> > 
> > run!(simulation)
> > real_filename = filename * ".jld2"
> > jldopen(real_filename)
> > ```
> 
> I appreciate this feedback but can you clarify why this code is "unclear"?
 
Maybe unclear isn't the right word to use here, but I'm just pointing out that you'd end up with two things that a human would call a file name: `filename` (without extension) and `real_filename` (with extension).

**Comment by tomchor** [comment]
> The other possibility which achieves the same goal (and which I'm fine with) is to enforce `.nc` in `filename` for `NetCDFOutputWriter`. We'd have to change a lot fewer tests for that too...

I personally would prefer that option instead of having the extension be automatically appended. Mostly because the name you pass to the writer (`something.jld2` or whatever it is) uniquely identifies the file that gets generated on your computer.

**Comment by tomchor** [comment]
This may be beyond the point of this PR, but I feel like lots of these discussions that ultimately mostly impact user interface and experience would hugely benefit from, well, user input! 

This fact, coupled with the fact that Oceananigans probably now has a decently-sized user-base, may mean that we could start using polls and directly asking users about user-interface decisions. That way we can get more hard data on what makes the code easier and clearer to most users and weight that more accurately against other aspects of the decision.

Just a thought...

**Comment by francispoulin** [comment]
I have read through this discussion and don't have a strong feeling either way.  Whether the whole file name or the root file name is called the `file name`, is a matter of semantics.  

As a user, I would ideally just want to define the root file name and then have the ending added as need be.

I realize this means that when we read the file in, what we called the filename is not truly the file name, and we need to add the ending.  I have not been bothered by this and am happy to do whatever is easier for the average user.

**Comment by simone-silvestri** [comment]
My two cents on this:

1) I think that output writers and readers always have to work with the correct extension (jld2 with `.jld2` and netcdf with `.nc`) and this should be always enforced 
2) It would be a good idea in my opinion to support either options of passing the prefix or the filename (as many softwares do) so that we get the best of both options while always preserving the extension which I believe is our priority. (Just implement a check on the last relevant characters, if there is a correct extension leave it as is otherwise append it)

**Comment by glwagner** [comment]
> 2\. It would be a good idea in my opinion to support either options of passing the prefix or the filename (as many softwares do) so that we always preservw the extension which I believe is our priority. (Just implement a check on the last relevant characters, if there is a correct extension leave it as is otherwise append it)

I guess we can do

```julia
dotindex = findlast('.', filename)
possible_ext = isnothing(dotindex) ? "" : filename[dotindex+1:end]
possible_ext == ".nc" || filename *= ".nc"
```

We can put similar logic into `FieldTimeSeries`.

**Comment by tomchor** [comment]
> > 2. It would be a good idea in my opinion to support either options of passing the prefix or the filename (as many softwares do) so that we always preservw the extension which I believe is our priority. (Just implement a check on the last relevant characters, if there is a correct extension leave it as is otherwise append it)
> 
> I think this is an excellent suggestion!
> 
> We can do
> 
> ```julia
> dotindex = findlast('.', filename)
> possible_ext = isnothing(dotindex) ? "" : filename[dotindex+1:end]
> possible_ext == ".nc" || filename *= ".nc"
> ```

Agreed. I think that's a great compromise.

**Comment by glwagner** [comment]
@tomchor do you approve? Are there any further changes you'd like to see ?

**Comment by tomchor** [comment]
> @tomchor do you approve? Are there any further changes you'd like to see ?

I was waiting for the checks to pass to review. Let me review it right now.

**Review by tomchor — APPROVED** [review]
lgtm!

**Comment by glwagner** [comment]
> > @tomchor do you approve? Are there any further changes you'd like to see ?
> 
> I was waiting for the checks to pass to review. Let me review it right now.

Got it. PR is complete so only minor debugging left (if anything -- every test passed except the one that used a `.jld2` filename)

**Pull request merged**
