### PR TITLE
Correct accessing velocities from the background field

### PR DESCRIPTION
**Pull request by liuchihl**
https://github.com/CliMA/Oceananigans.jl/pull/3646#issuecomment-2433267716 @glwagner implementing the fix suggested by Greg

### CODE REVIEW

**Comment by hdrake** [comment]
@glwagner, is that what you were intending? We're still learning the ropes on collaborative development via git here...

**Review by glwagner — APPROVED** [review]

**Comment by glwagner** [comment]
Yes! I was ok to put this in though. Just wanted to see the test first, it's like eating vegetables before dessert!

**Comment by glwagner** [comment]
I also forgot that the branch was mine and that you can only change it through a PR

**Comment by hdrake** [comment]
@glwagner, I think there was a misunderstanding about the test failing. For the background-flux-divergence PR, we were just confused as to why it wasn't passing the existing test suite.

The separate issue of adding a new test is for the [unrelated PR](https://github.com/CliMA/Oceananigans.jl/pull/3721) related to refactoring `AveragedTimeInterval` to fix the existing bug. @liuchihl has some local branches where he'd merged both of those and was testing them in combination, so we got our signals crossed.

**Pull request merged**
