### PR TITLE
Make Bickley example work on GPU

### PR DESCRIPTION
**Pull request by francispoulin**
I know that we need U to be defined as a constant for this to work.  I figured why not define the other constants as well but don't think we need to.  I'm happy with only making the required changes if people prefer.

### CODE REVIEW

**Review by ali-ramadhan — APPROVED** [review]
We might even be able to run the example with `architecture = GPU()` but not 100% sure it'll work right now.

**Comment by francispoulin** [comment]
Good suggestion.  I will try it in this PR and we will find out.  If it fails we can revert back to the default.

**Comment by francispoulin** [comment]
I just tried editing the file but then it creates a new PR.  Do you mind if I merge this then create another PR that tries GPU's?

**Comment by navidcy** [comment]
@francispoulin,why that creates a new PR? I don't understand...

@ali-ramadhan are the docs being build with GPU on?

**Comment by francispoulin** [comment]
@navidcy , no good reason and I just pushed the change now.  

@ali-ramadhan suggested that the docs might still be built, and if yes, this should be faster.  I guess we will try and find out.  If it fails I can just revert back and this PR will be done, I think.

**Comment by navidcy** [comment]
Good! :)
If it runs, then before merging just add a remark before  saying "We construct the model to run on GPU by `architectures=...`; to run on CPU simply change to `architecture = CPU()`."

**Comment by francispoulin** [comment]
It seems to have failed already so I will revert to what @navidcy suggested.

The error message is copied below.

```
[ Info: Populate: populating indices.
--
  | ERROR: LoadError: `makedocs` encountered an error. Terminating build
  | Stacktrace:
  | [1] error(::String) at ./error.jl:33
  | [2] runner(::Type{Documenter.Builder.RenderDocument}, ::Documenter.Documents.Document) at /storage7/buildkite-agent/.julia-1687/packages/Documenter/bFHi4/src/Builder.jl:255
  | [3] dispatch(::Type{Documenter.Builder.DocumentPipeline}, ::Documenter.Documents.Document) at /storage7/buildkite-agent/.julia-1687/packages/Documenter/bFHi4/src/Utilities/Selectors.jl:170
  | [4] #2 at /storage7/buildkite-agent/.julia-1687/packages/Documenter/bFHi4/src/Documenter.jl:249 [inlined]
  | [5] cd(::Documenter.var"#2#3"{Documenter.Documents.Document}, ::String) at ./file.jl:104
  | [6] #makedocs#1 at /storage7/buildkite-agent/.julia-1687/packages/Documenter/bFHi4/src/Documenter.jl:248 [inlined]
  | [7] top-level scope at /storage7/buildkite-agent/builds/tartarus-mit-edu-4/clima/oceananigans/docs/make.jl:145
  | [8] include(::Function, ::Module, ::String) at ./Base.jl:380
  | [9] include(::Module, ::String) at ./Base.jl:368
  | [10] exec_options(::Base.JLOptions) at ./client.jl:296
  | [11] _start() at ./client.jl:506
  | in expression starting at /storage7/buildkite-agent/builds/tartarus-mit-edu-4/clima/oceananigans/docs/make.jl:145
  | 🚨 Error: The command exited with status 1


```

**Comment by navidcy** [comment]
Because we don't have CUDA.jl in docs/Project.toml...
Shall I try to fix it and see?

**Comment by navidcy** [comment]
Merge now.

I think it'll be good to make sure all example work on GPU() just by changing `architecture=GPU()`...
So if Docs can run on GPU() we can confirm that this is the case.

But that's beyond this PR...

**Comment by ali-ramadhan** [comment]
Ah sorry for the slow reply. Docs build on `tartarus.mit.edu` through Buildkite which has GPUs but we disable the GPU through the Buildkite config.

I think if we just remove this line we can build examples on the GPU!

https://github.com/CliMA/Oceananigans.jl/blob/81d9c0e061cae4aa5a0ec770ff8348be7517aa53/.buildkite/pipeline.yml#L324

Doesn't have to happen in this PR of course.

**Comment by francispoulin** [comment]
Thanks @ali-ramadhan , and it's good to know that we can run the examples with CUDA, and how to do it.  I'm tempted to do this but then I wonder if this maybe cause confusion for the user if they try running the example and don't have any GPUs on their computer?  

I think I'm going to merge as is and then maybe we can revisit this later?  I know that with all the talk of multi-GPU going on now, there will certainly be some examples that we will want to run on GPUs.  Maybe that will be a good time to evaluate what examples would be best suited to do this?  I suspect speed will be a major consideration at that stage.

**Pull request merged**
