### PR TITLE
Add extension feature for plotting fields when nodes are provided

### PR DESCRIPTION
**Pull request by glwagner**
I noticed that there was code in the grids tutorial that could benefit from this feature.

### CODE REVIEW

**Comment by navidcy** [comment]
Like which code? I mean what's an example that benefits from what changed here so I can test it to approve?

**Comment by glwagner** [comment]
> Like which code? I mean what's an example that benefits from what changed here so I can test it to approve?

This PR supports this kind of code:

```julia
c = Field{Center, Center, Nothing}(grid)
x, y, z = nodes(c)
heatmap(x, y, c)
```

The coordinates `x, y` can also be divided by a normalization (say 1000 to convert from `m` to `km`).

**Review by navidcy — APPROVED** [review]
Great! LGTM!

For future, we might wanna consider making this work:

```julia
c = CenterField(grid)
x, y, z = nodes(c)
heatmap(x, y, view(c, :, :, 1))
```
or
```julia
heatmap(x, z, view(c, :, 2, :))
```

**Comment by navidcy** [comment]
> Great! LGTM!
> 
> For future, we might wanna consider making this work:
> 
> ```julia
> c = CenterField(grid)
> x, y, z = nodes(c)
> heatmap(x, y, view(c, :, :, 1))
> ```
> 
> or
> 
> ```julia
> heatmap(x, z, view(c, :, 2, :))
> ```

I take it back! This actually works!

**Comment by glwagner** [comment]
> Great! LGTM!
> 
> For future, we might wanna consider making this work:
> 
> ```julia
> c = CenterField(grid)
> x, y, z = nodes(c)
> heatmap(x, y, view(c, :, :, 1))
> ```
> 
> or
> 
> ```julia
> heatmap(x, z, view(c, :, 2, :))
> ```

This PR supports this syntax I thought

**Comment by glwagner** [comment]
Ah yeah. I didn't put `view` in the example just to keep it simple.

**Pull request merged**
