### PR TITLE
Switch to using DocumenterCitations.jl

### LINKED ISSUE #1096: Switch to using DocumenterCitations.jl
Now that https://github.com/ali-ramadhan/DocumenterCitations.jl v0.1.0 has been tagged and is used as a Documenter.jl plugin we should switch to using it.

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Resolves #1096

### CODE REVIEW

**Comment by navidcy** [comment]
Docs weren't not build...

**Comment by ali-ramadhan** [comment]
Well technically docs were built on Buildkite: https://buildkite.com/clima/oceananigans/builds/642#fa6c4066-a6b0-47c5-89bc-0b76f786d2bb

But they were not deployed because of https://github.com/CliMA/Oceananigans.jl/issues/1186

**Comment by navidcy** [comment]
OK, so to see them I should build locally?
(I need to see them to review ;))

Btw, this seems like something we should raise as an issue in Documenter.jl: push_previews should be able to deploy from buildkite.

**Comment by ali-ramadhan** [comment]
Hmmm maybe it'll be better to just resolve https://github.com/CliMA/Oceananigans.jl/issues/1186 (even before tagging the next release so we actually get stable docs)

I think CUDA.jl deploys docs (and push previews?) from Buildkite so I'll try replicating their pipeline.

**Comment by ali-ramadhan** [comment]
@navidcy Docs for this PR should be online at https://clima.github.io/OceananigansDocumentation/previews/PR1202/

Looks like they're working :tada:

**Comment by navidcy** [comment]
Are these curly brackets in the papers' titles an artefact of this PR?

Screen Shot 2020-11-27 at 6 31 58 am

**Comment by ali-ramadhan** [comment]
Ah no it's unfortunately still an open issue on Bibliography.jl: https://github.com/Azzaare/Bibliography.jl/issues/9

**Review by glwagner — APPROVED** [review]

**Pull request merged**
