### PR TITLE
Add link to arXiv for scalings in README

### PR DESCRIPTION
**Pull request by navidcy**
What do you both think?

### CODE REVIEW

**Comment by glwagner** [comment]
seems relevant

**Review by glwagner — APPROVED** [review]

**Comment by glwagner** [comment]
It looks like GPU tests did not run for this PR. Any idea why it was merged?

**Comment by navidcy** [comment]
They were run!
https://buildkite.com/clima/oceananigans/builds/13516

I'm not sure why there are two builds....
@glwagner probably you are referring to 
https://buildkite.com/clima/oceananigans/builds/13574
right?

**Comment by glwagner** [comment]
Hmm ok I didn't notice that. It makes sense too because I think the current problems on `main` are from https://github.com/CliMA/Oceananigans.jl/commit/1b4736614d3528d6a7b5cad00459bacad580052c, which succeeded this PR.

**Pull request merged**
