### PR TITLE
(0.91.15) Make GPUAdaptedFieldTimeSeries an AbstractField with Nothing grid

### PR DESCRIPTION
**Pull request by glwagner**
Helpful because we get some methods, like `location`.

cc @francispoulin @simone-silvestri

### CODE REVIEW

**Comment by francispoulin** [comment]
Glad you could figure it out.

Did you want me to test if this change removes the error?

**Comment by glwagner** [comment]
> Glad you could figure it out.
> 
> Did you want me to test if this change removes the error?

It would be great to put a test of this on ClimaOcean. We also need to test it here (but that's more work because we cano't use your MWE).

**Comment by glwagner** [comment]
xref https://github.com/CliMA/ClimaOcean.jl/issues/186

**Review by simone-silvestri — APPROVED** [review]

**Comment by wsmoses** [comment]
@glwagner can the failures here be rerun, the PR otherwise should be fine now

**Comment by glwagner** [comment]
we got the dreaded exit status -1

**Comment by wsmoses** [comment]
Oh whoops this was the wrong compathrlper PR than the one I was thinking of, ignore me

**Comment by glwagner** [comment]
> Oh whoops this was the wrong compathrlper PR than the one I was thinking of, ignore me

i suspected as much...

**Comment by navidcy** [comment]
merge?

**Pull request merged**
