### PR TITLE
[WIP] Implements homogeneous difference and interpolation operators

### PR DESCRIPTION
**Pull request by glwagner**
This major PR changes the way difference operators work so that across boundaries (either the end of the domain in `Bounded` directions, or across immersed boundaries), differences always return 0 and interpolation always returns the value on the "active" or "wet" side of the domain.

This change means the halos do not need to be filled for `Value / Gradient` boundary conditions. Instead, value and gradient boundary conditions will be enforced across `Bounded` the same way they are enforced across immersed boundaries. Moreover these boundary conditions will only be supported for `AbstractScalarDiffusivity`.

This leads to considerable code reduction, because it unifies the algorithms for non-immersed and immersed boundaries. This may decrease compile times. In addition, the reduction in halo filling will hopefully lead to further performance increases, as we have found that halo filling is inefficient especially on the GPU and should be avoided when possible. Finally, avoiding halo filling is important for distributed models, since it eliminates the dependency that halos must be filled across `Bounded` before they are sent between processes across a `Communication` topology. Evaluating performance changes will be an important part of this PR.

There's still a bit todo:

- [x] Refactor halo filling and `apply_flux_x` to enforce value / gradient boundary conditions
- [x] Implement homogeneous interpolation operators
- [ ] Possibly eliminate halo filling for `OpenBoundaryCondition`, leaving halo filling only for periodic and communication bcs

### CODE REVIEW

**Comment by glwagner** [comment]
@simone-silvestri do you know where these:

https://github.com/CliMA/Oceananigans.jl/blob/e1bfccb797d7b140bd8880859cea97c2e0bb8291/src/Operators/interpolation_operators.jl#L3-L14

are used? They were added here: https://github.com/CliMA/Oceananigans.jl/commit/a16f7f806c7a7a174a6e6e27ca1adef03e0d21f5

**Comment by simone-silvestri** [comment]
They are used in the `tangential_stencil_u` and `tangential_stencil_v` in `weno_fifth_order.jl`

**Comment by glwagner** [comment]
I believe the changes in this PR are resulting in a significant slowdown (I only tested small CPU models, but the slowdown was around 50%), so I'm going to experiment a bit. The goal is speed _up_ not slowdown...

**Comment by glwagner** [comment]
Here's some benchmarks against the current implementation. Contrary to what I just claimed, there is significant speed up for `Bounded` domains, especially with 2D problems (where avoiding halos is advantages). Note these are with `WENO5` advection, which should pessimize `Periodic` models as there are larger halos to fill.

I came to the prior conclusions by running the two-dimensional turbulence example. I'll try to make sure the "speed up" is generic and also benchmark GPU and the hydrostatic model.

# `main`

## Modest 3D model (128x128x128)

```
                                                                 Topologies benchmarks
┌───────────────┬─────────────────┬────────────────────────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────┬─────────┐
│ Architectures │              Ns │                     Topologies │        min │     median │       mean │        max │     memory │ allocs │ samples │
├───────────────┼─────────────────┼────────────────────────────────┼────────────┼────────────┼────────────┼────────────┼────────────┼────────┼─────────┤
│           CPU │ (128, 128, 128) │  (Periodic, Bounded, Periodic) │ 900.894 ms │ 901.887 ms │ 902.516 ms │ 905.129 ms │ 703.45 KiB │   1081 │       6 │
│           CPU │ (128, 128, 128) │   (Bounded, Periodic, Bounded) │ 895.527 ms │ 911.386 ms │ 910.441 ms │ 921.211 ms │ 772.19 KiB │   1131 │       6 │
│           CPU │ (128, 128, 128) │   (Periodic, Bounded, Bounded) │ 900.389 ms │ 904.161 ms │ 906.879 ms │ 916.145 ms │ 771.44 KiB │   1115 │       6 │
│           CPU │ (128, 128, 128) │    (Bounded, Bounded, Bounded) │ 903.676 ms │ 910.638 ms │ 910.295 ms │ 914.968 ms │ 837.97 KiB │   1154 │       6 │
│           CPU │ (128, 128, 128) │  (Periodic, Periodic, Bounded) │ 886.053 ms │ 892.564 ms │ 894.281 ms │ 904.917 ms │ 703.45 KiB │   1081 │       6 │
│           CPU │ (128, 128, 128) │  (Bounded, Periodic, Periodic) │ 910.500 ms │ 924.085 ms │ 923.571 ms │ 931.683 ms │ 703.45 KiB │   1081 │       6 │
│           CPU │ (128, 128, 128) │ (Periodic, Periodic, Periodic) │ 914.391 ms │ 916.636 ms │ 916.407 ms │ 917.164 ms │ 575.12 KiB │   1010 │       6 │
│           CPU │ (128, 128, 128) │   (Bounded, Bounded, Periodic) │ 923.307 ms │ 925.553 ms │ 926.892 ms │ 932.185 ms │ 772.19 KiB │   1131 │       6 │
└───────────────┴─────────────────┴────────────────────────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────┴─────────┘
[2022/05/03 01:05:45.458] INFO  Writing Topologies_benchmarks.html...
                               Topologies relative performance (CPU)
┌───────────────┬─────────────────┬────────────────────────────────┬──────────┬─────────┬─────────┐
│ Architectures │              Ns │                     Topologies │ slowdown │  memory │  allocs │
├───────────────┼─────────────────┼────────────────────────────────┼──────────┼─────────┼─────────┤
│           CPU │ (128, 128, 128) │    (Bounded, Bounded, Bounded) │ 0.993457 │ 1.45702 │ 1.14257 │
│           CPU │ (128, 128, 128) │   (Bounded, Bounded, Periodic) │  1.00973 │ 1.34264 │  1.1198 │
│           CPU │ (128, 128, 128) │   (Bounded, Periodic, Bounded) │ 0.994272 │ 1.34264 │  1.1198 │
│           CPU │ (128, 128, 128) │  (Bounded, Periodic, Periodic) │  1.00813 │ 1.22313 │  1.0703 │
│           CPU │ (128, 128, 128) │   (Periodic, Bounded, Bounded) │  0.98639 │ 1.34134 │ 1.10396 │
│           CPU │ (128, 128, 128) │  (Periodic, Bounded, Periodic) │  0.98391 │ 1.22313 │  1.0703 │
│           CPU │ (128, 128, 128) │  (Periodic, Periodic, Bounded) │ 0.973739 │ 1.22313 │  1.0703 │
│           CPU │ (128, 128, 128) │ (Periodic, Periodic, Periodic) │      1.0 │     1.0 │     1.0 │
└───────────────┴─────────────────┴────────────────────────────────┴──────────┴─────────┴─────────┘
```

## 2D model

```
                                                              Topologies benchmarks
┌───────────────┬───────────────┬────────────────────────────────┬───────────┬───────────┬───────────┬───────────┬────────────┬────────┬─────────┐
│ Architectures │            Ns │                     Topologies │       min │    median │      mean │       max │     memory │ allocs │ samples │
├───────────────┼───────────────┼────────────────────────────────┼───────────┼───────────┼───────────┼───────────┼────────────┼────────┼─────────┤
│           CPU │ (256, 256, 1) │   (Bounded, Periodic, Bounded) │ 23.527 ms │ 23.573 ms │ 23.652 ms │ 24.354 ms │ 771.44 KiB │   1115 │      10 │
│           CPU │ (256, 256, 1) │ (Periodic, Periodic, Periodic) │ 30.958 ms │ 31.004 ms │ 31.160 ms │ 31.948 ms │ 575.12 KiB │   1010 │      10 │
│           CPU │ (256, 256, 1) │  (Periodic, Periodic, Bounded) │ 23.061 ms │ 23.442 ms │ 25.189 ms │ 39.441 ms │ 703.45 KiB │   1081 │      10 │
│           CPU │ (256, 256, 1) │   (Periodic, Bounded, Bounded) │ 23.479 ms │ 23.727 ms │ 23.792 ms │ 24.619 ms │ 771.44 KiB │   1115 │      10 │
│           CPU │ (256, 256, 1) │  (Bounded, Periodic, Periodic) │ 30.863 ms │ 30.990 ms │ 31.205 ms │ 31.858 ms │ 703.45 KiB │   1081 │      10 │
│           CPU │ (256, 256, 1) │  (Periodic, Bounded, Periodic) │ 31.041 ms │ 31.521 ms │ 31.982 ms │ 33.815 ms │ 703.45 KiB │   1081 │      10 │
│           CPU │ (256, 256, 1) │    (Bounded, Bounded, Bounded) │ 25.631 ms │ 26.845 ms │ 26.749 ms │ 28.206 ms │ 837.97 KiB │   1154 │      10 │
│           CPU │ (256, 256, 1) │   (Bounded, Bounded, Periodic) │ 31.354 ms │ 31.398 ms │ 31.477 ms │ 32.215 ms │ 771.44 KiB │   1115 │      10 │
└───────────────┴───────────────┴────────────────────────────────┴───────────┴───────────┴───────────┴───────────┴────────────┴────────┴─────────┘
[2022/05/03 00:56:15.050] INFO  Writing Topologies_benchmarks.html...
                              Topologies relative performance (CPU)
┌───────────────┬───────────────┬────────────────────────────────┬──────────┬─────────┬─────────┐
│ Architectures │            Ns │                     Topologies │ slowdown │  memory │  allocs │
├───────────────┼───────────────┼────────────────────────────────┼──────────┼─────────┼─────────┤
│           CPU │ (256, 256, 1) │    (Bounded, Bounded, Bounded) │ 0.865858 │ 1.45702 │ 1.14257 │
│           CPU │ (256, 256, 1) │   (Bounded, Bounded, Periodic) │  1.01269 │ 1.34134 │ 1.10396 │
│           CPU │ (256, 256, 1) │   (Bounded, Periodic, Bounded) │ 0.760326 │ 1.34134 │ 1.10396 │
│           CPU │ (256, 256, 1) │  (Bounded, Periodic, Periodic) │ 0.999539 │ 1.22313 │  1.0703 │
│           CPU │ (256, 256, 1) │   (Periodic, Bounded, Bounded) │ 0.765277 │ 1.34134 │ 1.10396 │
│           CPU │ (256, 256, 1) │  (Periodic, Bounded, Periodic) │  1.01667 │ 1.22313 │  1.0703 │
│           CPU │ (256, 256, 1) │  (Periodic, Periodic, Bounded) │ 0.756078 │ 1.22313 │  1.0703 │
│           CPU │ (256, 256, 1) │ (Periodic, Periodic, Periodic) │      1.0 │     1.0 │     1.0 │
└───────────────┴───────────────┴────────────────────────────────┴──────────┴─────────┴─────────┘
```

# This PR

## Modest 3D model (128x128x128)

```
                                                                 Topologies benchmarks
┌───────────────┬─────────────────┬────────────────────────────────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────┬─────────┐
│ Architectures │              Ns │                     Topologies │        min │     median │       mean │        max │     memory │ allocs │ samples │
├───────────────┼─────────────────┼────────────────────────────────┼────────────┼────────────┼────────────┼────────────┼────────────┼────────┼─────────┤
│           CPU │ (128, 128, 128) │  (Periodic, Bounded, Periodic) │ 896.626 ms │ 899.133 ms │ 900.518 ms │ 909.853 ms │ 703.45 KiB │   1081 │       6 │
│           CPU │ (128, 128, 128) │   (Bounded, Periodic, Bounded) │ 895.069 ms │ 895.299 ms │ 895.293 ms │ 895.583 ms │ 772.19 KiB │   1131 │       6 │
│           CPU │ (128, 128, 128) │   (Periodic, Bounded, Bounded) │ 891.466 ms │ 891.811 ms │ 891.996 ms │ 893.026 ms │ 771.44 KiB │   1115 │       6 │
│           CPU │ (128, 128, 128) │    (Bounded, Bounded, Bounded) │ 899.668 ms │ 899.891 ms │ 899.881 ms │ 900.082 ms │ 837.97 KiB │   1154 │       6 │
│           CPU │ (128, 128, 128) │  (Periodic, Periodic, Bounded) │ 882.563 ms │ 883.710 ms │ 883.524 ms │ 884.131 ms │ 703.45 KiB │   1081 │       6 │
│           CPU │ (128, 128, 128) │  (Bounded, Periodic, Periodic) │ 912.389 ms │ 916.994 ms │ 915.908 ms │ 917.212 ms │ 703.45 KiB │   1081 │       6 │
│           CPU │ (128, 128, 128) │ (Periodic, Periodic, Periodic) │ 916.691 ms │ 917.084 ms │ 917.270 ms │ 918.438 ms │ 575.12 KiB │   1010 │       6 │
│           CPU │ (128, 128, 128) │   (Bounded, Bounded, Periodic) │ 918.221 ms │ 920.232 ms │ 920.871 ms │ 925.207 ms │ 772.19 KiB │   1131 │       6 │
└───────────────┴─────────────────┴────────────────────────────────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────┴─────────┘
[2022/05/03 00:36:02.528] INFO  Writing Topologies_benchmarks.html...
                               Topologies relative performance (CPU)
┌───────────────┬─────────────────┬────────────────────────────────┬──────────┬─────────┬─────────┐
│ Architectures │              Ns │                     Topologies │ slowdown │  memory │  allocs │
├───────────────┼─────────────────┼────────────────────────────────┼──────────┼─────────┼─────────┤
│           CPU │ (128, 128, 128) │    (Bounded, Bounded, Bounded) │ 0.981253 │ 1.45702 │ 1.14257 │
│           CPU │ (128, 128, 128) │   (Bounded, Bounded, Periodic) │  1.00343 │ 1.34264 │  1.1198 │
│           CPU │ (128, 128, 128) │   (Bounded, Periodic, Bounded) │ 0.976245 │ 1.34264 │  1.1198 │
│           CPU │ (128, 128, 128) │  (Bounded, Periodic, Periodic) │ 0.999901 │ 1.22313 │  1.0703 │
│           CPU │ (128, 128, 128) │   (Periodic, Bounded, Bounded) │ 0.972442 │ 1.34134 │ 1.10396 │
│           CPU │ (128, 128, 128) │  (Periodic, Bounded, Periodic) │ 0.980426 │ 1.22313 │  1.0703 │
│           CPU │ (128, 128, 128) │  (Periodic, Periodic, Bounded) │ 0.963608 │ 1.22313 │  1.0703 │
│           CPU │ (128, 128, 128) │ (Periodic, Periodic, Periodic) │      1.0 │     1.0 │     1.0 │
└───────────────┴─────────────────┴────────────────────────────────┴──────────┴─────────┴─────────┘
```

## 2D model

```
                                                              Topologies benchmarks
┌───────────────┬───────────────┬────────────────────────────────┬───────────┬───────────┬───────────┬───────────┬────────────┬────────┬─────────┐
│ Architectures │            Ns │                     Topologies │       min │    median │      mean │       max │     memory │ allocs │ samples │
├───────────────┼───────────────┼────────────────────────────────┼───────────┼───────────┼───────────┼───────────┼────────────┼────────┼─────────┤
│           CPU │ (256, 256, 1) │   (Bounded, Periodic, Bounded) │ 23.465 ms │ 23.687 ms │ 23.895 ms │ 24.833 ms │ 772.19 KiB │   1131 │      10 │
│           CPU │ (256, 256, 1) │ (Periodic, Periodic, Periodic) │ 34.145 ms │ 35.596 ms │ 35.767 ms │ 38.008 ms │ 575.12 KiB │   1010 │      10 │
│           CPU │ (256, 256, 1) │  (Periodic, Periodic, Bounded) │ 23.208 ms │ 23.282 ms │ 23.646 ms │ 24.667 ms │ 703.45 KiB │   1081 │      10 │
│           CPU │ (256, 256, 1) │   (Periodic, Bounded, Bounded) │ 23.736 ms │ 24.691 ms │ 24.854 ms │ 26.482 ms │ 771.44 KiB │   1115 │      10 │
│           CPU │ (256, 256, 1) │  (Bounded, Periodic, Periodic) │ 31.277 ms │ 32.486 ms │ 32.212 ms │ 32.999 ms │ 703.45 KiB │   1081 │      10 │
│           CPU │ (256, 256, 1) │  (Periodic, Bounded, Periodic) │ 30.844 ms │ 30.903 ms │ 31.003 ms │ 31.769 ms │ 703.45 KiB │   1081 │      10 │
│           CPU │ (256, 256, 1) │    (Bounded, Bounded, Bounded) │ 23.704 ms │ 23.832 ms │ 24.042 ms │ 25.055 ms │ 837.97 KiB │   1154 │      10 │
│           CPU │ (256, 256, 1) │   (Bounded, Bounded, Periodic) │ 31.354 ms │ 31.632 ms │ 31.816 ms │ 32.916 ms │ 772.19 KiB │   1131 │      10 │
└───────────────┴───────────────┴────────────────────────────────┴───────────┴───────────┴───────────┴───────────┴────────────┴────────┴─────────┘
[2022/05/03 00:42:25.915] INFO  Writing Topologies_benchmarks.html...
                              Topologies relative performance (CPU)
┌───────────────┬───────────────┬────────────────────────────────┬──────────┬─────────┬─────────┐
│ Architectures │            Ns │                     Topologies │ slowdown │  memory │  allocs │
├───────────────┼───────────────┼────────────────────────────────┼──────────┼─────────┼─────────┤
│           CPU │ (256, 256, 1) │    (Bounded, Bounded, Bounded) │ 0.669516 │ 1.45702 │ 1.14257 │
│           CPU │ (256, 256, 1) │   (Bounded, Bounded, Periodic) │ 0.888622 │ 1.34264 │  1.1198 │
│           CPU │ (256, 256, 1) │   (Bounded, Periodic, Bounded) │ 0.665425 │ 1.34264 │  1.1198 │
│           CPU │ (256, 256, 1) │  (Bounded, Periodic, Periodic) │ 0.912619 │ 1.22313 │  1.0703 │
│           CPU │ (256, 256, 1) │   (Periodic, Bounded, Bounded) │ 0.693639 │ 1.34134 │ 1.10396 │
│           CPU │ (256, 256, 1) │  (Periodic, Bounded, Periodic) │ 0.868158 │ 1.22313 │  1.0703 │
│           CPU │ (256, 256, 1) │  (Periodic, Periodic, Bounded) │ 0.654046 │ 1.22313 │  1.0703 │
│           CPU │ (256, 256, 1) │ (Periodic, Periodic, Periodic) │      1.0 │     1.0 │     1.0 │
```

The fastest is fully bounded for whatever reason.

**Comment by glwagner** [comment]
Just a few notes:

* There's surprisingly little "interpolation" / reconstruction in our code (except for trivial reconstruction). Most of the reconstruction occurs for advection, but advective reconstruction doesn't need to be touched by this PR. So this PR actually mostly affects the implementation of GM.
* There are a few things re: using homogeneous operators for Coriolis forces. I suspect that it won't have an effect, but it needs to be tested.
* It should be feasible to use homogeneous / boundary-aware operators _only_ for fluxes. 
* Finally, I'm going to implement an "enforce_impenetrability!" operator that does 3D masking and works for both non-immersed and immersed boundaries. After that, we can use `nothing` as a default boundary condition for velocities rather than `ImpenetrableBoundaryCondition`. It seems that impenetrable is still useful for users though so we may want to keep it...
* An even further step would eliminate the need for masking boundary regions by never updating the tendency there. But this approach allows users to more easily make mistakes, ie changing the velocity field during a run, but forgetting to enforce incompressibility.

**Comment by francispoulin** [comment]
This all looks very promising.  Silly question, how is `slowdown` computed exactly?

**Comment by glwagner** [comment]
> This all looks very promising. Silly question, how is `slowdown` computed exactly?

Probably

test / reference

so < 1 means "speed _up_"

**Comment by glwagner** [comment]
It looks like our problems with GM are not solved by this PR --- even when we correctly mask interior values (it might be worth testing this a second time, but I think I did this correctly).

Here are results for https://github.com/CliMA/Oceananigans.jl/pull/2477/commits/1c183f9a8df7b97f5074f18ce622b247b7b1c923, in which the stencil is rewritten to compute the "gradient of the average". When we do this, and use "boundary-aware averages", we eliminate a dependence on the boundary (ie the GM stencil is "inward looking"). It doesn't fix the basic issue with spurious fluxes near the boundary:

https://user-images.githubusercontent.com/15271942/166609754-1c832d73-3089-48d0-89c4-a99caac344b1.mp4

Hmm...

For reference, here's what happens when we revert to "average of the gradient" via https://github.com/CliMA/Oceananigans.jl/pull/2477/commits/b7a67598db1fe8d5afea27cece5d35d0c20aac93:


https://user-images.githubusercontent.com/15271942/166610211-95376390-bb80-4993-8b7b-6a3cbe27bebf.mp4

**Comment by glwagner** [comment]
I implemented the advective form for GM and the results are much much much much much better:

https://user-images.githubusercontent.com/15271942/168515158-91148ba0-0c1d-4fac-a18f-af6dfe96756f.mp4

cc @sandreza

**Comment by glwagner** [comment]
It also bears mention that the curious behavior in the lat-lon results above (what looks like spurious boundary fluxes after around 20 days) apparently occurs whether we include the GM parameterization or not. So something else is wrong, perhaps with Bounded boundary conditions on lat-lon (but not sure).

**Comment by glwagner** [comment]
@simone-silvestri should we close this? There's quite a few conflicts now...

**Comment by glwagner** [comment]
It's stale!

**Pull request closed without merging**
