### PR TITLE
Adds grid as positional argument to WENO functions and extracts floating point type for arithmetic

### LINKED ISSUE #1771: Some WENO5 operations are not Float32-friendly
Mainly this one (and friends):

https://github.com/CliMA/Oceananigans.jl/blob/aeb7a52751154034344e4430f9fe4f6cf56137b6/src/Advection/weno_fifth_order.jl#L92

because 

https://github.com/CliMA/Oceananigans.jl/blob/aeb7a52751154034344e4430f9fe4f6cf56137b6/src/Advection/weno_fifth_order.jl#L89

is `Float64`.

I think we just need to convert `ε` to `eltype(grid)`. Otherwise, we'll hit CUDA funcs for exponentiating `Float64` rather than `Float32` or `Float16` 😱 

For that we need to pass `grid` into those little functions. Pretty easy fix.

### PR DESCRIPTION
**Pull request by glwagner**
Resolves #1771 .

### CODE REVIEW

**Review by navidcy — APPROVED** [review]
Seems good. If tests pass then merge!

**Comment by navidcy** [comment]
Any insight to why [shallow water tests fail on gpu](https://buildkite.com/clima/oceananigans/builds/3153#f8f52f7d-7e1d-4d88-9a0b-5b1c18b4d90b)?

**Comment by francispoulin** [comment]
I can confirm that it does fail on gpus by having tried to on my desktop. It seems to fail at this line [here](https://github.com/CliMA/Oceananigans.jl/blob/0aa8e32ef2c821330100980902c2c6469c13b719/test/test_shallow_water_models.jl#L171) 

When I ran it in REPL I found the following error.  I'm not sure exactly what this PR does as I haven't had a chance to look into it yet but this is the intial output that I got in the error.

```
Time-stepping ShallowWaterModels [GPU(), WENO5]: Error During Test at REPL[37]:4
  Test threw exception
  Expression: time_stepping_shallow_water_model_works(arch, topos[1], nothing, advection)
  InvalidIRError: compiling kernel gpu_calculate_Guh!(Cassette.Context{nametype(CUDACtx), KernelAbstractions.CompilerMetadata{KernelAbstractions.NDIteration.StaticSize{(1, 1, 1)}, KernelAbstractions.NDIteration.DynamicCheck, Nothing, Nothing, KernelAbstractions.NDIteration.NDRange{3, KernelAbstractions.NDIteration.StaticSize{(1, 1, 1)}, KernelAbstractions.NDIteration.StaticSize{(1, 1, 1)}, Nothing, Nothing}}, Nothing, KernelAbstractions.var"##PassType#257", Nothing, Cassette.DisableHooks}, typeof(Oceananigans.Models.ShallowWaterModels.gpu_calculate_Guh!), OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}, RegularRectilinearGrid{Float64, Periodic, Periodic, Flat, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}}, Float64, WENO5, Nothing, Nothing, Nothing, NamedTuple{(:uh, :vh, :h), Tuple{OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}, OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}, OffsetArrays.OffsetArray{Float64, 3, CUDA.CuDeviceArray{Float64, 3, 1}}}}, NamedTuple{(), Tuple{}}, Nothing, NamedTuple{(:uh, :vh, :h), Tuple{typeof(Oceananigans.Forcings.zeroforcing), typeof(Oceananigans.Forcings.zeroforcing), typeof(Oceananigans.Forcings.zeroforcing)}}, NamedTuple{(:time, :iteration, :stage), Tuple{Float64, Int64, Int64}}) resulted in invalid LLVM IR
  Reason: unsupported call through a literal pointer (call to )
  Stacktrace:
   [1] overdub
     @ array.jl:271
   [2] overdub
     @ array.jl:313
   [3] copyto!(::Vector{UInt8}, ::Int64, ::Vector{UInt8}, ::Int64, ::Int64)
     @ array.jl:304
   [4] overdub
     @ array.jl:304
   [5] overdub
     @ iobuffer.jl:295
   [6] overdub
     @ iobuffer.jl:315
   [7] overdub
     @ ~/.julia/packages/Cassette/N5kbV/src/overdub.jl:0
   [8] multiple call sites
     @ unknown:0
  Reason: unsupported call to the Julia runtime (call to jl_f_tuple)
```

**Comment by navidcy** [comment]
Yeap, that's the same as the buildkite log... :)

**Comment by navidcy** [comment]
@glwagner any idea why tests fail? happy to zoom to dig into this?

**Comment by glwagner** [comment]
My guess is that it's the use of `Rational` via the double slash (eg `11//6`). I doubt there's any issue with changing all these to the `Float64` literals `11/6`.

**Comment by navidcy** [comment]
Indeed, changing rationals to floats did the job!

**Pull request merged**
