### PR TITLE
Removes `architecture` from `ShallowWaterModel` docstring

### PR DESCRIPTION
**Pull request by aramirezreyes**
This makes the docstring consistent with the changes to the constructor from https://github.com/CliMA/Oceananigans.jl/pull/2078/

### CODE REVIEW

**Comment by francispoulin** [comment]
Thanks @aramirezreyes for creating this, and I think this is a great idea to make things more uniformity.

Unfortunately, there are some errors.  When I looked at the first one it seemed to have an errror due to another model?

```
Immersed boundaries test divergent flow solve with hydrostatic free surface models: Error During Test at /var/lib/buildkite-agent/builds/tartarus-1/clima/oceananigans/test/test_hydrostatic_free_surface_immersed_boundaries_congrad_solve.jl:8
  | Got exception outside of a @test
  | ArgumentError: The grid halo (1, 1, 1) must be larger than (3, 3, 3).
  | Stacktrace:
  | [1] HydrostaticFreeSurfaceModel(; grid::ImmersedBoundaryGrid{Float64, Periodic, Periodic, Bounded, RectilinearGrid{Float64, Periodic, Periodic, Bounded, Float64, Float64, Float64, OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}}, CPU}, GridFittedBottom{OffsetMatrix{Float64, Matrix{Float64}}}, CPU}, clock::Clock{Float64}, momentum_advection::CenteredSecondOrder, tracer_advection::WENO5{Float64, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing}, buoyancy::Nothing, coriolis::Nothing, free_surface::ImplicitFreeSurface{Nothing, Float64, Nothing, Nothing, Symbol, Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}}, forcing::NamedTuple{(), Tuple{}}, closure::Nothing, boundary_conditions::NamedTuple{(), Tuple{}}, tracers::Nothing, particles::Nothing, velocities::Nothing, pressure::Nothing, diffusivity_fields::Nothing, auxiliary_fields::NamedTuple{(), Tuple{}})
  | @ Oceananigans.Models.HydrostaticFreeSurfaceModels ~/builds/tartarus-1/clima/oceananigans/src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl:113
  | [2] macro expansion
  | @ ~/builds/tartarus-1/clima/oceananigans/test/test_hydrostatic_free_surface_immersed_boundaries_congrad_solve.jl:41 [inlined]
  | [3] macro expansion
  | @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
  | [4] top-level scope
  | @ ~/builds/tartarus-1/clima/oceananigans/test/test_hydrostatic_free_surface_immersed_boundaries_congrad_solve.jl:9
  | [5] include(fname::String)
  | @ Base.MainInclude ./client.jl:444
  | [6] macro expansion
  | @ ~/builds/tartarus-1/clima/oceananigans/test/runtests.jl:65 [inlined]
  | [7] macro expansion
  | @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
  | [8] macro expansion
  | @ ~/builds/tartarus-1/clima/oceananigans/test/runtests.jl:58 [inlined]
  | [9] macro expansion
  | @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
  | [10] top-level scope
  | @ ~/builds/tartarus-1/clima/oceananigans/test/runtests.jl:4
  | [11] include(fname::String)
  | @ Base.MainInclude ./client.jl:444
  | [12] top-level scope
  | @ none:6
  | [13] eval
  | @ ./boot.jl:360 [inlined]
  | [14] exec_options(opts::Base.JLOptions)
  | @ Base ./client.jl:261
  | [15] _start()
  | @ Base ./client.jl:485
 
```

**Comment by aramirezreyes** [comment]
I noticed that as well but it seems that those errors are present in the latest commit in master (I don't seem to have touched anything related):

https://buildkite.com/clima/oceananigans/builds/4868#67294627-d75d-4346-8392-c67b358b5c3c

**Review by navidcy — APPROVED** [review]
Thanks 🙏

**Comment by navidcy** [comment]
I don’t understand why tests fail. Most probably is not because of editing docstring. Will look at this after New Years.

**Comment by navidcy** [comment]
We need to deal with #2131  and rebase.

**Comment by aramirezreyes** [comment]
If it is easier, I can also resubmit the changes in a new PR once #2131 is solved.


Argel Ramírez Reyes

**Comment by navidcy** [comment]
> If it is easier, I can also resubmit the changes in a new PR once #2131 is solved.

Nah don't worry. It's very easy to do. (I can also deal with it when #2131 is merged.)

**Comment by navidcy** [comment]
@aramirezreyes, could you bring this up to date with `main` branch? Perhaps all tests pass then and we can merge.

**Comment by glwagner** [comment]
Thanks for the PR @aramirezreyes !

**Pull request merged**
