### PR TITLE
Change Cartesian --> rectilinear

### LINKED ISSUE #1377: Our grids are usually not Cartesian
According to [wikipedia](https://en.wikipedia.org/wiki/Regular_grid), we have been using the term "Cartesian" incorrectly, since "Cartesian" only applies to coordinate systems with unit areas and volumes:

> A Cartesian grid is a special case where the elements are unit squares or unit cubes, and the vertices are points on the integer lattice.

Thus "RegularCartesianGrid" should really be called RegularRectilinearGrid and "VerticallyStretchedCartesianGrid" should be called VerticallyStretchedRectilinearGrid (in the latter case, horizontal regularity is implicit).

### PR DESCRIPTION
**Pull request by navidcy**
This PR changes "Cartesian" to "rectilinear" to comply with widely used conventions.

According to wikipedia:
> A Cartesian grid is a special case where the elements are unit squares or unit cubes, and the vertices are points on the integer lattice.

Closes  #1377

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
That was quick! I think we didn't rush to resolve #1377 since it's a pretty major breaking change but as long as tests pass (and people agree with the change) we should tag a release!

**Comment by ali-ramadhan** [comment]
Hmmm, doesn't rectilinear imply orthogonal?

`RegularRectilinearOrthogonalGrid` might be a little redundant?

**Comment by navidcy** [comment]
> Hmmm, doesn't rectilinear imply orthogonal?
> 
> `RegularRectilinearOrthogonalGrid` might be a little redundant?

No. Rectilinear just means that lines of, e.g., "constant x" are straight lines... But the axis could intercept in angles other than 90 degrees.

**Comment by ali-ramadhan** [comment]
Hmmm if we go by the [Regular grid Wikipedia article](https://en.wikipedia.org/wiki/Regular_grid) that formed the basis for #1377 and this PR then

> A rectilinear grid is a tessellation by rectangles or rectangular cuboids

Rectangles always have 90 degree angles so by this definition the axes can only intercept at 90 degree angles and are orthogonal?

**Comment by navidcy** [comment]
Perhaps the "Regular" implies orthogonal them? Because "rectilinear" by itself just means straight lines. We can have "orthogonal rectilinear" and "skew rectilinear".

**Comment by ali-ramadhan** [comment]
I think regular implies constant spacing, not necessarily orthogonal.

Sounds like "rectilinear" means straight lines by itself but a "rectilinear grid" is a tesselation by rectangles which would imply that a "rectilinear grid" is orthogonal?

**Comment by francispoulin** [comment]
What do people think of `OrthogonalRectilinearGrid`?

**Comment by navidcy** [comment]
> What do people think of `OrthogonalRectilinearGrid`?

But `Regular` was there to differentiate from `VerticallyStretched`. So @francispoulin you are suggesting:

`OrthogonalRectilinearGrid` and `VerticallyStretchedOrthogonalRectilinearGrid`?

**Comment by francispoulin** [comment]
> > What do people think of `OrthogonalRectilinearGrid`?
> 
> But `Regular` was there to differentiate from `VerticallyStretched`. So @francispoulin you are suggesting:
> 
> `OrthogonalRectilinearGrid` and `VerticallyStretchedOrthogonalRectilinearGrid`?

To be perfectly clear I suppose we could use the following

`VerticallyUniformOrthogonalRectilinearGrid` and `VerticallyStretchedOrthogonalRectilinearGrid`

but that makes for a lot of characters.  Not very attractive I'm afraid.

**Comment by ali-ramadhan** [comment]
I'm usually for verbose names as they are clearer but in this case the basic regular rectilinear grid is something every user will interact with and will show up in at the top of each example/tutorial so I agree with @francispoulin that a shorter name would be good.

We probably need more than just 1 approval to merge this PR, preferably unanimous consent amongst ourselves?

**Comment by navidcy** [comment]
I agree. Let's settle on the naming and I'll adjust.

I vote:
`OrthogonalRectilinearGrid` and `VerticallyStretchedOrthogonalRectilinearGrid`

**Comment by christophernhill** [comment]
> I agree. Let's settle on the naming and I'll adjust.
> 
> I vote:
> `OrthogonalRectilinearGrid` and `VerticallyStretchedOrthogonalRectilinearGrid`

Doesn't Rectilinear imply Orthogonal. I don't think a non-orthogonal grid can be Rectilinear?

**Comment by navidcy** [comment]
> > I agree. Let's settle on the naming and I'll adjust.
> > I vote:
> > `OrthogonalRectilinearGrid` and `VerticallyStretchedOrthogonalRectilinearGrid`
> 
> Doesn't Rectilinear imply Orthogonal. I don't think a non-orthogonal grid can be Rectilinear?
> 
> e.g. http://evshelp.ctech.com/Content/workbooks/fundamentals_of_visualizing_environmental_data/rectilinear_grids.htm
> 
> https://www.researchgate.net/figure/a-cartesian-grid-b-regular-grid-c-general-rectilinear-grid-d-structured-grid_fig2_221252521

Perhaps @christophernhill is right...

(I think I already [7am] need a second coffee already :))

**Comment by ali-ramadhan** [comment]
I vote for:
* `RegularRectilinearGrid`
* `VerticallyStretchedRectilinearGrid`
* Future: `RectilinearGrid` could be stretched/compressed in x, y, z (should not be a problem with `ShallowWaterModel`).

**Comment by glwagner** [comment]
I agree with @ali-ramadhan's suggestion.

**Comment by navidcy** [comment]
Closing in favor of #1393.

**Pull request closed without merging**
