### PR TITLE
Change log level for doctesting with warnings

### LINKED ISSUE #3705: Convert code blocks documenting `ImmersedBoundaryCondition` to doctests
lgtm!

@glwagner, could you open an issue pointing to this PR and saying that some doctests were removed and we need to attend to them with proper filtering etc?

_Originally posted by @navidcy in https://github.com/CliMA/Oceananigans.jl/pull/3692#pullrequestreview-2236731923_

### PR DESCRIPTION
**Pull request by glwagner**
Closes #3705 

*sigh*

### CODE REVIEW

**Review by navidcy — APPROVED** [review]
lgtm

thanks for dealing with the annoying doctests....

**Comment by navidcy** [comment]
hey you need to use 

```@meta
DocTestSetup = quote
    function foo(x)
        return x^2
    end
end
```

**Comment by glwagner** [comment]
> hey you need to use
> 
> ```
> DocTestSetup = quote
>     function foo(x)
>         return x^2
>     end
> end
> ```

I wanted to avoid activating it globally

**Comment by glwagner** [comment]
Feel free to try to get it to work

**Comment by navidcy** [comment]
OK I'll try later!

**Comment by navidcy** [comment]
but FYI:

```@setup example1

```
 is used to configure `@examples`, not doctests; that's why it didn't work.

On a different note, using `# hide` notation won't work in the sense the code will run but it won't be hidden -- that's syntax from Literate.jl package and we are not liberating the docs; only examples.jl

**Comment by glwagner** [comment]
Didn't work

**Pull request closed without merging**
