### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by navidcy**
@glwagner I'm testing in this PR using https://github.com/glwagner/OceananigansArtifacts.jl

### CODE REVIEW

**Review by glwagner — APPROVED** [review]

**Comment by navidcy** [comment]
I'm quite confused that this test from `test_seawater.jl` fails:

https://buildkite.com/clima/oceananigans/builds/15457#018eec75-847a-4323-b8e9-9f104d750297/37-1020

On tartarus everything passes...

**Comment by navidcy** [comment]
> I'm quite confused that this test from `test_seawater.jl` fails:
> 
> https://buildkite.com/clima/oceananigans/builds/15457#018eec75-847a-4323-b8e9-9f104d750297/37-1020
> 
> On tartarus everything passes...

OK I can reproduce the fail on tartarus. I'm on it.

**Comment by navidcy** [comment]
The differences are O(1e-13).

**Comment by jbisits** [comment]
> This test:
> 
> https://github.com/CliMA/Oceananigans.jl/blob/63cb6713efed46d47372038cc75c11192c75b73b/test/test_seawater_density.jl#L90
> 
> is failing on `GPU()` with `Float64` and `RoquetEquationOfState(:SimplestRealistic)`. I don't know if something changed -- I think nothing has changed.
> 
> I suggest `.==` -> `.\approx`
> 
> (cc'ing @jbisits, @glwagner in case you have an idea of something that changed in SeaWaterPolynomials or you can see a flaw in the tests, eg FT not passed in properly etc)

Just curious, does the test for the `potential_density` function

https://github.com/CliMA/Oceananigans.jl/blob/63cb6713efed46d47372038cc75c11192c75b73b/test/test_seawater_density.jl#L118

also fail? (when on `GPU()` with `Float64` and `RoquetEquationOfState(:SimplestRealistic)`).

**Comment by navidcy** [comment]
Test of potential density pass. 
The insitundensity difference for k=2 is instead of 0 is 2e-13…

**Comment by jbisits** [comment]
> Test of potential density pass. The insitu density difference for k=2 is instead of 0 is 2e-13…

In that case I think your suggestion  `.== `-> `.\approx` should do the trick!

**Pull request merged**
