### PR TITLE
Fix `ShallowWaterModel` closure for tracers in the vector invariant form

### PR DESCRIPTION
**Pull request by francispoulin**
Discussed with @simone-silvestri

### CODE REVIEW

**Comment by francispoulin** [comment]
I copied one of the errors below.  I remember seeing this error before but I'm not sure how it was resolved.  Restarting the tests?

```
Precompiling project...
  | ✓ Oceananigans
  | 1 dependency successfully precompiled in 87 seconds (200 already precompiled)
  | Testing Running tests...
  | ERROR: LoadError: LoadError: SystemError: opening file "/data5/glwagner/.julia-7803/compiled/v1.6/Oceananigans/hU93i_V4y9F.ji": No such file or directory
  | Stacktrace:
...
```

**Comment by glwagner** [comment]
Is this for ShallowWaterModel?

**Comment by francispoulin** [comment]
> Is this for ShallowWaterModel?

Yes, the closure terrm for tracers was not done correctly and gave an error in the previous form.  This fixes it for the `VectorInvariantForm`, but more work needs to be done for the `ConservativeForm`.  I plan to talk to @simone-silvestri on Monday about this and other things.

**Comment by glwagner** [comment]
> > Is this for ShallowWaterModel?
> 
> Yes, the closure terrm for tracers was not done correctly and gave an error in the previous form. This fixes it for the `VectorInvariantForm`, but more work needs to be done for the `ConservativeForm`. I plan to talk to @simone-silvestri on Monday about this and other things.

Sounds good, I updated the PR title so no one gets alarmed

**Comment by francispoulin** [comment]
> Usually restarting the test works for me to clear that error

Good to know.  How can I do that?

**Comment by glwagner** [comment]
> > Usually restarting the test works for me to clear that error
> 
> Good to know. How can I do that?

I don't think you can because you need access to the Clima buildkite. But @simone-silvestri can do it.

**Comment by navidcy** [comment]
I did it :)

**Comment by francispoulin** [comment]
Thank you @navidcy!  

Mind if I ask how?  I feel like I might have been given permission to do this last year, but just never tried it.  If I don't have permission, no problem, but if I do I can learn to do this to avoid bothering others with this.

**Comment by navidcy** [comment]
> Thank you @navidcy!  
> 
> 
> 
> Mind if I ask how?  I feel like I might have been given permission to do this last year, but just never tried it.  If I don't have permission, no problem, but if I do I can learn to do this to avoid bothering others with this. 

I don't have permission to give you permission. :(

**Review by navidcy — APPROVED** [review]

**Pull request merged**
