### PR TITLE
Delete spherical_splash.jl

### PR DESCRIPTION
**Pull request by navidcy**
Perhaps first merge #1665 so that the example is bugless in the git history?

### CODE REVIEW

**Comment by glwagner** [comment]
Sure, I can do that.

**Review by glwagner — APPROVED** [review]
Just needs a merge master and passing tests.

**Comment by navidcy** [comment]
I'll proceed with nuking as soon as tests pass.

But I do advocate for the need of a simple example on the sphere to appear in the docs soon... :)

**Comment by glwagner** [comment]
Yes, a simple example would be great.

**Pull request merged**
