### PR TITLE
Adds AveragedField test for 256 x 256 x 128 Field

### PR DESCRIPTION
**Pull request by glwagner**
Tries to catch the race condition that produces #1767 .

### CODE REVIEW

**Comment by navidcy** [comment]
Tests fail, is this a "success"?

Does this test have to use `256 x 256 x 128`? Smaller fields won't do the job?

**Comment by glwagner** [comment]
It's failing for the wrong reasons, I think. We want to see CPU pass and GPU fail.

**Comment by glwagner** [comment]
Bleh.

**Comment by navidcy** [comment]
You can modify the buildkite pipeline here so that only the relevant tests run. Eg no need to build docs. :)

**Comment by glwagner** [comment]
:/

**Comment by navidcy** [comment]
> :/

Only if that will make your life simpler though. :) Just a suggestion so you avoid waiting for ever to see if the test actually fail.

**Comment by navidcy** [comment]
> I'm drinking coffee, but some might describe that as "waiting"

Keep calm and keep caffeinated.

**Comment by ali-ramadhan** [comment]
Looks like the new test only ran on the CPU on Sverdrup which could explain why it took 3+ hours and passed? https://buildkite.com/clima/oceananigans/builds/3043#c40e50d1-2fc1-4804-b44a-14c09f0efb50/16-351

Hmmm, this might be happening on master as well...

**Comment by glwagner** [comment]
The test in this PR passes on the CPU and fails on the GPU, so the intended result is achieved.

**Pull request closed without merging**
