### PR TITLE
Automatically-generated function signatures with DocStringExtensions

### PR DESCRIPTION
**Pull request by tomchor**
This PR implements automatically-generated function signatures with DocStringExtensions. I think this will avoid human errors when creating docstrings and also making documenting stuff easier, which hopefully will ultimately help users and novice developers.

Starting this as a draft since I wanna see what effects this will have on the docs.

### CODE REVIEW

**Comment by tomchor** [comment]
Docs preview should be at https://clima.github.io/OceananigansDocumentation/preview/PR2879

**Comment by glwagner** [comment]
Nice! We probably want to replace docstrings judiciously, since there are some we may want to reduce (for the purpose of readability / understability) relative to the automatically generated versions?

**Comment by tomchor** [comment]
> Nice! We probably want to replace docstrings judiciously, since there are some we may want to reduce (for the purpose of readability / understability) relative to the automatically generated versions?

I think the way DocStringExtensions includes things is pretty minimally invasive so I don't think too-verbose docstring will be an issue (if I understand your point correctly). But I agree with your point.

Just as a point of comparison, here's what the start of the docstrings for `RectilinearGrid` looks like on main:

```julia
help?> RectilinearGrid
search: RectilinearGrid

  RectilinearGrid([architecture = CPU(), FT = Float64];
                  size,
                  x = nothing,
                  y = nothing,
                  z = nothing,
                  halo = nothing,
                  extent = nothing,
                  topology = (Periodic, Periodic, Bounded))

  Creates a RectilinearGrid with size = (Nx, Ny, Nz) grid points.
```

and here's what it looks like o this branch after using DocStringExtensions:

```julia
help?> RectilinearGrid
search: RectilinearGrid

  RectilinearGrid()
  RectilinearGrid(architecture)
  RectilinearGrid(
      architecture,
      FT;
      size,
      x,
      y,
      z,
      halo,
      extent,
      topology
  )
  

  Creates a RectilinearGrid with size = (Nx, Ny, Nz) grid points.
```

For now the automatic signature isn't showing the default for each argument, which isn't great, but there might be a way to include that with some options.

**Comment by tomchor** [comment]
It looks like one would expect in the docs as well:

image

**Comment by glwagner** [comment]
I prefer the version on `main`. How about you?

**Comment by tomchor** [comment]
> I prefer the version on `main`. How about you?

As it is I also prefer main. But I'll try to tweak DocStringExtensions to try and improve the output.

**Comment by tomchor** [comment]
It seems like DocStringExtensions doesn't yet have the ability to specify default arguments, but this feature might come in a [not-so-distant future](https://github.com/JuliaDocs/DocStringExtensions.jl/issues/19#issuecomment-1418284136).

I'll close this PR for now and open it again when this feature is implemented upstream.

**Pull request closed without merging**
