### PR TITLE
Restrict LatitudeLongitueGrid topologies

### PR DESCRIPTION
**Pull request by glwagner**
I believe @simone-silvestri argued for this. I may have been against it at some time. But now I think it is actually useful for documenting the behavior of `LatitudeLongitudeGrid`, so I'm adding it...

cc @navidcy

### CODE REVIEW

**Comment by jagoosw** [comment]
I might be missing something but why can't they be periodic in z?

**Comment by simone-silvestri** [comment]
If I have to guess, it is not physical to have something that moves radially outwards and re-enters at a smaller radius.

Since we have a thin shell approximation, we can "technically" allow it, but a periodic domain is meant to represent an infinite domain, so the think shell approximation would not hold with a periodic z-direction

**Review by navidcy — APPROVED** [review]

**Comment by glwagner** [comment]
We can allow `Periodic` in z if people want that

**Comment by navidcy** [comment]
@glwagner merge?

**Pull request merged**
