### PR TITLE
Bump to 0.58.9

### PR DESCRIPTION
**Pull request by glwagner**
Release notes:

* Fixes a major bug with `ImmersedBoundaryGrid` that elided all viscous fluxes

### CODE REVIEW

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
@glwagner this should have been committed with `[skip ci]` really. It's just taking up resources :)

**Comment by glwagner** [comment]
I prefer to having passing tests before a merge to master, even in cases where we "think" it's fine.

**Comment by navidcy** [comment]
OK. Last time it happened.

**Comment by glwagner** [comment]
Those resources have a purpose and it's to help me sleep soundly at night which is very important

**Comment by navidcy** [comment]
Actually me too. I take my statement back 100%.

**Comment by glwagner** [comment]
But I actually I agree that for non-final commits [skip ci] is great. Just maybe not for the final commit before a merge.

**Pull request merged**
