### PR TITLE
Updates packages used for building the Docs

### PR DESCRIPTION
**Pull request by navidcy**
Updates `docs/Manifest.toml`.

### CODE REVIEW

**Comment by navidcy** [comment]
@ali-ramadhan, there is a strange error in the [docs log](https://buildkite.com/clima/oceananigans/builds/2637#a8b79673-9564-4527-94c6-209dedd870a2) about `Kumar16`... Any idea? Is it related with bumping up DocumenterCitations.jl from 0.2.1 -> 0.2.2?

**Comment by ali-ramadhan** [comment]
Hmmm, the docs Manifest.toml is using Bibliography.jl v0.2.6 and BibParser.jl v0.1.10 while this PR upgrades to Bibliography.jl v0.2.8 and BibParser.jl v0.1.14.

The packages definitely have some open issues so maybe there's a new bug with `@book` entries or something? `Kumar16` is a `@book` entry. Maybe worth opening an issue on Bibliography.jl if we can isolate the issue?

**Comment by navidcy** [comment]
Can I pin specific versions of dependencies to try out?

**Comment by navidcy** [comment]
I have a hunch that the problem with `Kumar16` was the lack of curly brackets in the bib entry; see 
58fd3dd

**Review by francispoulin — APPROVED** [review]
Thanks for going over all of these!

**Pull request merged**
