### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Some regular maintenance

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Hmmm, so it looks like tests take longer now so Travis CI and GitLab CI will more often than not time out and fail 😞 

Maybe it's time to split up the tests into 3-4 smaller jobs?

**Comment by navidcy** [comment]
I don't understand why you have the `Manifest.toml`? With proper use of the `[compat]` section in `Project.toml` there is no need to have the Manifest.toml in the package (and thus no need to keep updating it). Am I missing something?

**Comment by glwagner** [comment]
@navidcy that is only true in theory I think. In reality we need to maintain the precise versions of packages that are used.

**Comment by ali-ramadhan** [comment]
@navidcy I think you're right that with proper `[compat]` bounds, a `Manifest.toml` is unnecessary. But I think that would mean that as developers we would have to be meticulous about updating lower and upper bounds of dependencies. In particular, if a bug is introduced in a dependency then it could cause our master branch to fail (unless we had very strict upper `[compat]` bounds and updated them regularly).

I guess I see strict `[compat]` bounds as saying that "our package is guaranteed to work as long as your dependencies lie between these versions" (might take a lot of testing to ensure all version combinations are fine), while just using a `Manifest.toml` with loose `[compat]` bounds is saying "our package is guaranteed to work with the versions prescribed in the `Manifest.toml`".

I like the `Manifest.toml` approach as it gives us more control: we only update dependencies when we're ready and deal with any new issues one-by-one before merging. And it lets us play around with upgrading/downgrading the version on different dependencies, e.g. CUDA.jl, without worrying about `[compat]` bounds.

**Comment by ali-ramadhan** [comment]
Hmmm looks like it was `TEST_GROUP=integration` that went from taking ~20 minutes to ~32 minutes, enough to cause timeouts. We can live with this for now I suppose, can look into it in the future.

**Pull request merged**
