### PR TITLE
Docstring for `ShallowWaterScalarDiffusivity`

### LINKED ISSUE #2939: Docstring needed for `ShallowWaterScalarDiffusivity`
https://github.com/CliMA/Oceananigans.jl/blob/56309fcdb1503669b76ea3c1d8c0c210d1667851/src/Models/ShallowWaterModels/shallow_water_diffusion_operators.jl#L28-L32

### PR DESCRIPTION
**Pull request by navidcy**
I made an attempt. But it can be definitely improved...

So this diffusivity is applied to the dynamics regardless the formulation?

@francispoulin can you edit the docstring? Or @simone-silvestri?

Closes #2939

### CODE REVIEW

**Review by simone-silvestri — APPROVED** [review]

**Review by francispoulin — APPROVED** [review]
Looks great!  Thank you @navidcy for doing this.

**Comment by navidcy** [comment]
So is what I wrote ok? Does it apply for both formulations or should we distinguish?

**Comment by simone-silvestri** [comment]
It applies to both formulations. `sw_∂ⱼ_τ₁ⱼ` uses fields `u` and `v` to calculate ``t``. Both formulations have a `u` and `v` field,  in the `ConservativeFormulation`, they are diagnostic quantities while in the `VectorInvariant` they are the prognostic velocity

https://github.com/CliMA/Oceananigans.jl/blob/b6cf30e7bf98d102a97aa303858ae0dd4640e3bf/src/Models/ShallowWaterModels/shallow_water_model.jl#L219-L234

**Comment by simone-silvestri** [comment]
The only distinction is that in the `VectorInvariantFormulation` (that evolves $u$ and $v$) you want to compute
$h^{-1} \nabla \nu h \nabla t$,
while in the `ConservativeFormulation` (that evolves $uh$ and $vh$) 
$\nabla \nu h \nabla t$

**Comment by navidcy** [comment]
Ok. Will add a remark and merge ;)

**Pull request merged**
