### PR TITLE
Small fix for single column model mode

### PR DESCRIPTION
**Pull request by glwagner**
PR #2121 changed some function signatures, which broke functionality provided by `single_column_model_mode.jl` that sets `model.free_surface = nothing`. This PR restores that functionality.

I think we could add a test, but the experimental nature of `single_column_model_mode.jl` could also mean it'd be better to wait.

### CODE REVIEW

**Comment by navidcy** [comment]
Something's still not right... :(

**Comment by navidcy** [comment]
Do we need a `with_halo` method for `LatitudeLongitudeGrid`?

**Comment by simone-silvestri** [comment]
A with_halo for lat lon grid can be very usefull

**Comment by glwagner** [comment]
Huh, not sure how `with_halo` for the lat lon grid got deleted... I'll put it back.

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
I think the previews folder in `gh-pages` has overgrown again... Will deal with it! :)

**Comment by navidcy** [comment]
ok, merge?

**Pull request merged**
