### PR TITLE
Fill halo regions for `Face-Face-Any` fields on `ConformalCubedSphereGrid`

### PR DESCRIPTION
**Pull request by siddharthabishnu**
This PR introduces test functions to verify the accurate halo filling at face-face locations of the orthogonal spherical shell grids comprising the six panels of the conformal cubed sphere. Additionally, it provides comments and docstrings for these test functions, thereby closing #3242.

### CODE REVIEW

**Comment by navidcy** [comment]
@siddharthabishnu somehow there are 38 commits in this PR...

**Comment by navidcy** [comment]
I tried to sort it out but couldn't.

@siddharthabishnu can you branch off main and then commit the changes in [a340885](https://github.com/CliMA/Oceananigans.jl/pull/3277/commits/a34088504d2e90035b2a97baab3b39f3c62c3495)?

**Comment by glwagner** [comment]
why are there so many commits already? can we start from `main`?

**Comment by siddharthabishnu** [comment]
@navidcy and @glwagner, I created this halo test branch from your tracer advection branch the day before yesterday, prior to its merger with the main. Given that the tracer advection, along with other branches, was integrated into the main branch yesterday, this branch started displaying numerous reverse changes. To address this, I merged the main branch into this one, leading to multiple commits. I will close this PR and create a fresh branch from the main. I will then push my commits. Please bear with me for a few minutes while I do this.

**Comment by siddharthabishnu** [comment]
Closing this PR only to re-create this one from the main branch!

**Comment by navidcy** [comment]
@siddharthabishnu I think you are still not doing the default merge behavior that’s why you end up with these sort of situations. I believe if I had done what you described the PR would be clean. We can zoom and exchange notes (eg each do a demo new PR and see what happens).

**Comment by siddharthabishnu** [comment]
> @siddharthabishnu I think you are still not doing the default merge behavior that’s why you end up with these sort of situations. I believe if I had done what you described the PR would be clean. We can zoom and exchange notes (eg each do a demo new PR and see what happens).

I am uncertain as to why my previous approach resulted in multiple commits. I am always open to a Zoom call and exchanging notes, as you suggested. However, for this specific issue, I opted for the nuclear option: I closed this PR, deleted the associated branch, and then recreated it. The new PR is now streamlined with just a single commit.

**Pull request closed without merging**
