### PR TITLE
Update dependency packages

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Comment by glwagner** [comment]
Thanks @navidcy !

**Comment by navidcy** [comment]
Any idea why [distributed tests](https://buildkite.com/clima/oceananigans/builds/6805#646493ef-a91c-418c-b51f-4cafeced8ff1) fail?

**Comment by glwagner** [comment]
Possibly related to discussion on #2347 ? Broadcasting ordinary arrays with PencilArrays is fragile. It needs to be fixed...

**Comment by tomchor** [comment]
> Possibly related to discussion on #2347 ? Broadcasting ordinary arrays with PencilArrays is fragile. It needs to be fixed...

I think that's correct. A way to test this is to change the following lines: 
https://github.com/CliMA/Oceananigans.jl/blob/3ba95e07a27d93129a87f266aecc3c11d20aac14/test/test_distributed_models.jl#L471-L472

to 

```julia
 arch = MultiArch(ranks=(1, 4, 1)) 
 grid = RectilinearGrid(arch, topology=topo, size=(8, 2, 8), extent=(1, 2, 3)) 
```

And it should make tests pass. For some reason I found that the condition `Rx*Nx == Ry*Ny == Rz*Nz` needs to be satisfied in order to make tests pass (see https://github.com/CliMA/Oceananigans.jl/issues/2445).

I don't necessarily recommend merging that way, since this doesn't fix the issue, instead it circumvents it, but I'm pretty sure we won't be able to update the packages (including updating to julia 1.7) before fixing this issue.

On the other hand, this test passes right now on main only because of a coincidence, and there's most likely a bug in code (based on answer by @glwagner and @jipolanco), so the test is not doing its intended purpose. That might be an argument for removing that test until we have time to fix the issue, since it's keeping us from updating other packages.

**Comment by glwagner** [comment]
We could change to `@test_broken`.

**Comment by glwagner** [comment]
Another possibility is to write some tests using `HydrostaticFreeSurfaceModel` with `ExplicitFreeSurface`, which is entirely explicit and thus requires only halo filling via MPI (with no PencilArrays dependency)

**Review by glwagner — APPROVED** [review]

**Comment by navidcy** [comment]
All tests pass except the cleanup cpu. 
i’ll merge.

**Comment by navidcy** [comment]
We need to make tests shorter… :(

**Pull request merged**
