### PR TITLE
Change default scheme for `HydrostaticSphericalCoriolis`

### PR DESCRIPTION
**Pull request by glwagner**
The default should be `ActiveCellEnstrophyConserving` according to @simone-silvestri

### CODE REVIEW

**Review by navidcy — APPROVED** [review]

**Review by navidcy — CHANGES_REQUESTED** [review]
you only seem to have changed the docstring function signature.
let's change the description below to agree with the signature...

and also, the constructor at the moment seems to suggests that it's actually the EnergyConserving that is the default, no?

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
OK, some regression tests break with this change (probably because the data was produced with the default scheme which was different). Also some unit tests. I'll have a look.

**Comment by glwagner** [comment]
oh sorry

**Comment by navidcy** [comment]
No worries!
it brings up an issue that regression tests and generation scripts should not rely on default args/kwargs

**Review by navidcy — APPROVED** [review]

**Pull request merged**
