### PR TITLE
Update shallow_water_Bickley_jet.jl

### PR DESCRIPTION
**Pull request by francispoulin**
Removing `interior` allows this example to run on both CPUs and GPUs.

### CODE REVIEW

**Comment by glwagner** [comment]
We also just need to use a computed field, we should be able to use

```julia
perturbation_norm(args...) = norm(v)
```

For this we need to change the implementation of `norm` in the source slightly.

Do you mind if I make these changes?

**Comment by glwagner** [comment]
I'm also wondering if it would be better to compute the discrete perturbation vorticity by calculating the initial vorticity analytically, storing it, and using it when we calculate the perturbation. The downside is that the perturbation will contain the noise in addition to the Bickley jet. But since the noise is small this may not be a big deal.

**Comment by francispoulin** [comment]
Please go ahead @glwagner and get this started.  I am happy to help where I can but clearly you understand what needs to be done here better than I do.

**Comment by francispoulin** [comment]
I am open to trying something different with how vorticity is computed.  I computed it exactly and used those analytical expressions, but this is a pain when you want to consider a different jet, and you have to compute this again. If we can simply state the initial velocity and height, and then compute the voriticty, that migth be easier.

**Comment by glwagner** [comment]
> I am open to trying something different with how vorticity is computed. I computed it exactly and used those analytical expressions, but this is a pain when you want to consider a different jet, and you have to compute this again. If we can simply state the initial velocity and height, and then compute the voriticty, that migth be easier.

Right! In addition to being more flexible and illustrating the diagnostic procedure in general, a discrete calculation is more "exact" than an analytical expression.

**Comment by francispoulin** [comment]
> > I am open to trying something different with how vorticity is computed. I computed it exactly and used those analytical expressions, but this is a pain when you want to consider a different jet, and you have to compute this again. If we can simply state the initial velocity and height, and then compute the voriticty, that migth be easier.
> 
> Right! In addition to being more flexible and illustrating the diagnostic procedure in general, a discrete calculation is more "exact" than an analytical expression.

I am puzzled by your statement here.  A discrete, i.e. numerical calculation, is more exact than the analytical (so called exact) expression?  

I guess it's more appropriate for the discretization that we are using, which is probably the point you are making.  Okay, I see that and agree it's probably the better way to go.

**Comment by glwagner** [comment]
> > > I am open to trying something different with how vorticity is computed. I computed it exactly and used those analytical expressions, but this is a pain when you want to consider a different jet, and you have to compute this again. If we can simply state the initial velocity and height, and then compute the voriticty, that migth be easier.
> > 
> > 
> > Right! In addition to being more flexible and illustrating the diagnostic procedure in general, a discrete calculation is more "exact" than an analytical expression.
> 
> I am puzzled by your statement here. A discrete, i.e. numerical calculation, is more exact than the analytical (so called exact) expression?
> 
> I guess it's more appropriate for the discretization that we are using, which is probably the point you are making. Okay, I see that and agree it's probably the better way to go.

Correct. There's a "discrete vorticity". The analytically calculated vorticity is close to the discrete vorticity, but not exactly equal to it. For example, the perturbation vorticity in the current definition may not be initially zero, even if there were no noise.

A similar concept holds for geostrophic balance. There is a discrete geostrophic balance condition contains in a model that's stratified and rotating. This discrete condition is close to, but not exactly identical to the continuous geostrophic balance condition.

This point has to do with approximation / discretization in general, through for some discretization (eg spectral decompositions), discrete representations may be closer to continuous analytical representations.

**Comment by francispoulin** [comment]
Thanks @glwagner and I am now converted.  Yes, this is the better way to go and something I will keep in mind for the future.

**Comment by francispoulin** [comment]
If wonder whether this change will remove the jump we have in the growth rate plot that happens at the first instant?  I think it should.  This should give a prettier picture, I would think.

https://clima.github.io/OceananigansDocumentation/stable/generated/shallow_water_Bickley_jet/

**Comment by glwagner** [comment]
Ah yeah. Perhaps we should also calculate the mean vorticity prior to adding noise? I can do that.

I've added this piece of code to the source:

```julia
function Statistics.norm(a::AbstractField)
    arch = a.architecture
    grid = a.grid

    r = zeros(arch, grid, 1)

    Base.mapreducedim!(x -> x * x, +, r, a)

    return CUDA.@allowscalar b[1]
end
```

which hopefully works with `AbstractOperations`. I also kept the original definition, applied to `AbstractDataField`.

I think there might be a better / more general way to do this in the future by appropriately defining `similar` for `AbstractField`, but perhaps this is good enough for now. Checking to see if the example runs on GPU...

**Comment by glwagner** [comment]
> I think that calculating the mean vorticity before we compute the noise would be great.
> 
> Your code looks very clean, but I'm not quite sure what it's doing different from what we had before?

Previously we had

```julia
Statistics.norm(a::AbstractField) = sqrt(mapreduce(x -> x * x, +, interior(a)))
```

`interior(a)` returns a `view` over `parent(a)` that contains only the interior indices. Moreover `GPUArray` recognizes a `view` over a `CuArray` as on the GPU, and thus this function hooks into a special GPU-specific `mapreduce`.

But this strategy fails for AbstractOperations, which have no `parent` array. To use GPU-specific code, we have to a) ensure that the output of `mapreduce` is initialized properly through `similar` or b) attempt to use `Base.mapreducedim!` instead. By using `mapreducedim!`, we can ensure GPU-specific code is called by initializing the output.

It's a bit silly for the case of 0-dimensional output. Nevertheless, what I've done is initialized a 1-element array, reduced into it, and then output the result, indexing with `CUDA.@allowscalar`.

**Comment by glwagner** [comment]
Just realized I'm missing the `sqrt` part.

**Comment by francispoulin** [comment]
Yes, thanks for the explanation and I agree that a `sqrt` will make things much beter. This gives us a `2-norm`, and one can definite any `p-norm` similarly I presume.

**Comment by glwagner** [comment]
> Yes, thanks for the explanation and I agree that a `sqrt` will make things much beter. This gives us a `2-norm`, and one can definite any `p-norm` similarly I presume.

It's easy to write generic code for that, but would require more work to write _fast_ generic code since we may need to treat small integers differently than large ones.

**Comment by glwagner** [comment]
Here's the result:

https://user-images.githubusercontent.com/15271942/126214584-e9994bdc-7c9a-46c5-b83d-1c3fb31ce6a4.mp4

**Comment by glwagner** [comment]
Let me know what you think @francispoulin and feel free to change anything.

**Review by glwagner — APPROVED** [review]

**Comment by francispoulin** [comment]
The movie looks as good as before. Can you post the image that's produced?  Unfortunately, I don't think it's saved when you run the example on it's own.

**Comment by glwagner** [comment]
I suppose we'll see it when the example is compiled into a preview.

**Comment by francispoulin** [comment]
> I suppose we'll see it when the example is compiled into a preview.

Sounds good and I looked through the code and everything looks good to me.  

I will merge after the tests pass.

**Comment by francispoulin** [comment]
Looking at the new plot of the growth rate, I see the intial spike has not disappeared.  Makes me wonder whether maybe the first value is 0, which it shouldn't be.  I'll look at this tomorrow, but glad we got this done today.  Thanks @glwagner for all the help!

https://clima.github.io/OceananigansDocumentation/dev/generated/shallow_water_Bickley_jet/

**Comment by glwagner** [comment]
I don't think those docs are updated for this PR yet, right?

**Comment by francispoulin** [comment]
I looked at the dev docs. Those should have the changes, right?

**Comment by glwagner** [comment]
I don't think the docs build.

The tests hadn't finished running when the PR was merged:

image

**Comment by glwagner** [comment]
Reading the script also shows that the changes aren't in there. But for me the biggest clue was the movie. In this PR the changes lead to an initial frame:

image

whereas in the old docs the initial frame was

image

I believe the initial large scale pattern in the perturbation vorticity is the difference between the analytically calculated vorticity and the discretely calculated vorticity.

**Comment by glwagner** [comment]
The initial jump is still there though:

image

Getting rid of that may require a smoother perturbation? I think the perturbation is divergent; it have to rapidly adjust.

**Comment by francispoulin** [comment]
Some nice detective work @glwagner , and I agree that the initial profile looks much better and therefore justifies this improvement.

As for the growth rate plot, in the movies, both cases have an intial perturbation O(1e-3) or so.  I can believe this has a norm of O(1e-2).  However, initially, the value is much smaller and I'm guessing it's zero.  This is probably because we don't compute it at the first index.  I will have to look at the plotting script and see why that is.  

One easy fix is to start plotting at the second point. A more satisfying fix would be to actually compute the norm at the first index.  I will try and figure this out later today, but now breakfast!

**Pull request merged**
