### PR TITLE
Add update_state! to set_shallow_water_model.jl

### PR DESCRIPTION
**Pull request by francispoulin**

### CODE REVIEW

**Review by glwagner — APPROVED** [review]
Looks good!

**Comment by ali-ramadhan** [comment]
Sorry validation pipeline was accidently triggered so I canceled it. Fixed it so shouldn't happen in the future.

**Comment by francispoulin** [comment]
> Sorry validation pipeline was accidently triggered so I canceled it. Fixed it so shouldn't happen in the future.

Does that mean it will retry the tests?

**Comment by ali-ramadhan** [comment]
> Does that mean it will retry the tests?

Ah no unfortunately it still says failed on some checks since they were canceled but all regular Oceananigans tests passed so should be good to merge! https://buildkite.com/clima/oceananigans/builds/1018

**Comment by francispoulin** [comment]
@glwagner you okay with me merging?

**Comment by glwagner** [comment]
Looks good!

**Pull request merged**
