### PR TITLE
Adaptive time-stepping on all grids

### LINKED ISSUE #1201: Are we computing CFL correctly?
https://github.com/CliMA/Oceananigans.jl/blob/a343711f1101b1a433124f5f9697ce60b1011a40/src/Utils/cell_advection_timescale.jl#L2-L12

I guess the [proper way (?)](https://en.wikipedia.org/wiki/Courant%E2%80%93Friedrichs%E2%80%93Lewy_condition#The_two_and_general_n-dimensional_case) to compute the cell advection timescale would be to compute `Δx/u + Δy/v + Δz/w` at every grid point then take the maximum of that field but this requires an intermediate field and is probably slower than the current implementation.

I guess the problem is you can have diagonal velocities, i.e. time step needs to be lower if u = v = w = 1 compared to u = 1, v = w = 0 even with isotropic grid spacing.

Could this help explain why we find that we have to keep CFL a bit lower than expected by theory?

### LINKED ISSUE #1447: Ensure we can use `TimeStepWizard` for all grids
Right now I think `TimeStepWizard` fails for vertically stretched grids (see issue #1429). cc @mukund-gupta 

For a proper calculation of CFL on stretched and curvilinear grids we may need a scratch space to compute CFL at every grid point then do a `maximum` reduction.

We might also be able to make use of `mapreduce` which would be a pretty sweet way of correctly computing CFL (and should be fast on the GPU).

### PR DESCRIPTION
**Pull request by ali-ramadhan**
This PR adds a new function `accurate_cell_advection_timescale` that is used to compute CFL at every grid point then reduced to find the maximum (which is the correct way as discussed in #1201).

It will allow us to use the `TimeStepWizard` for adaptive time-stepping on all grids. I'll also extend it to `ShallowWaterModel` before merging.

So it works great and scales well on the CPU but not so well on the GPU (see below). At 256^3, `cfl(model)` takes as long as ~5 time steps.

Is this something we want to merge? If we don't want to slow down adaptive time-stepping for existing models we could just export `accurate_cell_advection_timescale` so that adaptive time-stepping with accurate CFL is opt-in, e.g. via an `AccurateTimeStepWizard` or something.

Motivation for using Tullio.jl:

Originally I tried just using `mapreduce` but couldn't get it to work without a nested `mapreduce` which would trigger tons of kernel launches: https://discourse.julialang.org/t/is-it-possible-to-do-a-mapreduce-with-multiple-arrays-while-broadcasting-over-so/57433

Then I found out about Tullio.jl (super neat package we might want to use more) which allows us to compute CFL and reduce it down elegantly, however, reducing to one scalar does not currently work so I have to reduce the 3D CFL calculation to a 1D vector: https://github.com/mcabbott/Tullio.jl/issues/91

Apparently optimizing reductions on the GPU is non-trivial but can be done: https://developer.download.nvidia.com/compute/cuda/1.1-Beta/x86_website/projects/reduction/doc/reduction.pdf Not sure if an optimized reduction kernel is available in Julia/CUDA.jl but maybe they will be in the future. @maleadt or @vchuravy might know...

```
julia> model.architecture
CPU()

julia> size(grid)
(32, 32, 32)

julia> @btime time_step!(model, 1)
  5.977 ms (2090 allocations: 343.97 KiB)

julia> @btime cfl(model)
  127.870 μs (10 allocations: 2.36 KiB)
```

```
julia> model.architecture
GPU()

julia> size(grid)
(32, 32, 32)

julia> @btime time_step!(model, 1)
  2.632 ms (7058 allocations: 820.19 KiB)

julia> @btime cfl(model)
  1.294 ms (257 allocations: 25.36 KiB)
```

```
julia> model.architecture
CPU()

julia> size(grid)
(256, 256, 256)

julia> @btime time_step!(model, 1)
  3.378 s (2090 allocations: 343.97 KiB)

julia> @btime cfl(model)
  134.737 ms (10 allocations: 4.16 KiB)
```

```
julia> model.architecture
GPU()

julia> size(grid)
(256, 256, 256)

julia> @btime time_step!(model, 1)
  22.507 ms (7066 allocations: 1.09 MiB)

julia> @btime cfl(model)
  128.361 ms (257 allocations: 41.53 KiB)
```

Resolves #1201
Resolves #1447

X-Ref: #1422

### CODE REVIEW

**Review by francispoulin — COMMENTED** [review]
Neat idea!  I guess this is trying to find a more accurate estimation of the CFL condition and therefore the time step needed for numerical stability.  The previous method was less accurate, more conservative, but much faster.  

I don't see any problem with this but as a user, since both are simply estiamtes (we need to pick a scaling factor in both cases) I am probably more inclined to pick the faster more conservative estimate, but why not give the user the choice and they can decide?

**Comment by maleadt** [comment]
> Apparently optimizing reductions on the GPU is non-trivial but can be done: https://developer.download.nvidia.com/compute/cuda/1.1-Beta/x86_website/projects/reduction/doc/reduction.pdf Not sure if an optimized reduction kernel is available in Julia/CUDA.jl but maybe they will be in the future. @maleadt or @vchuravy might know...

The CUDA.jl implementation is such an implementation: https://github.com/JuliaGPU/CUDA.jl/blob/2310b88738c11449867e6f37c5acbfcd453dc2c8/src/mapreduce.jl#L60-L69. It probably needs to be profiled and optimized if you really want to squeeze out performance, but it isn't a naive implementation either. It's exposed via `Base.mapreducedim` and friends.

**Comment by glwagner** [comment]
@ali-ramadhan can you explain in greater detail why this problem requires nested calls to `mapreduce`?

**Comment by ali-ramadhan** [comment]
Thanks @maleadt! I didn't know about `Base.mapreducedim`. Will look into using it when I revisit this PR!

> I don't see any problem with this but as a user, since both are simply estiamtes (we need to pick a scaling factor in both cases) I am probably more inclined to pick the faster more conservative estimate, but why not give the user the choice and they can decide?

Yes definitely agree. The default can be the very fast `cell_advection_timescale` function while this PR can add a new `accurate_cell_advection_timescale`.

The main use for `accurate_cell_advection_timescale` will be for curvilinear grids where a fast method is probably too conservative (or for when you want an accurate CFL diagnostic). I've been using it on the cubed sphere in PR #1522 and it seems to work great (fast enough on the CPU).

> @ali-ramadhan can you explain in greater detail why this problem requires nested calls to mapreduce?

Yes. We essentially want to `mapreduce` over operations like `w / Δz` but `w` and `Δz` need to have the same size for `mapreduce` to work on multiple iterators (`w` and `Δz`). They have different sizes on all grids right now.

Only way I could figure out how to do it using just `mapreduce` was to do an "inner `mapreduce`" where e.g. `w[i, j, :]` and `Δz` have the same size and the "outer `mapreduce`" iterates over the other dimensions. So we would need slightly different `mapreduce` implementations for the different grids.

**Comment by glwagner** [comment]
> Yes. We essentially want to mapreduce over operations like w / Δz but w and Δz need to have the same size for mapreduce to work on multiple iterators (w and Δz). They have different sizes on all grids right now.

Can we wrap the reduced objects somehow so that the iterators for both objects match?

**Comment by ali-ramadhan** [comment]
> Can we wrap the reduced objects somehow so that the iterators for both objects match?

That should work. Could be done with a new `Field` type?

Would you object to merging this PR in it's current form though? It's an optional feature that works for curvilinear grids and is tested. It's been helpful for debugging cubed sphere validation experiments so I'm using it in PR #1522.

**Pull request merged**
