### PR TITLE
Testing this change from type-stable-with-tracers

### PR DESCRIPTION
**Pull request by jlk9**
Just seeing if the change to top_boundary_conditions breaks anything.

### CODE REVIEW

**Comment by wsmoses** [comment]
@glwagner can you review this? The failures seem unrelated, e.g. `Reason: unsupported dynamic function invocation (call to Base.Fix1{typeof(Adapt.adapt), Float64})` and I'm not sure what already is expected to fail

**Comment by glwagner** [comment]
> The failures seem unrelated, e.g. `Reason: unsupported dynamic function invocation (call to Base.Fix1{typeof(Adapt.adapt), Float64})`

wut

> I'm not sure what already is expected to fail

Nothing is expected to fail

Where does `Fix1` come from?

**Comment by glwagner** [comment]
`Fix1` is a julia function:

```julia
help?> Base.Fix1
  Fix1(f, x)

  A type representing a partially-applied version of the two-argument function
  f, with the first argument fixed to the value "x". In other words, Fix1(f,
  x) behaves similarly to y->f(x, y).

  See also Fix2.
```

I don't see where this gets created.

**Comment by glwagner** [comment]
Something fishy is happening. The error is

```julia
Reason: unsupported dynamic function invocation (call to Base.Fix1{typeof(Adapt.adapt), Float64})
```

This means we created a partially-applied function via `Fix1(adapt, x)`. 

This looks like a bug that has to do with some package update, maybe to `Adapt`?

**Comment by glwagner** [comment]
This issue crept in on https://github.com/CliMA/Oceananigans.jl/pull/3402. That PR should not have been merged. So, we have to rewind it I guess.

**Review by glwagner — APPROVED** [review]

**Pull request closed without merging**
