### PR TITLE
Remove redundant advection aliases

### PR DESCRIPTION
**Pull request by simone-silvestri**
Since they have been removed from the exported methods, I think we do not have a need for them anymore.

### CODE REVIEW

**Review by glwagner — APPROVED** [review]
Agree. They aren't useful

**Comment by tomchor** [comment]
Wasn't this a breaking PR?

**Comment by simone-silvestri** [comment]
Hmmm, you are right. We probably should bump the version

**Comment by tomchor** [comment]
I think so. Although maybe we wanna for https://github.com/CliMA/Oceananigans.jl/pull/3143 before registering a new version in order to avoid two breaking releases in a row. That PR seems ready to merge.

**Comment by simone-silvestri** [comment]
sounds good! I want to merge also #3894 but I can merge now when the tests pass

**Pull request merged**
