### PR TITLE
Change `'\n'` -> `"\n"`

### PR DESCRIPTION
**Pull request by navidcy**
Our style uses double quotes for strings everywhere except `'\n'`. This PR homogenizes the style.

### CODE REVIEW

**Review by tomchor — APPROVED** [review]

**Review by francispoulin — APPROVED** [review]
Good idea and thanks for doing the work!

**Comment by glwagner** [comment]
> Our style uses double quotes for strings everywhere except `'\n'`. This PR homogenizes the style.

Ah! This was intentional --- note that single quotes denote a character, not a string. So '\n' is the single newline character. It doesn't really matter, but `"\n"` isn't necessary, because we don't need a full-bore string if we only have one character. I thought using single quotes just clarified that it was one character (can get lost when reading, since there is two literal characters when we read it).

**Comment by navidcy** [comment]
We can undo this. Didn't know.

**Comment by glwagner** [comment]
Def not worth undoing!

**Pull request merged**
