### PR TITLE
Fixes CPU slowdown with KernelAbstractions >= v0.8

### LINKED ISSUE #2996: 10-100x slowdown on CPU after upgrade to KernelAbstractions 0.8 (due to type inference failure?)
I observe a discontinuous doubling of docs building time from 3 hours on

https://buildkite.com/clima/oceananigans/builds/9920#01862a69-61ee-4e59-82b4-5c4b4684e7b6

to 6 hours after "Merge pull request #2899 from CliMA/vc/ka_upgrade"

https://buildkite.com/clima/oceananigans/builds/9935#01862d0c-e009-4a05-a8bb-023d1159a2ae

cc @simone-silvestri, @vchuravy

### PR DESCRIPTION
**Pull request by simone-silvestri**
Apparently, the issue with #2996 is caused by the fact that slurping inside a kernel signature 
i.e:
```
@kernel function test_func(r, c, args...)
      i, j, k = @index(Global, NTuple)
      r[i, j, k] = whatever_inlined_function(i, j, k, c, args...)
end
```
This can be fixed by passing the size of the `Vararg` tuple
like this
```
@kernel function test_func(r, c, args::Vararg{T, N}) where {T, N}
      i, j, k = @index(Global, NTuple)
       r[i, j, k] = whatever_inlined_function(i, j, k, c, args...)
end
```

Edit, this approach only works if all Varargs are of the same type `T`.

Edit, Edit, with @glwagner we decided to pass all additional arguments to the kernel as a tuple, so
```
@kernel function test_func(r, c, args)
      i, j, k = @index(Global, NTuple)
      r[i, j, k] = whatever_inlined_function(i, j, k, c, args...)
end
```
which means that from now on, when calling a kernel
```
caller_func(arch, grid, r, c, args...) = launch!(arch, grid, worksize, test_func, r, c, args...)
```
will become
```
caller_func(arch, grid, r, c, args...) = launch!(arch, grid, worksize, test_func, r, c, Tuple(args))
```
Resolves #2996

### CODE REVIEW

**Comment by navidcy** [comment]
@simone-silvestri is this done? shall I test it on my laptop?

**Comment by simone-silvestri** [comment]
Sure give it a try. We can merge when tests pass

**Comment by navidcy** [comment]
Well if the docs take 6hrs then it's a sign that the problem persists...?

**Comment by simone-silvestri** [comment]
no worries, they seem to be finishing (~ 3hrs maybe). We should definitely separate the docs testing for when the PR is ready to merge, 3 hrs is a very long time for little returns

**Comment by glwagner** [comment]
@navidcy how about a Nonhydrostatic example?

**Comment by navidcy** [comment]
### using Oceananigans main
```Julia
julia> include("ocean_wind_mixing_and_convection.jl")
[ Info: Initializing simulation...
Iteration: 0000, time: 0 seconds, Δt: 11 seconds, max(|w|) = 1.1e-05 ms⁻¹, wall time: 0 seconds
[ Info:     ... simulation initialization complete (2.049 seconds)
[ Info: Executing initial time step...
[ Info:     ... initial time step complete (16.222 seconds).
Iteration: 0020, time: 3.403 minutes, Δt: 13.310 seconds, max(|w|) = 8.8e-06 ms⁻¹, wall time: 23.980 seconds
Iteration: 0040, time: 7.488 minutes, Δt: 16.105 seconds, max(|w|) = 5.5e-06 ms⁻¹, wall time: 30.307 seconds
Iteration: 0060, time: 12 minutes, Δt: 10.350 seconds, max(|w|) = 8.9e-06 ms⁻¹, wall time: 36.549 seconds
Iteration: 0080, time: 15 minutes, Δt: 8.284 seconds, max(|w|) = 4.4e-05 ms⁻¹, wall time: 42.839 seconds
Iteration: 0100, time: 17.509 minutes, Δt: 7.101 seconds, max(|w|) = 1.2e-04 ms⁻¹, wall time: 49.022 seconds
Iteration: 0120, time: 19.561 minutes, Δt: 6.358 seconds, max(|w|) = 5.5e-04 ms⁻¹, wall time: 55.315 seconds
Iteration: 0140, time: 21.505 minutes, Δt: 5.772 seconds, max(|w|) = 2.5e-03 ms⁻¹, wall time: 1.026 minutes
Iteration: 0160, time: 23.277 minutes, Δt: 5.356 seconds, max(|w|) = 1.0e-02 ms⁻¹, wall time: 1.129 minutes
Iteration: 0180, time: 24.961 minutes, Δt: 5.303 seconds, max(|w|) = 2.6e-02 ms⁻¹, wall time: 1.232 minutes
Iteration: 0200, time: 26.626 minutes, Δt: 5.806 seconds, max(|w|) = 6.5e-02 ms⁻¹, wall time: 1.337 minutes
Iteration: 0220, time: 28.639 minutes, Δt: 6.807 seconds, max(|w|) = 1.0e-01 ms⁻¹, wall time: 1.440 minutes
Iteration: 0240, time: 30.873 minutes, Δt: 8.041 seconds, max(|w|) = 9.1e-02 ms⁻¹, wall time: 1.544 minutes
Iteration: 0260, time: 33.412 minutes, Δt: 8.474 seconds, max(|w|) = 7.0e-02 ms⁻¹, wall time: 1.652 minutes
Iteration: 0280, time: 35.873 minutes, Δt: 8.997 seconds, max(|w|) = 5.9e-02 ms⁻¹, wall time: 1.761 minutes
Iteration: 0300, time: 38.766 minutes, Δt: 9.388 seconds, max(|w|) = 6.3e-02 ms⁻¹, wall time: 1.866 minutes
[ Info: Simulation is stopping after running for 2.052 minutes.
[ Info: Simulation time 40 minutes equals or exceeds stop time 40 minutes.
```

### Using this PR
```Julia
julia> include("ocean_wind_mixing_and_convection.jl")
[ Info: Initializing simulation...
Iteration: 0000, time: 0 seconds, Δt: 11 seconds, max(|w|) = 1.0e-05 ms⁻¹, wall time: 0 seconds
[ Info:     ... simulation initialization complete (2.042 seconds)
[ Info: Executing initial time step...
[ Info:     ... initial time step complete (15.933 seconds).
Iteration: 0020, time: 3.403 minutes, Δt: 13.310 seconds, max(|w|) = 8.0e-06 ms⁻¹, wall time: 18.398 seconds
Iteration: 0040, time: 7.488 minutes, Δt: 16.105 seconds, max(|w|) = 6.0e-06 ms⁻¹, wall time: 18.752 seconds
Iteration: 0060, time: 12 minutes, Δt: 10.350 seconds, max(|w|) = 1.2e-05 ms⁻¹, wall time: 19.105 seconds
Iteration: 0080, time: 15 minutes, Δt: 8.284 seconds, max(|w|) = 4.8e-05 ms⁻¹, wall time: 19.541 seconds
Iteration: 0100, time: 17.509 minutes, Δt: 7.101 seconds, max(|w|) = 1.3e-04 ms⁻¹, wall time: 19.889 seconds
Iteration: 0120, time: 19.557 minutes, Δt: 6.359 seconds, max(|w|) = 6.3e-04 ms⁻¹, wall time: 20.244 seconds
Iteration: 0140, time: 21.504 minutes, Δt: 5.734 seconds, max(|w|) = 3.8e-03 ms⁻¹, wall time: 20.680 seconds
Iteration: 0160, time: 23.276 minutes, Δt: 5.325 seconds, max(|w|) = 1.4e-02 ms⁻¹, wall time: 21.026 seconds
Iteration: 0180, time: 24.959 minutes, Δt: 5.372 seconds, max(|w|) = 3.9e-02 ms⁻¹, wall time: 21.370 seconds
Iteration: 0200, time: 26.677 minutes, Δt: 6.354 seconds, max(|w|) = 7.1e-02 ms⁻¹, wall time: 21.800 seconds
Iteration: 0220, time: 28.672 minutes, Δt: 7.391 seconds, max(|w|) = 8.6e-02 ms⁻¹, wall time: 22.149 seconds
Iteration: 0240, time: 31 minutes, Δt: 8.598 seconds, max(|w|) = 8.4e-02 ms⁻¹, wall time: 22.498 seconds
Iteration: 0260, time: 33.878 minutes, Δt: 9.101 seconds, max(|w|) = 6.1e-02 ms⁻¹, wall time: 22.933 seconds
Iteration: 0280, time: 36.770 minutes, Δt: 8.891 seconds, max(|w|) = 6.2e-02 ms⁻¹, wall time: 23.287 seconds
Iteration: 0300, time: 39.637 minutes, Δt: 9.291 seconds, max(|w|) = 4.9e-02 ms⁻¹, wall time: 23.640 seconds
[ Info: Simulation is stopping after running for 23.692 seconds.
[ Info: Simulation time 40 minutes equals or exceeds stop time 40 minutes.
```

### using Oceananigans v0.79.2 (with KernelAbstractions v0.7.2)
```Julia
julia> include("ocean_wind_mixing_and_convection.jl")
[ Info: Precompiling CairoMakie [13f3f980-e62b-5c42-98c6-ff1f3baf88f0]
[ Info: Oceananigans will use 6 threads
[ Info: Initializing simulation...
Iteration: 0000, time: 0 seconds, Δt: 11 seconds, max(|w|) = 1.0e-05 ms⁻¹, wall time: 0 seconds
[ Info:     ... simulation initialization complete (5.240 seconds)
[ Info: Executing initial time step...
[ Info:     ... initial time step complete (46.825 seconds).
Iteration: 0020, time: 3.403 minutes, Δt: 13.310 seconds, max(|w|) = 8.4e-06 ms⁻¹, wall time: 52.487 seconds
Iteration: 0040, time: 7.488 minutes, Δt: 16.105 seconds, max(|w|) = 5.8e-06 ms⁻¹, wall time: 52.987 seconds
Iteration: 0060, time: 12 minutes, Δt: 10.350 seconds, max(|w|) = 1.6e-05 ms⁻¹, wall time: 53.334 seconds
Iteration: 0080, time: 15 minutes, Δt: 8.284 seconds, max(|w|) = 3.8e-05 ms⁻¹, wall time: 53.685 seconds
Iteration: 0100, time: 17.509 minutes, Δt: 7.100 seconds, max(|w|) = 1.7e-04 ms⁻¹, wall time: 54.035 seconds
Iteration: 0120, time: 19.669 minutes, Δt: 6.321 seconds, max(|w|) = 9.0e-04 ms⁻¹, wall time: 54.549 seconds
Iteration: 0140, time: 21.602 minutes, Δt: 5.748 seconds, max(|w|) = 4.9e-03 ms⁻¹, wall time: 54.895 seconds
Iteration: 0160, time: 23.370 minutes, Δt: 5.313 seconds, max(|w|) = 1.7e-02 ms⁻¹, wall time: 55.244 seconds
Iteration: 0180, time: 25 minutes, Δt: 5.172 seconds, max(|w|) = 3.6e-02 ms⁻¹, wall time: 55.592 seconds
Iteration: 0200, time: 26.737 minutes, Δt: 5.996 seconds, max(|w|) = 7.7e-02 ms⁻¹, wall time: 56.116 seconds
Iteration: 0220, time: 28.705 minutes, Δt: 6.649 seconds, max(|w|) = 8.4e-02 ms⁻¹, wall time: 56.467 seconds
Iteration: 0240, time: 30.929 minutes, Δt: 7.464 seconds, max(|w|) = 7.1e-02 ms⁻¹, wall time: 56.822 seconds
Iteration: 0260, time: 33.261 minutes, Δt: 8.024 seconds, max(|w|) = 7.9e-02 ms⁻¹, wall time: 57.178 seconds
Iteration: 0280, time: 35.866 minutes, Δt: 8.694 seconds, max(|w|) = 7.1e-02 ms⁻¹, wall time: 57.860 seconds
Iteration: 0300, time: 38.732 minutes, Δt: 8.671 seconds, max(|w|) = 5.8e-02 ms⁻¹, wall time: 58.212 seconds
[ Info: Simulation is stopping after running for 58.372 seconds.
[ Info: Simulation time 40 minutes equals or exceeds stop time 40 minutes.
```

all seem the same??

**Comment by glwagner** [comment]
They don't seem the same at all --- this PR is way faster? It'd be easier if we printed the differential wall time tho

**Comment by glwagner** [comment]
I think there's some stuff still to do for the hydrostatic model on this PR but not sure what

**Comment by navidcy** [comment]
can we please wait for https://github.com/CliMA/Oceananigans.jl/pull/2991 ?

**Comment by navidcy** [comment]
I've been struggling to merge that for days.....

**Comment by simone-silvestri** [comment]
hmmm weird that non-hydrostatic is way faster and hydrostatic is similar/slower than 0.79.2

**Comment by navidcy** [comment]
Damn, I'm silly!! I was looking at Δt which IS the same!!

**Comment by glwagner** [comment]
I'm cautiously optimistic that we'll get a big speed up... just have to figure out the final touches for hydrostatic model

**Comment by glwagner** [comment]
Here's a simple hydrostatic model benchmark

```julia
using Oceananigans
using BenchmarkTools

grid = RectilinearGrid(CPU(), size=(128, 128, 1), x=(0, 2π), y=(0, 2π), z=(0, 1), topology=(Periodic, Periodic, Bounded))
model = HydrostaticFreeSurfaceModel(; grid, momentum_advection=WENO(), tracer_advection=WENO())
ϵ(x, y, z) = 2rand() - 1
set!(model, u=ϵ, v=ϵ)

function lots_of_steps!(model, Δt, steps=100)
    for _ = 1:steps
        time_step!(model, Δt)
    end
end

@btime lots_of_steps!(model, 0.01)
```

Results

```julia
10.220 s (85845109 allocations: 37.94 GiB) # this PR
6.284 s (66184308 allocations: 16.31 GiB) # this PR with KA downgraded to 0.7.2
```

So we are close but not there yet.

What about solvers ... ?

**Comment by glwagner** [comment]
> hmmm weird that non-hydrostatic is way faster and hydrostatic is similar/slower than 0.79.2

Actually looking more closely at the results, it's only the compile time that is improved. The run time is the same for both. Nevertheless that is a big improvement and _should_ help docs a lot.

**Comment by navidcy** [comment]
shall we merge? or investigate more?

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
I'll merge! And we can investigate more if we think it's needed?

**Comment by navidcy** [comment]
Damn sorry! I didn't see all these comments @glwagner

**Comment by navidcy** [comment]
Let me reopen the issue

**Comment by navidcy** [comment]
We can undo the merging by `git reset --hard ae12376d1e31128e2e17e6b9447e75d37510e550`?

**Pull request merged**
