### PR TITLE
Convergence test for advection schemes in shallow water 

### PR DESCRIPTION
**Pull request by francispoulin**
This PR creates a new script that computes the convergence rates for all of the advection schemes and plots them together in one figure, which is doing what #1276 tried to do.

The output is a figure and the following:
```
Results are for the L1-norm:

Method = CenteredSecondOrder(), Rate of Convergence = 1.99, Expected = 2
Method = UpwindBiasedThirdOrder(), Rate of Convergence = 2.99, Expected = 3
Method = CenteredFourthOrder(), Rate of Convergence = 3.98, Expected = 4
Method = UpwindBiasedFifthOrder(), Rate of Convergence = 4.97, Expected = 5
Method = WENO5(), Rate of Convergence = 5.00, Expected = 5
``` 

convergence_rates

The rates are very, very close to the theory.

Questions:

- Can someone help me align the output so that Rate of Convergence appears in the same location?
- Any suggestions on how to improve the plot?
- I needed to add Polynomials to do this.  Any problems with adding this to the Manifest?

Next Steps:

@ali-ramadhan suggested using this to validate new advection schemes, and I think it's a good idea.  Things we could do next include,

- [ ] First order upwinding
- [ ] Sixth order center differencing
- [ ] Nth-order WENO

### CODE REVIEW

**Comment by glwagner** [comment]
`@sprintf` / `@printf` formatters allow right-padding with the syntax `% 123s`, where `123` is the number of spaces. for example:

```julia
julia> a = "hi"
"hi"

julia> b = "bye"
"bye"

julia> c = "yeah sure"
"yeah sure"

julia> @printf("a: % 12s\nb: % 12s\nc: % 12s", a, b, c)
a:           hi
b:          bye
c:    yeah sure
```

Other points:

* The plot looks great!
* I would suggest just merging this plot and working on new advection schemes in another PR.
* You can let a validation script depend on `Polynomials` without adding `Polynomials` to the Oceananigans `Project.toml`. There's a few other validation scripts that depend on random packages that are not a part of Oceananigans.
* This PR also adds a bunch of new examples that are variants on the Bickley jet. Probably not intended?

**Comment by ali-ramadhan** [comment]
Definitely looks good! I guess it belongs more in `validation/`?

We can eventually run it as part of the validation pipeline to generate the plot every night and make sure everything still converges.

Also noticed that `examples/Inertial_Instability_2D_old.mp4` was somehow included in this PR (I thought `*.mp4` was in `.gitignore`). I think we'll want to remove it then make sure to "squash and merge" this PR so the mp4 file doesn't enter git history (and increase the repo size).

**Comment by francispoulin** [comment]
Thanks for the feedback.  

First, I used the formatting to get nicer output,
```
Method =    CenteredSecondOrder(), Rate of Convergence = 1.99, Expected = 2 
Method = UpwindBiasedThirdOrder(), Rate of Convergence = 2.99, Expected = 3 
Method =    CenteredFourthOrder(), Rate of Convergence = 3.98, Expected = 4 
Method = UpwindBiasedFifthOrder(), Rate of Convergence = 4.97, Expected = 5 
Method =                  WENO5(), Rate of Convergence = 5.00, Expected = 5 
```

Second, sorry about the extra files. I will probably close this and create a new one rather than having a bunch of commits, as that will be cleaner.  I presume that's the preferred option?

Third, can you point me to another validation experiment that uses a library not in the library?

Fourth, I won't do any other advection schemes for this PR.

Fifth, I will move this into the validation folder and chane the name of the files appropriately.

**Comment by glwagner** [comment]
This script has `using GLMakie` at the top:

https://github.com/CliMA/Oceananigans.jl/blob/master/validation/lat_lon_barotropic_turbulence/visualize.jl

**Pull request closed without merging**
