### PR TITLE
Change Cartesian -> rectilinear

### LINKED ISSUE #1377: Our grids are usually not Cartesian
According to [wikipedia](https://en.wikipedia.org/wiki/Regular_grid), we have been using the term "Cartesian" incorrectly, since "Cartesian" only applies to coordinate systems with unit areas and volumes:

> A Cartesian grid is a special case where the elements are unit squares or unit cubes, and the vertices are points on the integer lattice.

Thus "RegularCartesianGrid" should really be called RegularRectilinearGrid and "VerticallyStretchedCartesianGrid" should be called VerticallyStretchedRectilinearGrid (in the latter case, horizontal regularity is implicit).

### PR DESCRIPTION
**Pull request by navidcy**
This PR changes "Cartesian" to "rectilinear" to comply with widely used conventions.

According to wikipedia:
> A Cartesian grid is a special case where the elements are unit squares or unit cubes, and the vertices are points on the integer lattice.

Closes  #1377

(This PR came to replace #1386. Resolving merge conflicts in #1386 was a mess so I decided to create a new PR.)

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Happy to approve this if there's unanimous consent.

I guess we should tag v0.50.0 with this PR and get the pain of breaking changes out of the way?

Out of paranoia I'm also running the convergence tests manually for this PR manually: https://buildkite.com/clima/oceananigans-validation-experiments/builds/128

**Review by glwagner — APPROVED** [review]

**Comment by ali-ramadhan** [comment]
@navidcy Do you want to bump v0.50.0?

Might be good to merge ASAP too before merging other PRs leads to merge conflict hell...

**Comment by glwagner** [comment]
conflict hell is imminent.

**Comment by glwagner** [comment]
Conflicts 😱

**Comment by navidcy** [comment]
> Conflicts 😱

I’ll deconflict them

**Comment by navidcy** [comment]
@ali-ramadhan, @glwagner, @francispoulin, @tomchor: please hold on merging anything else until I merge this. Will do so as soon as tests pass!

**Comment by ali-ramadhan** [comment]
Ah I think you added `sandbox/vertically_stretched_plankton.jl` back in when we meant to keep it nuked but we can worry about it after this PR is merged.

**Comment by navidcy** [comment]
@ali-ramadhan, should we re-run the validation tests?

**Comment by navidcy** [comment]
> Ah I think you added `sandbox/vertically_stretched_plankton.jl` back in when we meant to keep it nuked but we can worry about it after this PR is merged.

I was also puzzled why that happened. I just pulled master and then `git merge master`...

**Comment by ali-ramadhan** [comment]
> @ali-ramadhan, should we re-run the validation tests?

I'm sure they're fine. They passed earlier today: https://buildkite.com/clima/oceananigans-validation-experiments/builds/128

They take a while to run. And we'll know tomorrow morning if they fail! They're set to run nightly at 3pm ET.

**Pull request merged**
