### PR TITLE
New benchmarking framework

### LINKED ISSUE #1088: More powerful and elegant benchmarking framework
Using `BenchmarkGroup` from BenchmarkTools.jl, DataFrames.jl, and PrettyTables.jl we can develop a more powerful and elegant benchmarking framework, allowing us to easily perform more benchmarks and compare them.

`BenchmarkGroup` is serializable so we can use BSON.jl or JLD2.jl to save multiple benchmarks or suites of benchmarks to disk and collect them afterwards. This would allow us to automate multi-threading benchmarks and run benchmarks for large models that almost fill memory (GPU garbage collection doesn't always seem to free memory in these cases?).

Using `BenchmarkGroup` will also allow us to automate benchmarking between branches so we can easily discover performance regressions. Right now I do this manually.

Here is a crude first working example: https://github.com/CliMA/Oceananigans.jl/blob/fd6e173042497464d78e4f03f4e850f55171c74a/compressible/benchmarks/benchmark_compressible_model.jl

### PR DESCRIPTION
**Pull request by ali-ramadhan**
This PR rewrites how we do benchmarking so it's easier to analyze, visualize, and compare benchmark results. It's also easier to add new benchmarks. And we have automated multithreading benchmarks (we can approach MPI benchmarking in a similar manner).

We used to use TimerOutputs.jl for benchmarking but really it's made more for profiling. This PR
1. switches to using the `BenchmarkGroup` from BenchmarkTools.jl which makes it easy to compare benchmarks (e.g. check for CPU -> GPU performance and for performance relative to a base case).
2. Dataframes.jl and PrettyTables.jl are used to visualize benchmarks, which are prettier, and you can output HTML tables that can be easily embedded into documentation.
3. PkgBenchmark.jl allows use to compare benchmarks between two commits or branches (right now only via `benchmark_regression.jl`) which should make it easy to automate checking for performance regressions between PRs and the master branch.

The next big step for benchmarking would be to create a Buildkite benchmarks pipeline that can be triggered via GitHub comments (this would involve looking into https://github.com/buildkite/trigger-pipeline-action).

I started embedding HTML tables into the docs but it's going to be hard for users to parse tables full of numbers. Plots and bar graphs might be much more useful here, but this might require a Buildkite pipeline to generate the figures to embed into the documentation. So I'll leave this important step for a different PR.

I also want to add a script that generates a better version of the benchmark plots in the README, but this might have to wait for a future PR.

It's a little rough around the edges but I think it's polished enough to be considered for merging. Feels like benchmarks share a lot of boilerplate but might try to reduce it in a future PR.

Some fun benchmarking facts:
* GPU models using WENO-5 are 250x faster than CPU models using WENO-5!
* TEOS-10 slows down your CPU model by ~30%, but only ~3% for GPU models!
* 2D Leith is most expensive closure.

Resolves #1088

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
# Some selected benchmark results

## Advection scheme benchmarks

<table>
  <caption style = "text-align: center; ">Advection schemes relative performance (CPU)</caption>
  <tr class = "header headerLastRow">
    <th style = "text-align: right; ">Architectures</th>
    <th style = "text-align: right; ">Schemes</th>
    <th style = "text-align: right; ">slowdown</th>
    <th style = "text-align: right; ">memory</th>
    <th style = "text-align: right; ">allocs</th>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">CenteredFourthOrder</td>
    <td style = "text-align: right; ">2.68376</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">CenteredSecondOrder</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">UpwindBiasedFifthOrder</td>
    <td style = "text-align: right; ">3.19781</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">UpwindBiasedThirdOrder</td>
    <td style = "text-align: right; ">2.84754</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">WENO5</td>
    <td style = "text-align: right; ">8.25962</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
</table>

<table>
  <caption style = "text-align: center; ">Advection schemes relative performance (GPU)</caption>
  <tr class = "header headerLastRow">
    <th style = "text-align: right; ">Architectures</th>
    <th style = "text-align: right; ">Schemes</th>
    <th style = "text-align: right; ">slowdown</th>
    <th style = "text-align: right; ">memory</th>
    <th style = "text-align: right; ">allocs</th>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">CenteredFourthOrder</td>
    <td style = "text-align: right; ">1.67825</td>
    <td style = "text-align: right; ">1.02677</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">CenteredSecondOrder</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">UpwindBiasedFifthOrder</td>
    <td style = "text-align: right; ">2.05742</td>
    <td style = "text-align: right; ">1.02812</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">UpwindBiasedThirdOrder</td>
    <td style = "text-align: right; ">1.47568</td>
    <td style = "text-align: right; ">1.02677</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">WENO5</td>
    <td style = "text-align: right; ">3.04361</td>
    <td style = "text-align: right; ">1.02812</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
</table>

## Arbitrary tracers benchmarks

<table>
  <caption style = "text-align: center; ">Arbitrary tracers relative performance (CPU)</caption>
  <tr class = "header headerLastRow">
    <th style = "text-align: right; ">Architectures</th>
    <th style = "text-align: right; ">Ns</th>
    <th style = "text-align: right; ">tracers</th>
    <th style = "text-align: right; ">slowdown</th>
    <th style = "text-align: right; ">memory</th>
    <th style = "text-align: right; ">allocs</th>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(0, 0)</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(0, 1)</td>
    <td style = "text-align: right; ">1.19815</td>
    <td style = "text-align: right; ">1.18011</td>
    <td style = "text-align: right; ">1.1898</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(0, 2)</td>
    <td style = "text-align: right; ">1.36597</td>
    <td style = "text-align: right; ">1.43581</td>
    <td style = "text-align: right; ">1.4021</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(1, 0)</td>
    <td style = "text-align: right; ">1.2004</td>
    <td style = "text-align: right; ">1.18011</td>
    <td style = "text-align: right; ">1.1898</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(2, 0)</td>
    <td style = "text-align: right; ">1.38267</td>
    <td style = "text-align: right; ">1.43688</td>
    <td style = "text-align: right; ">1.40735</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(2, 10)</td>
    <td style = "text-align: right; ">3.02528</td>
    <td style = "text-align: right; ">4.0899</td>
    <td style = "text-align: right; ">5.05926</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(2, 3)</td>
    <td style = "text-align: right; ">1.87883</td>
    <td style = "text-align: right; ">2.18814</td>
    <td style = "text-align: right; ">2.50863</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(2, 5)</td>
    <td style = "text-align: right; ">2.20522</td>
    <td style = "text-align: right; ">2.70298</td>
    <td style = "text-align: right; ">3.16129</td>
  </tr>
</table>

<table>
  <caption style = "text-align: center; ">Arbitrary tracers relative performance (GPU)</caption>
  <tr class = "header headerLastRow">
    <th style = "text-align: right; ">Architectures</th>
    <th style = "text-align: right; ">Ns</th>
    <th style = "text-align: right; ">tracers</th>
    <th style = "text-align: right; ">slowdown</th>
    <th style = "text-align: right; ">memory</th>
    <th style = "text-align: right; ">allocs</th>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(0, 0)</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(0, 1)</td>
    <td style = "text-align: right; ">1.10818</td>
    <td style = "text-align: right; ">1.19745</td>
    <td style = "text-align: right; ">1.16449</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(0, 2)</td>
    <td style = "text-align: right; ">1.23007</td>
    <td style = "text-align: right; ">1.43936</td>
    <td style = "text-align: right; ">1.34169</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(1, 0)</td>
    <td style = "text-align: right; ">1.13209</td>
    <td style = "text-align: right; ">1.19775</td>
    <td style = "text-align: right; ">1.1659</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(2, 0)</td>
    <td style = "text-align: right; ">1.23935</td>
    <td style = "text-align: right; ">1.44093</td>
    <td style = "text-align: right; ">1.34475</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(2, 10)</td>
    <td style = "text-align: right; ">2.77406</td>
    <td style = "text-align: right; ">4.30545</td>
    <td style = "text-align: right; ">3.30755</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(2, 3)</td>
    <td style = "text-align: right; ">1.68306</td>
    <td style = "text-align: right; ">2.25033</td>
    <td style = "text-align: right; ">1.96409</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">(2, 5)</td>
    <td style = "text-align: right; ">1.98803</td>
    <td style = "text-align: right; ">2.79892</td>
    <td style = "text-align: right; ">2.35453</td>
  </tr>
</table>

## Equation of state benchmarks

<table>
  <caption style = "text-align: center; ">Equation of state relative performance (CPU)</caption>
  <tr class = "header headerLastRow">
    <th style = "text-align: right; ">Architectures</th>
    <th style = "text-align: right; ">EquationsOfState</th>
    <th style = "text-align: right; ">slowdown</th>
    <th style = "text-align: right; ">memory</th>
    <th style = "text-align: right; ">allocs</th>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">LinearEquationOfState</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">RoquetEquationOfState</td>
    <td style = "text-align: right; ">1.14378</td>
    <td style = "text-align: right; ">1.00266</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">TEOS10EquationOfState</td>
    <td style = "text-align: right; ">1.32274</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
</table>

<table>
  <caption style = "text-align: center; ">Equation of state relative performance (GPU)</caption>
  <tr class = "header headerLastRow">
    <th style = "text-align: right; ">Architectures</th>
    <th style = "text-align: right; ">EquationsOfState</th>
    <th style = "text-align: right; ">slowdown</th>
    <th style = "text-align: right; ">memory</th>
    <th style = "text-align: right; ">allocs</th>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">LinearEquationOfState</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">RoquetEquationOfState</td>
    <td style = "text-align: right; ">1.00497</td>
    <td style = "text-align: right; ">1.00222</td>
    <td style = "text-align: right; ">1.00018</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">TEOS10EquationOfState</td>
    <td style = "text-align: right; ">1.02813</td>
    <td style = "text-align: right; ">0.999823</td>
    <td style = "text-align: right; ">1.00018</td>
  </tr>
</table>

## Static ocean benchmarks

<table>
  <caption style = "text-align: center; ">Incompressible model CPU -> GPU speedup</caption>
  <tr class = "header headerLastRow">
    <th style = "text-align: right; ">Float_types</th>
    <th style = "text-align: right; ">Ns</th>
    <th style = "text-align: right; ">speedup</th>
    <th style = "text-align: right; ">memory</th>
    <th style = "text-align: right; ">allocs</th>
  </tr>
  <tr>
    <td style = "text-align: right; ">Float32</td>
    <td style = "text-align: right; ">32</td>
    <td style = "text-align: right; ">2.32184</td>
    <td style = "text-align: right; ">2.64782</td>
    <td style = "text-align: right; ">3.5709</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">Float32</td>
    <td style = "text-align: right; ">64</td>
    <td style = "text-align: right; ">13.7668</td>
    <td style = "text-align: right; ">2.81205</td>
    <td style = "text-align: right; ">3.56876</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">Float32</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">85.6191</td>
    <td style = "text-align: right; ">3.16384</td>
    <td style = "text-align: right; ">3.57836</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">Float32</td>
    <td style = "text-align: right; ">256</td>
    <td style = "text-align: right; ">113.908</td>
    <td style = "text-align: right; ">3.8535</td>
    <td style = "text-align: right; ">3.5677</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">Float64</td>
    <td style = "text-align: right; ">32</td>
    <td style = "text-align: right; ">2.43102</td>
    <td style = "text-align: right; ">2.4664</td>
    <td style = "text-align: right; ">3.5677</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">Float64</td>
    <td style = "text-align: right; ">64</td>
    <td style = "text-align: right; ">14.9961</td>
    <td style = "text-align: right; ">2.60208</td>
    <td style = "text-align: right; ">3.56557</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">Float64</td>
    <td style = "text-align: right; ">128</td>
    <td style = "text-align: right; ">79.6534</td>
    <td style = "text-align: right; ">2.89207</td>
    <td style = "text-align: right; ">3.56876</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">Float64</td>
    <td style = "text-align: right; ">256</td>
    <td style = "text-align: right; ">108.399</td>
    <td style = "text-align: right; ">3.46246</td>
    <td style = "text-align: right; ">3.5645</td>
  </tr>
</table>

## Topologies benchmarks

<table>
  <caption style = "text-align: center; ">Topologies relative performance (CPU)</caption>
  <tr class = "header headerLastRow">
    <th style = "text-align: right; ">Architectures</th>
    <th style = "text-align: right; ">Ns</th>
    <th style = "text-align: right; ">Topologies</th>
    <th style = "text-align: right; ">slowdown</th>
    <th style = "text-align: right; ">memory</th>
    <th style = "text-align: right; ">allocs</th>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">192</td>
    <td style = "text-align: right; ">(Periodic, Bounded, Bounded)</td>
    <td style = "text-align: right; ">1.26896</td>
    <td style = "text-align: right; ">1.27649</td>
    <td style = "text-align: right; ">1.37815</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">192</td>
    <td style = "text-align: right; ">(Periodic, Periodic, Bounded)</td>
    <td style = "text-align: right; ">1.10985</td>
    <td style = "text-align: right; ">1.12536</td>
    <td style = "text-align: right; ">1.12605</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">192</td>
    <td style = "text-align: right; ">(Periodic, Periodic, Periodic)</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
</table>

<table>
  <caption style = "text-align: center; ">Topologies relative performance (GPU)</caption>
  <tr class = "header headerLastRow">
    <th style = "text-align: right; ">Architectures</th>
    <th style = "text-align: right; ">Ns</th>
    <th style = "text-align: right; ">Topologies</th>
    <th style = "text-align: right; ">slowdown</th>
    <th style = "text-align: right; ">memory</th>
    <th style = "text-align: right; ">allocs</th>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">192</td>
    <td style = "text-align: right; ">(Periodic, Bounded, Bounded)</td>
    <td style = "text-align: right; ">2.67701</td>
    <td style = "text-align: right; ">1.31634</td>
    <td style = "text-align: right; ">1.36185</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">192</td>
    <td style = "text-align: right; ">(Periodic, Periodic, Bounded)</td>
    <td style = "text-align: right; ">1.10911</td>
    <td style = "text-align: right; ">1.1314</td>
    <td style = "text-align: right; ">1.13269</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">192</td>
    <td style = "text-align: right; ">(Periodic, Periodic, Periodic)</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
</table>

## Turbulence closure benchmarks

<table>
  <caption style = "text-align: center; ">Turbulence closures relative performance (CPU)</caption>
  <tr class = "header headerLastRow">
    <th style = "text-align: right; ">Architectures</th>
    <th style = "text-align: right; ">Closures</th>
    <th style = "text-align: right; ">slowdown</th>
    <th style = "text-align: right; ">memory</th>
    <th style = "text-align: right; ">allocs</th>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">AnisotropicBiharmonicDiffusivity</td>
    <td style = "text-align: right; ">2.05198</td>
    <td style = "text-align: right; ">1.00469</td>
    <td style = "text-align: right; ">1.00536</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">AnisotropicDiffusivity</td>
    <td style = "text-align: right; ">1.16121</td>
    <td style = "text-align: right; ">1.00469</td>
    <td style = "text-align: right; ">1.00536</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">IsotropicDiffusivity</td>
    <td style = "text-align: right; ">1.16634</td>
    <td style = "text-align: right; ">1.00139</td>
    <td style = "text-align: right; ">1.00536</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">Nothing</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">SmagorinskyLilly</td>
    <td style = "text-align: right; ">1.81978</td>
    <td style = "text-align: right; ">1.06441</td>
    <td style = "text-align: right; ">1.07824</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">TwoDimensionalLeith</td>
    <td style = "text-align: right; ">2.52298</td>
    <td style = "text-align: right; ">1.06287</td>
    <td style = "text-align: right; ">1.07824</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">CPU</td>
    <td style = "text-align: right; ">VerstappenAnisotropicMinimumDissipation</td>
    <td style = "text-align: right; ">1.821</td>
    <td style = "text-align: right; ">1.16951</td>
    <td style = "text-align: right; ">1.20525</td>
  </tr>
</table>

<table>
  <caption style = "text-align: center; ">Turbulence closures relative performance (GPU)</caption>
  <tr class = "header headerLastRow">
    <th style = "text-align: right; ">Architectures</th>
    <th style = "text-align: right; ">Closures</th>
    <th style = "text-align: right; ">slowdown</th>
    <th style = "text-align: right; ">memory</th>
    <th style = "text-align: right; ">allocs</th>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">AnisotropicBiharmonicDiffusivity</td>
    <td style = "text-align: right; ">1.61022</td>
    <td style = "text-align: right; ">1.0052</td>
    <td style = "text-align: right; ">1.00149</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">AnisotropicDiffusivity</td>
    <td style = "text-align: right; ">1.05231</td>
    <td style = "text-align: right; ">1.00498</td>
    <td style = "text-align: right; ">1.00044</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">IsotropicDiffusivity</td>
    <td style = "text-align: right; ">1.04851</td>
    <td style = "text-align: right; ">1.00122</td>
    <td style = "text-align: right; ">1.00009</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">Nothing</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
    <td style = "text-align: right; ">1.0</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">SmagorinskyLilly</td>
    <td style = "text-align: right; ">1.54132</td>
    <td style = "text-align: right; ">1.0719</td>
    <td style = "text-align: right; ">1.08389</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">TwoDimensionalLeith</td>
    <td style = "text-align: right; ">2.28276</td>
    <td style = "text-align: right; ">1.07022</td>
    <td style = "text-align: right; ">1.08389</td>
  </tr>
  <tr>
    <td style = "text-align: right; ">GPU</td>
    <td style = "text-align: right; ">VerstappenAnisotropicMinimumDissipation</td>
    <td style = "text-align: right; ">1.70008</td>
    <td style = "text-align: right; ">1.19835</td>
    <td style = "text-align: right; ">1.24028</td>
  </tr>
</table>

**Comment by navidcy** [comment]
`Topologies benchmarks` --> Add `(Bounded, Bounded, Bounded)` for CPU, no?

**Comment by ali-ramadhan** [comment]
> `Topologies benchmarks` --> Add `(Bounded, Bounded, Bounded)` for CPU, no?

Yeah that would probably make sense but then the code would fail when trying to compare CPU and GPU results for the same topologies (to calculate a CPU -> GPU speedup):

https://github.com/CliMA/Oceananigans.jl/blob/55b6743dffd8d45040d6a677c2dfecaaf35f6a23/benchmark/benchmark_topologies.jl#L37-L41

I thought about adding some logic to ignore cases that aren't common to both the CPU and GPU benchmark suites but then thought it would be better to just resolve #1007 haha

**Review by glwagner — APPROVED** [review]
Sweet. Does it make sense to add a README to `benchmarks/` that explains how to run them?

**Comment by glwagner** [comment]
This info is so helpful. Thanks @ali-ramadhan .

**Comment by ali-ramadhan** [comment]
Good catch! Added a `README.md` generally describing the benchmarks and with instructions on how to instantiate and run benchmarks scripts.

**Pull request merged**
