### PR TITLE
Set `-O0` when testing

### LINKED ISSUE #1076: Use `-O1` or even `-O0` to reduce compile time for faster testing?
This significantly reduced the time to first plot for Plots.jl: https://github.com/JuliaPlots/Plots.jl/pull/2544

I guess the idea is we don't care about performance when running our tests. Most of the time is spent compiling so if we can reduce compile time (at the cost of having sub-optimal code) then our tests will run faster.

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Resolves #1076

### CODE REVIEW

**Review by glwagner — APPROVED** [review]

**Comment by glwagner** [comment]
Might be better to use `-O1` according to Jeff's comments: https://github.com/JuliaPlots/Plots.jl/pull/2544 but it's not a big deal...

**Comment by ali-ramadhan** [comment]
Yeah I saw that comment. My understanding is that `-O1` is a good compromise between performance and latency but in our case we just want to reduce latency as performance during testing doesn't matter. But I guess `-O0` didn't really do much. Perhaps the optimizations (might only be in Julia 1.6+) mostly affect compilation when loading/importing packages.

Should we still consider merging this? Once tests run I can do a comparison to see how many minutes (or seconds?) `-O0` saves us?

**Comment by glwagner** [comment]
> as performance during testing doesn't matter

We do have a small number of tests that might benefit from faster code, like the pressure solver convergence tests? 

> Should we still consider merging this? Once tests run I can do a comparison to see how many minutes (or seconds?) `-O0` saves us?

If it doesn't slow the tests down, I'm happy to merge and we can consider changing the optimization level in the future if its warranted. I think being explicit and deliberate about it is a positive change.

**Comment by ali-ramadhan** [comment]
> If it doesn't slow the tests down, I'm happy to merge and we can consider changing the optimization level in the future if its warranted. I think being explicit and deliberate about it is a positive change.

Looks like this makes a significant difference as the latest build on this PR took 25 minutes 1 second (https://buildkite.com/clima/oceananigans/builds/333).

Previous 3 builds (which all passed) took 32~33 minutes:
https://buildkite.com/clima/oceananigans/builds/330
https://buildkite.com/clima/oceananigans/builds/331
https://buildkite.com/clima/oceananigans/builds/332

> We do have a small number of tests that might benefit from faster code, like the pressure solver convergence tests?

Yes but pressure solver FFTs go through the FFTW C library where the `julia -O` flag doesn't affect performance. If we want some performance optimization for specific test sets we can do that, e.g. `-O2` on unit tests.

**Pull request merged**
