### PR TITLE
Update CATKE numerics and implement MEWSVerticalDiffusivity for mesoscale interfacial form stress

### PR DESCRIPTION
**Pull request by glwagner**

### CODE REVIEW

**Comment by navidcy** [comment]
[7f07b3a](https://github.com/CliMA/Oceananigans.jl/pull/2864/commits/7f07b3aa9947f167d73858b63e844a674b433b97) -> 🐈

**Comment by navidcy** [comment]
Perhaps split out a PR with just CATKE update + a validation script that runs in 3D? Might make things quicker?

**Comment by glwagner** [comment]
We don't need MEWS to work perfectly to merge this

**Comment by glwagner** [comment]
We can merge now / soon if we like?

**Comment by glwagner** [comment]
MEWS in action

https://user-images.githubusercontent.com/15271942/211849199-0be004d5-ec9d-45e1-bfc4-c6203e877564.mp4

**Comment by navidcy** [comment]
Yeah. Something broke in the tests?

**Comment by glwagner** [comment]
Something about closure tuples, but not sure why that happened. I'll fix it.

**Comment by navidcy** [comment]
Can you have a look/review?

**Comment by glwagner** [comment]
happy to merge this whenever. there's a few experimental things in there but we can add tests later

**Review by simone-silvestri — APPROVED** [review]

**Pull request merged**
