### PR TITLE
Add Downloads badges on README.md

### PR DESCRIPTION
**Pull request by navidcy**
Is something like this useful? See how they look at https://github.com/CliMA/Oceananigans.jl/tree/ncc/readme-downloads

### CODE REVIEW

**Comment by glwagner** [comment]
Seems nice but what exactly is a "download"? A fork, `Pkg.add("Oceananigans")` or what?

**Comment by navidcy** [comment]
> Seems nice but what exactly is a "download"? A fork, `Pkg.add("Oceananigans")` or what?

I’m not quite sure.

**Comment by glwagner** [comment]
It could be based on this post https://discourse.julialang.org/t/announcing-package-download-stats/69073

which means that the number represents the number of unique IP addresses that have downloaded Oceananigans from the julia registry (I think), excluding IP addresses that are suspected to originate from bots / CI. that would mostly be `Pkg.add` I think.

**Review by glwagner — APPROVED** [review]
Might be good just to add a comment somewhere / somehow that explains what it means

**Pull request merged**
