### PR TITLE
Adds GridMetric AbstractOperation

### LINKED ISSUE #1452: Grid metrics and differences as AbstractOperations
It might be useful if grid metrics and differences (`δx`) were provided as abstract operations. For example:

```julia
struct GridMetric{M, G} <: AbstractOperation
    metric :: M
    grid :: G
end

getindex(gm::GridMetric, i, j, k) = gm.metric(i, j, k, grid)
```

We can then define operations for grid spacings and area, which would mean, for example, that an operation computing vertical vorticity could be constructed via

```julia
Δyᶜᶠᵃ = GridMetric(Oceananigans.Operators.Δyᶜᶠᵃ, grid)
Δxᶠᶜᵃ = GridMetric(Oceananigans.Operators.Δyᶠᶜᵃ, grid)
Axᶠᶠᵃ = GridMetric(Oceananigans.Operators.Axᶠᶠᵃ, grid)

Γ = δx(Δyᶜᶠᵃ * v) - δy(Δxᶠᶜᵃ * u)
ζ = Γ / Axᶠᶠᵃ
```

For this we also need

```julia
struct Difference{D} <: AbstractOperation
    δ :: D
    grid :: G
end
```

similar to `Derivative` for partial derivatives with respect to x, y, z.

### PR DESCRIPTION
**Pull request by glwagner**
Resolves #1452 .

Example:

```julia
julia> using Oceananigans

julia> using Oceananigans.AbstractOperations: GridMetric

julia> grid = RegularRectilinearGrid(size=(1, 1, 1), extent=(1, 1, 1))
RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded}
                   domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [-1.0, 0.0]
                 topology: (Periodic, Periodic, Bounded)
  resolution (Nx, Ny, Nz): (1, 1, 1)
   halo size (Hx, Hy, Hz): (1, 1, 1)
grid spacing (Δx, Δy, Δz): (1.0, 1.0, 1.0)

julia> Δz = GridMetric{Center, Center, Center}(Oceananigans.Operators.Δzᵃᵃᶜ, grid)
GridMetric at (Center, Center, Center)
├── grid: RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded}(Nx=1, Ny=1, Nz=1)
│   └── domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [-1.0, 0.0]
└── tree: 
    GridMetric at (Center, Center, Center)

julia> c = CenterField(CPU(), grid)
Field located at (Center, Center, Center)
├── data: OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}, size: (3, 3, 3)
├── grid: RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded}(Nx=1, Ny=1, Nz=1)
└── boundary conditions: x=(west=Periodic, east=Periodic), y=(south=Periodic, north=Periodic), z=(bottom=ZeroFlux, top=ZeroFlux)

julia> c_dz = c * Δz
BinaryOperation at (Center, Center, Center)
├── grid: RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded}(Nx=1, Ny=1, Nz=1)
│   └── domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [-1.0, 0.0]
└── tree: 
    * at (Center, Center, Center)
    ├── Field located at (Center, Center, Center)
    └── GridMetric at (Center, Center, Center)
```

TODO:

- [x] Add `architecture(grid)` for grids other than `RegularRectilinearGrid`.
- [x] Tests
- [x] Explore the possibility of special objects `Δx, Δy, Δz` that infer `BinaryOperation` location and create appropriate `GridMetric` operations at appropriate locations automagically.
- [x] I don't think we need `Difference` as proposed on #1452, but if others disagree we can add them here.

cc @tomchor

### CODE REVIEW

**Comment by glwagner** [comment]
Even better:

```julia
julia> using Oceananigans
[ Info: Precompiling Oceananigans [9e8cae18-63c1-5223-a75c-80ca9d6e9a09]
[ Info: Oceananigans will use 8 threads

julia> grid = RegularRectilinearGrid(size=(1, 1, 1), extent=(2, 2, 2))
RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded}
                   domain: x ∈ [0.0, 2.0], y ∈ [0.0, 2.0], z ∈ [-2.0, 0.0]
                 topology: (Periodic, Periodic, Bounded)
  resolution (Nx, Ny, Nz): (1, 1, 1)
   halo size (Hx, Hy, Hz): (1, 1, 1)
grid spacing (Δx, Δy, Δz): (2.0, 2.0, 2.0)

julia> using Oceananigans.AbstractOperations: Δz

julia> c = CenterField(CPU(), grid)
Field located at (Center, Center, Center)
├── data: OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}, size: (3, 3, 3)
├── grid: RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded}(Nx=1, Ny=1, Nz=1)
└── boundary conditions: x=(west=Periodic, east=Periodic), y=(south=Periodic, north=Periodic), z=(bottom=ZeroFlux, top=ZeroFlux)

julia> c_dz = c * Δz
BinaryOperation at (Center, Center, Center)
├── grid: RegularRectilinearGrid{Float64, Periodic, Periodic, Bounded}(Nx=1, Ny=1, Nz=1)
│   └── domain: x ∈ [0.0, 2.0], y ∈ [0.0, 2.0], z ∈ [-2.0, 0.0]
└── tree: 
    * at (Center, Center, Center)
    ├── Field located at (Center, Center, Center)
    └── GridMetricOperation at (Center, Center, Center)

julia> set!(c, (x, y, z) -> rand())
1×1×1 view(OffsetArray(::Array{Float64,3}, 0:2, 0:2, 0:2), 1:1, 1:1, 1:1) with eltype Float64:
[:, :, 1] =
 0.1308337558599868

julia> c_dz[1, 1, 1]
0.2616675117199736
```

**Review by tomchor — COMMENTED** [review]
Looks good! My only suggestion is a simple docstring with a brief example for the user-facing function

**Comment by glwagner** [comment]
I'm wondering if it might be a bit much to put docstrings on every single `AbstractGridMetric` for this experimental feature? They aren't exported so not user-facing (I think we may end up using this internally only for things like `IntegratedField` down the line). But I can copy paste the PR comment into the docstring for \Delta z as an example. Note that `GridMetricOperation` is used internally only, it's really the instances `\Delta z`, etc that are meant to be combined in `AbstractOperations`.

**Comment by glwagner** [comment]
Scratch that --- I can't actually put a docstring on the instances `\Delta z`. I'll put a docstring on `AbstractGridMetric`. Perhaps that will help.

**Comment by tomchor** [comment]
> I'm wondering if it might be a bit much to put docstrings on every single AbstractGridMetric for this experimental feature? They aren't exported so not user-facing (I think we may end up using this internally only for things like IntegratedField down the line).

Fair point. But internal docstrings also help I think. It's way easier for me to contribute, for example, when the internal functions are well-documented. I think the more we add these, the more likely we are to get contributions from people outside of the regular group, no?

**Comment by glwagner** [comment]
Hmm double scratch, it looks like instances can be doc'd. I'll do that as an experiment.

**Comment by glwagner** [comment]
Docs are good, and so are new features. We have finite time, is all.

**Comment by tomchor** [comment]
> Docs are good, and so are new features. We have finite time, is all.

Well, I will leave it up to you then. Feel free to merge if you think it's ready!

**Comment by glwagner** [comment]
I've added an experimental docstring on \Delta z.

Still needs tests.

**Comment by glwagner** [comment]
To summarize the state of documentation: I added docstrings on the _instances_ of `AbstractGridMetric`s `Δz` and `volume`. The purpose of these instances is for building `BinaryOperation`s between fields and grid properties. The workings of the other 5 metrics is identical except for the meaning of the metric. These two docstrings (and the few lines in `binary_operations.jl` dedicated to `AbstractGridMetric` and `GridMetricOperation`) hopefully illustrate how these objects work together to allow specification of binary operations between fields and grid "metrics", which include grid spacings, areas, and volumes.

**Pull request merged**
