### PR TITLE
Removed outdated model_setup/time_stepping from docs

### LINKED ISSUE #1358: Possibly out-of-date docs page
I think this page is out-of-date: https://clima.github.io/OceananigansDocumentation/latest/model_setup/time_stepping/

Can someone please confirm?

### PR DESCRIPTION
**Pull request by tomchor**
Closes #1358

### CODE REVIEW

**Review by ali-ramadhan — APPROVED** [review]
Nice! Might also be good to bump the version to v0.47.2 in `Project.toml` so we can tag a new release and everyone gets updated docs.

**Comment by tomchor** [comment]
@ali-ramadhan  Done. I'm not sure how you guys do the tagging, so feel free to merge the PR and tag it!

**Comment by ali-ramadhan** [comment]
Ah once the PR is merged you just do it via a comment (we comment on the latest commit): https://github.com/CliMA/Oceananigans.jl/commit/47caa85138047acb4584cf97092c62c3e59b3543#comments

You're a repo collaborator so you should be able to tag new releases.

Under ColPrac people should merge their own PRs to avoid surprises but I'll take your comment as permission to merge and tag a new release :P

**Comment by ali-ramadhan** [comment]
Ah wait PR #1346 was a breaking change so we should be tagging v0.48.0 I think. I'll make the change and merge.

**Comment by tomchor** [comment]
> Under ColPrac people should merge their own PRs to avoid surprises but I'll take your comment as permission to merge and tag a new release :P

I have been doing that. I'm just not sure about the tagging thing so I thought it was best if you did it.

**Pull request merged**
