### PR TITLE
Adds support for advection=nothing

### PR DESCRIPTION
**Pull request by glwagner**
Collaboration with @francispoulin.

Todo:

- [x] Add time-stepping test with `advection=nothing` in `IncompressibleModel`
- [x] Add time-stepping test with `advection=nothing` in `ShallowWaterModel`

### CODE REVIEW

**Review by francispoulin — APPROVED** [review]
Very direct and to the point.  Well done and so fast.

**Review by francispoulin — APPROVED** [review]
I presume that removing grid still allows us to call this function in the same way as before, but wtih more flexibility.  Nice.

**Comment by glwagner** [comment]
> I presume that removing grid still allows us to call this function in the same way as before, but wtih more flexibility. Nice.

Ah it has no affect on function --- it just indicates to the code-reader that the _value_ of the argument is irrelevant (only its _type_ is used).

**Review by francispoulin — APPROVED** [review]
Looks good!

**Comment by francispoulin** [comment]
Do we know why these 4 tests fail?  From looking at the first one it seems gpu related but I'm no expert.

**Comment by glwagner** [comment]
> Do we know why these 4 tests fail? From looking at the first one it seems gpu related but I'm no expert.

One test failed because `AbstractGrid` was not imported. I'm not sure about the GPU issue since I didn't get to look at that.

**Review by ali-ramadhan — APPROVED** [review]

**Comment by francispoulin** [comment]
Looks like now all the checks are passing.  @glwagner is GPU still a concern?

**Comment by glwagner** [comment]
Thanks for noticing @francispoulin ! The GPU issue was a failing test, so if tests are passing, there's no issue! Perhaps a gift from St. Nick.

**Comment by francispoulin** [comment]
Great!  I will not look a gift horse in the mouth.

**Pull request merged**
