### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by navidcy**
This bot automatically suggests updates of GitHub action workflows.

### CODE REVIEW

**Comment by tomchor** [comment]
Sorry, I'm a bit out of the loop. Do you mind explaining what sorts of actions and the general utility here?

**Comment by navidcy** [comment]
It’s like CompatHelper but for GitHub actions, eg

https://github.com/CliMA/Oceananigans.jl/blob/558de0cac5ae76cc36603289a6c71a25f6a3f65e/.github/workflows/TagBot.yml#L12

**Comment by navidcy** [comment]
(It's not that important for Oceananigans since most of our tests run with buildkite rather than with GitHub Actions. But it's a good thing to have anyway.)

**Review by glwagner — APPROVED** [review]

**Comment by glwagner** [comment]
It would be nice to run unit tests on github actions before launching buildkite jobs. Someday...

**Comment by navidcy** [comment]
Good idea

**Pull request merged**
