### PR TITLE
Bump compat entries for PencilFFTs and PencilArrays

### PR DESCRIPTION
**Pull request by navidcy**
Supercedes #3119 #3120

### CODE REVIEW

**Review by glwagner — APPROVED** [review]

**Comment by glwagner** [comment]
Do these support `CuArray`?

**Comment by navidcy** [comment]
Think so. GPU tests passed, only docs are failing now (but I think they just failed to start... I'm restarting!)

**Comment by glwagner** [comment]
I don't think we use PencilArray for CuArray either in the source code or tests. My question is: does bumping PencilArrays and PencilFFTs mean that we can extend the distributed FFT algorithm (currently only implemented on CPU) to GPUs?

**Comment by navidcy** [comment]
Oh I see. This was not at all clear to me from your previous question. I thought you were asking whether the new versions dropped support to CuArrays and therefore explain why tests were failing!

Let me get back on your question now that I understand!

**Comment by navidcy** [comment]
I doubt it... I understood that the main change in the packages is https://github.com/jipolanco/PencilFFTs.jl/pull/65

**Comment by navidcy** [comment]
But then this issue (https://github.com/jipolanco/PencilFFTs.jl/issues/56) implies that already these packages work for GPUs over distributed. No?

**Comment by glwagner** [comment]
Yes, I think they do. I was wondering if the update here brought in that change (another possibility is that it's already supported)

**Pull request merged**
