### PR TITLE
Use on_architecture more liberally with boundary conditions

### PR DESCRIPTION
**Pull request by glwagner**
Addressing some of the issues on #3892, though we need tests.

### CODE REVIEW

**Comment by glwagner** [comment]
ok this is ready

**Review by navidcy — APPROVED** [review]
lgtm

**Comment by navidcy** [comment]
@glwagner any idea about this: 

https://buildkite.com/clima/oceananigans/builds/18542#0192e8c3-934a-4c74-b837-125fb8924484/31-1854

**Comment by glwagner** [comment]
> @glwagner any idea about this:
> 
> https://buildkite.com/clima/oceananigans/builds/18542#0192e8c3-934a-4c74-b837-125fb8924484/31-1854

Yes that was based on the wrong thinking that the flux of `v` is located at `Center, Face, Center` but it is actually located at `Center, Face, Nothing` (no vertical location)

**Comment by glwagner** [comment]
Pretty sure the Enzyme errors are unrelated

**Pull request merged**
