### PR TITLE
Don't set `JULIA_CUDA_USE_BINARYBUILDER`; up to CUDA@3.3.1

### LINKED ISSUE #1794: GPU CI is actually running tests on the CPU
Looking at the latest Buildkite build for the master branch it looks like GPU CI is only running CPU tests: https://buildkite.com/clima/oceananigans/builds/3045

Not sure why this would be the case... `CUDA.versioninfo()` seems to return the expected info on Sverdrup during initialization: https://buildkite.com/clima/oceananigans/builds/3045#ad4268d2-9b56-4cc0-ab46-ab9fdd61527b/31-253

I wonder if `CUDA.has_cuda()` is returning `false` on Sverdrup for some weird reason? https://github.com/CliMA/Oceananigans.jl/blob/dfc028667493bdd0eb1056d66d287c46e2591a7f/test/runtests.jl#L56

### PR DESCRIPTION
**Pull request by glwagner**
Resolves #1794 .

We should also come up with a more permanent solution (perhaps another environment variable to toggle GPU-CI) that throws an error if GPU tests can't run on the GPU.

### CODE REVIEW

**Comment by glwagner** [comment]
I think this line

https://github.com/CliMA/Oceananigans.jl/blob/b4e217244f1d594ce2854260e4dfa5c97156e162/.buildkite/pipeline.yml#L27

is throwing an error.

**Comment by glwagner** [comment]
The issue is coming from a boundserror. But on CUDA#master the bug may have been fixed:

https://github.com/JuliaGPU/CUDA.jl/blob/3c251c1c210ff3fc75cef8dad688d170caadc275/deps/bindeps.jl#L180

So we might just need to update CUDA. Looking into it...

**Comment by glwagner** [comment]
@ali-ramadhan do we need to call `CUDA.versioninfo()`? Can we avoid this for now?

**Review by tomchor — APPROVED** [review]
If it solves the problem, feel free to merge

**Comment by glwagner** [comment]
Looks like the tests run on the GPU now:

```
[2021/07/01 10:39:51.478] INFO      Testing vertically stretched rectilinear grid construction [GPU, Float64]...
--
  | [2021/07/01 10:39:51.496] INFO      Testing vertically stretched rectilinear grid spacings [GPU, Float64]...
  | VerticallyStretchedRectilinearGrid{Float64, Periodic, Periodic, Bounded}
  | domain: x ∈ [0.0, 1.0], y ∈ [0.0, 1.0], z ∈ [0.0, 361.0]
  | topology: (Periodic, Periodic, Bounded)
  | resolution (Nx, Ny, Nz): (1, 1, 19)
  | halo size (Hx, Hy, Hz): (1, 1, 1)
  | grid spacing (Δx, Δy, Δz): (1.0, 1.0, [min=1.0, max=37.0])
```

**Review by ali-ramadhan — APPROVED** [review]
> @ali-ramadhan do we need to call `CUDA.versioninfo()`? Can we avoid this for now?

Ah I don't think it's necessary, might just provide useful debugging information.

Actually though, I think if you're using the artifact installation then `CUDA.versioninfo()` will trigger CUDA.jl to download CUDNN (and CUTENSOR?) artifacts. Although we don't use them, it might be better to download them once at the beginning. But without `JULIA_CUDA_USE_BINARYBUILDER=true` it probably doesn't matter.

**Comment by glwagner** [comment]
> it might be better to download them once at the beginning.

Are the artifacts downloaded even if we don't use them?

**Comment by glwagner** [comment]
I think the disadvantage of using artifacts is that we are a bit more exposed to bugs and I think that's the cause of at least some of our pain here. The advantage is that it's less work to maintain our local CUDA software and our test environment might be more realistic / relevant since users typically use artifacts (I think).

**Comment by glwagner** [comment]
> Ah I don't think it's necessary, might just provide useful debugging information.

3.3.1 fixes a bug with `CUDA.versioninfo()` during CI: https://github.com/JuliaGPU/CUDA.jl/issues/970

So we can continue to call it.

**Comment by ali-ramadhan** [comment]
> Are the artifacts downloaded even if we don't use them?

Yeah apparently so. I think for some reason CUDA artifacts are downloaded first but certain calls like `CUDA.versioninfo()` can trigger further artifact downloads of CUDNN and CUTENSOR.

> I think the disadvantage of using artifacts is that we are a bit more exposed to bugs and I think that's the cause of at least some of our pain here. The advantage is that it's less work to maintain our local CUDA software and our test environment might be more realistic / relevant since users typically use artifacts (I think).

The CUDA.jl docs recommend using artifacts (https://cuda.juliagpu.org/dev/installation/overview/#CUDA-toolkit) but this may be because new users are less likely to encounter issues if they use the artifacts (which usually work out of the box) instead of fidgeting with local installs especially on servers without root access. For CI maintaining a local toolkit installation may be better?

**Comment by glwagner** [comment]
> The CUDA.jl docs recommend using artifacts (https://cuda.juliagpu.org/dev/installation/overview/#CUDA-toolkit)

True, but CI may be a special case, eg

https://github.com/JuliaGPU/CUDA.jl/blob/b25d9b751516240dc9a436b94c5617ffe4d6b719/deps/bindeps.jl#L62-L63

**Pull request merged**
