### PR TITLE
Bump compat entry for CubedSphere

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Review by Sbozzolo — APPROVED** [review]

**Review by ali-ramadhan — COMMENTED** [review]
Does Oceananigans.jl actually work with CubedSphere.jl v0.1? I'm just assuming stuff has been fixed/updated since then, but it's still in the `[compat]`.

**Comment by navidcy** [comment]
not sure tbh

**Comment by navidcy** [comment]
> Does Oceananigans.jl actually work with CubedSphere.jl v0.1? I'm just assuming stuff has been fixed/updated since then, but it's still in the `[compat]`.

Tried it and `test_multiregion_cubedsphere.jl` was failing with CubedSphere v0.1 so I removed the compat entry! Good catch @ali-ramadhan

**Review by simone-silvestri — APPROVED** [review]

**Review by ali-ramadhan — APPROVED** [review]
Thanks for checking @navidcy!

**Pull request merged**
