### PR TITLE
New example: Microbial rock paper scissors

### PR DESCRIPTION
**Pull request by ali-ramadhan**
This PR adds a new example called "Microbial rock paper scissors" in which an idealized diurnal cycle is simulated with an agent-based model of marine microbes as Lagrangian particles playing rock paper scissors.

This example is loosely based off of https://github.com/ali-ramadhan/lagrangian-microbes and can be extended to to study competition between marine microbes in an idealized setting.

The purposes of this example are to show users how to:
1. use Lagrangian particle tracking.
2. define their own custom particle types.
3. implement interacting particle pairs using KD trees.
4. write fields and particles to NetCDF.
5. easily read, analyze, and plot data from NetCDF using GeoData.jl.

This example has aided me in figuring out which abstractions are needed for particle tracking in #1091 and are helping me figure out which plotting recipes would be good to implement as part of https://github.com/rafaqz/GeoData.jl/pull/106.

This PR in a work-in-progress and depends on #1091. I still need to make it Literate.

The example also produces a neat animation of particles being advected (too big to include as a gif) and I'm hoping to expand the data analysis a bit.

image

species_count

# Plotting with GeoData.jl

I think reading data with JLD2 and plotting it can be cumbersome (and makes the examples more complicated than they should be in my opinion). I think once GeoData.jl is a bit more mature I think we should encourage users to use it as it simplifies data analysis and plotting greatly. For example, plotting w and b looks something like (could still be improved of course, contourf might be better)

```julia
anim = @animate for n in 1:Nt
    @info "Plotting idealized diurnal cycle frame $n/$Nt..."

    w_plot = plot(w[Ti=n, xC=32], color=:balance, clims=(-0.02, 0.02), aspect_ratio=:auto,
                  title="Idealized diurnal cycle: $(prettytime(times[n]))")

    b_plot = plot(b[Ti=n, xC=32], color=:thermal, clims=(-5e-4, 4e-4), aspect_ratio=:auto, title="")

    plot(w_plot, b_plot, layout=(2, 1), size=(1600, 900))
end
```

image

### CODE REVIEW

**Comment by glwagner** [comment]
Can we use a wrapper that automagically loads data from file for the specified time index (and also perform spatial slicing), using the nice GeoData getindex syntax?

**Comment by maeckha** [comment]
Hi, is there a reason why this isn't in the official examples?

**Comment by glwagner** [comment]
> Hi, is there a reason why this isn't in the official examples?

Is it ready? This comment suggests it's not:

> This PR in a work-in-progress and depends on #1091. I still need to make it Literate.

Perhaps @ali-ramadhan wouldn't mind some help though.

It's probably stale right now and would need a merge master and update.

**Comment by glwagner** [comment]
This PR is stale so I'm closing it.

**Pull request closed without merging**
