### PR TITLE
Regression test for Hydrostatic free surface model

### PR DESCRIPTION
**Pull request by simone-silvestri**
Regression test on the latitude longitude grid 
- Hydrostatic free surface model
- only tested the explicit free surface 
- both periodic and bounded latitude topology tested

Comments
- at the moment the data is generated on the fly at tests/test_regression.jl on the CPU() and tested on the GPU()
- explore the option to load the data in OceananigansArtifacts.jl

### CODE REVIEW

**Comment by simone-silvestri** [comment]
The reason why this test does not pass on the GPU for periodic boundary conditions in the longitudinal direction might have something to do with the synchronization of the halo filling (PR #1985)

**Review by navidcy — COMMENTED** [review]
@simone-silvestri, will you expand this regression to `ImplicitFreeSurface` as well?
If not, then perhaps add a note in one of the `@info` messages clarifying e.g. "... with explicit free surface formulation"?

**Comment by simone-silvestri** [comment]
Added implicit free surface test

**Comment by glwagner** [comment]
> @simone-silvestri, will you expand this regression to `ImplicitFreeSurface` as well? If not, then perhaps add a note in one of the `@info` messages clarifying e.g. "... with explicit free surface formulation"?

Good idea, if the test is still cheap!

**Review by glwagner — APPROVED** [review]

**Pull request merged**
