### PR TITLE
Update Physics Docs for the various Models

### LINKED ISSUE #1460: Basic Documentation for ShallowWaterModel?
I think it's time to have something there. At lease a docs page that writes down the equations solved and the state variables...

cc @francispoulin

### PR DESCRIPTION
**Pull request by navidcy**
This PR restructures the Physics section of the Docs so that equations solved by each model are written down.

Preview of the docs: http://clima.github.io/OceananigansDocumentation/previews/PR1690

Closes #1460.

### CODE REVIEW

**Review by francispoulin — APPROVED** [review]
Changes look good to me.  

Might suggest saying that the mass transport velocities are evolved, which can be used to determine the velocities.

**Comment by navidcy** [comment]
Sure @francispoulin, this was just a placeholder.
I'll add more details and ping you to either chip in or simply have a look...

**Review by glwagner — APPROVED** [review]
Awesome! It might make sense to put this up at the top after "Naiver-Stokes and tracer conservation equations". It'd probably also be helpful to change the title of that section to indicate that it refers to the equations being solved by `IncompressibleModel`.

**Comment by navidcy** [comment]
I think I'm envisioning somehow a split in subsections where the equations solved by each model (`IncompressibleModels`, `HydrostaticFreeSurfaceModels`, and `ShallowWaterModels`) are written down. What do you think?

@glwagner, @ali-ramadhan, @francispoulin

**Comment by francispoulin** [comment]
Great idea!

**Comment by navidcy** [comment]
My main question is: from all doc pages under "Physics", which are model independent and which are only relevant to `IncompressibleModels`? Is the following correct?

model independent: `Coriolis forces`, `Turbulence closures`, 
`IncompressibleModels`-related: `N-S and tracer conservation eqs`, `Buoyancy models and eqs of state`, `Surface gravity waves + Craik-Leibovich`.

**Comment by glwagner** [comment]
> I think I'm envisioning somehow a split in subsections where the equations solved by each model (`IncompressibleModels`, `HydrostaticFreeSurfaceModels`, and `ShallowWaterModels`) are written down. What do you think?
> 
> @glwagner, @ali-ramadhan, @francispoulin

Agree with this.

> My main question is: from all doc pages under "Physics", which are model independent and which are only relevant to IncompressibleModels? Is the following correct?

It's mixed. The LES closures are not supported by anything but `IncompressibleModel`. Some of the `TurbulenceClosures` are only supported by `HydrostaticFreeSurfaceModel`. Some are supported by all (like `IsotropicDiffusivity`).

Probably we don't want to organize the physics docs by model type. We could include a comment at the end of each turbulence closure description that's something like

> Supported by:
> * `IncompressibleModel`
> * `HydrostaticFreeSurfaceModel`
> * `ShallowWaterModel`

Such a structure might be feasible to maintain moving forwards.

**Comment by navidcy** [comment]
@glwagner could you write up the equations solved by the `HydrostaticFreeSurfaceModel` somewhere in `docs/src/physics/hydrostatic_free_surface_model.md`? Just write down the eqs --- no need to format or anything. I'll deal with the rest.

**Review by ali-ramadhan — APPROVED** [review]
❤️

**Pull request merged**
