### PR TITLE
Improves phrasing in `RegularRectilinearGrid` docstring

### PR DESCRIPTION
**Pull request by maeckha**
I was reading this doc and I think it would be easier for the reader's understanding to read "those" directions since we are talking about specific ones.

### CODE REVIEW

**Review by tomchor — APPROVED** [review]

**Review by francispoulin — APPROVED** [review]
good catch

**Comment by maeckha** [comment]
> good catch

thanks :)

**Review by glwagner — APPROVED** [review]

**Comment by tomchor** [comment]
@maeckha any specific reason why this was closed without merging? I think it's a small positive change that should be merged

**Comment by maeckha** [comment]
Sorry, mistake on my side.

**Comment by glwagner** [comment]
Feel free to press the green button @maeckha! (PR owners are given the responsibility to merge their PRs unless they state otherwise.)

**Comment by tomchor** [comment]
@maeckha do you have access to Oceananigas.jl? i.e. can you merge this PR yourself?

**Review by ali-ramadhan — APPROVED** [review]
Thank you @maeckha!

Yeah I think only collaborators can merge but with now 4 approvals I'll take the liberty of pressing the shiny green button.

**Comment by glwagner** [comment]
I was confused and thought that @maeckha could merge after approval. `CONTRIBUTING.md` is misleading in this regard.

**Comment by maeckha** [comment]
@tomchor , thanks for the suggestion, but didn't have any access.

@ali-ramadhan , thanks for merging!

**Pull request merged**
