### PR TITLE
Rework CI to use buildkite plugin

### PR DESCRIPTION
**Pull request by vchuravy**

### CODE REVIEW

**Review by navidcy — APPROVED** [review]
This looks good! Only downside that we loose the emojis for each step -- we can live without them.

@vchuravy any particular advantage to this over the previous version?

**Comment by navidcy** [comment]
perhaps let's wait to wait from @glwagner and @simone-silvestri before we merge?

**Comment by simone-silvestri** [comment]
This seems like a way forward, but I would wait for #2924 (that seems to be our bottleneck) to pass before changing CI

**Comment by vchuravy** [comment]
@glwagner is this something you would want? Otherwise I will close this PR.

**Comment by navidcy** [comment]
I think this might be helpful.

**Comment by navidcy** [comment]
OK, I brought the emojis back!

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
@vchuravy if/when the tests pass merge!

**Comment by navidcy** [comment]
Something's wrong; all jobs seem to have the same error (those which failed and those which passed)?

**Comment by navidcy** [comment]
@vchuravy could you have a look here? this seems to run, but e.g., were there any tests actually tested in https://buildkite.com/clima/oceananigans/builds/11987#018912fd-4e55-4160-87ce-0e7195b271aa ?

**Comment by vchuravy** [comment]
Yeah adding the Unicode symbols broke the test, since the tests group detection doesn't recognize them

**Comment by navidcy** [comment]
Oh damn, I’ll remove them then…

**Comment by navidcy** [comment]
@vchuravy how about now? still there is some weird TOML parser error...

**Comment by glwagner** [comment]
😢

**Pull request closed without merging**
