### PR TITLE
Slight terminology upgrade in eady example

### PR DESCRIPTION
**Pull request by navidcy**
Enhancement in the Eady turbulence example.

### CODE REVIEW

**Comment by glwagner** [comment]
> change to `# quadratic drag coefficient`?

Seems legit

**Comment by navidcy** [comment]
Travis tests keep failing... It's disappointing/frustrating... (#1186)

**Comment by navidcy** [comment]
Looks good to me!

@ali-ramadhan could you review this?

This was done by @glwagner but I opened the PR so I can't officially review... haha

**Review by ali-ramadhan — APPROVED** [review]

**Comment by ali-ramadhan** [comment]
@navidcy Sorry for the super slow review!

**Pull request merged**
