### PR TITLE
Adds `update_state!` to the end of all model constructors

### PR DESCRIPTION
**Pull request by tomchor**
Closes https://github.com/CliMA/Oceananigans.jl/issues/1889

@glwagner Went ahead and tried it. Feel free to not accept if you think it's not a good idea.

### CODE REVIEW

**Comment by glwagner** [comment]
I think we should add this to all the model constructors.

**Comment by tomchor** [comment]
Agreed

**Review by glwagner — APPROVED** [review]
Great improvement to the `model` abstractions.

Let's get the tests passing before merging.

**Comment by glwagner** [comment]
@tomchor I think I know what I need to do to resolve the issues. Basically we have built models in a way that would not withstand time stepping (but the tests passed because we never tried to time step). We just need to stop running those tests. Also `restore_from_checkpoint` should be skipped (and the whole feature deprecated).

**Comment by tomchor** [comment]
> @tomchor I think I know what I need to do to resolve the issues. Do you mind if I send commits to this PR?
> 
> Basically we have built models in a way that would not withstand time stepping (but the tests passed because we never tried to time step). We just need to stop running those tests. Also `restore_from_checkpoint` should be skipped (and the whole feature deprecated).

Please, commit away! And thanks

**Comment by francispoulin** [comment]
This looks like a good idea to me and the changes in the code look reasonable, but I can't say that I know how to fix this.  

Looking forward to seeing this PR progress!

**Comment by glwagner** [comment]
> > @tomchor I think I know what I need to do to resolve the issues. Do you mind if I send commits to this PR?
> > Basically we have built models in a way that would not withstand time stepping (but the tests passed because we never tried to time step). We just need to stop running those tests. Also `restore_from_checkpoint` should be skipped (and the whole feature deprecated).
> 
> Please, commit away! And thanks

Gonna resolve the restore from checkpoint thing in a separate PR once and for all rather than fiddle around with it here.

**Comment by tomchor** [comment]
Seems like @glwagner's nuking of `restore_from_checkpoint` worked well. I'm gonna merge this soon.

Is it worth bump a patch release since the initial diffusivities might be wrong without this?

**Comment by glwagner** [comment]
> Seems like @glwagner's nuking of `restore_from_checkpoint` worked well. I'm gonna merge this soon.
> 
> Is this worth bumping a patch release since the initial diffusivities might be wrong without this?

This is breaking, so I think we should bump a major release.

**Comment by tomchor** [comment]
>This is breaking, so I think we should bump a major release.

Bumped and merged. @glwagner I'm waiting for https://github.com/CliMA/Oceananigans.jl/pull/1892 to be merged as well before actually tagging a new release, but feel free to go ahead and just tag one if that's not good practice.

**Comment by glwagner** [comment]
Probably best if we can access this release through the registry right? Why wait?

**Pull request merged**
