### PR TITLE
Add missing `adapt_structure` for stokes drift

### PR DESCRIPTION
**Pull request by jagoosw**
(Btw I came across this trying to pass parameters that aren't just a named tuple of numbers.)

### CODE REVIEW

**Review by glwagner — APPROVED** [review]

**Comment by jagoosw** [comment]
@glwagner could I be added to the buildkite organisation so I can rerun the test please?

**Comment by glwagner** [comment]
> @glwagner could I be added to the buildkite organisation so I can rerun the test please?

Unfortunately I think we have to limit access to that to Clima folks, but it affects all Clima software (not just Oceananigans). As an example, none of us have permissions to add people to the buildkite.

**Comment by jagoosw** [comment]
> Unfortunately I think we have to limit access to that to Clima folks, but it affects all Clima software (not just Oceananigans). As an example, none of us have permissions to add people to the buildkite.

No worries makes sense!

**Comment by navidcy** [comment]
Reminder to add the `(0.90.5)` at the beginning of titles of PR that change the version number...

**Pull request merged**
