### PR TITLE
Bugfix in `fill_halo` for julia < 1.7

### LINKED ISSUE #2358: Fill Halo not working in julia < 1.7
In my last PR (#2335) I introduced tupled halo filling. 

This PR required inferring the length of a Tuple of different element types on the GPU (which is not necessarily easy).
I found a hack to do it, but I was working in julia 1.7.

Today, running a simulation with several different functional boundary conditions (in `discrete_form`) with julia 1.6, I found out that the compiler does not like my solution and does not infer the Tuple length (spitting out an `Invalid LLVM` error). This error is not there in julia-1.7

Unfortunately, I already merged my PR because I stupidly did not think to test all possible BC with julia-1.6.

Now, to revert to a non-tupled halo filling which works across julia distribution it's a one-liner (in `field_tuples.jl`)
```
@inline fill_halo_regions_field_tuple!(full_fields, grid, args...; kwargs...) = 
        fill_halo_regions!(extract_field_data.(full_fields), extract_field_bcs.(full_fields), grid, args...; kwargs...)
```
to
```
@inline fill_halo_regions_field_tuple!(full_fields, grid, args...; kwargs...) = 
   for field in full_fields
      fill_halo_regions!(field, args...; kwargs...)
   end
end
```

What should we do? We could change this line and leave the infrastructure intact for when we update to julia-1.7 (then we would't have tupled halo filling till then) or find a completely different solution (which will require a lot of restructuring)
Probably we also need more tests for boundary conditions with different BC on different sides.

I see that the tests that run on julia-1.6 do not return an error though.  Do other people encounter the same error?

### PR DESCRIPTION
**Pull request by simone-silvestri**
closes #2358

### CODE REVIEW

**Comment by navidcy** [comment]
Bump patch release?
Perhaps a test?

**Comment by simone-silvestri** [comment]
It's weird... time stepping itself should be a test because of the multiple `fill_halo_regions!` both on individual fields and tuples. Here it seems that everything passes...

**Comment by navidcy** [comment]
> It's weird... time stepping itself should be a test because of the multiple `fill_halo_regions!` both on individual fields and tuples. Here it seems that everything passes...

Let's bump a patch release and merge then.

**Comment by navidcy** [comment]
> It's weird... time stepping itself should be a test because of the multiple `fill_halo_regions!` both on individual fields and tuples. Here it seems that everything passes also without this fix...

without this fix?

**Comment by simone-silvestri** [comment]
yeah, it helped me getting it working on julia 1.6 on my computer but tests which use julia 1.6 passed already when I merged https://github.com/CliMA/Oceananigans.jl/pull/2335

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
Merge?

**Review by tomchor — APPROVED** [review]

**Pull request merged**
