### PR TITLE
Move CATKE diffusivities to vertical cell interfaces

### PR DESCRIPTION
**Pull request by glwagner**
Part of CATKE's numerics overhaul along with #2426.

@simone-silvestri hope this also improves (CA)TKE + mass flux!

### CODE REVIEW

**Comment by glwagner** [comment]
@adelinehillier these updates are relevant to you too. Not sure what the effect this change will have on the closure + closure accuracy, so we'll have to see.

**Comment by glwagner** [comment]
The code seems to work:

https://user-images.githubusercontent.com/15271942/164299773-fd2ef564-42e7-46ad-a352-2f4bd091f343.mp4

I'll try to produce a comparison between CATKE in this PR versus CATKE on `main` (where diffusivities are at cell centers).

**Comment by glwagner** [comment]
Welp, it's a minor difference at 8m resolution here:

https://user-images.githubusercontent.com/15271942/164351531-dae7cec6-de9a-43a7-a60f-29f6bbeeb060.mp4

"new" is this PR. The results are expected though I think: when we put the diffusivity at cell interfaces (holding everything else the same / all parameters constant), the mixing rate is slightly reduced.

@navidcy @simone-silvestri @adelinehillier shall we merge?

**Comment by glwagner** [comment]
Bumped to 0.75.1. Merge when ready.

**Review by simone-silvestri — APPROVED** [review]

**Pull request merged**
