### PR TITLE
Updated docs for IncompressibleModel to reflect arbitrary buoyant acceleration direction

### PR DESCRIPTION
**Pull request by tomchor**

### CODE REVIEW

**Comment by glwagner** [comment]
Would it be better to use `b \boldsymbol{\hat g}`? There's been some confusion about the meaning of `b` in the past so that notation could help.

**Review by glwagner — APPROVED** [review]

**Comment by glwagner** [comment]
(Or some other notation for the gravitational unit vector --- doesn't have to be `\boldsymbol{\hat g}`.)

**Comment by tomchor** [comment]
> Would it be better to use b \boldsymbol{\hat g} and define \boldsymbol{\hat g} as the gravitational_unit_vector to match the constructors / code? There's been some confusion about the meaning of b in the past so that notation could help.

I like this idea. Just made the changed

Not sure what to do about the GPU failure though. Seems to be completely unrelated to my change.

**Comment by glwagner** [comment]
CI is broken because of a driver issue on sverdrup. Hopefully it will be fixed soon.

**Comment by glwagner** [comment]
You can merge this --- the changes are clearly enough concentrated in docs.

**Comment by glwagner** [comment]
I believe GPU CI is back online.

**Pull request merged**
