### PR TITLE
(0.87.3) BugFix for computing `Field(::KernelFunctionOperation)`

### LINKED ISSUE #3232: Possible bug in computing `Field(::KernelFunctionOperation)`
This is what's keeping tests in https://github.com/tomchor/Oceanostics.jl/pull/151 from passing.

Here's the simplest MWE I could come up with:

```julia
julia> using Oceananigans

julia> grid = RectilinearGrid(size=(1, 1, 1), extent=(1, 1, 1));

julia> model = NonhydrostaticModel(; grid,);

julia> test(i, j, k, grid, auxiliary_fields,) = 1.0;

julia> a = KernelFunctionOperation{Center, Center, Center}(test, model.grid, model.auxiliary_fields);

julia> compute!(Field(a))
ERROR: ArgumentError: collection must be non-empty
Stacktrace:
  [1] first(itr::NamedTuple{(), Tuple{}})
    @ Base ./abstractarray.jl:466
  [2] isregional(t::NamedTuple{(), Tuple{}})
    @ Oceananigans.Utils ~/.julia/packages/Oceananigans/pbNSE/src/Utils/multi_region_transformation.jl:105
  [3] _findfirst_rec (repeats 2 times)
    @ ./tuple.jl:414 [inlined]
  [4] findfirst(f::Function, t::Tuple{Tuple{DataType, DataType, DataType}, NamedTuple{(), Tuple{}}})
    @ Base ./tuple.jl:421
  [5] #construct_regionally#52
    @ ~/.julia/packages/Oceananigans/pbNSE/src/Utils/multi_region_transformation.jl:146 [inlined]
  [6] construct_regionally
    @ ~/.julia/packages/Oceananigans/pbNSE/src/Utils/multi_region_transformation.jl:143 [inlined]
  [7] #construct_regionally#51
    @ ~/.julia/packages/Oceananigans/pbNSE/src/Utils/multi_region_transformation.jl:139 [inlined]
  [8] construct_regionally(::Function, ::Tuple{DataType, DataType, DataType}, ::NamedTuple{(), Tuple{}})
    @ Oceananigans.Utils ~/.julia/packages/Oceananigans/pbNSE/src/Utils/multi_region_transformation.jl:139
  [9] indices(κ::KernelFunctionOperation{Center, Center, Center, RectilinearGrid{Float64, Periodic, Periodic, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, CPU}, Float64, typeof(test), Tuple{NamedTuple{(), Tuple{}}}})
    @ Oceananigans.AbstractOperations ~/.julia/packages/Oceananigans/pbNSE/src/AbstractOperations/kernel_function_operation.jl:74
 [10] Field(operand::KernelFunctionOperation{Center, Center, Center, RectilinearGrid{Float64, Periodic, Periodic, Bounded, Float64, Float64, Float64, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, OffsetArrays.OffsetVector{Float64, StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}}, CPU}, Float64, typeof(test), Tuple{NamedTuple{(), Tuple{}}}})
    @ Oceananigans.AbstractOperations ~/.julia/packages/Oceananigans/pbNSE/src/AbstractOperations/computed_field.jl:37
 [11] top-level scope
    @ REPL[12]:1
```

For some reason it seems this only happens when passing `auxiliary_fields` to KFO.

### PR DESCRIPTION
**Pull request by simone-silvestri**
This ought to fix #3232. 

Closes #3232.

### CODE REVIEW

**Comment by tomchor** [comment]
This indeed seems to fix the issue. Is there a test we can include to prevent this in the future?

**Comment by glwagner** [comment]
@tomchor what about your example

**Comment by tomchor** [comment]
> @tomchor what about your example

I'm okay with that, although my initial thought was that it's too specific, which is why I didn't suggest it. But if you guys think that works, please use it!

**Review by tomchor — APPROVED** [review]
@simone-silvestri I think we need a test though. If you agree with @glwagner we can simply use my MWE in https://github.com/CliMA/Oceananigans.jl/issues/3232#issue-1866033526

**Comment by simone-silvestri** [comment]
I am fine with having that as a test. Do you want to add it and merge?

**Comment by tomchor** [comment]
> I am fine with having that as a test. Do you want to add it and merge?

Sure!

**Comment by tomchor** [comment]
Can I bump the patch version and release a new version?

**Comment by glwagner** [comment]
Don't forget to update the title of the PR

**Pull request merged**
