### PR TITLE
Use julia v1.9

### PR DESCRIPTION
**Pull request by navidcy**
This PR moves tests on Julia v1.9.

### CODE REVIEW

**Comment by navidcy** [comment]
Anyone has any idea why all the errors with `all` or `interior` or `parent`? E.g.,

https://buildkite.com/clima/oceananigans/builds/11267#0187fd3b-6ccf-4f23-be19-445f384d6722/35-377

**Comment by tomchor** [comment]
> Anyone has any idea why all the errors with `all` or `interior` or `parent`? E.g.,
> 
> https://buildkite.com/clima/oceananigans/builds/11267#0187fd3b-6ccf-4f23-be19-445f384d6722/35-377

I did a bit of investigating but couldn't figure it out. It would be really nice to have 1.9 going sometime soon since it apparently significantly decreases the TTFX.

**Comment by simone-silvestri** [comment]
Do these test pass locally?

**Comment by navidcy** [comment]
I don't think I have access to Sverdrup. Could I get access? I wanted to try to run the test there to see what's happening...

**Comment by navidcy** [comment]
@glwagner, @simone-silvestri, @sandreza?

**Comment by navidcy** [comment]
> Do these test pass locally?

E.g., on tartarus when I run the `test_timestepping.jl` it passed on GPU.

**Comment by glwagner** [comment]
> No, I did
> 
> ```
> julia -O0 --color=yes --project -e 'using Pkg; Pkg.test()'
> ```
> 
> which I took from buildkite.yml

Ah ok. Using `Pkg.test()` sets `--check-bounds=yes`. I wasn't sure if you were running `test_timestepping.jl` individually.

**Comment by glwagner** [comment]
Interested to see if CI speeds up because faster compilation

**Comment by navidcy** [comment]
Me too! I need some help I think here... I'm not sure why tests fail.

**Comment by glwagner** [comment]
What does one of tests return versus what is expected? The buildkite log only says they fail so there's no way to figure out what's going wrong.

**Comment by glwagner** [comment]
It's something to do with GPU, maybe GPU reductions?

```
[2023/05/24 21:41:15.102] INFO          Testing grid utils on variably spaced grid....
--
  | Grid initialization: Test Failed at /net/ocean/home/data44/data5/glwagner/.buildkite-agent/builds/sverdrup-4/clima/oceananigans/test/test_grids.jl:199
  | Expression: minimum_xspacing(grid) ≈ FT(π / 3)
  | Evaluated: 0.0 ≈ 1.0471975511965976
```

**Comment by navidcy** [comment]
> It's something to do with GPU, maybe GPU reductions?
> 
> ```
> [2023/05/24 21:41:15.102] INFO          Testing grid utils on variably spaced grid....
> --
>   | Grid initialization: Test Failed at /net/ocean/home/data44/data5/glwagner/.buildkite-agent/builds/sverdrup-4/clima/oceananigans/test/test_grids.jl:199
>   | Expression: minimum_xspacing(grid) ≈ FT(π / 3)
>   | Evaluated: 0.0 ≈ 1.0471975511965976
> ```

I see this error. But I can't reproduce it. On tartarus it's not happening and I don't have access to Svedrup. So I don't know what to do... :(

**Comment by navidcy** [comment]
Also we get some deprecation warnings. E.g., for

```
SpecifiedTimes(times::Vararg{<:Number}) = SpecifiedTimes(sort([Float64(t) for t in times]), 0)
```

we get

```
Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
```

I don't understand what that means tho.

**Comment by navidcy** [comment]
> Also we get some deprecation warnings. E.g., for
> 
> ```
> SpecifiedTimes(times::Vararg{<:Number}) = SpecifiedTimes(sort([Float64(t) for t in times]), 0)
> ```
> 
> we get
> 
> ```
> Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).
> ```
> 
> I don't understand what that means tho.

I think a39445a dealt with this

**Comment by glwagner** [comment]
> Wrapping `Vararg` directly in UnionAll is deprecated (wrap the tuple instead).

The internet says to use `times::Vararg{Number}`

somewhere in 

https://discourse.julialang.org/t/deprecation-warnings-from-atom-with-v1-7/72400/3

**Comment by glwagner** [comment]
> > It's something to do with GPU, maybe GPU reductions?
> > ```
> > [2023/05/24 21:41:15.102] INFO          Testing grid utils on variably spaced grid....
> > --
> >   | Grid initialization: Test Failed at /net/ocean/home/data44/data5/glwagner/.buildkite-agent/builds/sverdrup-4/clima/oceananigans/test/test_grids.jl:199
> >   | Expression: minimum_xspacing(grid) ≈ FT(π / 3)
> >   | Evaluated: 0.0 ≈ 1.0471975511965976
> > ```
> 
> I see this error. But I can't reproduce it. On tartarus it's not happening and I don't have access to Svedrup. So I don't know what to do... :(

I guess its a CUDA version issue or something

**Comment by navidcy** [comment]
OK, tests pass!!!!!

Woooooohoooooo!!

Ready to review. Ready to move forward to Julia v1.9


cc @glwagner, @simone-silvestri

**Comment by navidcy** [comment]
I'm debating whether we should bump minor release. In principle there shouldn't be any breaking change. But we stopped testing on v1.8 and start testing on v1.9...

**Comment by simone-silvestri** [comment]
I am not sure. There are a bunch of breaking changes happening recently, and I would rather just wait for the next one (for example #3142)

**Review by simone-silvestri — APPROVED** [review]

**Comment by navidcy** [comment]
True fair.

**Comment by navidcy** [comment]
OK, I'm merging! We can always undo. I think it's a step fwd.

**Pull request merged**
