### PR TITLE
Changed every instance of Cell in .jl files to Center using sed

### LINKED ISSUE #414: Change Cell to 'Center' and Face to 'Interface' to specify Field locations?

### PR DESCRIPTION
**Pull request by tomchor**
Closes #414

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Now begins the slog to fix all the tests haha.

Looks like `show_fields.jl` is complaining that `Center` is not defined: https://buildkite.com/clima/oceananigans/builds/982#b79d3314-e323-4bce-a443-35926baf3803/40-133

**Comment by tomchor** [comment]
Apparently I don't know how to run tests locally, because they all passed here without problems. Do you have any reference that I can check that shows how to run tests locally? In the meantime I'll do my best to change this on my end.

**Comment by navidcy** [comment]
```Julia
julia --project
]test
```
?

**Review by ali-ramadhan — APPROVED** [review]
Looks like all tests pass :tada:

I think there's one merge conflict that needs to be fixed but otherwise looks good to me.

Since it's a big API change it might be good to get @glwagner's approval as well before merging.

**Comment by navidcy** [comment]
And new release after?

**Comment by ali-ramadhan** [comment]
> And new release after?

Yes. I already tagged v0.46.0 in PR #1091 but not sure if it'll get merged soon. If either PR gets merged we should tag v0.46.0.

**Comment by glwagner** [comment]
I'm nervous but I think we should do it. Will make @jm-c happy; also we can revert if we need to.

**Comment by tomchor** [comment]
Now also replaced `CellField` with `CenterField`, so I _think_ it's ready to go.

**Pull request merged**
