### PR TITLE
Fix compat annotation in Docs

### PR DESCRIPTION
**Pull request by ErikQQY**
Use a ```compat``` annotation would be better

### CODE REVIEW

**Review by navidcy — APPROVED** [review]

**Comment by navidcy** [comment]
We need to deal with #2131 first and rebase.

**Comment by navidcy** [comment]
@ErikQQY, could you bring this up to date with `main` branch? Perhaps all tests pass then and we can merge.

**Comment by ErikQQY** [comment]
I brought my fork up to date, but it seems there are still some problems🤔

**Comment by navidcy** [comment]
> I brought my fork up to date, but it seems there are still some problems🤔

try again?

**Pull request merged**
