### PR TITLE
BibTeX citations and references in the docs

### PR DESCRIPTION
**Pull request by ali-ramadhan**
This PR **finally** adds proper citations that link to a references page all generated from an `oceananigans.bib` file. This is now possible thanks to the new Bibliography.jl package which I've used to hack in a Documenter.jl "plugin" at https://github.com/ali-ramadhan/DocumenterBibliographyTest.jl

This is currently the last action item for the JOSS submission.

The code that handles citations and bibliography expansion is a little messy and will hopefully evolve into a proper Documenter.jl plugin but for now I've copy pasted the code into Oceananigans.jl until the plugin has stabilized in some form. The `@cite` and `@bibliography` syntax should remain the same though.

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Temporarily sanitized the BibTeX file while some Bibliography.jl issues are sorted out

X-Ref: https://github.com/Azzaare/Bibliography.jl/issues/4
X-Ref: https://github.com/Azzaare/Bibliography.jl/issues/6
X-Ref: https://github.com/Azzaare/Bibliography.jl/issues/7

**Comment by ali-ramadhan** [comment]
Prototype up and running! Although I might wait until the above issues get resolved so the references look a bit cleaner before merging.

image

image

**Comment by johncmarshall54** [comment]
Hello Ali. If Joss paper back in?

**Comment by glwagner** [comment]
@ali-ramadhan what are the issues? I'd be ok with merging this before the issues are sorted, since this does seem like significant progress... !

**Comment by ali-ramadhan** [comment]
@glwagner Mostly BibTeX parsing issues like it can't currently handle comments and sometimes craps out with double braces, but I'll just modify the `.bib` file to work around those limitations until they're fixed.

Agree we should merge and periodically update as new versions of Bibliography.jl get released.

**Pull request merged**
