### PR TITLE
(0.95.2) Bugfix in the Polar BC

### PR DESCRIPTION
**Pull request by simone-silvestri**
Which now are tested also for `Flat` grids in the meridional direction. 

Required by https://github.com/CliMA/ClimaOcean.jl/pull/297
(see https://buildkite.com/clima/climaocean-ci/builds/2146#0193bf37-560c-4923-83d0-3a891fb843e7)

### CODE REVIEW

**Review by glwagner — APPROVED** [review]

**Comment by glwagner** [comment]
When tests pass here, I will bump to 0.95.2 and then merge.

**Comment by glwagner** [comment]
nooo that restarted the tests

**Comment by glwagner** [comment]
We have a way to bypass the test restrictions now which is useful, since the update here was a trivial bump of Project.toml

**Comment by simone-silvestri** [comment]
Ah sorry 😅  I forgot we can avoid updating now

**Pull request merged**
