### PR TITLE
Validate Implementation of Orthogonal Spherical Shell Grid

### PR DESCRIPTION
**Pull request by siddharthabishnu**
This PR closes issues #3217 and #3198.

### CODE REVIEW

**Comment by navidcy** [comment]
@sid is this ready? I presume not, right?

**Comment by siddharthabishnu** [comment]
> @siddharthabishnu is this ready? I presume not, right?

Not yet.

**Comment by navidcy** [comment]
@siddharthabishnu,
#3239 deals with #3198
so if the plan for this PR then is to deal with the other issue that is mentioned at the first comment (that is, #3217) perhaps the title is a bit misleading since it refers to `OrthogonalSphericalShellGrid` but #3217 is specific to `ConformalCubedSphereGrid`?

**Comment by navidcy** [comment]
@siddharthabishnu this PR changes 73 files at the moment. Are you sure this is intentional?

**Comment by glwagner** [comment]
What's the purpose of the PR? Is there any code in it?

**Comment by siddharthabishnu** [comment]
@glwagner, there isn't much code in it. So, it is safe to close this PR and delete the associated branch. I will proceed with that. @navid, after some digging, I discovered that my default git pull command was set to git rebase instead of git merge following git fetch. This altered the commit history to linearize it, causing confusion in both my previous tracer advection branch and the one associated with this PR. I have now reset the default setting. My apologies for the oversight.

**Comment by siddharthabishnu** [comment]
> @siddharthabishnu, #3239 deals with #3198 so if the plan for this PR then is to deal with the other issue that is mentioned at the first comment (that is, #3217) perhaps the title is a bit misleading since it refers to `OrthogonalSphericalShellGrid` but #3217 is specific to `ConformalCubedSphereGrid`?

I agree. I will open a new PR associated with issue #3217 if necessary. The longitude plots look better, and once I am confident in their accuracy, I will close the issue #3217.

**Comment by siddharthabishnu** [comment]
> @siddharthabishnu this PR changes 73 files at the moment. Are you sure this is intentional?
> 
> A lot of commits seem to have happened between _this post_ and my previous post. But they are mostly things already merged in main? But this PR seems to re-introduce the changes and sometimes undo them?

Please see my response above.

**Comment by siddharthabishnu** [comment]
> What's the purpose of the PR? Is there any code in it?

Minimal. Closing it now.

**Comment by siddharthabishnu** [comment]
Closing this PR due the reasons mentioned above.

**Comment by navidcy** [comment]
> The longitude plots look better, and once I gain confidence in their accuracy, I will proceed to close issue #3217.

You mean with the latest `#main` they look better? Better or perfect? Can you update the issue #3217?

**Pull request closed without merging**
