### PR TITLE
Remove dollar signs used for latexing in Docs

### PR DESCRIPTION
**Pull request by navidcy**
This PR replaces `$..$` with ` ``..`` `  and `$$..$$` with ` ```math ... ``` `.

According to @mortenpi dollar signs are deprecated.

Screen Shot 2020-10-24 at 9 34 31 am

### CODE REVIEW

**Comment by glwagner** [comment]
@navidcy you're a hero. I'd merge this but I want @ali-ramadhan to witness its beauty.

**Review by glwagner — APPROVED** [review]
🌅

**Comment by ali-ramadhan** [comment]
@navid the hero every package needs, but not every package is worthy of.

**Review by ali-ramadhan — APPROVED** [review]

**Comment by ali-ramadhan** [comment]
Just noticed that Buildkite got a little stuck on the last build (CPU environment failed to initialize) so I reran the build. Should pass as all previous builds passed.

**Pull request merged**
