### PR TITLE
Deploy docs

### LINKED ISSUE #1909: Docs aren't being generated
I think the docs page hasn't been generated since v0.60.0:

Screenshot from 2021-07-29 08-26-21

I also haven't been able to see PR previews in a while. I assumed I was doing something wrong but maybe there's an issue here.

### PR DESCRIPTION
**Pull request by glwagner**
This PR bumps the patch version in order to deploy docs, now that the `DOCUMENTER_KEY` environment variable should be correctly set for the tartarus buildkite agent.

Resolves #1909

### CODE REVIEW

**Comment by navidcy** [comment]
Let's see what happens in the docs build!

**Comment by glwagner** [comment]
Where will the preview be again?

**Comment by navidcy** [comment]
https://clima.github.io/OceananigansDocumentation/previews/PR1940

But the docs log will also say if that has been deployed or not. If there was a DOCUMENTER_KEY issue or something else...

**Comment by navidcy** [comment]
From the [log](https://buildkite.com/clima/oceananigans/builds/3685#e88e73f9-20e6-43c6-8c05-64c492318d38) I see that the DOCUMENTER_KEY is OK! But I think the first commit doesn't generate the preview (this was already the case previously when things were working).

**Review by navidcy — APPROVED** [review]
Worked!! I approve from the bottom of my soul!!!

**Review by tomchor — APPROVED** [review]
I approve this so much. Thanks @glwagner

**Pull request merged**
