### PR TITLE
Clean up convergence test scripts and plots

### LINKED ISSUE #873: Run convergence tests as part of the verification testset
Otherwise they might go out of date. Also good to keep checking convergence I suppose.

X-Ref: https://github.com/openjournals/joss-reviews/issues/2018

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Last TODO item for the JOSS paper.

Was going to include the convergence tests as part of `test_verification.jl` but in cleaning them up (mostly by relying on the version of Oceananigans in the repository, `using .ConvergenceTests` as a local module, and making sure legends don't block off the plots) I noticed that the 2D convergence tests are all failing now.

Pretty sure this must be a stupid mistake as they were all converging correctly as of Oceananigans v0.30.0 but haven't tried to figure out what went wrong yet...

Since they're kinda important now I'm thinking we should have a test job that just runs all the convergence tests, tests that the order of convergence is as expected, and produces all the convergence plots so we can look at them. We can do this once we've set up Buildkite somewhere (see also @simonbyrne's https://github.com/CliMA/slurm-buildkite).

Also, @glwagner do we still need `analyze_single_forced_fixed_slip.jl` and `analyze_forced_fixed_slip_pressure.jl`? They're not mentioned in the convergence tests `README.md` so maybe we should remove them?

Resolves #873

# Convergence test plots

point_exponential_decay_time_stepper_convergence

cosine_advection_diffusion_solutions

cosine_advection_diffusion_error_convergence

gaussian_advection_diffusion_solutions

gaussian_advection_diffusion_error_convergence

two_dimensional_diffusion_convergence

taylor_green_convergence

forced_free_slip_convergence

forced_fixed_slip_convergence

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Hmmm, some competition between the x-ticks on some plots.

**Comment by ali-ramadhan** [comment]
Tried running the `two_dimensional_diffusion.jl` convergence test
* on the master branch where it failed (constant error, no convergence),
* on Oceananigans v0.31.0 (first tagged release to include the convergence tests), where it also failed, and
* on Oceananigans v0.30.0 (where it passed!).

Worth noting that the convergence tests `Manifest.toml` was explicitly specifying Oceananigans v0.30.0: https://github.com/CliMA/Oceananigans.jl/blob/v0.34.1/verification/convergence_tests/Manifest.toml#L255-L259

So this PR did not cause the convergence tests to fail. We must have made some changes between v0.30.0 and v0.31.0 that broke the convergence tests.

**Comment by glwagner** [comment]
@ali-ramadhan the convergence tests pass now, correct? `reshape=true` in `xnodes`, etc fixed it?

**Comment by ali-ramadhan** [comment]
Yes that's been fixed. We now have 77 rate of convergence tests that all pass (see below)! Running the Oceananigans tests with the `TEST_GROUP=convergence` environment variable will run all the convergence tests.

# Convergence test plots

I also updated the figures:

point_exponential_decay_time_stepper_convergence

cosine_advection_diffusion_solutions

cosine_advection_diffusion_error_convergence

gaussian_advection_diffusion_solutions

gaussian_advection_diffusion_error_convergence

two_dimensional_diffusion_convergence

taylor_green_convergence

forced_free_slip_convergence

forced_fixed_slip_convergence


# Rate of convergence tests
```
[2020/09/01 13:29:06.313] INFO  rate of convergence = 1.009563466619233 (expected ≈ 1.0, atol = 0.01)
[2020/09/01 13:31:40.030] INFO  1D cosine diffusion only u_L₁ rate of convergence = -2.001484816201546 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:31:40.030] INFO  1D cosine diffusion only v_L₁ rate of convergence = -2.0014848162011636 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:31:40.030] INFO  1D cosine diffusion only cx_L₁ rate of convergence = -2.001484816201546 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:31:40.030] INFO  1D cosine diffusion only cy_L₁ rate of convergence = -2.001484816201546 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:31:40.030] INFO  1D cosine diffusion only u_L∞ rate of convergence = -1.963755641838265 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:31:40.030] INFO  1D cosine diffusion only v_L∞ rate of convergence = -1.963755641838265 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:31:40.030] INFO  1D cosine diffusion only cx_L∞ rate of convergence = -1.963755641838265 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:31:40.030] INFO  1D cosine diffusion only cy_L∞ rate of convergence = -1.963755641838265 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:31:40.221] INFO  1D cosine advection only u_L₁ rate of convergence = -1.9980794852091928 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:31:40.222] INFO  1D cosine advection only v_L₁ rate of convergence = -1.9980794852091928 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:31:40.222] INFO  1D cosine advection only cx_L₁ rate of convergence = -1.9980794852091928 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:31:40.222] INFO  1D cosine advection only cy_L₁ rate of convergence = -1.9980794852091928 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:31:40.222] INFO  1D cosine advection only u_L∞ rate of convergence = -1.9644207410445413 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:31:40.222] INFO  1D cosine advection only v_L∞ rate of convergence = -1.9644207410445413 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:31:40.222] INFO  1D cosine advection only cx_L∞ rate of convergence = -1.9644207410445413 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:31:40.222] INFO  1D cosine advection only cy_L∞ rate of convergence = -1.9644207410445413 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:31:40.222] INFO  1D cosine advection-diffusion u_L₁ rate of convergence = -1.9980700699453309 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:31:40.222] INFO  1D cosine advection-diffusion v_L₁ rate of convergence = -1.9980700699453309 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:31:40.222] INFO  1D cosine advection-diffusion cx_L₁ rate of convergence = -1.9980700699453309 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:31:40.222] INFO  1D cosine advection-diffusion cy_L₁ rate of convergence = -1.9980700699453309 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:31:40.223] INFO  1D cosine advection-diffusion u_L∞ rate of convergence = -1.962474997837589 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:31:40.223] INFO  1D cosine advection-diffusion v_L∞ rate of convergence = -1.962474997837589 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:31:40.223] INFO  1D cosine advection-diffusion cx_L∞ rate of convergence = -1.962474997837589 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:31:40.223] INFO  1D cosine advection-diffusion cy_L∞ rate of convergence = -1.962474997837589 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:41:56.759] INFO  1D Gaussian diffusion only u_L₁ rate of convergence = -1.9618748622249815 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:41:56.759] INFO  1D Gaussian diffusion only v_L₁ rate of convergence = -1.9618748622249709 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:41:56.759] INFO  1D Gaussian diffusion only cx_L₁ rate of convergence = -1.9618748622247761 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:41:56.760] INFO  1D Gaussian diffusion only cy_L₁ rate of convergence = -1.9618748622249815 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:41:56.760] INFO  1D Gaussian diffusion only u_L∞ rate of convergence = -2.0009567885378985 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:41:56.760] INFO  1D Gaussian diffusion only v_L∞ rate of convergence = -2.0009567885374557 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:41:56.760] INFO  1D Gaussian diffusion only cx_L∞ rate of convergence = -2.0009567885374264 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:41:56.760] INFO  1D Gaussian diffusion only cy_L∞ rate of convergence = -2.0009567885378985 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:41:56.770] INFO  1D Gaussian advection only u_L₁ rate of convergence = -1.9134689334186734 (expected ≈ -2.0, atol = 0.1)
[2020/09/01 13:41:56.770] INFO  1D Gaussian advection only v_L₁ rate of convergence = -1.9134689334186734 (expected ≈ -2.0, atol = 0.1)
[2020/09/01 13:41:56.771] INFO  1D Gaussian advection only cx_L₁ rate of convergence = -1.9134689334186734 (expected ≈ -2.0, atol = 0.1)
[2020/09/01 13:41:56.771] INFO  1D Gaussian advection only cy_L₁ rate of convergence = -1.9134689334186734 (expected ≈ -2.0, atol = 0.1)
[2020/09/01 13:41:56.771] INFO  1D Gaussian advection only u_L∞ rate of convergence = -1.560991171522994 (expected ≈ -2.0, atol = 0.5)
[2020/09/01 13:41:56.771] INFO  1D Gaussian advection only v_L∞ rate of convergence = -1.560991171522994 (expected ≈ -2.0, atol = 0.5)
[2020/09/01 13:41:56.771] INFO  1D Gaussian advection only cx_L∞ rate of convergence = -1.560991171522994 (expected ≈ -2.0, atol = 0.5)
[2020/09/01 13:41:56.771] INFO  1D Gaussian advection only cy_L∞ rate of convergence = -1.560991171522994 (expected ≈ -2.0, atol = 0.5)
[2020/09/01 13:41:56.771] INFO  1D Gaussian advection-diffusion u_L₁ rate of convergence = -1.977030895926029 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:41:56.771] INFO  1D Gaussian advection-diffusion v_L₁ rate of convergence = -1.9770308959260363 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:41:56.771] INFO  1D Gaussian advection-diffusion cx_L₁ rate of convergence = -1.977030895926029 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:41:56.771] INFO  1D Gaussian advection-diffusion cy_L₁ rate of convergence = -1.977030895926029 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 13:41:56.771] INFO  1D Gaussian advection-diffusion u_L∞ rate of convergence = -2.008467701332351 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:41:56.771] INFO  1D Gaussian advection-diffusion v_L∞ rate of convergence = -2.008467701332351 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:41:56.771] INFO  1D Gaussian advection-diffusion cx_L∞ rate of convergence = -2.008467701332351 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:41:56.772] INFO  1D Gaussian advection-diffusion cy_L∞ rate of convergence = -2.008467701332351 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:48:50.076] INFO  2D diffusion (Periodic, Periodic, Bounded) L₁ rate of convergence = -2.0083073827620237 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:48:50.193] INFO  2D diffusion (Periodic, Periodic, Bounded) L∞ rate of convergence = -1.947766867108851 (expected ≈ -2.0, atol = 0.06)
[2020/09/01 13:48:50.194] INFO  2D diffusion (Periodic, Bounded, Bounded) L₁ rate of convergence = -2.003208945092345 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:48:50.194] INFO  2D diffusion (Periodic, Bounded, Bounded) L∞ rate of convergence = -1.965491374875283 (expected ≈ -2.0, atol = 0.06)
[2020/09/01 13:48:50.194] INFO  2D diffusion (Bounded, Bounded, Bounded) L₁ rate of convergence = -1.9995730043199613 (expected ≈ -2.0, atol = 0.01)
[2020/09/01 13:48:50.194] INFO  2D diffusion (Bounded, Bounded, Bounded) L∞ rate of convergence = -1.984678368453777 (expected ≈ -2.0, atol = 0.06)
[2020/09/01 13:52:28.324] INFO  Taylor-Green L₁ rate of convergence = -2.0004700529312727 (expected ≈ -2.0, atol = 0.001)
[2020/09/01 13:52:28.369] INFO  Taylor-Green L∞ rate of convergence = -1.95032035517191 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 14:11:26.553] INFO  Forced flow free slip (x, y) L₁ rate of convergence = -1.999738241539891 (expected ≈ -2.0, atol = 0.001)
[2020/09/01 14:11:26.598] INFO  Forced flow free slip (x, y) L∞ rate of convergence = -1.9992989311721168 (expected ≈ -2.0, atol = 0.001)
[2020/09/01 14:11:26.611] INFO  Forced flow free slip (x, z) L₁ rate of convergence = -1.999738243255539 (expected ≈ -2.0, atol = 0.001)
[2020/09/01 14:11:26.611] INFO  Forced flow free slip (x, z) L∞ rate of convergence = -1.999298932806858 (expected ≈ -2.0, atol = 0.001)
[2020/09/01 14:15:04.586] INFO  Forced flow fixed slip (x, y) L₁ rate of convergence = -1.9978175950101218 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 14:15:04.627] INFO  Forced flow fixed slip (x, y) L∞ rate of convergence = -1.935360007296416 (expected ≈ -2.0, atol = 0.1)
[2020/09/01 14:15:04.640] INFO  Forced flow fixed slip (x, z) L₁ rate of convergence = -1.9978175950117558 (expected ≈ -2.0, atol = 0.05)
[2020/09/01 14:15:04.641] INFO  Forced flow fixed slip (x, z) L∞ rate of convergence = -1.9353600072951698 (expected ≈ -2.0, atol = 0.1)
```

**Pull request merged**
