### PR TITLE
Revert "Updating Benchmark Docs"

### LINKED ISSUE #1949: Documentation build is failing
I think #1930 broke the documentation:

https://buildkite.com/clima/oceananigans/builds/3719#6b051652-7cab-4257-82c6-4be2bfb04f92

@hennyg888 should we revert #1930, or can this problem be easily fixed with a new PR?

### PR DESCRIPTION
**Pull request by glwagner**
Reverts CliMA/Oceananigans.jl#1930

Resolves #1949

### CODE REVIEW

**Comment by glwagner** [comment]
Hopefully the docs build passes here. @hennyg888

**Comment by glwagner** [comment]
@hennyg888 also feel free to re-open a PR from your branch.

**Comment by hennyg888** [comment]
Documentations test passed, seems like it was #1930 that was breaking it. All I did was edit the markdown file `benchmarks.md`. What could've broken it?

**Comment by francispoulin** [comment]
I wonder if it considers `benchmarks.md` as part of the docs, which is not too crazy a thought.  If so, then anyline in your file that is not consistent with markdown standard could cause a problem?

I would suggest trying viewing your file using a markdown program and see if it complains about any particular lines. Or, are there any lines that don't appear?

**Comment by hennyg888** [comment]
Doesn't seem to be the case @francispoulin. Everything at least looked fine.

**Review by hennyg888 — APPROVED** [review]

**Comment by glwagner** [comment]
> I wonder if it considers `benchmarks.md` as part of the docs, which is not too crazy a thought. If so, then anyline in your file that is not consistent with markdown standard could cause a problem?
> 
> I would suggest trying viewing your file using a markdown program and see if it complains about any particular lines. Or, are there any lines that don't appear?

`benchmarks.md` is part of the docs: https://clima.github.io/OceananigansDocumentation/stable/appendix/benchmarks/

**Pull request merged**
