### PR TITLE
Journal of Open Source Software paper

### PR DESCRIPTION
**Pull request by ali-ramadhan**
Once we decide on a final draft on Google Docs I'll update `paper.md`. JOSS requires a Markdown paper to be available in the repository.

X-Ref: https://github.com/openjournals/joss-reviews/issues/1965
X-Ref: https://github.com/openjournals/joss-reviews/issues/2018

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Thanks for your comments @alanedelman, I've updated the paper.

**Comment by christophernhill** [comment]
@ali-ramadhan and @glwagner how close are things to done on this. Could I approve?

**Comment by ali-ramadhan** [comment]
@christophernhill We replied to reviewers and addressed their comments. I think we're waiting for an editor reply at https://github.com/openjournals/joss-reviews/issues/2018 maybe.

If you can approve that would be great, but we probably shouldn't merge until https://github.com/openjournals/joss-reviews/issues/2018 has been closed I think.

**Comment by ali-ramadhan** [comment]
openjournals/joss-reviews#2018 has been approved so we should merge this now.

**Review by glwagner — APPROVED** [review]
🥳

**Pull request merged**
