### PR TITLE
Fixes mangled docstring for Field

### LINKED ISSUE #1268: Example in Field docstring is mangled
https://github.com/CliMA/Oceananigans.jl/blob/ebd7858000c78f7b1754112a68c587e6195e620b/src/Fields/field.jl#L32

### PR DESCRIPTION
**Pull request by glwagner**
Resolves #1268

### CODE REVIEW

**Review by navidcy — APPROVED** [review]
I was wondering whether a doctest would be better here. That would catch any changes caused by any future development.

```julia
Example
=======

```jldoctest; output = false
julia> using Oceananigans
julia> ω = Field(Face, Face, Cell, CPU(), RegularCartesianGrid(size=(1, 1, 1), extent=(1, 1, 1)))

# output
Field located at (Face, Face, Cell)
├── data: OffsetArrays.OffsetArray{Float64,3,Array{Float64,3}}, size: (3, 3, 3)
├── grid: RegularCartesianGrid{Float64, Periodic, Periodic, Bounded}(Nx=1, Ny=1, Nz=1)
└── boundary conditions: x=(west=Periodic, east=Periodic), y=(south=Periodic, north=Periodic), z=(bottom=ZeroFlux, top=ZeroFlux)
```
```

**Comment by glwagner** [comment]
I think a doctest is a good idea... just avoided it here because they're often finnicky and I didn't feel like I had the time to debug.

**Comment by glwagner** [comment]
Ok, I put in a doctest. Lets see if it passes.

**Comment by navidcy** [comment]
@ali-ramadhan, out of curiosity do you know why this fails?
https://buildkite.com/clima/oceananigans/builds/894#25866b57-d2c9-48ec-a969-c2f1a11d7f39

error says `ERROR: UndefVarError: CPU not defined`... weird...

**Pull request merged**
