### PR TITLE
Validate the convergence rates for advection

### PR DESCRIPTION
**Pull request by francispoulin**
This is created in place of #1648.

I don't know if `using Polynomials` is done correctly but if not, it should be easy to fix.

### CODE REVIEW

**Comment by ali-ramadhan** [comment]
Looks great! I think we still don't want images like `validation/convergence_tests/convergence_rates.png` getting into the repo but we can "squash and merge" this PR to avoid this.

**Comment by francispoulin** [comment]
Not sure what "squash and merge" means but I deleted the file locally and then wanted to push the change but couldn't.  If someone can tell me how to delete it I'm happy to do it.

Also, I see that the tests pass so my use of `Polynomials` presumably worked?

Anything else that people would like done before someone approves this PR?

**Comment by ali-ramadhan** [comment]
> Not sure what "squash and merge" means 

Ah it's one of the three merge options, e.g.

image

where it combines all the commits into one commit then merges. Then intermediate changes (like a file that was created then deleted) do not enter git history.

> I deleted the file locally and then wanted to push the change but couldn't. If someone can tell me how to delete it I'm happy to do it.

That should be all it takes... What error does git produce? I can also try locally.

> Also, I see that the tests pass so my use of `Polynomials` presumably worked?

Ah I don't think `plot_rates_convergence_advection.jl` is actually run as part of CI right now. We could add it in this PR if you're interested. I think we'd want to actually add it to the validation pipeline (not the main pipeline) so we would add a new test set in https://github.com/CliMA/Oceananigans.jl/blob/master/test/test_convergence.jl and add a new build step in https://github.com/CliMA/Oceananigans.jl/blob/master/.buildkite/validation-pipeline.yml then it would show up in these builds with plots, e.g.: https://buildkite.com/clima/oceananigans-validation-experiments/builds/208

> Anything else that people would like done before someone approves this PR?

I think it looks good to merge, just without the extra image file!

**Comment by francispoulin** [comment]
Thanks @ali-ramadhan 

After deleting the file and then trying to do `git add` get the following,
```
$ git add convergence_rates.png
fatal: pathspec 'convergence_rates.png' did not match any files
```
Maybe it's easier if I try and delete it directly on github?

**Review by ali-ramadhan — APPROVED** [review]
Ah nice, that works! Looks good to squash and merge.

Hmmm, maybe with `git add convergence_rates.png` you were in the wrong directory? If not then maybe going to the top-level directory of the repo and doing `git add .` might work?

**Review by ali-ramadhan — APPROVED** [review]

**Comment by francispoulin** [comment]
I think it's been deleted so I don't need to worry about adding it but will keep it in mind for next time.

After the checks pass I will merge.

**Comment by ali-ramadhan** [comment]
Ah I think you forgot to squash and merge and instead created a merge commit so the image file entered git history, e.g. it's now in the `master` branch: https://github.com/CliMA/Oceananigans.jl/commit/0d10840b92e67c60c18102d5183affff993f896a

It's not a big deal since this particular file only increases the repo size by 64 KiB but in general I think we should avoid merging binary files like images into the repo since the increase in repo size is cumulative.

**Comment by francispoulin** [comment]
Sorry about that.  I guess I can go to master and delete the file there.  I will give that a try, or do you prefer that I undo the merge?

**Comment by ali-ramadhan** [comment]
Ah it's not a big deal so I wouldn't worry about for this PR!

It's too late to undo right now since it's in git history and fully deleting it would involve rewriting git history which is usually bad haha. We did it once before (https://github.com/CliMA/Oceananigans.jl/issues/509) but we had lots of 50 MiB files so it was needed.

**Comment by glwagner** [comment]
Changing git history is also a bit annoying and somewhat labor intensive; there's no quick undo.

**Pull request merged**
